### ISSUE TITLE
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got GPT2LMHeadModel

### ISSUE THREAD

**Issue by George-Ogden** [huggingface/transformers#10139]
I'm having this issue, and I think it's my fault, but can someone, please, advise me in case this is a bug rather than a mistake:
```
from transformers import TFTrainer, TFTrainingArguments, GPT2Tokenizer, GPT2LMHeadModel
training_args = TFTrainingArguments(
    do_train=True,
    output_dir="results",
    overwrite_output_dir=True,
    num_train_epochs=4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    logging_dir="logs",
)
model = GPT2LMHeadModel.from_pretrained("distilgpt2")
trainer = TFTrainer(model=model,args=training_args,train_dataset=data)
trainer.train()
```
which returns the error:
```
Traceback (most recent call last):
  File ".\train-tf.py", line 52, in <module>
    trainer.train()
  File "C:\Anaconda3\lib\site-packages\transformers\trainer_tf.py", line 492, in train
    ckpt = tf.train.Checkpoint(optimizer=self.optimizer, model=self.model)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1929, in __init__
    _assert_trackable(converted_v)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1410, in _assert_trackable
    raise ValueError(
ValueError: `Checkpoint` was expecting a trackable object (an object derived from `TrackableBase`), got GPT2LMHeadModel(
```
and then it displays the model data.
Thanks for anything that you can add.

**Comment by George-Ogden** [comment]
Oh no! I was using the PyTorch model with the TF trainer! I have fixed it now.
