### ISSUE TITLE
ONNX Export - cannot resolve operator 'Shape' with opsets: ai.onnx v11

### ISSUE THREAD

**Issue by biro-mark** [huggingface/transformers#10198]
## Environment info
- `transformers` version: 4.3.2
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.8.7
- PyTorch version (GPU?): 1.7.1+cu110 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help
@LysandreJik

## Information

Model I am using: DistilBertForTokenClassification

The problem arises when using:
Exporting the model to ONNX and trying to load it with onnxjs in NodeJS.

The tasks I am working on is:
Classifying tokens with DistilBertForTokenClassification

## To reproduce
Try to convert DistilBertForTokenClassification to ONNX and load it with onnxjs. I have prepared this minimal repo https://github.com/biro-mark/transformers-onnx-shape-operator-issue 
1. python save_model.py
2. python -m transformers.convert_graph_to_onnx --model ./model --framework pt --tokenizer distilbert-base-uncased onnx/out.onnx
3. node index.js

This outputs ```RuntimeError: abort(TypeError: cannot resolve operator 'Shape' with opsets: ai.onnx v11). Build with -s ASSERTIONS=1 for more info.
    at process.abort (C:\Users\marki\node_modules\onnxjs\dist\onnx-wasm.js:9:13921)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)```

## Expected behavior
Expected no error to be thrown. ONNX export should only use operators that are valid for the opset. `Shape` operator looks like it was added in opset v13 but I might also be misinterpreting this table https://github.com/onnx/onnx/blob/master/docs/Operators.md. Adding `--opset 13` flag to the `convert_graph_to_onnx` gives
```
====== Converting model to ONNX ======
ONNX opset version set to: 13
Loading pipeline (model: ./model, tokenizer: distilbert-base-uncased)
Creating folder C:\Users\marki\eg\onnx
Using framework PyTorch: 1.7.1+cu110
Found input input_ids with shape: {0: 'batch', 1: 'sequence'}
Found input attention_mask with shape: {0: 'batch', 1: 'sequence'}
Found output output_0 with shape: {0: 'batch', 1: 'sequence'}
Ensuring inputs are in correct order
head_mask is not present in the generated input list.
Generated inputs order: ['input_ids', 'attention_mask']
Error while converting the model: Unsupported ONNX opset version: 13
```

**Comment by biro-mark** [comment]
Sorry I think I misinterpreted the operators table https://github.com/onnx/onnx/blob/master/docs/Operators.md and `Shape` should have been available since opset 1, getting an update in opset 13. 

This seems to be an issue with `onnxjs` not implementing the full set of operators in opset 11.
