### ISSUE TITLE
[examples s2s] AttributeError: 'MBartTokenizerFast' object has no attribute 'tgt_lang'

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#10292]
After this PR https://github.com/huggingface/transformers/pull/10205 This is still broken for other models:

```
python examples/seq2seq/run_seq2seq.py     --model_name_or_path facebook/mbart-large-en-ro      --do_train     --do_eval     --task translation_en_to_ro     --dataset_name wmt16     --dataset_config_name ro-en     --source_prefix "translate English to Romanian: "     --output_dir /tmp/tst-translation     --per_device_train_batch_size=16     --per_device_eval_batch_size=16     --overwrite_output_dir     --predict_with_generate     --max_train_samples 500     --max_val_samples 500
```

```
Traceback (most recent call last):
  File "examples/seq2seq/run_seq2seq.py", line 668, in <module>
    main()
  File "examples/seq2seq/run_seq2seq.py", line 469, in main
    train_dataset = train_dataset.map(
  File "/mnt/nvme1/code/huggingface/datasets-master/src/datasets/arrow_dataset.py", line 1120, in map
    update_data = does_function_return_dict(test_inputs, test_indices)
  File "/mnt/nvme1/code/huggingface/datasets-master/src/datasets/arrow_dataset.py", line 1091, in does_function_return_dict
    function(*fn_args, indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "examples/seq2seq/run_seq2seq.py", line 450, in preprocess_function
    with tokenizer.as_target_tokenizer():
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/models/mbart/tokenization_mbart_fast.py", line 193, in as_target_tokenizer
    self.set_tgt_lang_special_tokens(self.tgt_lang)
AttributeError: 'MBartTokenizerFast' object has no attribute 'tgt_lang'
```

@patil-suraj, @sgugger

**Comment by sgugger** [comment]
#10287 contains the fix.

**Comment by stas00** [comment]
Confirmed that it works, albeit the cl args changed so tested with:
```
PYTHONPATH=src python examples/seq2seq/run_translation.py     --model_name_or_path facebook/mbart-large-en-ro      --do_train     --do_eval      --dataset_name wmt16     --dataset_config_name ro-en       --output_dir /tmp/tst-translation     --per_device_train_batch_size=2     --per_device_eval_batch_size=2     --overwrite_output_dir     --predict_with_generate     --max_train_samples 500     --max_val_samples 500 --source_lang en_XX --target_lang ro_RO --max_val_samples 10  --max_train_samples 10
```
