### ISSUE TITLE
[predict] AttributeError: 'Seq2SeqTrainer' object has no attribute 'metrics_format'

### ISSUE THREAD

**Issue by Tan1997** [huggingface/transformers#10296]
Hi everybody

When using mbart for machine translation prediction, i got:

Traceback (most recent call last):
  File "/Users/lishuqi/Desktop/WAT2021/transformers-master/examples/seq2seq/run_seq2seq.py", line 667, in <module>
    main()
  File "/Users/lishuqi/Desktop/WAT2021/transformers-master/examples/seq2seq/run_seq2seq.py", line 637, in main
    metrics_formatted = trainer.metrics_format(metrics)
AttributeError: 'Seq2SeqTrainer' object has no attribute 'metrics_format'

Am I doing something wrong with the translation?
@patil-suraj

**Comment by patil-suraj** [comment]
`metrics_format` was recently introduced on master, you should update the transformers version to master.

**Comment by nickyongzhang** [comment]
I have updated to the latest 4.3.2 version but still see the error.

**Comment by Tan1997** [comment]
Thanks! I'll try it again!
