### ISSUE TITLE
mBART 50 models not found in model shortcut name list

### ISSUE THREAD

**Issue by codingnoobneedshelp** [huggingface/transformers#10327]
Transformers version: 4.4.0.dev0

Hello, I'm trying to fine-tune mBART 50 with your seq2seq examples.

Getting this error:

Model name 'facebook/mbart-large-50' not found in model shortcut name list (facebook/mbart-large-en-ro, facebook/mbart-large-cc25).

Traceback (most recent call last):
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 668, in <module>
    main()
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 349, in main
    use_auth_token=True if model_args.use_auth_token else None,
  File "/usr/local/lib/python3.6/dist-packages/transformers/models/auto/tokenization_auto.py", line 399, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1789, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1806, in _from_pretrained
    **(copy.deepcopy(kwargs)),
  File "/usr/local/lib/python3.6/dist-packages/transformers/tokenization_utils_base.py", line 1860, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/models/mbart/tokenization_mbart.py", line 109, in __init__
    self.set_src_lang_special_tokens(kwargs.get("src_lang", "en_XX"))
  File "/usr/local/lib/python3.6/dist-packages/transformers/models/mbart/tokenization_mbart.py", line 199, in set_src_lang_special_tokens
    self.cur_lang_code = self.lang_code_to_id[src_lang]
KeyError: None

Any Ideas on how to fix this?

Thanks

**Comment by patil-suraj** [comment]
Hi @codingnoobneedshelp , thank for reporting this issue. Right now MBart50Tokenizer does not work with `AutoTokenizer`.
There will be a new script for translation in the next ~2 weeks that will handle this issue. For now, you could just modify the script to  use `MBart50Tokenizer`, instead of `AutoTokenizer`.

**Comment by patil-suraj** [comment]
Hi @codingnoobneedshelp 

This is now resolved, the `run_translation.py` script now supports fine-tuning mBART-50.
