### ISSUE TITLE
DeepSpeedEngine object has no attribute 'no_sync'

### ISSUE THREAD

**Issue by ayubSubhaniya** [huggingface/transformers#10394]
## Environment info

- `transformers` version: 4.3.0
- Platform: Linux-4.14.209-160.339.amzn2.x86_64-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.8
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: distributed

### Who can help
Library:
- deepspeed: @stas00

## Information
Deepspeed with single node, multi gpus breaking

```
Traceback (most recent call last):
  File "training/run_training.py", line 273, in <module>
    raise e
  File "training/run_training.py", line 270, in <module>
    remaining_args=remaining_args)
  File "training/run_training.py", line 186, in main
    trainer.train(model_path=model_path)
  File "/usr/local/lib/python3.6/dist-packages/transformers/trainer.py", line 937, in train
    with model.no_sync():
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DeepSpeedEngine' object has no attribute 'no_sync'
```

```
deepspeed \
        --num_gpus ${GPUS_ALLOWED} \
        training/run_training.py \
        --deepspeed ds_config.json \
        --output_dir ${OUTPUT_BASE_PATH} \
        --model_name_or_path ${MODEL_NAME_OR_PATH} \
        --per_device_train_batch_size ${TRAIN_BATCH_SIZE} \
        --per_device_eval_batch_size ${TEST_BATCH_SIZE} \
        --gradient_accumulation_steps ${GRAD_STEP} \
        --evaluation_strategy steps \
        --eval_steps ${EVAL_STEP} \
        --num_train_epochs ${EPOCH} \
        --save_steps ${SAVE_STEP} \
        --logging_steps ${LOG_STEP} \
        --dataloader_num_workers ${DATALOADER_NUM_WORKERS} \
        --load_best_model_at_end true \
        --do_train true \
        --do_eval true \
        --fp16 true \
        --dataloader_drop_last true \
        --overwrite_output_dir true \
        --use_lazy true \
        --logging_first_step true || { echo 'training failed' ; exit 0; }

echo 'training successful'
```

```
ds_config.json
{
  "zero_optimization": {
     "stage": 2,
     "allgather_partitions": true,
     "reduce_scatter": true,
     "overlap_comm": true,
     "contiguous_gradients": true,
     "cpu_offload": true,
     "allgather_bucket_size": 2e8,
     "reduce_bucket_size": 2e8,
  }
}
```

**Comment by stas00** [comment]
Thank you for your report. This issue has already been fixed in `transformers` master.
