### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by omerarshad** [huggingface/transformers#10444]
While running run_seq2seq.py for summarization task on my own CSV,  i get following error:

All the weights of BartForConditionalGeneration were initialized from the model checkpoint at sshleifer/distilbart-cnn-12-6.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BartForConditionalGeneration for predictions without further training.
Traceback (most recent call last):
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 645, in <module>
    main()
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 476, in main
    load_from_cache_file=not data_args.overwrite_cache,
  File "/usr/local/lib/python3.7/dist-packages/datasets/arrow_dataset.py", line 1120, in map
    update_data = does_function_return_dict(test_inputs, test_indices)
  File "/usr/local/lib/python3.7/dist-packages/datasets/arrow_dataset.py", line 1091, in does_function_return_dict
    function(*fn_args, indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 448, in preprocess_function
    inputs = [prefix + inp for inp in inputs]
  File "/content/transformers/examples/seq2seq/run_seq2seq.py", line 448, in <listcomp>
    inputs = [prefix + inp for inp in inputs]
TypeError: can only concatenate str (not "int") to str

**Comment by mariosasko** [comment]
Hi,

if  the `text_column` and `summary_column` arguments are not specified when running the script, it is assumed that the first column in a csv file contains the full text and the second column the corresponding summaries. From the error message, it seems your csv file has integers in the first column.

**Comment by omerarshad** [comment]
done with this but now this error:

**Comment by omerarshad** [comment]
File "run_seq2seq.py", line 645, in <module>
    main()
  File "run_seq2seq.py", line 518, in main
    pad_to_multiple_of=8 if training_args.fp16 else None,
TypeError: __init__() got an unexpected keyword argument 'model'

**Comment by patil-suraj** [comment]
This is because the `DataCollatorForSeq2Seq` now adds a new `model` argument. Upgrading to master will fix this issue.

Also, as is mentioned at the very beginning of the [examples README,](https://github.com/huggingface/transformers/tree/master/examples#important-note) running the examples requires an install from source.
