### ISSUE TITLE
Can't load config for hosted model, works when downloaded

### ISSUE THREAD

**Issue by MatejUlcar** [huggingface/transformers#10607]
I have recently (19 hours ago) uploaded a new model to huggingface: https://huggingface.co/EMBEDDIA/sloberta

When attempting to load it with `model = AutoModelForMaskedLM.from_pretrained("EMBEDDIA/sloberta")`  I get the following error:

```
Traceback (most recent call last):
  File "/home/mulcar/.conda/envs/transformerslatest/lib/python3.8/site-packages/transformers/configuration_utils.py", line 353, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mulcar/.conda/envs/transformerslatest/lib/python3.8/site-packages/transformers/modeling_auto.py", line 1105, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/mulcar/.conda/envs/transformerslatest/lib/python3.8/site-packages/transformers/configuration_auto.py", line 272, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/mulcar/.conda/envs/transformerslatest/lib/python3.8/site-packages/transformers/configuration_utils.py", line 362, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'EMBEDDIA/sloberta'. Make sure that:

- 'EMBEDDIA/sloberta' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'EMBEDDIA/sloberta' is the correct path to a directory containing a config.json file
```

If I download the model from the huggingface.co, eg. cloning the model's repo, it loads perfectly fine. Is there a waiting time before a new model is completely added to the system? Or is there an other issue going on?

**Comment by LysandreJik** [comment]
Hello! I can do `model = AutoModelForMaskedLM.from_pretrained("EMBEDDIA/sloberta")` without any issues on my end.

Could it be linked to a connection issue?

```py
>>> from transformers import AutoModelForMaskedLM
>>> model = AutoModelForMaskedLM.from_pretrained("EMBEDDIA/sloberta")
Downloading: 100%|██████████| 520/520 [00:00<00:00, 215kB/s]
Downloading: 100%|██████████| 443M/443M [00:38<00:00, 11.5MB/s]

```

**Comment by MatejUlcar** [comment]
Tested from two computers on two different networks, didn't work. Managed to load it on Google Colab, though.

Anyway, it does work now. I was foiled by conda loading an old version of transformers instead of a newer one. Thanks!
