### ISSUE TITLE
Converting marian tatoeba models

### ISSUE THREAD

**Issue by Dmitry-Sn** [huggingface/transformers#10943]
## Environment info

- `transformers` version: 4.4.2
- Platform: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.8.0+cu101 (False)
- Tensorflow version (GPU?): 2.4.1 (False)
- Using GPU in script?: False
- Using distributed or parallel set-up in script?: False

### Who can help

- marian: @patrickvonplaten, @patil-suraj

## Information

Model I am using (Bert, XLNet...): marian

The problem arises when using:
* [x] the official example scripts: Tatoeba models converting script
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: machine translation
* [ ] my own task or dataset: (give details below)

## To reproduce

All steps are the same as in [official script](https://github.com/huggingface/transformers/blob/master/scripts/tatoeba/README.md) for converting marian tatoeba models to pytorch.

Error log:
```
Traceback (most recent call last):
  File "src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py", line 1267, in <module>
    resolver = TatoebaConverter(save_dir=args.save_dir)
  File "src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py", line 80, in __init__
    released.columns = released_cols
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/internals/managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 7 elements, new values have 9 elements
```

## Expected behavior

IMO, main problem is in changes in fields of file [Tatoeba-Challenge/models/released-models.txt](https://github.com/Helsinki-NLP/Tatoeba-Challenge/blob/master/models/released-models.txt). 
I'm expecting clean conversion of model for choosed language pair.

**Comment by Dmitry-Sn** [comment]
@patil-suraj unstale?

**Comment by patil-suraj** [comment]
Unstale

**Comment by LysandreJik** [comment]
Unstale

**Comment by patrickvonplaten** [comment]
@patil-suraj - do you think you find time to take a look here? Otherwise I can probably free some time for it

**Comment by patil-suraj** [comment]
I will take a look at it this week.
