### ISSUE TITLE
Can't find ibert-roberta-base model

### ISSUE THREAD

**Issue by shon-otmazgin** [huggingface/transformers#10990]
## Environment info
- `transformers` version: 4.4.2
- Platform: Linux-4.15.0-1109-azure-x86_64-with-Ubuntu-16.04-xenial
- Python version: 3.6.13
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

Models:
- ibert: @kssteven418 

Documentation: 
- @sgugger

## Information

Model I am using I-BERT:

The problem arises when using:
* [X] the official example scripts: (give details below)

## To reproduce
From [documentation](https://huggingface.co/transformers/model_doc/ibert.html):

```python 
from transformers import RobertaTokenizer, IBertModel
import torch
tokenizer = RobertaTokenizer.from_pretrained('ibert-roberta-base')
model = IBertModel.from_pretrained('ibert-roberta-base')
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)
last_hidden_states = outputs.last_hidden_state
```

1. install pytorch and transformers 
2. run the code example from docs

```python 
Traceback (most recent call last):
  File "/home/sotmazgi/PycharmProjects/s2e-coref/ibert_test.py", line 3, in <module>
    tokenizer = RobertaTokenizer.from_pretrained('ibert-roberta-base')
  File "/home/sotmazgi/PycharmProjects/s2e-coref/venv/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1693, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'ibert-roberta-base'. Make sure that:

- 'ibert-roberta-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'ibert-roberta-base' is the correct path to a directory containing relevant tokenizer files
```

## Expected behavior
get the embedding for the example sentence

**Comment by LysandreJik** [comment]
Fixing it in https://github.com/huggingface/transformers/pull/10994

**Comment by shon-otmazgin** [comment]
Hello @LysandreJik,  
We should specify `kssteven/ibert-roberta-base` in `from_pretrained` function?

**Comment by LysandreJik** [comment]
Yes, that's right! That's the checkpoint you're looking for.

The docs are now updated on `master`, and the next release (next few days) will have them.

**Comment by shon-otmazgin** [comment]
Thanks @LysandreJik

After reinstalling from source:

python
```
Traceback (most recent call last):
  File "/home/sotmazgi/PycharmProjects/s2e-coref/ibert_test.py", line 3, in <module>
    tokenizer = RobertaTokenizer.from_pretrained('kssteven/ibert-roberta-base')
  File "/home/sotmazgi/PycharmProjects/s2e-coref/venv/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1705, in from_pretrained
    resolved_vocab_files, pretrained_model_name_or_path, init_configuration, *init_inputs, **kwargs
  File "/home/sotmazgi/PycharmProjects/s2e-coref/venv/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1776, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/sotmazgi/PycharmProjects/s2e-coref/venv/lib/python3.6/site-packages/transformers/models/roberta/tokenization_roberta.py", line 171, in __init__
    **kwargs,
  File "/home/sotmazgi/PycharmProjects/s2e-coref/venv/lib/python3.6/site-packages/transformers/models/gpt2/tokenization_gpt2.py", line 179, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by LysandreJik** [comment]
Ah, it seems that the I-BERT authors have not uploaded some slow tokenizer files. Can you try it with a `RobertaTokenizerFast` instead of a `RobertaTokenizer` and let me know if it works for you?

**Comment by shon-otmazgin** [comment]
Yes thank you
