### ISSUE TITLE
Cannot run the gpt neo 2.7B example

### ISSUE THREAD

**Issue by donno2048** [huggingface/transformers#11017]
## Environment info
- `transformers` version: 4.4.2
- Platform: Windows and Linux (using wsl)
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.1+cpu (False)
- Tensorflow version (GPU?): 2.4.1 (False)

Library:

- text generation: @patrickvonplaten
- pipelines: @LysandreJik

## Information

When running the example for gpt-neo i.e.
```py
>>> from transformers import pipeline
>>> generator = pipeline('text-generation', model='EleutherAI/gpt-neo-2.7B')
>>> generator("EleutherAI has", do_sample=True, min_length=50)
```
I get this:
```
Downloading: 100%|█████████████████████████████████████████████████████████████████| 1.46k/1.46k [00:00<00:00, 2.27MB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/donno2048/.local/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 344, in pipeline
    framework = framework or get_framework(model)
  File "/home/donno2048/.local/lib/python3.8/site-packages/transformers/pipelines/base.py", line 71, in get_framework
    model = AutoModel.from_pretrained(model, revision=revision)
  File "/home/donno2048/.local/lib/python3.8/site-packages/transformers/models/auto/modeling_auto.py", line 809, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/donno2048/.local/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 389, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
KeyError: 'gpt_neo'
```

**Comment by LysandreJik** [comment]
Hi @donno2048. the GPT Neo is available on the master branch, and is not yet in a release. I invite you to install transformers from source, with the following:
```
pip install git+https://github.com/huggingface/transformers
```

**Comment by donno2048** [comment]
Thanks

**Comment by Zselter07** [comment]
Does the min_length param work for you? I do the same as above and it doesn't seem to change anything
