### ISSUE TITLE
error while training wave2vec on arabic text

### ISSUE THREAD

**Issue by omerarshad** [huggingface/transformers#11164]
Traceback (most recent call last):
  File "/content/transformers/examples/research_projects/wav2vec2/run_asr.py", line 480, in <module>
    main()
  File "/content/transformers/examples/research_projects/wav2vec2/run_asr.py", line 430, in main
    num_proc=2,
  File "/usr/local/lib/python3.7/dist-packages/datasets/dataset_dict.py", line 448, in map
    for k, dataset in self.items()
  File "/usr/local/lib/python3.7/dist-packages/datasets/dataset_dict.py", line 448, in <dictcomp>
    for k, dataset in self.items()
  File "/usr/local/lib/python3.7/dist-packages/datasets/arrow_dataset.py", line 1289, in map
    update_data = does_function_return_dict(test_inputs, test_indices)
  File "/usr/local/lib/python3.7/dist-packages/datasets/arrow_dataset.py", line 1260, in does_function_return_dict
    function(*fn_args, indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/content/transformers/examples/research_projects/wav2vec2/run_asr.py", line 423, in prepare_dataset
    batch["labels"] = processor(batch[data_args.target_text_column]).input_ids
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/wav2vec2/processing_wav2vec2.py", line 117, in __call__
    return self.current_processor(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 2266, in __call__
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 2451, in batch_encode_plus
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils.py", line 543, in _batch_encode_plus
    verbose=verbose,
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils.py", line 606, in _batch_prepare_for_model
    return_attention_mask=return_attention_mask,
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 2579, in pad
    while len(required_input[index]) == 0:
IndexError: list index out of range
[ ]

**Comment by raja1196** [comment]
Hello, Can you provide more information about the dataset you are using. The error message alone seems very vague, but pointing towards input.

**Comment by omerarshad** [comment]
Its my custom dataset. Arabic audio and arabic transcription
