### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects hyperparameter_search raytune

### ISSUE THREAD

**Issue by maxzzze** [huggingface/transformers#11249]
## Environment info

- `transformers` version: v4.5.1
- Platform: Linux
- Python version: 3.7.8
- PyTorch version (GPU?): yes
- Tensorflow version (GPU?):
- Using GPU in script?: 
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...): bert-base-uncased 

The problem arises when using:
* [ x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ x] my own task or dataset: (give details below)

## To reproduce

1. Run hyperparameter tuning with raytune
2.
3.

```
2021-04-14 15:44:01,389 INFO services.py:1264 -- View the Ray dashboard at http://127.0.0.1:8265
Traceback (most recent call last):
  File "pipeline_training.py", line 311, in <module>
    keep_checkpoints_num=0
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1459, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/integrations.py", line 235, in run_hp_search_ray
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/tune.py", line 297, in run
    _ray_auto_init()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/tune.py", line 664, in _ray_auto_init
    ray.init()
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 785, in init
    hook()
  File "/opt/conda/lib/python3.7/site-packages/ray/tune/registry.py", line 171, in flush
    self.references[k] = ray.put(v)
  File "/opt/conda/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 1481, in put
    object_ref = worker.put_object(value)
  File "/opt/conda/lib/python3.7/site-packages/ray/worker.py", line 266, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/opt/conda/lib/python3.7/site-packages/ray/serialization.py", line 324, in serialize
    return self._serialize_to_msgpack(value)
  File "/opt/conda/lib/python3.7/site-packages/ray/serialization.py", line 304, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/opt/conda/lib/python3.7/site-packages/ray/serialization.py", line 264, in _serialize_to_pickle5
    raise e
  File "/opt/conda/lib/python3.7/site-packages/ray/serialization.py", line 261, in _serialize_to_pickle5
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/opt/conda/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/opt/conda/lib/python3.7/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 580, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
```

The code chunk to start the `hyperparameter_search`: 

```python
def my_hp_space(trial):
    from ray import tune
    return {
        "learning_rate": tune.uniform(1e-5, 5e-5),
        "num_train_epochs": tune.choice(range(1, 6)),
        "per_device_train_batch_size": tune.choice([2,4]),
        "weight_decay": tune.uniform(0.0, 0.3),
        "adam_epsilon": tune.loguniform(1e-10, 1e-6),
        "per_device_eval_batch_size": 32
    }
    
best_run = trainer.hyperparameter_search(
    backend="ray",
    n_trials=15,
    hp_space=my_hp_space,
    stop=None,    
    checkpoint_score_attr="training_iteration",
    keep_checkpoints_num=0
    compute_objective=lambda x: my_objective(x, metric='eval_' + used_metric)
)
```

## Expected behavior

Expect that it will not throw an error. Note that this script does work on `4.2.0`.

**Comment by cb-podsights** [comment]
I also have this issue (bump)

**Comment by LysandreJik** [comment]
Pinging @richardliaw, @amogkam

**Comment by amogkam** [comment]
@maxzzze looks like a serialization error with the Trainer. We will take a look at this, but in the meantime can you downgrade your transformers version to 4.4. Also see https://github.com/ray-project/ray/issues/15439.

**Comment by richardliaw** [comment]
So it looks like this seems to work as soon as we disable the memory tracker:

```
trainer._memory_tracker = None
```

Will it be possible to expose an API to temporarily disable this? 

The other issue is that we should have tests that catch these regressions right?

**Comment by victor-ab** [comment]
I am having the same problem.
Disabling the memory tracker worked for me.

**Comment by amogkam** [comment]
Yes, if you disable the memory tracker (pass in `skip_memory_metrics=True` into your `TrainingArguments`) then you will no longer get the pickling error.

In the next transformers release, the Ray Tune integration will automatically disable memory tracking if it's currently being enabled.

**Comment by abs-xyz** [comment]
I am facing this issue in transformers version 4.19.4.
This is the code I'm using:
```
args = TrainingArguments(
    f"{model_name}-hyperp-{task}",
    evaluation_strategy = "epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
    num_train_epochs=3,
    weight_decay=0.01,
    skip_memory_metrics=True,       # https://github.com/huggingface/transformers/issues/12177 [picking error]
)

trainer = Trainer(
    model_init=model_init,             # function to initialize model (using 'from_pretrained')
    args=args,
    train_dataset = tokenized_datasets["train"],
    eval_dataset = tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.hyperparameter_search(
    hp_space=lambda _: tune_config,
    backend="ray",
    n_trials=10,
    resources_per_trial={"cpu": 1, "gpu": 0},
    scheduler=scheduler,
    keep_checkpoints_num=1,
    checkpoint_score_attr="training_iteration",
    progress_reporter=reporter,
    local_dir="/ray_results/",
    name="tune_transformer_pbt",
    log_to_file=True,
)
```

Error:
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-50-3716493001d6>](https://localhost:8080/#) in <module>()
     33     local_dir="/ray_results/",
     34     name="tune_transformer_pbt",
---> 35     log_to_file=True,
     36 )
     37 

[/usr/local/lib/python3.7/dist-packages/transformers/trainer.py](https://localhost:8080/#) in hyperparameter_search(self, hp_space, compute_objective, n_trials, direction, backend, hp_name, **kwargs)
   2083             HPSearchBackend.WANDB: run_hp_search_wandb,
   2084         }
-> 2085         best_run = backend_dict[backend](self, n_trials, direction, **kwargs)
   2086 
   2087         self.hp_search_backend = None

[/usr/local/lib/python3.7/dist-packages/transformers/integrations.py](https://localhost:8080/#) in run_hp_search_ray(trainer, n_trials, direction, **kwargs)
    296         config=trainer.hp_space(None),
    297         num_samples=n_trials,
--> 298         **kwargs,
    299     )
    300     best_trial = analysis.get_best_trial(metric="objective", mode=direction[:3])

[/usr/local/lib/python3.7/dist-packages/ray/tune/tune.py](https://localhost:8080/#) in run(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, max_concurrent_trials, _experiment_checkpoint_dir, loggers, _remote)
    363 
    364     if not trial_executor or isinstance(trial_executor, RayTrialExecutor):
--> 365         _ray_auto_init()
    366 
    367     if _remote:

[/usr/local/lib/python3.7/dist-packages/ray/tune/tune.py](https://localhost:8080/#) in _ray_auto_init()
    876             "call `ray.init(...)` before `tune.run`."
    877         )
--> 878         ray.init()

[/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

[/usr/local/lib/python3.7/dist-packages/ray/worker.py](https://localhost:8080/#) in init(address, num_cpus, num_gpus, resources, object_store_memory, local_mode, ignore_reinit_error, include_dashboard, dashboard_host, dashboard_port, job_config, configure_logging, logging_level, logging_format, log_to_driver, namespace, runtime_env, storage, _enable_object_reconstruction, _redis_max_memory, _plasma_directory, _node_ip_address, _driver_object_store_memory, _memory, _redis_password, _temp_dir, _metrics_export_port, _system_config, _tracing_startup_hook, _node_name, **kwargs)
   1120 
   1121     for hook in _post_init_hooks:
-> 1122         hook()
   1123 
   1124     node_id = global_worker.core_worker.get_current_node_id()

[/usr/local/lib/python3.7/dist-packages/ray/tune/registry.py](https://localhost:8080/#) in flush(self)
    230                 self.references[k] = v
    231             else:
--> 232                 self.references[k] = ray.put(v)
    233         self.to_flush.clear()

[/usr/local/lib/python3.7/dist-packages/ray/_private/client_mode_hook.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

[/usr/local/lib/python3.7/dist-packages/ray/worker.py](https://localhost:8080/#) in put(value, _owner)
   1892     with profiling.profile("ray.put"):
   1893         try:
-> 1894             object_ref = worker.put_object(value, owner_address=serialize_owner_address)
   1895         except ObjectStoreFullError:
   1896             logger.info(

[/usr/local/lib/python3.7/dist-packages/ray/worker.py](https://localhost:8080/#) in put_object(self, value, object_ref, owner_address)
    305             ), "Local Mode does not support inserting with an ObjectRef"
    306 
--> 307         serialized_value = self.get_serialization_context().serialize(value)
    308         # This *must* be the first place that we construct this python
    309         # ObjectRef because an entry with 0 local references is created when

[/usr/local/lib/python3.7/dist-packages/ray/serialization.py](https://localhost:8080/#) in serialize(self, value)
    419             return RawSerializedObject(value)
    420         else:
--> 421             return self._serialize_to_msgpack(value)

[/usr/local/lib/python3.7/dist-packages/ray/serialization.py](https://localhost:8080/#) in _serialize_to_msgpack(self, value)
    398             metadata = ray_constants.OBJECT_METADATA_TYPE_PYTHON
    399             pickle5_serialized_object = self._serialize_to_pickle5(
--> 400                 metadata, python_objects
    401             )
    402         else:

[/usr/local/lib/python3.7/dist-packages/ray/serialization.py](https://localhost:8080/#) in _serialize_to_pickle5(self, metadata, value)
    359         except Exception as e:
    360             self.get_and_clear_contained_object_refs()
--> 361             raise e
    362         finally:
    363             self.set_out_of_band_serialization()

[/usr/local/lib/python3.7/dist-packages/ray/serialization.py](https://localhost:8080/#) in _serialize_to_pickle5(self, metadata, value)
    355             self.set_in_band_serialization()
    356             inband = pickle.dumps(
--> 357                 value, protocol=5, buffer_callback=writer.buffer_callback
    358             )
    359         except Exception as e:

[/usr/local/lib/python3.7/dist-packages/ray/cloudpickle/cloudpickle_fast.py](https://localhost:8080/#) in dumps(obj, protocol, buffer_callback)
     71                 file, protocol=protocol, buffer_callback=buffer_callback
     72             )
---> 73             cp.dump(obj)
     74             return file.getvalue()
     75 

[/usr/local/lib/python3.7/dist-packages/ray/cloudpickle/cloudpickle_fast.py](https://localhost:8080/#) in dump(self, obj)
    618     def dump(self, obj):
    619         try:
--> 620             return Pickler.dump(self, obj)
    621         except RuntimeError as e:
    622             if "recursion" in e.args[0]:

TypeError: can't pickle _thread.lock objects
```

**Comment by SaiSandeepKantareddy** [comment]
Hi, with transformers 4.26.1 on Sage maker I am still having this error: TypeError: cannot pickle '_thread.lock' object.

def hp_space(trial):
    return {
        "learning_rate": trial.suggest_float("learning_rate", 1e-5, 1e-3, log=True),
        "num_train_epochs": trial.suggest_int("num_train_epochs", 1, 10),
        "seed": trial.suggest_int("seed", 1, 40),
        "per_device_train_batch_size": trial.suggest_categorical("per_device_train_batch_size", [16, 32, 64]),
        "weight_decay": trial.suggest_float("weight_decay", 1e-3, 1e-1, log=True),
    }

best_run = trainer.hyperparameter_search(n_trials=20, direction="minimize", hp_space=hp_space)
