### ISSUE TITLE
PreTrainedTokenizerFast.save_pretrained() ERROR

### ISSUE THREAD

**Issue by liyucheng09** [huggingface/transformers#11397]
## Environment info

- `transformers` version: 4.1.1
- Platform: macOS-11.1-arm64-arm-64bit
- Python version: 3.9.1
- PyTorch version (GPU?): 1.8.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Description

It a bizarre error. When I run
```
from transformers import AutoTokenizer
t=AutoTokenizer.from_pretrained('distilroberta-base')
t.save_pretrained('vocab/')
```

It gives me the following errors:
```
>>> t.save_pretrained('vocab/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liyucheng/miniforge3/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2005, in save_pretrained
    return self._save_pretrained(
  File "/Users/liyucheng/miniforge3/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 528, in _save_pretrained
    vocab_files = self.save_vocabulary(save_directory, filename_prefix=filename_prefix)
  File "/Users/liyucheng/miniforge3/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 172, in save_vocabulary
    files = self._tokenizer.model.save(save_directory, name=filename_prefix)
TypeError: PyModel.save() got an unexpected keyword argument: name
```

It looks that the saving process called the `save_vocabulary` function in `gpt2/tokenization_gpt2_fast.py`. But the tokenizer I wanted to save is `distilroberta-base`.

Does anyone get some ideas?

**Comment by liyucheng09** [comment]
It is because the version of `tokenizers` lib and the version of `transformers` lib do not match.
