### ISSUE TITLE
`TypeError: TextInputSequence must be str` from Fast Tokenizer

### ISSUE THREAD

**Issue by ElvaHuang** [huggingface/transformers#11568]
### Bug

On version 4.5.1, trying to use fast tokenizer for Roberta, and got the above error. Weirdly, saw `transformers/models/gpt2/tokenization_gpt2_fast.py` in the traceback even no `gpt2` models are involved. 

**Script to reproduce**

```
from transformers import AutoTokenizer
from transformers.data.processors.utils import InputExample

if __name__ == "__main__":
    tokenizer = AutoTokenizer.from_pretrained(
        "roberta-base", use_fast=True
    )

    MAX_LENGTH = 256
    LABEL_LIST = [0, 1]
    OUTPUT_MODE = "classificaiton"

    inputs = ["Ututu goes public.", "This moon is huge."]
    examples = [InputExample(guid=str(index), text_a=text, label=None) for index, text in enumerate(inputs)]

    # this throws TypeError: TextInputSequence must be str
    batch_encoding = tokenizer(
        [(example.text_a, example.text_b) for example in examples],
        max_length=MAX_LENGTH,
        padding='max_length',
        truncation=True
    )
    print(batch_encoding)
```

**Traceback**

```
Traceback (most recent call last):
  File "tests/integration/tmp_test.py", line 22, in <module>
    truncation=True
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2271, in __call__
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2456, in batch_encode_plus
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py", line 163, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py", line 388, in _batch_encode_plus
    is_pretokenized=is_split_into_words,
TypeError: TextInputSequence must be str
```

Saw a similar issue raised for QnA pipeline, but I'm not doing QnA here. Thoughts?

**Comment by LysandreJik** [comment]
You're sending this to your tokenizer: `[(example.text_a, example.text_b) for example in examples]`

But this is: `[('Ututu goes public.', None), ('This moon is huge.', None)]`.

A tokenizer cannot handle `None`, only text.
