### ISSUE TITLE
Finetune - Helsinki-NLP/opus-mt-fr-en 

### ISSUE THREAD

**Issue by dinosaxon** [huggingface/transformers#11774]
Hi all

I am new to huggingface!

I am trying to finetune the Helsinki-NLP/opus-mt-fr-en but I am getting the error:

```
2021-05-19 14:20:33.882388: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dyn
amic library libcudart.so.11.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1205, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/marian/examples/transformers/examples/research_projects/seq2seq-distillation/finetune.py", line 442, in <m
odule>
    main(args)
  File "/marian/examples/transformers/examples/research_projects/seq2seq-distillation/finetune.py", line 381, in ma
in
    model: SummarizationModule = SummarizationModule(args)
  File "/marian/examples/transformers/examples/research_projects/seq2seq-distillation/finetune.py", line 65, in __i
nit__
    super().__init__(hparams, num_labels=None, mode=self.mode, **kwargs)
  File "/marian/examples/transformers/examples/research_projects/seq2seq-distillation/lightning_base.py", line 109,
 in __init__
    self.model = self.model_type.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 381, in from_pretrai
ned
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1207, in from_pretrained
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/marian/examples/test' at '/marian/examples/test/
pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

Could you tell me where I can set the from_tf=True?

Also, how can I convert a pytorch_model.bin to tf model?

Is there any step-by-step tutorial regarding this task?

Best

**Comment by LysandreJik** [comment]
Could you share your code so that we may help?

I believe this is covered in the quicktour! https://huggingface.co/transformers/quicktour.html

**Comment by dinosaxon** [comment]
here is my code

`python3 /marian/examples/transformers/examples/research_projects/seq2seq-distillation/finetune.py \
 --learning_rate=3e-5 \
 --fp16 \
 --gpus 1 \
 --do_train \
 --do_predict \
 --n_val 1000 \
 --val_check_interval 0.1 \
 --src_lang "fr" \
 --tgt_lang "en" \
 --num_train_epochs 400 \
 --warmup_steps 20 \
 --train_batch_size 10 \
 --eval_batch_size 10 \
 --data_dir "/marian/examples/test/data" \
 --output_dir "/marian/examples/test/out" \
 --cache_dir "/marian/examples/test/cache" \
 --max_source_length 128 \
 --max_target_length 128 \
 --val_max_target_length 128 \
 --test_max_target_length 128 \
 --model_name_or_path "/marian/examples/test"
 "$@"`

**Comment by dinosaxon** [comment]
Thank you, I will give it a try
