### ISSUE TITLE
Trainer API

### ISSUE THREAD

**Issue by kruthikakr** [huggingface/transformers#11991]
I am using Trainer API to pretrain BERT model 

Start training...
Traceback (most recent call last):
  File "/home/kruthika/PycharmProjects/huggingfaceBert/pretrain_transformers_pytorch.py", line 451, in <module>
    trainer.train(model_path=model_path)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/transformers/trainer.py", line 1208, in train
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/transformers/trainer_callback.py", line 340, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/transformers/trainer_callback.py", line 388, in call_event
    **kwargs,
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/transformers/integrations.py", line 717, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/transformers/integrations.py", line 694, in setup
    **init_args,
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 747, in init
    wi.setup(kwargs)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 154, in setup
    wandb_login._login(anonymous=anonymous, force=force, _disable_warning=True)
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 238, in _login
    wlogin.prompt_api_key()
  File "/home/kruthika/PycharmProjects/huggingfaceBert/venv/lib/python3.6/site-packages/wandb/sdk/wandb_login.py", line 174, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])

Process finished with exit code 1

**Comment by LysandreJik** [comment]
Maybe @borisdayma @sgugger have an idea

**Comment by borisdayma** [comment]
What is your environment?
Can you try to call `wandb login` in the console before running your script? You typically only have to do it once.
Otherwise you can always use you key and login within your script or use environment variables.
