### ISSUE TITLE
some issue in FlaxBertForMultipleChoice

### ISSUE THREAD

**Issue by vasudevgupta7** [huggingface/transformers#12009]
## Environment info

- `transformers` version: 4.7.0.dev0
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.1 (False)
- Tensorflow version (GPU?): 2.5.0 (False)
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

Model I am using (Bert, XLNet ...): Bert

## To reproduce

```python3
from transformers import BertConfig, FlaxBertForMultipleChoice
import numpy as np
model = FlaxBertForMultipleChoice(BertConfig())

model(np.ones((1, 4)))
```

Output

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vasudevgupta/Local/transformers/src/transformers/models/bert/modeling_flax_bert.py", line 600, in __call__
    return self.module.apply(
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/flax/linen/module.py", line 936, in apply
    return apply(
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/flax/core/scope.py", line 687, in wrapper
    y = fn(root, *args, **kwargs)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/flax/linen/module.py", line 1178, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/flax/linen/module.py", line 275, in wrapped_module_method
    y = fun(self, *args, **kwargs)
  File "/Users/vasudevgupta/Local/transformers/src/transformers/models/bert/modeling_flax_bert.py", line 1022, in __call__
    reshaped_logits = logits.reshape(-1, num_choices)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1322, in _reshape
    newshape = _compute_newshape(a, args[0] if len(args) == 1 else args)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1316, in _compute_newshape
    return tuple(- core.divide_shape_sizes(np.shape(a), newshape)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1316, in <genexpr>
    return tuple(- core.divide_shape_sizes(np.shape(a), newshape)
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/jax/core.py", line 1360, in divide_shape_sizes
    return handler.divide_shape_sizes(ds[:len(s1)], ds[len(s1):])
  File "/Users/vasudevgupta/miniconda3/lib/python3.8/site-packages/jax/core.py", line 1280, in divide_shape_sizes
    raise InconclusiveDimensionOperation(f"Cannot divide evenly the sizes of shapes {tuple(s1)} and {tuple(s2)}")
jax.core.InconclusiveDimensionOperation: Cannot divide evenly the sizes of shapes (1, 1) and (-1, 4)
```

I am probably missing something here. Please help me to figure out the issue here.

@LysandreJik @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Ah I see! 

So multiple choice is actually the only class where the `input_ids` have to be of shape `(batch_size, num_choices, seq_length)` instead of `(batch_size, seq_length)` (see [docs](https://huggingface.co/transformers/model_doc/bert.html?highlight=flaxbert#flaxbertformultiplechoice) here).

This means that the code example should be changed to:

```python
from transformers import BertConfig, FlaxBertForMultipleChoice
import numpy as np
model = FlaxBertForMultipleChoice(BertConfig())

model(np.ones((1, 1, 4)))
```
in order to work :-)

**Comment by vasudevgupta7** [comment]
Okay. I missed that😅. Sorry for this simple issue. I will fix bigbird also accordingly.

**Comment by patrickvonplaten** [comment]
Absolutely no worries ;-)
