### ISSUE TITLE
ImportError: cannot import name 'AutoTokenizer' from 'transformers'

### ISSUE THREAD

**Issue by Fushier** [huggingface/transformers#12046]
transformers: 4.6.1
tokenizers: 0.10.3

I installed transformers with 
`conda install -c huggingface transformers`
but when I `from transformers import AutoTokenizer`

Traceback (most recent call last):
  File "D:/IIE/WorkSpace/Pycharm WorkSpace/HuggingfaceNER/tokenizers.py", line 1, in <module>
    from transformers import AutoTokenizer
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\__init__.py", line 48, in <module>
    from .data import (
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\data\__init__.py", line 6, in <module>
    from .processors import (
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\data\processors\__init__.py", line 5, in <module>
    from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\data\processors\glue.py", line 25, in <module>
    from ...tokenization_utils import PreTrainedTokenizer
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\tokenization_utils.py", line 26, in <module>
    from .tokenization_utils_base import (
  File "D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\tokenization_utils_base.py", line 31, in <module>
    from tokenizers import AddedToken
  File "D:\IIE\WorkSpace\Pycharm WorkSpace\HuggingfaceNER\tokenizers.py", line 1, in <module>
    from transformers import AutoTokenizer
ImportError: cannot import name 'AutoTokenizer' from 'transformers' (D:\Environment\Anaconda3\envs\huggingface\lib\site-packages\transformers\__init__.py)

It even worked well yesterday, and I didn't upgrade anything...

**Comment by NeevrajKB** [comment]
same issue

**Comment by wertyhb-sns** [comment]
你好 我们是一样的问题 你解决了吗？

**Comment by ZaidArman** [comment]
Same Issue :(

**Comment by amyeroberts** [comment]
@ZaidArman Could you confirm your running environment, how transformers was installed and a code snippet to reproduce? I'm unable to replicate this on `main`
