### ISSUE TITLE
got multiple values for argument 'input_shape'

### ISSUE THREAD

**Issue by garner1** [huggingface/transformers#12128]
## Environment info
- `transformers` version: 4.6.1
- Platform: Linux-4.14.232-176.381.amzn2.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.7.9
- PyTorch version (GPU?): 1.8.1+cu102 (True)
- Tensorflow version (GPU?): 2.5.0 (True)
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: No

### Who can help
@TevenLeScao, @Patrickvonplaten

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. bash transformers/examples/research_projects/performer/sanity_script.sh

[05:45:53] - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False
[05:45:53] - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir=experiments, overwrite_output_dir=True, do_train=True, do_eval=False, do_predict=False, evaluation_strategy=IntervalStrategy.NO, prediction_loss_only=False, per_device_train_batch_size=4, per_device_eval_batch_size=8, gradient_accumulation_steps=1, eval_accumulation_steps=None, learning_rate=0.0005, weight_decay=0.0, adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=3.0, max_steps=-1, lr_scheduler_type=SchedulerType.LINEAR, warmup_ratio=0.0, warmup_steps=100, logging_dir=runs/Jun12_05-45-53_ip-10-228-58-93.int.klarna.net, logging_strategy=IntervalStrategy.STEPS, logging_first_step=False, logging_steps=500, save_strategy=IntervalStrategy.STEPS, save_steps=500, save_total_limit=None, no_cuda=False, seed=42, fp16=False, fp16_opt_level=O1, fp16_backend=auto, fp16_full_eval=False, local_rank=-1, tpu_num_cores=None, tpu_metrics_debug=False, debug=[], dataloader_drop_last=False, eval_steps=500, dataloader_num_workers=0, past_index=-1, run_name=experiments, disable_tqdm=False, remove_unused_columns=True, label_names=None, load_best_model_at_end=False, metric_for_best_model=None, greater_is_better=None, ignore_data_skip=False, sharded_ddp=[], deepspeed=None, label_smoothing_factor=0.0, adafactor=False, group_by_length=False, length_column_name=length, report_to=['tensorboard'], ddp_find_unused_parameters=None, dataloader_pin_memory=True, skip_memory_metrics=False, use_legacy_prediction_loop=False, push_to_hub=False, resume_from_checkpoint=None, _n_gpu=1, mp_parameters=)
[05:45:53] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): s3.amazonaws.com:443
[05:45:53] - DEBUG - urllib3.connectionpool -   https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:53] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:54] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:54] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:54] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/dataset_infos.json HTTP/1.1" 200 0
[05:45:54] - WARNING - datasets.builder -   Reusing dataset wikipedia (/home/silvano.garnerone/.cache/huggingface/datasets/wikipedia/20200501.simple/1.0.0/2fe8db1405aef67dff9fcc51e133e1f9c5b0106f9d9e9638188176d278fd5ff1)
[05:45:54] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): s3.amazonaws.com:443
[05:45:54] - DEBUG - urllib3.connectionpool -   https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:54] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:54] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:54] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:55] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/dataset_infos.json HTTP/1.1" 200 0
[05:45:55] - WARNING - datasets.builder -   Reusing dataset wikipedia (/home/silvano.garnerone/.cache/huggingface/datasets/wikipedia/20200501.simple/1.0.0/2fe8db1405aef67dff9fcc51e133e1f9c5b0106f9d9e9638188176d278fd5ff1)
[05:45:55] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): s3.amazonaws.com:443
[05:45:55] - DEBUG - urllib3.connectionpool -   https://s3.amazonaws.com:443 "HEAD /datasets.huggingface.co/datasets/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:55] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:55] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/wikipedia.py HTTP/1.1" 200 0
[05:45:55] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): raw.githubusercontent.com:443
[05:45:55] - DEBUG - urllib3.connectionpool -   https://raw.githubusercontent.com:443 "HEAD /huggingface/datasets/1.8.0/datasets/wikipedia/dataset_infos.json HTTP/1.1" 200 0
[05:45:55] - WARNING - datasets.builder -   Reusing dataset wikipedia (/home/silvano.garnerone/.cache/huggingface/datasets/wikipedia/20200501.simple/1.0.0/2fe8db1405aef67dff9fcc51e133e1f9c5b0106f9d9e9638188176d278fd5ff1)
[05:45:55] - INFO - absl -   Starting the local TPU driver.
[05:45:55] - INFO - absl -   Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
[05:45:55] - INFO - absl -   Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
[05:45:56] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): huggingface.co:443
[05:45:56] - DEBUG - urllib3.connectionpool -   https://huggingface.co:443 "HEAD /bert-base-cased/resolve/main/config.json HTTP/1.1" 200 0
[05:45:56] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): huggingface.co:443
[05:45:56] - DEBUG - urllib3.connectionpool -   https://huggingface.co:443 "HEAD /bert-base-cased/resolve/main/config.json HTTP/1.1" 200 0
[05:45:56] - DEBUG - urllib3.connectionpool -   Starting new HTTPS connection (1): huggingface.co:443
[05:45:57] - DEBUG - urllib3.connectionpool -   https://huggingface.co:443 "HEAD /bert-base-cased/resolve/main/flax_model.msgpack HTTP/1.1" 302 0
Traceback (most recent call last):
  File "run_mlm_performer.py", line 543, in <module>
    dropout_rate=0.1,
  File "/home/silvano.garnerone/.local/lib/python3.7/site-packages/transformers/modeling_flax_utils.py", line 326, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/silvano.garnerone/performer/modeling_flax_performer.py", line 482, in __init__
    super().__init__(config, module, input_shape=input_shape, seed=seed, dtype=dtype) #input_shape is already present in config
TypeError: __init__() got multiple values for argument 'input_shape'
## Expected behavior

The script to run without error

**Comment by garner1** [comment]
Hi, 
It seems to me that `input_shape` is defined twice inside super().init(...), probably both in 'config' and 'input_shape'.
Thanks for helping!

**Comment by patrickvonplaten** [comment]
Hey @garner1, 

Would you like to open a PR to fix it in `research_projects/performer/`?
