### ISSUE TITLE
RuntimeError: Could not infer dtype of numpy.int64 on Squad T5

### ISSUE THREAD

**Issue by helloworld123-lab** [huggingface/transformers#12141]
Hello,

I try to run the code for T5 on Squad dataset in [https://colab.research.google.com/github/patil-suraj/exploring-T5/blob/master/T5_on_TPU.ipynb](url)
I install the required libraries as:
```
!pip install transformers==2.9.1
!pip install -U nlp
!pip install sentencepiece
```
I fixed the xla error as in [https://stackoverflow.com/questions/67257008/oserror-libmkl-intel-lp64-so-1-cannot-open-shared-object-file-no-such-file-or](url)

However, when the training starts, it gives the following error:
Exception in thread Thread-17:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch_xla/distributed/parallel_loader.py", line 139, in _loader_worker
    _, data = next(data_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/nlp/arrow_dataset.py", line 719, in __getitem__
    format_kwargs=self._format_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/nlp/arrow_dataset.py", line 707, in _getitem
    format_kwargs=format_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/nlp/arrow_dataset.py", line 619, in _convert_outputs
    v = map_nested(command, v, **map_nested_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nlp/utils/py_utils.py", line 191, in map_nested
    return function(data_struct)
RuntimeError: Could not infer dtype of numpy.int64
```

**Comment by wanglec** [comment]
I think this issue is still occuring.

**Comment by patil-suraj** [comment]
Hi @wanglec , that's an old notebook and has not been updated since, so I don't recommend it anymore.
There's a new example in transformers for fine-tuning T5 for qa, [here](https://github.com/huggingface/transformers/tree/master/examples/pytorch/question-answering#fine-tuning-t5-on-squad20). It also uses `Trainer`, so supports training on TPUs. [Here's](https://github.com/huggingface/transformers/tree/master/examples/pytorch#running-on-tpus) a short guide about how to run these scripts on tpu
