### ISSUE TITLE
Exception during hyperparameter search with Ray and transformers library starting from version 4.5.0

### ISSUE THREAD

**Issue by sven-h** [huggingface/transformers#12177]
I currently face the problem that with recent versions of the transformers library (issue starting at version 4.5.0)
the hyperparameter search with ray tune runs into a serialization issue described below.

## Environment info
- `transformers` version: 4.5.0
- Platform: Linux-4.19.0-16-amd64-x86_64-with-glibc2.17
- Python version: 3.8.10
- PyTorch version (GPU?): 1.8.1+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no
- Ray version: 1.4.0 

### Who can help
Maybe it is interesting to @richardliaw and @amogkam because they were mentioned as responsible for ray/raytune.

## Information

Model I am using (Bert, XLNet ...): distilbert-base-uncased ( model doesn't matter)

The problem arises when using:
* [ x] my own modified scripts: (give details below)

The tasks I am working on is:
* [x ] an official GLUE/SQUaD task: (give the name): GLUE mrpc

## To reproduce

I have created a small working example which shows the error which (at least) I get:.
The code is mainly based on the [blog entry covering ray tune](https://huggingface.co/blog/ray-tune)

```python
import os
os.environ['TOKENIZERS_PARALLELISM'] = 'false'

from datasets import load_dataset, load_metric
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from ray import tune
from ray.util import inspect_serializability

model_name = 'distilbert-base-uncased'

tokenizer = AutoTokenizer.from_pretrained(model_name)
dataset = load_dataset('glue', 'mrpc')


def encode(examples):
    outputs = tokenizer(examples['sentence1'], examples['sentence2'], truncation=True)
    return outputs

encoded_dataset = dataset.map(encode, batched=True)

def model_init():
    return AutoModelForSequenceClassification.from_pretrained(model_name, return_dict=True)

def compute_metrics(eval_pred):
    metric = load_metric('glue', 'mrpc')
    predictions, labels = eval_pred
    predictions = predictions.argmax(axis=-1)
    return metric.compute(predictions=predictions, references=labels)

training_args = TrainingArguments("test")

trainer = Trainer(
    args=training_args,
    tokenizer=tokenizer,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    model_init=model_init,
    compute_metrics=compute_metrics,
)

def search_params(trial):
    return {
        #toy example
        "learning_rate": tune.grid_search([0.000001, 0.00001, 0.0001, 0.001]),
    }
    
trainer.hyperparameter_search(
    direction="maximize", 
    backend="ray", 
    hp_space = search_params,
    n_trials=1,
)
```

This code snippet works with transformers version 4.4.2 and ealier but not on versions 4.5.0 and later.

The error which appeared is
```python
Traceback (most recent call last):
  File "working_example.py", line 48, in <module>
    trainer.hyperparameter_search(
  File "/site-packages/transformers/trainer.py", line 1459, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/site-packages/transformers/integrations.py", line 231, in run_hp_search_ray
    analysis = ray.tune.run(
  File "/site-packages/ray/tune/tune.py", line 297, in run
    _ray_auto_init()
  File "/site-packages/ray/tune/tune.py", line 664, in _ray_auto_init
    ray.init()
  File "/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/site-packages/ray/worker.py", line 866, in init
    hook()
  File "/site-packages/ray/tune/registry.py", line 171, in flush
    self.references[k] = ray.put(v)
  File "/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/site-packages/ray/worker.py", line 1527, in put
    object_ref = worker.put_object(value)
  File "/site-packages/ray/worker.py", line 280, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/site-packages/ray/serialization.py", line 326, in serialize
    return self._serialize_to_msgpack(value)
  File "/site-packages/ray/serialization.py", line 306, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/site-packages/ray/serialization.py", line 266, in _serialize_to_pickle5
    raise e
  File "/site-packages/ray/serialization.py", line 262, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 580, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.RLock' object
```

Based on this error, I searched for code to check which part is not serializable (because the whole trainer is transferred to each ray trial). I found the [ray serialization page](https://docs.ray.io/en/master/serialization.html#troubleshooting) and executed
```python
inspect_serializability(trainer, name="test")
```
The output was:

```
================================================================================
Checking Serializability of <transformers.trainer.Trainer object at 0x7fce1cbbeee0>
================================================================================
!!! FAIL serialization: cannot pickle '_thread.RLock' object
    Serializing 'compute_metrics' <function compute_metrics at 0x7fce1cb5b5e0>...
    Serializing 'model_init' <function model_init at 0x7fce1cb5b550>...
    Serializing '_gather_and_numpify' <bound method Trainer._gather_and_numpify of <transformers.trainer.Trainer object at 0x7fce1cbbeee0>>...
    !!! FAIL serialization: cannot pickle '_thread.RLock' object
        Serializing '__func__' <function Trainer._gather_and_numpify at 0x7fce1f739940>...
    WARNING: Did not find non-serializable object in <bound method Trainer._gather_and_numpify of <transformers.trainer.Trainer object at 0x7fce1cbbeee0>>. This may be an oversight.
================================================================================
Variable:

        FailTuple(_gather_and_numpify [obj=<bound method Trainer._gather_and_numpify of <transformers.trainer.Trainer object at 0x7fce1cbbeee0>>, parent=<transformers.trainer.Trainer object at 0x7fce1cbbeee0>])

was found to be non-serializable. There may be multiple other undetected variables that were non-serializable.
Consider either removing the instantiation/imports of these variables or moving the instantiation into the scope of the function/class.
If you have any suggestions on how to improve this error message, please reach out to the Ray developers on github.com/ray-project/ray/issues/
================================================================================
```

I did not find any major changes between version 4.4.2 and 4.5.0 with regards to integrations.py and trainer.py.

I think the first step would be, that someone else reproduce the behaviour if possible (maybe something is also wrong on my side/setup).

**Comment by amogkam** [comment]
Hey @sven-h yes this is a known issue, same as https://github.com/huggingface/transformers/issues/11249.

From this thread:

> If you disable the memory tracker (pass in skip_memory_metrics=True into your TrainingArguments) then you will no longer get the pickling error. In the next transformers release, the Ray Tune integration will automatically disable memory tracking if it's currently being enabled.

**Comment by sven-h** [comment]
Hi @amogkam
thanks for the fast reply and the answer.

**Comment by ledondodo** [comment]
Hey, I have a similar issue which cannot be resolved with skip_memory_metrics=True.

**Environment**
python 3.13.11 (main, Jan 28 2026, 00:01:45) [Clang 21.1.4 ]
transformers 4.57.3
torch 2.9.1+cu128
ray[tune] 2.54.0
cuda_available True
cuda_version 12.8
device NVIDIA GeForce RTX 4060 Laptop GPU
OS Linux 6.14.0-37-generic

**Code**

```
class CustomTrainer(Trainer):
    def __init__(self, loss_func, **kwargs):
        super().__init__(**kwargs)
        self.loss_func = loss_func

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=0):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        loss = self.loss_func(outputs.logits, labels)
        return (loss, outputs) if return_outputs else loss

...

class TrainerPipeline:

def init_model(self):
        init_seed(self.config.seed)
        set_seed(self.config.seed)
        return AutoModelForAudioClassification.from_pretrained(
            self.config.pretrained_model,
            ignore_mismatched_sizes=True,
            num_labels=len(self.id2label),
            id2label=self.id2label,
            label2id=self.label2id,
            attn_implementation="sdpa",
            problem_type="multi_label_classification",
        )

...

TrainingArguments(
            output_dir=outpath or self.save_path,
            eval_strategy="epoch",
            save_strategy="epoch",
            learning_rate=self.config.learning_rate,
            num_train_epochs=nepochs,
            per_device_train_batch_size=self.config.batch_size,
            gradient_accumulation_steps=self.config.gradient_accumulation_steps,
            per_device_eval_batch_size=self.config.batch_size,
            warmup_ratio=self.config.warmup_ratio,
            load_best_model_at_end=True,
            save_total_limit=1,
            metric_for_best_model="eval_loss",
            greater_is_better=False,
            dataloader_pin_memory=self.device == "cuda",
            seed=self.config.seed,
            data_seed=self.config.seed,
            logging_strategy="epoch",
            skip_memory_metrics=True,
        )

...

CustomTrainer(
            model=None,
            model_init=self.init_model,
            args=training_args,
            train_dataset=train_set,
            eval_dataset=eval_set,
            processing_class=self.feature_extractor,
            compute_metrics=None if self.use_multitag else self.compute_metrics,
            callbacks=[EarlyStoppingCallback(early_stopping_patience=patience)],
            loss_func=FocalLoss(self.use_multitag, alpha=0.25, weight=w),
        )

...

def train(self, ...):

        best_trial = trainer.hyperparameter_search(backend="ray", n_trials=5, direction="minimize")

```

**Output**

```

Traceback (most recent call last):
  File ".../__main__.py", line 54, in __init__
    self.process()
    ~~~~~~~~~~~~^^
  File ".../__main__.py", line 325, in process
    self.args.func(self.args)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File ".../__main__.py", line 316, in cmd_train
    pipeline.train(nepochs=args.epochs, patience=args.patience)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../nn/scripts/train.py", line 307, in train
    best_trial = trainer.hyperparameter_search(
        backend="ray",
        n_trials=self.hp_trials,
        direction="minimize",
    )
  File ".../.venv/lib/python3.13/site-packages/transformers/trainer.py", line 3767, in hyperparameter_search
    best_run = backend_obj.run(self, n_trials, direction, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/transformers/hyperparameter_search.py", line 87, in run
    return run_hp_search_ray(trainer, n_trials, direction, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/transformers/integrations/integration_utils.py", line 438, in run_hp_search_ray
    analysis = ray.tune.run(
        dynamic_modules_import_trainable,
    ...<2 lines>...
        **kwargs,
    )
  File ".../.venv/lib/python3.13/site-packages/ray/tune/tune.py", line 527, in run
    _ray_auto_init(entrypoint=error_message_map["entrypoint"])
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/ray/tune/tune.py", line 252, in _ray_auto_init
    ray.init()
    ~~~~~~~~^^
  File ".../.venv/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/ray/_private/worker.py", line 2042, in init
    hook()
    ~~~~^^
  File ".../.venv/lib/python3.13/site-packages/ray/tune/registry.py", line 318, in flush
    self.references[k] = ray.put(v)
                         ~~~~~~~^^^
  File ".../.venv/lib/python3.13/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
  File ".../.venv/lib/python3.13/site-packages/ray/_private/worker.py", line 3070, in put
    object_ref = worker.put_object(
        value,
        owner_address=serialize_owner_address,
        _tensor_transport=_tensor_transport,
    )
  File ".../.venv/lib/python3.13/site-packages/ray/_private/worker.py", line 866, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File ".../.venv/lib/python3.13/site-packages/ray/_private/serialization.py", line 752, in serialize
    return self._serialize_to_msgpack(value)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File ".../.venv/lib/python3.13/site-packages/ray/_private/serialization.py", line 669, in _serialize_to_msgpack
    pickle5_serialized_object = self._serialize_to_pickle5(
        metadata, python_objects
    )
  File ".../.venv/lib/python3.13/site-packages/ray/_private/serialization.py", line 616, in _serialize_to_pickle5
    raise e
  File ".../.venv/lib/python3.13/site-packages/ray/_private/serialization.py", line 611, in _serialize_to_pickle5
    inband = pickle.dumps(
        value, protocol=5, buffer_callback=writer.buffer_callback
    )
  File ".../.venv/lib/python3.13/site-packages/ray/cloudpickle/cloudpickle.py", line 1479, in dumps
    cp.dump(obj)
    ~~~~~~~^^^^^
  File ".../.venv/lib/python3.13/site-packages/ray/cloudpickle/cloudpickle.py", line 1245, in dump
    return super().dump(obj)
           ~~~~~~~~~~~~^^^^^
  File ".../.venv/lib/python3.13/site-packages/torch/nn/utils/parametrize.py", line 340, in getstate
    raise RuntimeError(
    ...<4 lines>...
    )
RuntimeError: Serialization of parametrized modules is only supported through state_dict(). See:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training
```

The error seems to come from:

transformers/integrations/integration_utils.py: run_hp_search_ray, line 395
gives the trainer in kwargs to ray tune with_parameters
`    trainable = ray.tune.with_parameters(_objective, local_trainer=trainer)`

ray/tune/trainable/util.py: with_parameters , line 106
which fails to register the trainer in kwargs
```
for k, v in kwargs.items():
        parameter_registry.put(prefix + k, v)
```

**Comment by ledondodo** [comment]
maybe @richardliaw @amogkam can help as they were mentioned as responsible for ray/raytune.
