### ISSUE TITLE
MLM training fails with no validation file

### ISSUE THREAD

**Issue by Souvic** [huggingface/transformers#12406]
## Environment info

- `transformers` version: 4.9.0.dev0
- Platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.10
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): 2.5.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

## Information

Model I am using (Bert, XLNet ...): distilbert-base-cased

The problem arises when using: the official example scripts: (give details below)

The tasks I am working on is: MLM finetuning

## To reproduce

1. Just run the tensorflow  examples
2. python3 ./transformers/examples/tensorflow/language-modeling/run_mlm.py\
 --model_name_or_path distilbert-base-cased \
 --output_dir ./g \
 --train_file "customdata.txt" \
3. The model fails with error message that no validation file is there.

## Expected behavior
it should use the validation split percentage parameter to divide the training set into training and eval samples.

**Comment by Souvic** [comment]
Log:
Grouping texts in chunks of 512: 100% 87/87 [00:26<00:00,  3.25ba/s]
Traceback (most recent call last):
  File "./transformers/examples/tensorflow/language-modeling/run_mlm.py", line 604, in <module>
    main()
  File "./transformers/examples/tensorflow/language-modeling/run_mlm.py", line 493, in main
    eval_dataset = tokenized_datasets["validation"]
  File "/usr/local/lib/python3.7/dist-packages/datasets/dataset_dict.py", line 37, in __getitem__
    return super().__getitem__(k)
KeyError: 'validation'

**Comment by Souvic** [comment]
Fixed.
