### ISSUE TITLE
`transformers-cli env` doesn't work out-of-the-box on v3-8 TPU

### ISSUE THREAD

**Issue by cakiki** [huggingface/transformers#12509]
**Running `transformers-cli env` returns the following stack trace**
```bash
(gpt-2-german) christopher@t1v-n-97918dcd-w-0:~$ transformers-cli env
Traceback (most recent call last):
  File "/home/christopher/gpt-2-german/bin/transformers-cli", line 33, in <module>
    sys.exit(load_entry_point('transformers', 'console_scripts', 'transformers-cli')())
  File "/home/christopher/gpt-2-german/bin/transformers-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/christopher/transformers/src/transformers/commands/transformers_cli.py", line 23, in <module>
    from .run import RunCommand
  File "/home/christopher/transformers/src/transformers/commands/run.py", line 17, in <module>
    from ..pipelines import SUPPORTED_TASKS, TASK_ALIASES, Pipeline, PipelineDataFormat, pipeline
  File "/home/christopher/transformers/src/transformers/pipelines/__init__.py", line 26, in <module>
    from ..models.auto.feature_extraction_auto import FEATURE_EXTRACTOR_MAPPING, AutoFeatureExtractor
  File "/home/christopher/transformers/src/transformers/models/auto/feature_extraction_auto.py", line 20, in <module>
    from transformers import DeiTFeatureExtractor, Speech2TextFeatureExtractor, ViTFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/christopher/transformers/src/transformers/__init__.py", line 3060, in __getattr__
    return super().__getattr__(name)
  File "/home/christopher/transformers/src/transformers/file_utils.py", line 1890, in __getattr__
    value = getattr(module, name)
  File "/home/christopher/transformers/src/transformers/file_utils.py", line 1889, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/christopher/transformers/src/transformers/models/speech_to_text/__init__.py", line 82, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/christopher/transformers/src/transformers/models/speech_to_text/feature_extraction_speech_to_text.py", line 23, in <module>
    import torchaudio.compliance.kaldi as ta_kaldi
  File "/home/christopher/gpt-2-german/lib/python3.8/site-packages/torchaudio/__init__.py", line 13, in <module>
    from torchaudio.backend import (
  File "/home/christopher/gpt-2-german/lib/python3.8/site-packages/torchaudio/backend/__init__.py", line 2, in <module>
    from . import utils
  File "/home/christopher/gpt-2-german/lib/python3.8/site-packages/torchaudio/backend/utils.py", line 7, in <module>
    from . import (
  File "/home/christopher/gpt-2-german/lib/python3.8/site-packages/torchaudio/backend/soundfile_backend.py", line 11, in <module>
    import soundfile
  File "/home/christopher/gpt-2-german/lib/python3.8/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

## Environment info

- `transformers` version: '4.9.0.dev0' (editable pip install from `git` source)
- Platform: TPU v3-8 (Operating System: Ubuntu 20.04.2 LTS, Kernel: Linux 5.4.0-1043-gcp, Architecture: x86-64)
- Python version: Python 3.8.10 [GCC 9.4.0] on linux
- PyTorch version (GPU?): '1.9.0+cu102' (extras['all'])
- Tensorflow version (GPU?): '2.5.0' (extras['all'])
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: Yes

### Who can help

@patrickvonplaten and @patil-suraj 

## Information

Model I am using: roBERTa

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [X] my own task or dataset: (give details below)

## To reproduce

1. Run the `env` subcommand on a v3-8  TPU

## Expected behavior

The environment information to be printed out

**Comment by patil-suraj** [comment]
@LysandreJik do we need all `dev` dependencies for `transformers-cli` ?

**Comment by LysandreJik** [comment]
Not 100% sure, but I think the issue comes from having `torchaudio` installed but not `sndfile`

It's not required to have all the `dev` dependencies for `transformers-cli`.
