### ISSUE TITLE
Facing Issue while loading pytorch model as flax model

### ISSUE THREAD

**Issue by bhadreshpsavani** [huggingface/transformers#12603]
I am trying to convert pytorch model in flax so i can train in downstream task
I wrote converting script like this
```python
from transformers import AutoConfig, FlaxAutoModelForMaskedLM
config = AutoConfig.from_pretrained("./")
model = FlaxAutoModelForMaskedLM.from_pretrained("./", from_pt=True,  config=config)
model.save_pretrained("./")
```
By taking this [reference](https://huggingface.co/transformers/model_doc/auto.html#transformers.FlaxAutoModelForSeq2SeqLM)
This was the logs
```
Traceback (most recent call last):
  File "convert_to_flax.py", line 3, in <module>
    model = FlaxAutoModelForMaskedLM.from_pretrained("./", from_pt=True,  config=config)
  File "/home/bhadresh/transformers/src/transformers/models/auto/auto_factory.py", line 387, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: FlaxAutoModelForMaskedLM.
Model type should be one of RobertaConfig, BertConfig, BigBirdConfig, BartConfig, ElectraConfig.
```

**Comment by bhadreshpsavani** [comment]
using `FlaxAutoModelForSeq2SeqLM` solved the issue, It was typing mistake
