### ISSUE TITLE
Can't load pretrained model when working in virtual environment

### ISSUE THREAD

**Issue by aclifton314** [huggingface/transformers#12659]
## Environment info

- `transformers` version: 4.8.2
- Platform: Pytorch
- Python version: 3.7.6
- PyTorch version (GPU?): 1.9.0 no GPU
- Using GPU in script?:  No.
- Using distributed or parallel set-up in script?: No

### Who can help
@LysandreJik

## Information
Using Bert, specifically BertForSequenceClassification

## To reproduce

1. Create a virtual environment `python -m venv <name_of_env>`
2. `pip install transformers`
3. `source /path/to/venv/bin/activate`
4. Try to load the BertForSequenceClassification model

Here is a code snippet:
```python
from transformers import BertForSequenceClassification
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
```

Below is the error message I get:
```python
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/connection.py", line 506, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/aclifton/anaconda3/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/home/aclifton/anaconda3/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/home/aclifton/anaconda3/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/configuration_utils.py", line 505, in get_config_dict
    user_agent=user_agent,
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/file_utils.py", line 1337, in cached_path
    local_files_only=local_files_only,
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/file_utils.py", line 1499, in get_from_cache
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=etag_timeout)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/api.py", line 104, in head
    return request('head', url, **kwargs)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/config.json (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1086, in from_pretrained
    **kwargs,
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/configuration_utils.py", line 440, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/aclifton/venvs/hf_test/lib/python3.7/site-packages/transformers/configuration_utils.py", line 517, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a config.json file
```

## Expected behavior
I had expected that the virtual environment would not affect the download or declaring the `model` variable.

If I don't run the virtual environment, the above code works. I believe I have located the models in the `~/.cache/huggingface/transformers` directory so if there is a particular place those should be copied to in the `/path/to/venv/` directory let me know. I tried just copying `~/.cache/huggingface` to `/path/to/venv/` and still get the same error.

I will also mention that I am working behind a proxy, but setting the `proxies` parameter doesn't seem to help either. That being said, I do have the model in `~/.cache/huggingface/transformers` and the proxy does not affect the above code snippet when running without the virtual environment. Thanks in advance for your help!

**UPDATE**
I changed from `transformers 4.8.2` to `transformers 4.4.2` and the problem goes away.

**Comment by LysandreJik** [comment]
Hello! There shouldn't be any difference between using the system-wide environment vs the virtual environment. We mostly use virtual environments to work on `transformers` and we heavily recommend using one when working with `transformers`. 

Are you sure the error comes from the virtual environment and now from another setup issue?

**Comment by aclifton314** [comment]
@LysandreJik If I run:
```python
from transformers import BertForSequenceClassification
model = BertForSequenceClassification.from_pretrained('bert-base-uncased')
```
using the system-wide environment, then everything works fine. If I activate the venv and run the exact same code, I get the above error. I'm not sure if there is other information I can provide you that would be useful, but I don't change anything in the setup.

Making the system-wide and venv `transformers` version `4.4.2` resolves the error. Making the venv `transformers` version `4.8.2` reproduces the error.
