### ISSUE TITLE
Can't load config for [community model] : DeepESP/gpt2-spanish 

### ISSUE THREAD

**Issue by ruanchaves** [huggingface/transformers#12773]
## Environment info

- `transformers` version: 3.3.1
- Platform: Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
- 
### Who can help

@julien-c 

@mfuntowicz 

## Information

`DeepESP/gpt2-spanish` is not recognized as a community model. 

Same issue as #6226 and #6688. 

As you can see from previous issues, this was supposedly fixed past year but for some reason this bug is back again.

## To reproduce

```
from transformers import AutoConfig
config = AutoConfig.from_pretrained("DeepESP/gpt2-spanish")
```

This will result in the following error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 359, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 310, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 368, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'DeepESP/gpt2-spanish'. Make sure that:

- 'DeepESP/gpt2-spanish' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'DeepESP/gpt2-spanish' is the correct path to a directory containing a config.json file
```

## Expected behavior

`DeepESP/gpt2-spanish` should be recognized as a community model on `AutoConfig`.

**Comment by ruanchaves** [comment]
Solved by upgrading `transformers` to a higher version.
