### ISSUE TITLE
`transformers-cli` fails out of the box

### ISSUE THREAD

**Issue by StellaAthena** [huggingface/transformers#12838]
## Environment info
I was unable to run `transformers-cli`

- `transformers` version: `transformers-4.9.0.dev0`
- Platform: Mac OS
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.1
- Tensorflow version (GPU?): 2.5.0
- Using GPU in script?: n/a
- Using distributed or parallel set-up in script?: n/a

### Who can help

Maybe @sgugger?

## Information

Model I am using (Bert, XLNet ...): None

The problem arises when using:
* [X] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. run `pip install -e ".[dev]"
2. run `transformers-cli add-new-model` or `transformers-cli`

```
(base) stellabiderman@Stellas-MBP transformers % transformers-cli
Traceback (most recent call last):
  File "/Users/stellabiderman/opt/anaconda3/bin/transformers-cli", line 33, in <module>
    sys.exit(load_entry_point('transformers', 'console_scripts', 'transformers-cli')())
  File "/Users/stellabiderman/opt/anaconda3/bin/transformers-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/stellabiderman/Documents/transformers/src/transformers/commands/transformers_cli.py", line 23, in <module>
    from .run import RunCommand
  File "/Users/stellabiderman/Documents/transformers/src/transformers/commands/run.py", line 17, in <module>
    from ..pipelines import SUPPORTED_TASKS, TASK_ALIASES, Pipeline, PipelineDataFormat, pipeline
  File "/Users/stellabiderman/Documents/transformers/src/transformers/pipelines/__init__.py", line 26, in <module>
    from ..models.auto.feature_extraction_auto import FEATURE_EXTRACTOR_MAPPING, AutoFeatureExtractor
  File "/Users/stellabiderman/Documents/transformers/src/transformers/models/auto/feature_extraction_auto.py", line 20, in <module>
    from transformers import DeiTFeatureExtractor, Speech2TextFeatureExtractor, ViTFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1978, in __getattr__
    value = getattr(module, name)
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1977, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1986, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/stellabiderman/Documents/transformers/src/transformers/models/speech_to_text/feature_extraction_speech_to_text.py", line 23, in <module>
    import torchaudio.compliance.kaldi as ta_kaldi
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so, 6): Symbol not found: __ZN2at6detail10noopDeleteEPv
  Referenced from: /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so
  Expected in: /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so
 ```

```
(base) stellabiderman@Stellas-MBP transformers % transformers-cli add-new-model
Traceback (most recent call last):
  File "/Users/stellabiderman/opt/anaconda3/bin/transformers-cli", line 33, in <module>
    sys.exit(load_entry_point('transformers', 'console_scripts', 'transformers-cli')())
  File "/Users/stellabiderman/opt/anaconda3/bin/transformers-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/stellabiderman/Documents/transformers/src/transformers/commands/transformers_cli.py", line 23, in <module>
    from .run import RunCommand
  File "/Users/stellabiderman/Documents/transformers/src/transformers/commands/run.py", line 17, in <module>
    from ..pipelines import SUPPORTED_TASKS, TASK_ALIASES, Pipeline, PipelineDataFormat, pipeline
  File "/Users/stellabiderman/Documents/transformers/src/transformers/pipelines/__init__.py", line 26, in <module>
    from ..models.auto.feature_extraction_auto import FEATURE_EXTRACTOR_MAPPING, AutoFeatureExtractor
  File "/Users/stellabiderman/Documents/transformers/src/transformers/models/auto/feature_extraction_auto.py", line 20, in <module>
    from transformers import DeiTFeatureExtractor, Speech2TextFeatureExtractor, ViTFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1978, in __getattr__
    value = getattr(module, name)
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1977, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/stellabiderman/Documents/transformers/src/transformers/file_utils.py", line 1986, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/stellabiderman/Documents/transformers/src/transformers/models/speech_to_text/feature_extraction_speech_to_text.py", line 23, in <module>
    import torchaudio.compliance.kaldi as ta_kaldi
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/extension/extension.py", line 19, in _init_script_module
    torch.classes.load_library(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/Users/stellabiderman/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so, 6): Symbol not found: __ZN2at6detail10noopDeleteEPv
  Referenced from: /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so
  Expected in: /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/stellabiderman/opt/anaconda3/lib/python3.8/site-packages/torchaudio/_torchaudio.so
 ```
## Expected behavior

I expected the new model builder to work.

**Comment by LysandreJik** [comment]
Hi @StellaAthena, thank you for your detailed issue. This error is usually due to mismatched versions of `torch` and `torchaudio`, see [here](https://discuss.huggingface.co/t/setup-questions/6796/8). We recommend either uninstalling `torchaudio`, or reinstalling torch and torchaudio to their latest versions (v1.9.0 and v0.9.0 respectively).

If none of these work, would you mind sending me the result of `conda list` so that I may try and see what's going on? Thank you!

**Comment by StellaAthena** [comment]
@LysandreJik It looks like that works! Thanks.
