### ISSUE TITLE
Default process group has not been initialized while using sagemaker data parallel

### ISSUE THREAD

**Issue by yl-to** [huggingface/transformers#12847]
## Environment info

- `transformers` version: 4.9.0 - dev
- Platform: Sagemaker
- Python version: 
- PyTorch version (GPU?): 1.8.1
- Tensorflow version (GPU?):
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: Yes

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: SQUaD
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Run Squad finetune using transformers 4.9.0 - dev

```
[1,5]<stdout>:Traceback (most recent call last):
--
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,5]<stdout>:    "__main__", mod_spec)
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,5]<stdout>:    exec(code, run_globals)
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,5]<stdout>:    main()
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,5]<stdout>:    run_command_line(args)
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,5]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,5]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,5]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,3]<stdout>:    run_command_line(args)
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,3]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,3]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 96, in _run_module_code
[1,3]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,3]<stdout>:    exec(code, run_globals)
[1,3]<stdout>:  File "run_qa.py", line 646, in <module>
[1,3]<stdout>:    main()
[1,3]<stdout>:  File "run_qa.py", line 427, in main
[1,3]<stdout>:    with training_args.main_process_first(desc="train dataset map pre-processing"):
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
[1,3]<stdout>:    return next(self.gen)
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/transformers/training_args.py", line 1033, in main_process_first
[1,3]<stdout>:    torch.distributed.barrier()
[1,3]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
[1,3]<stdout>:    default_pg = _get_default_group()
[1,2]<stdout>:Traceback (most recent call last):
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,2]<stdout>:    "__main__", mod_spec)
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,2]<stdout>:    exec(code, run_globals)
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,2]<stdout>:    main()
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,2]<stdout>:    run_command_line(args)
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,2]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,2]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,2]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,4]<stdout>:    "__main__", mod_spec)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,4]<stdout>:    exec(code, run_globals)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,4]<stdout>:    main()
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,4]<stdout>:    run_command_line(args)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,4]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,4]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 96, in _run_module_code
[1,4]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,4]<stdout>:    exec(code, run_globals)
[1,4]<stdout>:  File "run_qa.py", line 646, in <module>
[1,4]<stdout>:    main()
[1,4]<stdout>:  File "run_qa.py", line 427, in main
[1,4]<stdout>:    with training_args.main_process_first(desc="train dataset map pre-processing"):
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
[1,6]<stdout>:    "__main__", mod_spec)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,6]<stdout>:    exec(code, run_globals)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,6]<stdout>:    main()
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 196, in main
[1,6]<stdout>:    run_command_line(args)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,6]<stdout>:    run_path(sys.argv[0], run_name='__main__')
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 263, in run_path
[1,6]<stdout>:    pkg_name=pkg_name, script_name=fname)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 96, in _run_module_code
[1,6]<stdout>:    mod_name, mod_spec, pkg_name, script_name)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
[1,6]<stdout>:    exec(code, run_globals)
[1,6]<stdout>:  File "run_qa.py", line 646, in <module>
[1,6]<stdout>:    main()
[1,6]<stdout>:  File "run_qa.py", line 427, in main
[1,6]<stdout>:    with training_args.main_process_first(desc="train dataset map pre-processing"):
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
[1,6]<stdout>:    return next(self.gen)
[1,6]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/transformers/training_args.py", line 1033, in main_process_first
[1,6]<stdout>:    torch.distributed.barrier()
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/contextlib.py", line 81, in __enter__
[1,4]<stdout>:    return next(self.gen)
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/transformers/training_args.py", line 1033, in main_process_first
[1,4]<stdout>:    torch.distributed.barrier()
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 2419, in barrier
[1,4]<stdout>:    default_pg = _get_default_group()
[1,4]<stdout>:  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 347, in _get_default_group
[1,4]<stdout>:    raise RuntimeError("Default process group has not been initialized, "
[1,4]<stdout>:RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

**Comment by yl-to** [comment]
@philschmid @sgugger

**Comment by sandeep-krishnamurthy** [comment]
From offline discussion, the issue seem to be the following:
1. You can’t use torch.distributed and smdp at the same time. You might want to change torch.distributed.barrier to sm_dist.barrier
2. You could do import either torch.distributed or smdistributed.dataparallel.torch.distributed as dist at the top of the file. Then, you can simply write dist.xyz elsewhere

Likely the PR from which this issue originated is below:
https://github.com/huggingface/transformers/pull/12464
