### ISSUE TITLE
bert:What is the tf version corresponding to tensformers?

### ISSUE THREAD

**Issue by xmcs111** [huggingface/transformers#13331]
I use python3.7, tf2.4.0, cuda11.1 and cudnn 8.0.4 to run bert-base-un and report an error
- albert, bert, xlm: @LysandreJik
- tensorflow: @Rocketkn

**Comment by xmcs111** [comment]
@Rocketknight1

**Comment by LysandreJik** [comment]
Hello! Do you mind providing the error you're seeing? Thank you!

**Comment by xmcs111** [comment]
'''
I:?[35mVENTILATOR?[0m:freeze, optimize and export graph, could take a while...
2021-08-30 20:07:49.360788: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
d:\users\...\pycharmprojects\machine learning i don't study\venv37\lib\site-packages\bert_serving\server\helper.py:176: UserWarning: Tensorflow 2.4.0 is not tested!
 It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/
  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)
E:?[36mGRAPHOPT?[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\...\PycharmProjects\machine learning I don't study\venv37\Scripts\bert-serving-start.exe\__main__.py", line 7, in <module>
  File "d:\users\...\pycharmprojects\machine learning i don't study\venv37\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "d:\users\...\pycharmprojects\machine learning i don't study\venv37\lib\site-packages\bert_serving\server\__init__.py", line 71, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object
'''

**Comment by Rocketknight1** [comment]
Hi, it seems like you're using [bert-as-service](https://github.com/hanxiao/bert-as-service) with an unsupported version of Tensorflow. That isn't a Huggingface project, so we can't really support it here, unfortunately! Try filing an issue at that repo instead!

If you're interested in learning to use the Transformers library, you can check out our [documentation](https://huggingface.co/transformers/quicktour.html), our [course](https://huggingface.co/course/chapter1) or our [example code](https://github.com/huggingface/transformers/tree/master/examples, but we can't really answer questions on any of that in GitHub issues - try the [forums](https://discuss.huggingface.co/) instead!

I'm going to close this issue, but if you believe there's an actual problem in the Transformers library, separate from `bert-as-service`, please feel free to add more info and re-open it.
