### ISSUE TITLE
Official example not working, are you serious?

### ISSUE THREAD

**Issue by zhangguanqun** [huggingface/transformers#13435]
## Environment info

- `transformers` version: 4.10.0
- Platform: Ubuntu 18.04
- Python version:
- PyTorch version (GPU?): 1.9 GPU
- Tensorflow version (GPU?): 2.4.0 GPU
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: 

## Information

@LysandreJik

Model I am using Bert, official code not working :(

```
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = BertModel.from_pretrained("bert-base-cased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
```
[https://huggingface.co/bert-base-cased](url) to above code.
`https://huggingface.co/bert-base-cased`

Exception:
```
Traceback (most recent call last):
  File "/home/zhangguanqun/venv_tf_2.4/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 248, in __getattr__
    return self.data[item]
KeyError: 'size'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhangguanqun/projects/huggingface/bert.py", line 15, in <module>
    output = model(encoded_input)
  File "/home/zhangguanqun/venv_tf_2.4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangguanqun/venv_tf_2.4/lib/python3.6/site-packages/transformers/models/bert/modeling_bert.py", line 938, in forward
    input_shape = input_ids.size()
  File "/home/zhangguanqun/venv_tf_2.4/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 250, in __getattr__
    raise AttributeError
AttributeError

Process finished with exit code 1
```

What's wrong with that?

**Comment by flozi00** [comment]
I think it's because you try to pass the tensorflow output from tokenizer to an pytorch model.
Either use tfbertmodel or let the tokenizer return "pt" instead of "tf" tensors

**Comment by zhangguanqun** [comment]
@flozi00 You are right, if I change BertModel to TFBertModel, everything goes well.
BUT, the above codes come from [OFFICIAL TUTORIAL](https://huggingface.co/bert-base-cased),
PLEASE modify the doc to stop misleading others.

**Comment by shabie** [comment]
I think both official examples are wrong. The quote is from the [official link](https://huggingface.co/bert-base-cased):

Here is how to use this model to get the features of a given text in PyTorch:

```python
from transformers import BertTokenizer, TFBertModel       # <--- should be just BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = TFBertModel.from_pretrained("bert-base-cased")    # <--- should be just BertModel
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='pt')  
output = model(**encoded_input)
```
and in TensorFlow:

```python
from transformers import BertTokenizer, BertModel       # <--- should be  with TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = BertModel.from_pretrained("bert-base-cased")    # <--- should be  with TFBertModel
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)
```

**Comment by patrickvonplaten** [comment]
Just corrected it :-)

**Comment by thomwolf** [comment]
a lot more serious now indeed!

**Comment by shabie** [comment]
Such is the onus on HF to deliver correctly that one mistake can some question the seriousness of the whole enterprise :D

**Comment by Doragd** [comment]
Similar issue on examples https://huggingface.co/microsoft/xprophetnet-large-wiki100-cased-xglue-ntg:
@thomwolf @patrickvonplaten 
```python
from transformers import XLMProphetNetTokenizer, XLMProphetNetForConditionalGeneration, ProphetNetConfig

# should be just XLMProphetNetForConditionalGeneration & XLMProphetNetTokenizer
model = ProphetNetForConditionalGeneration.from_pretrained('microsoft/xprophetnet-large-wiki100-cased-xglue-ntg')
tokenizer = ProphetNetTokenizer.from_pretrained('microsoft/xprophetnet-large-wiki100-cased-xglue-ntg')
...
```
