### ISSUE TITLE
SQUAD: V2 referenced at top of Readme; V1 referenced in usage instructions

### ISSUE THREAD

**Issue by descartesholland** [huggingface/transformers#1351]
## ❓ Questions & Help

There seems to be an inconsistency in the README, namely that run_squad.py is cited to be trained on SQUAD v2 towards the top, but scrolling down to view the command shows that v1 is used. Running the command cited over a copy of the v2 dataset on my machine yields the following error:

```
Traceback (most recent call last):
  File "./examples/run_squad.py", line 533, in <module>
    main()
  File "./examples/run_squad.py", line 478, in main
    train_dataset = load_and_cache_examples(args, tokenizer, evaluate=False, output_examples=False)
  File "./examples/run_squad.py", line 291, in load_and_cache_examples
    version_2_with_negative=args.version_2_with_negative)
  File "./examples/utils_squad.py", line 151, in read_squad_examples
    "For training, each question should have exactly 1 answer.")
ValueError: For training, each question should have exactly 1 answer.

```

**Comment by descartesholland** [comment]
Need to use the flag 
--version_2_with_negative
