### ISSUE TITLE
Could not load from pretrain even with the same code

### ISSUE THREAD

**Issue by unbreading** [huggingface/transformers#13822]
environment: pytorch_transformers 1.1.0

I copy the code of `RobertaModel` from `pytorch_transformers.modeling_roberta` to a local directory with minimal requirements. 

```
from pytorch_transformers.modeling_bert import BertModel
from pytorch_transformers.modeling_roberta import RobertaConfig, ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP, RobertaEmbeddings

class RobertaModel(BertModel):
    config_class = RobertaConfig
    pretrained_model_archive_map = ROBERTA_PRETRAINED_MODEL_ARCHIVE_MAP
    base_model_prefix = "roberta"

    def __init__(self, config):
        super(RobertaModel, self).__init__(config)

        self.embeddings = RobertaEmbeddings(config)
        self.init_weights()

    def forward(self, input_ids, token_type_ids=None, attention_mask=None, position_ids=None, head_mask=None):
        if input_ids[:, 0].sum().item() != 0:
            print("A sequence with no special tokens has been passed to the RoBERTa model. "
                           "This model requires special tokens in order to work. "
                           "Please specify add_special_tokens=True in your encoding.")
        return super(RobertaModel, self).forward(input_ids, token_type_ids, attention_mask, position_ids, head_mask)
```

And I failed to load from pretrain in my main script:

```
from MyRoberta.RobertaTest import RobertaModel
bert_model = RobertaModel.from_pretrained(args.roberta_model)
```

exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/bs/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File ".../MyRoberta/RobertaTest.py", line 51, in __init__
    self.init_weights()
TypeError: init_weights() missing 1 required positional argument: 'module'
```

What's wrong? It should load successfully.

The reason I made the copy is that, I want to add a new embedding into roberta model, so I begin with running the original roberta code in my directory.

Thanks a lot.

**Comment by unbreading** [comment]
Problem solved using transformers instead of pytorch_transformers.
But I'm still curious about the reason behind such problem.
