### ISSUE TITLE
overflow error when initialising transformerXL model (transfo-xl-wt103)

### ISSUE THREAD

**Issue by blrtvs** [huggingface/transformers#13863]
## Information 

I don't if I'm allowed to post this here as I use pytorch-pretrained-bert, but maybe someone knows this error. I want to run the code below: 

```
import torch
from pytorch_pretrained_bert import TransfoXLTokenizer, TransfoXLModel, TransfoXLLMHeadModel
import logging


logging.basicConfig(level=logging.INFO)

model = TransfoXLModel.from_pretrained('transfo-xl-wt103')
```

But I get the following error: 

```
Traceback (most recent call last):
  File "load_transfo.py", line 7, in <module>
    model = TransfoXLModel.from_pretrained('transfo-xl-wt103')
  File "/home/user123/anaconda3/envs/test_transfo372/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling_transfo_xl.py", line 939, in from_pretrained
    model = cls(config, *inputs, **kwargs)
  File "/home/user123/anaconda3/envs/test_transfo372/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling_transfo_xl.py", line 1033, in __init__
    div_val=config.div_val)
  File "/home/user123/anaconda3/envs/test_transfo372/lib/python3.7/site-packages/pytorch_pretrained_bert/modeling_transfo_xl.py", line 780, in __init__
    self.emb_layers.append(nn.Embedding(r_idx-l_idx, d_emb_i))
  File "/home/user123/anaconda3/envs/test_transfo372/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 100, in __init__
    self.weight = Parameter(torch.Tensor(num_embeddings, embedding_dim))
RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at /pytorch/aten/src/TH/THGeneral.cpp:188

```

Has somebody an idea how to get this work? When I use newer versions of torch and pytorch-pretrained-bert I just get a different RuntimeError (RuntimeError: Trying to create tensor with negative dimension -200001: [-200001, 16])

## Environment info 

- `transformers` version: I use pytorch-pretrained-bert=0.6.1 
- Platform: Debian GNU/Linux 9.13 (stretch)
- Python version: 3.7
- PyTorch version (GPU?): 1.0.1
- Tensorflow version (GPU?):not installed

Models:
 @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Hey @blrtvs,

Could you maybe try to use a `transformers` version > 2.0 instead?
