### ISSUE TITLE
cannot load character bert

### ISSUE THREAD

**Issue by Nitinram23** [huggingface/transformers#14031]
## Environment info
- `transformers` version: 4.11.3
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.7.6
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

@LysandreJik I'm looking for help with character bert 

I am trying to use Character bert:

The problem arises when trying to load the model:

```
from transformers import AutoTokenizer, AutoModelForPreTraining
  
tokenizer = AutoTokenizer.from_pretrained("helboukkouri/character-bert")

model = AutoModelForPreTraining.from_pretrained("helboukkouri/character-bert")
```

```
from transformers import AutoTokenizer, AutoModelForPreTraining
  
tokenizer = AutoTokenizer.from_pretrained("helboukkouri/character-bert")

model = AutoModelForPreTraining.from_pretrained("helboukkouri/character-bert")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pupper/anaconda3/envs/work/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 463, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/Users/pupper/anaconda3/envs/work/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 529, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/Users/pupper/anaconda3/envs/work/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 278, in __getitem__
    raise KeyError(key)
KeyError: 'character_bert'
```

I expected it to load the model and tokenizer for use but it throws the error instead. Can anyone help here? Thanks!

**Comment by Nitinram23** [comment]
Much appreciated!
