### ISSUE TITLE
Question about an error occurring while running hf_argparser.py

### ISSUE THREAD

**Issue by seuly1203** [huggingface/transformers#14559]
## Environment info

- `transformers` version:
- Platform: Google Colab
- Python version: Python 3.7.12
- PyTorch version (GPU?): 1.8.0+cu111 (using Colab Pro - GPU/high-RAM)
- Tensorflow version (GPU?): 2.7.0
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help
<!-- Your issue will be replied to more quickly if you can figure out the right person to tag with @
 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

Models:
- encoder-decoder models (For example, BlenderBot, BART, Marian, Pegasus, T5, ByT5): @patrickvonplaten, @patil-suraj
-  seq2seq
If the model isn't in the list, ping @LysandreJik who will redirect you to the correct contributor.

## Information

Hello,

Model I am using (Bert, XLNet ...):
ET5 (pre-trained Korean language model using T5 and BART training pattern) developed by ETRI

I have downloaded the pre-trained model from ETRI(https://aiopen.etri.re.kr/service_dataset.php), and they suggests to use the model via PyTorch and the files are consist of HuggingFace model(.model) and SentencePiece tokenizer model(.bin) file.

I keep getting error message from running this part of a Python file(seq2seq_finetune_t5_ynat.py) that was given with ET5 model:
'''
def main():
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, Seq2SeqTrainingArguments))

    if len(sys.argv) == 3 and sys.argv[-1].endswith(".json"):  ### jihee
        # If we pass only one argument to the script and it's the path to a json file,
        # let's parse it to get our arguments.
        model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.abspath(sys.argv[-1]))  ### jihee
    else:
        model_args, data_args, training_args = parser.parse_args_into_dataclasses()
'''

and the error message looks like this:
'''
Traceback (most recent call last):
  File "seq2seq_finetune_t5_ynat.py", line 422, in <module>
    main()
  File "seq2seq_finetune_t5_ynat.py", line 199, in main
    parser = HfArgumentParser((ModelArguments, DataTrainingArguments, Seq2SeqTrainingArguments))
  File "/usr/local/lib/python3.7/dist-packages/transformers/hf_argparser.py", line 66, in __init__
    self._add_dataclass_arguments(dtype)
  File "/usr/local/lib/python3.7/dist-packages/transformers/hf_argparser.py", line 116, in _add_dataclass_arguments
    elif hasattr(field.type, "__origin__") and issubclass(field.type.__origin__, List):
  File "/usr/lib/python3.7/typing.py", line 721, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
'''

- I have checked that ModelArguments, DataTrainingArguments, and Seq2SeqTrainingArguments are declared as class in the Python file(seq2seq_finetune_t5_ynat.py), so I do not get why it raise the  TypeError.

Please excuse that I am very new to this field so if this post is irrelevant, please let me know, I will remove!

Thank you for your time.

**Comment by seuly1203** [comment]
I solved the problem by editing File "/usr/lib/python3.7/typing.py", line 721, in subclasscheck
return issubclass(cls, self.origin):
  return issubclass(cls, self.origin) -> return issubclass(type(cls), self.origin)

**Comment by bios-xiajun** [comment]
same issue to me.
