### ISSUE TITLE
Error loading Speech2Text2Processor.from_pretrained("facebook/wav2vec2-xls-r-2b-21-to-en")

### ISSUE THREAD

**Issue by ShRajSh** [huggingface/transformers#14601]
- `transformers` version: 4.12.5
- Platform: Linux-5.4.0-90-generic-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.6.9
- PyTorch version (GPU?): 1.9.0+cu102 (True)
- Tensorflow version (GPU?): 2.6.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'MBart50Tokenizer'. 
The class this function is called from is 'Speech2Text2Tokenizer'.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shivam/.local/lib/python3.6/site-packages/transformers/models/speech_to_text_2/processing_speech_to_text_2.py", line 106, in from_pretrained
    tokenizer = Speech2Text2Tokenizer.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/shivam/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1750, in from_pretrained
    **kwargs,
  File "/home/shivam/.local/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1872, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/shivam/.local/lib/python3.6/site-packages/transformers/models/speech_to_text_2/tokenization_speech_to_text_2.py", line 85, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by patrickvonplaten** [comment]
Hey @ShRajSh, 

Sorry we only recently fixed this error. The model should actually be loaded as follows:

```python
Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-xls-r-2b-21-to-en")
```
