### ISSUE TITLE
Facing Problems with RobertaForSequenceClassification.from_pretrained()

### ISSUE THREAD

**Issue by aflah02** [huggingface/transformers#14926]
I've been trying to run the code present here on new data - https://github.com/machelreid/lewis

In one of the steps there are the following lines of codes - 

```
    classifier = (
        RobertaForSequenceClassification.from_pretrained(
            f"{args.hf_dump}/pytorch_model.bin",
            config=f"{args.hf_dump}/config.json",
            output_attentions=True,
        )
        .half()
        .cuda()
        .eval()
    )
```

They are present inside https://github.com/machelreid/lewis/blob/master/get_synthesized_data.py

I get this error - 

``Traceback (most recent call last):
  File "get_synthesized_data.py", line 56, in <module>
    output_attentions=True,
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1272, in from_pretrained
    **kwargs,
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/transformers/configuration_utils.py", line 501, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/transformers/configuration_utils.py", line 554, in get_config_dict
    local_files_only=local_files_only,
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/transformers/configuration_utils.py", line 842, in get_configuration_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/transformers/file_utils.py", line 1952, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/huggingface_hub/hf_api.py", line 603, in list_repo_files
    repo_id, revision=revision, token=token, timeout=timeout
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/huggingface_hub/hf_api.py", line 586, in model_info
    r.raise_for_status()
  File "/home/aflah20082/yes/envs/lewis/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/downloads/roberta-classifier/dataset-eval/config.json``

I can't seem to figure out why does it try to go to that link since the path was to a local file

**Comment by aflah02** [comment]
I figured out my mistake the config file hadn't been generated 
Fixed that now
