### ISSUE TITLE
[Speech recognition examples] num_processing_workers not allowed to be set

### ISSUE THREAD

**Issue by flozi00** [huggingface/transformers#14962]
## Environment info

- `transformers` version: master
- Platform: ubuntu
- Python version:
- PyTorch version (GPU?): 
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help

@patrickvonplaten 

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) commonvoice
* [ ] my own task or dataset: (give details below)

## To reproduce

1. run one of the official speech recognition examples with num_processing_workers specified
2.
3.

```
Traceback (most recent call last):
  File "/mnt/f/Codes/Python Apps/asr/speech_recognition_seq2seq.py", line 504, in <module>
    main()
  File "/mnt/f/Codes/Python Apps/asr/speech_recognition_seq2seq.py", line 380, in main
    vectorized_datasets = raw_datasets.map(
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/dataset_dict.py", line 494, in map
    {
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/dataset_dict.py", line 495, in <dictcomp>
    k: dataset.map(
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2142, in map
    shards = [
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2143, in <listcomp>
    self.shard(num_shards=num_proc, index=rank, contiguous=True, keep_in_memory=keep_in_memory)
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 3168, in shard
    return self.select(
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/fingerprint.py", line 411, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2760, in select
    return self._new_dataset_with_indices(indices_buffer=buf_writer.getvalue(), fingerprint=new_fingerprint)
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2671, in _new_dataset_with_indices
    return Dataset(
  File "/home/flozi/anaconda3/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 661, in __init__
    raise ValueError(
ValueError: External features info don't match the dataset:
Got
{'client_id': Value(dtype='string', id=None), 'path': Value(dtype='string', id=None), 'audio': Audio(sampling_rate=16000, mono=True, _storage_dtype='string', id=None), 'sentence': Value(dtype='string', id=None), 'up_votes': Value(dtype='int64', id=None), 'down_votes': Value(dtype='int64', id=None), 'age': Value(dtype='string', id=None), 'gender': Value(dtype='string', id=None), 'accent': Value(dtype='string', id=None), 'locale': Value(dtype='string', id=None), 'segment': Value(dtype='string', id=None)}
with type
struct<client_id: string, path: string, audio: string, sentence: string, up_votes: int64, down_votes: int64, age: string, gender: string, accent: string, locale: string, segment: string>

but expected something like
{'client_id': Value(dtype='string', id=None), 'path': Value(dtype='string', id=None), 'audio': {'path': Value(dtype='string', id=None), 'bytes': Value(dtype='binary', id=None)}, 'sentence': Value(dtype='string', id=None), 'up_votes': Value(dtype='int64', id=None), 'down_votes': Value(dtype='int64', id=None), 'age': Value(dtype='string', id=None), 'gender': Value(dtype='string', id=None), 'accent': Value(dtype='string', id=None), 'locale': Value(dtype='string', id=None), 'segment': Value(dtype='string', id=None)}
with type
struct<client_id: string, path: string, audio: struct<path: string, bytes: binary>, sentence: string, up_votes: int64, down_votes: int64, age: string, gender: string, accent: string, locale: string, segment: string>
```

**Comment by patrickvonplaten** [comment]
Actually, I've seen this error before as well and it confused me a lot as well - thanks a lot for flagging it here @flozi00! I think it only happens though when the audio has to be resampled (like for Common Voice). 

@lhoestq - it's a weird bug with `datasets` I think. I'll try to get a minimum reproducible code-snippet.

**Comment by patrickvonplaten** [comment]
@lhoestq @albertovilla @mariosasko here is a minimal reproducible bug report:

```python
from datasets import load_dataset, DatasetDict
import datasets
from transformers import AutoFeatureExtractor

raw_datasets = DatasetDict()

raw_datasets["train"] = load_dataset("common_voice", "ab", split="train")

feature_extractor = AutoFeatureExtractor.from_pretrained("facebook/wav2vec2-base")

raw_datasets = raw_datasets.cast_column(
    "audio", datasets.features.Audio(sampling_rate=feature_extractor.sampling_rate)
)

num_workers = 16

def prepare_dataset(batch):
    sample = batch["audio"]

    inputs = feature_extractor(sample["array"], sampling_rate=sample["sampling_rate"])
    batch["input_values"] = inputs.input_values[0]
    batch["input_length"] = len(batch["input_values"])
    return batch

raw_datasets.map(
    prepare_dataset,
    remove_columns=next(iter(raw_datasets.values())).column_names,
    num_proc=16,
    desc="preprocess datasets",
)
```

**Comment by patrickvonplaten** [comment]
Opened an issue on datasets: https://github.com/huggingface/datasets/issues/3497 (feel free to disregard issue here)

**Comment by patrickvonplaten** [comment]
Think we can close this one no @lhoestq ?

**Comment by lhoestq** [comment]
Yes indeed, thanks for the heads up !
