### ISSUE TITLE
[FX] `symbolic_trace` yields a TraceError for `BertModel`

### ISSUE THREAD

**Issue by fxmarty** [huggingface/transformers#15045]
## Environment info

- `transformers` version: 4.16.0.dev0
- Platform: Linux
- Python version: 3.9.2
- PyTorch version (GPU?): 1.10.1+cpu
- Tensorflow version (GPU?): /
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help
@michaelbenayoun 

Models:
- BERT: @LysandreJik

## Information

Model I am using : Bert

The problem arises when using:
* [ x ] my own modified scripts

The tasks I am working on is:
* Convert a `BertModel` to `torch.fx.GraphModule`

## To reproduce

```
from transformers import BertModel
import torch
from transformers.utils.fx import symbolic_trace
import transformers

# see https://github.com/huggingface/transformers/issues/14632
transformers.utils.fx.is_torch_fx_available = lambda: True

model = BertModel.from_pretrained("bert-base-uncased")

model = model.eval()

g = symbolic_trace(model,
                   sequence_length=20)
```

Traceback message:
```
Traceback (most recent call last):
  File "<tmp 1>", line 20, in <module>
    g = symbolic_trace(model,
  File "/home/felix/.local/lib/python3.9/site-packages/transformers-4.16.0.dev0-py3.9.egg/transformers/utils/fx.py", line 581, in symbolic_trace
    traced_graph = tracer.trace(model, concrete_args=concrete_args)
  File "/home/felix/.local/lib/python3.9/site-packages/transformers-4.16.0.dev0-py3.9.egg/transformers/utils/fx.py", line 372, in trace
    graph = super().trace(root, concrete_args=concrete_args)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 615, in trace
    self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
  File "/home/felix/.local/lib/python3.9/site-packages/transformers-4.16.0.dev0-py3.9.egg/transformers/models/albert/modeling_albert.py", line 720, in forward
    encoder_outputs = self.encoder(
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 604, in module_call_wrapper
    return self.call_module(mod, forward, args, kwargs)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 422, in call_module
    return forward(*args, **kwargs)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 600, in forward
    return _orig_module_call(mod, *args, **kwargs)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/felix/.local/lib/python3.9/site-packages/transformers-4.16.0.dev0-py3.9.egg/transformers/models/albert/modeling_albert.py", line 484, in forward
    return BaseModelOutput(
  File "<string>", line 6, in __init__
  File "/home/felix/.local/lib/python3.9/site-packages/transformers-4.16.0.dev0-py3.9.egg/transformers/file_utils.py", line 2296, in __post_init__
    iterator = iter(first_field)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/proxy.py", line 248, in __iter__
    return self.tracer.iter(self)
  File "/home/felix/.local/lib/python3.9/site-packages/torch/fx/proxy.py", line 161, in iter
    raise TraceError('Proxy object cannot be iterated. This can be '
torch.fx.proxy.TraceError: Proxy object cannot be iterated. This can be attempted when the Proxy is used in a loop or as a *args or **kwargs function argument. See the torch.fx docs on pytorch.org for a more detailed explanation of what types of control flow can be traced, and check out the Proxy docstring for help troubleshooting Proxy iteration errors
```

Tweaking the parameters here https://github.com/huggingface/transformers/blob/master/src/transformers/utils/fx.py#L497 does not seem to help.

Maybe this is related, but I am not sure, I am not familiar with fx: https://github.com/pytorch/pytorch/issues/44665

Maybe Bert and other models are not yet fx-friendly?

## Expected behavior

No error.

**Comment by NielsRogge** [comment]
Hi,

In order to symbolic trace a model, you also need to provide the input_names:

```
from transformers import BertModel
from transformers.utils.fx import symbolic_trace

model = BertModel.from_pretrained("bert-base-uncased")

traced_model = symbolic_trace(
    model,
    input_names=["input_ids", "attention_mask", "token_type_ids"],
    batch_size=1,
    sequence_length=128,
)
```
This works for me on Transformers v4.15.0 and PyTorch 1.9.0 in Google Colab.

**Comment by fxmarty** [comment]
Thank you!

So it is a version problem. I let you know this code with

transformers version: 4.16.0.dev0
Python version: 3.9.2
PyTorch version (GPU?): 1.10.1+cpu

do yield the error I gave:

```
from transformers import BertModel
from transformers.utils.fx import symbolic_trace
import transformers

model = BertModel.from_pretrained("bert-base-uncased")

transformers.utils.fx.is_torch_fx_available = lambda: True

traced_model = symbolic_trace(
    model,
    input_names=["input_ids", "attention_mask", "token_type_ids"],
    batch_size=1,
    sequence_length=128,
)
```

I will downgrade PyTorch and transformers, thank you.

**Comment by michaelbenayoun** [comment]
Hi @fxmarty,
I am working on a PR (#14321) that should allow you to use both 1.9 and 1.10 version if everything goes well. It should be merged by the end of the week.

**Comment by fxmarty** [comment]
It's all good, thanks a lot!
