### ISSUE TITLE
Fine Tunning the Pytorch script

### ISSUE THREAD

**Issue by SatishDeshbhratar** [huggingface/transformers#15260]
I am trying a text summarization project mentioned in this link https://github.com/SatishDeshbhratar/transformers/tree/master/examples/pytorch/summarization

But I am facing the error related to hf argument parser as below

> (pytorch_nlp) PS D:\Docs\Course work\Final Project (Text Summarization)\Script> python run_summarization.py \ --train_file=/train.csv \ --validation_file=/val.csv \ --model_name_or_path=facebook/bart-large-cnn \ --learning_rate=3.0e-6 \ --per_device_train_batch_size=8 \ --per_device_eval_batch_size=4 \ --output_dir=/output \ --num_train_epochs=100 \ --overwrite_output_dir=True \ --max_source_length=1024 \ --max_target_length=512 \ --val_max_target_length=512 \ --pad_to_max_length=False \ --evaluation_strategy='steps' \ --eval_steps=1000 \ --metric_for_best_model='rouge2' \ --greater_is_better=True \ --load_best_model_at_end=True \ --save_strategy='steps' \ --save_steps=1000 \ --save_total_limit=1 \ --predict_with_generate=True \ --num_beams=4 --generation_num_beams=4 \ --generation_max_length=512 \ --overwrite_cache=True \ --do_train 

Traceback (most recent call last): File "D:\Docs\Course work\Final Project (Text Summarization)\Script\run_summarization.py", line 698, in <module> main() File "D:\Docs\Course work\Final Project (Text Summarization)\Script\run_summarization.py", line 281, in main model_args, data_args, training_args = parser.parse_args_into_dataclasses() File "C:\ProgramData\Anaconda3\envs\pytorch_nlp\lib\site-packages\transformers\hf_argparser.py", line 215, in parse_args_into_dataclasses raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}") ValueError: Some specified arguments are not used by the HfArgumentParser: ['\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\', '\\'] (pytorch_nlp) PS D:\Docs\Course work\Final Project (Text Summarization)\Script>

**Comment by Aureole-1210** [comment]
Maybe you remove all the '\' in the code, the problem will be solved.
