### ISSUE TITLE
No module named 'transformers.models.bort'

### ISSUE THREAD

**Issue by abhilashreddys** [huggingface/transformers#15377]
## Environment info

- `transformers` version: 4.16.0
- Platform: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.12
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- Tensorflow version (GPU?): 2.7.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help 
@sgugger @Narsil

## Error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 2704, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.bort'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/infoADAPET/src/test.py", line 5, in <module>
    from transformers import *
  File "<frozen importlib._bootstrap>", line 1031, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 2692, in __getattr__
    value = self._get_module(name)
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 2708, in _get_module
    ) from e
RuntimeError: Failed to import transformers.models.bort because of the following error (look up to see its traceback):
No module named 'transformers.models.bort'
```

**Comment by abhilashreddys** [comment]
v4.16.0  has this issue changing to v4.15.0 fixed it

**Comment by sgugger** [comment]
What command did you run exactly?

**Comment by abhilashreddys** [comment]
from transformers import *

**Comment by sgugger** [comment]
Thanks for flagging, a fix is on its way :-)

**Comment by LysandreJik** [comment]
Fixing on https://github.com/huggingface/transformers/pull/15378
