### ISSUE TITLE
Loading a fairseq trained wav2vec2 model with transformers

### ISSUE THREAD

**Issue by tensorfoo** [huggingface/transformers#15635]
```
>>> import transformers
>>> from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
>>> processor = Wav2Vec2Processor.from_pretrained("wav2vec_small.pt")

```

gives the error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/scratch/venv/lib/python3.8/site-packages/transformers/models/wav2vec2/processing_wav2vec2.py", line 110, in from_pretrained
    feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/tmp/scratch/venv/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 304, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/tmp/scratch/venv/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 423, in get_feature_extractor_dict
    text = reader.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

```

The file i'm trying to load is the wav2vec2 base model from the paper.

**Comment by jaketae** [comment]
Hey @tensorfoo, there is a [conversion script](https://github.com/huggingface/transformers/blob/master/src/transformers/models/wav2vec2/convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py) that can be used to convert original fairseq checkpoints to HF transformer format. Does this solve your issue?
