### ISSUE TITLE
Image classification example fails

### ISSUE THREAD

**Issue by juliensimon** [huggingface/transformers#15698]
Cats and dogs example fails.

transformers.__version__
'4.16.2'
datasets.__version__
'1.18.3'

```
python run_image_classification.py \
    --dataset_name cats_vs_dogs \
    --output_dir ./cats_vs_dogs_outputs/ \
    --remove_unused_columns False \
    --do_train \
    --do_eval \
    --push_to_hub \
    --push_to_hub_model_id vit-base-cats-vs-dogs \
    --learning_rate 2e-4 \
    --num_train_epochs 5 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 32 \
    --logging_strategy steps \
    --logging_steps 10 \
    --evaluation_strategy epoch \
    --save_strategy epoch \
    --load_best_model_at_end True \
    --save_total_limit 3 \
    --seed 1337

Downloading: 3.40kB [00:00, 842kB/s]
Downloading: 2.04kB [00:00, 1.74MB/s]
02/17/2022 15:38:33 - WARNING - datasets.builder - Using custom data configuration default
Downloading and preparing dataset cats_vs_dogs/default (download: 786.68 MiB, generated: 7.16 MiB, post-processed: Unknown size, total: 793.84 MiB) to /Users/juliensimon/.cache/huggingface/datasets/cats_vs_dogs/default/0.0.0/de304955b4952383ceadee4ab96ba2b291f67986bb213efb2255963db39d9ed8...
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 825M/825M [00:41<00:00, 19.8MB/s]
Traceback (most recent call last):
  File "/Users/juliensimon/Repos/transformers/examples/pytorch/image-classification/run_image_classification.py", line 352, in <module>
    main()
  File "/Users/juliensimon/Repos/transformers/examples/pytorch/image-classification/run_image_classification.py", line 204, in main
    ds = load_dataset(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/datasets/load.py", line 1702, in load_dataset
    builder_instance.download_and_prepare(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/datasets/builder.py", line 594, in download_and_prepare
    self._download_and_prepare(
  File "/usr/local/anaconda3/lib/python3.9/site-packages/datasets/builder.py", line 695, in _download_and_prepare
    verify_splits(self.info.splits, split_dict)
  File "/usr/local/anaconda3/lib/python3.9/site-packages/datasets/utils/info_utils.py", line 74, in verify_splits
    raise NonMatchingSplitsSizesError(str(bad_splits))
datasets.utils.info_utils.NonMatchingSplitsSizesError: [{'expected': SplitInfo(name='train', num_bytes=7503250, num_examples=23422, dataset_name='cats_vs_dogs'), 'recorded': SplitInfo(name='train', num_bytes=7871070, num_examples=23410, dataset_name='cats_vs_dogs')}]
```

**Comment by NielsRogge** [comment]
Update: I see you're using the cats and dogs image instead of beans. I'll rerun.

**Comment by NielsRogge** [comment]
Indeed, therefore closing this PR. For now, you have to install datasets from master to have it.

**Comment by juliensimon** [comment]
OK, thank you.
