### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by skpig** [huggingface/transformers#16390]
## Environment info

- `transformers` version:4.17.0
- Platform:Linux-4.15.0-142-generic-x86_64-with-debian-buster-sid
- Python version:3.6.6
- PyTorch version (GPU?): 1.7.1 (True)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten This issue is similar to https://github.com/huggingface/transformers/issues/9328, but I'm not so sure. If adding a merge.txt is able to fix the error, maybe the model hub should update many models / notify the creators.

## Information

Model I am using (Bert, XLNet ...): Bart

The problem arises when using:
* [x] the official example scripts: (give details below)
```
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("fnlp/bart-base-chinese")

model = AutoModel.from_pretrained("fnlp/bart-base-chinese")
```

## To reproduce
Just run the official script above. The error is reported as below
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/site-packages/transformers/models/auto/tokenization_auto.py", line 546, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1795, in from_pretrained
    **kwargs,
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1819, in _from_pretrained
    **(copy.deepcopy(kwargs)),
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1923, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/huangbz/.conda/envs/NLP/lib/python3.6/site-packages/transformers/models/bart/tokenization_bart.py", line 220, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by patrickvonplaten** [comment]
Hey @skpig, I think the model `fnlp/bart-base-chinese` is broken sadly. We would need to ping the author here to notify her/him. Soon this will be able on the Hub :heart: cc @julien-c

**Comment by skpig** [comment]
Thanks for your reply @patrickvonplaten .

**Comment by mcyhx** [comment]
The same problem occurs when the code is in a .py file in the colab but it works in the colab notebook.
