### ISSUE TITLE
wav2vec2 : Speech to text conversion fails when using large file 

### ISSUE THREAD

**Issue by iamshreeram** [huggingface/transformers#16564]
I'm trying to get the translation of an English Speech ( WAV file : 1.2 GB); But, Seeing error due to vector size. Same code works when the file size is low.

## Environment info

- `transformers` version: 4.17.0
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.12
- PyTorch version (GPU?): 1.11.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

Models: - Wav2Vec2: @patrickvonplaten, @anton-l

## Information

Model I am using (Bert, XLNet ...): [Wav2Vec2](https://huggingface.co/docs/transformers/model_doc/wav2vec2)

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

1. Download a english speech from youtube as mp3
2. Convert the mp3 to wav (almost 1.2 GB file size)
3. Use wav2vec2 to provide speech to text translation 
4. But, The 

### Stack Trace :
```
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    logits = model(input_values)["logits"]
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1751, in forward
    outputs = self.wav2vec2(
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1347, in forward
    extract_features = self.feature_extractor(input_values)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 515, in forward
    hidden_states = conv_layer(hidden_states)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 415, in forward
    hidden_states = self.conv(hidden_states)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Applications/anaconda3/envs/speechml/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 298, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Expected 2D (unbatched) or 3D (batched) input to conv1d, but got input of size: [1, 1, 2, 94417166]
```

## Expected behavior

To print the text that is converted from the audio

**Comment by iamshreeram** [comment]
Further details of the wav file - 

wav file for which the model works :
```
Framerate :  8000
Channel info :  1
Bytes/sample :  2
Maximum amplitude :  32767
Length of audio :  51028
```

wav file for which the model doesn't work :
```
Framerate :  44100
Channel info :  2
Bytes/sample :  2
Maximum amplitude :  32768
Length of audio :  5901073
```

**Comment by anton-l** [comment]
Hello @iamshreeram!

The error actually relates to the shape of the input: it should be `(batch_size, 1, sequence_length)`, meaning that the inputs have to be single-channel arrays (mono audio) while your second file has 2 channels (stereo audio).

But anyways, the model itself won't be able to run on the whole 1.2GB file since it's too long for a single batch (you'll see a memory error). For such long files we have an ASR pipeline with chunked inference, which you can learn about in this tutorial: https://huggingface.co/blog/asr-chunking 
The pipeline will handle stereo-to-mono conversion too, so you'll just have to specify an input filename.

Let me know if it works for you :)

**Comment by iamshreeram** [comment]
Hi, I have converted from stereo to mono (400MB) but inference still fails with below error. 
```
fish: Job 1, 'python main.py' terminated by signal SIGKILL (Forced quit)
```
I believe OS is terminating the process due to heavy memory usage. What is the max size limit for this inference to work?

**Comment by anton-l** [comment]
Hi! Could you please post a code snippet that shows the `pipeline` parameters that you've used for inference here? :)

**Comment by patrickvonplaten** [comment]
Also see docs here: https://huggingface.co/docs/transformers/main/en/main_classes/pipelines#transformers.AutomaticSpeechRecognitionPipeline.chunk_length_s

**Comment by iamshreeram** [comment]
Thanks for quick reply. The memory error was while performing inference with logits 
```
logits = model(input_values)["logits"]
logits.shape
```

While using `pipeline`, It took almost an hour to process but the output was empty.

Below is the snippet - 
```
from transformers import pipeline
import os
import logging

logging.basicConfig(
    format='%(asctime)s %(levelname)-8s %(message)s',
    level=logging.INFO,
    datefmt='%Y-%m-%d %H:%M:%S')

logging.info("Decoding the audio files..")
pipe = pipeline(model="facebook/wav2vec2-base-960h")
audio_url = "youtube/stevejobs-speech-mono.wav"
logging.info("Starting pipeline..")
output = pipe(audio_url, chunk_length_s=10, stride_length_s=(4, 2))
logging.info("Converted text :", output)
```

Output - 
```
2022-04-25 20:36:25 INFO     Decoding the audio files..
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.05k/2.05k [00:00<00:00, 688kB/s]
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
2022-04-25 20:36:40 INFO     Starting pipeline..
2022-04-25 21:25:26 INFO     Converted text :
```

**Comment by patrickvonplaten** [comment]
Hey @iamshreeram,

Can you maybe upload the audio of the video to somewhere it can be downloaded?
