### ISSUE TITLE
Can't load pretrained TrOCR model

### ISSUE THREAD

**Issue by NouamaneTazi** [huggingface/transformers#16687]
@NielsRogge I get this error when I try to load a local TrOCR checkpoint.
```python
>>> processor = TrOCRProcessor.from_pretrained("./checkpoint-2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/users/gpupro/gpu_tazi/.local/lib/python3.8/site-packages/transformers/processing_utils.py", line 186, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/usr/users/gpupro/gpu_tazi/.local/lib/python3.8/site-packages/transformers/processing_utils.py", line 230, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
  File "/usr/users/gpupro/gpu_tazi/.local/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 544, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/usr/users/gpupro/gpu_tazi/.local/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 564, in __getitem__
    raise KeyError(key)
KeyError: <class 'transformers.models.vision_encoder_decoder.configuration_vision_encoder_decoder.VisionEncoderDecoderConfig'>
```
This is the content of my checkpoint folder:
```
checkpoint-2
  |-trainer_state.json
  |-preprocessor_config.json
  |-training_args.bin
  |-scaler.pt
  |-optimizer.pt
  |-scheduler.pt
  |-pytorch_model.bin
  |-rng_state.pth
  |-config.json
```

Yet, loading a TrOCR checkpoint from the hub works just fine.

**Comment by CuarteroAlvaro** [comment]
I have exactly the same problem. If anyone finds a solution, input would be appreciated. If I manage to solve it, I will post it here ASAP.

**Comment by NouamaneTazi** [comment]
Could be related to https://github.com/huggingface/transformers/issues/14884

**Comment by emigomez** [comment]
I have the same problem, Is any solution to this?

**Comment by ydshieh** [comment]
@NouamaneTazi  If the new version 4.19 still doesn't work with your local checkpoint, could you please upload your checkpoint/config files to your HF Hub repo, and provide a link to it?

@emigomez Do you use a local checkpoint or a checkpoint from the Hub? Could you try with v4.19?

**Comment by CuarteroAlvaro** [comment]
Hi @emigomez , if the solution proposed by @ydshieh doesn't work for you, what I did was to train the model as in the tutorials and, once trained, load the model from the generated checkpoint:

```
model = VisionEncoderDecoderModel.from_pretrained(/path/to/local/checkpoint)
```

And the preprocessor I load it from the hub (using the same checkpoint of the pretrained model), for example, if you have finetuned the model from `microsoft/trocr-base-printed`:
```
preprocessor = TrOCRProcessor.from_pretrained(`microsoft/trocr-base-printed`).
```
This way the combination model + preprocessor works for me, allowing me to use the models to predict. 

I hope it helps you!

**Comment by emigomez** [comment]
Hi @ydshieh  I am using my local checkpoints obtained after fine tuning, and I am using the v4.19 yes
I have generated this pretrained model with     
```
    trainer = Seq2SeqTrainer(.....)
    trainer.train()
    trainer.save_model("./models")
```
    
Hi @CuarteroAlvaro I was trying to make the inference with my model with:
```
    MODEL_PATH = "./models/checkpoints/checkpoint_10000/" # option 1
    MODEL_PATH = "./models/" # option 2
    processor = TrOCRProcessor.from_pretrained(MODEL_PATH) 
    model = VisionEncoderDecoderModel.from_pretrained(MODEL_PATH)   
```
    
My error appears when I was trying to load the processor, so as you suggested I load the one used in my training:
`    processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-printed') `
    
This is the complete code that I'm using to infer:
```
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
import requests 
from PIL import Image
import time
import torch

MODEL_PATH = "./models/checkpoints/checkpoint_10000/" # option 1
MODEL_PATH = "./models/" # option 2

processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-printed') 
model = VisionEncoderDecoderModel.from_pretrained(MODEL_PATH)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Running in device:", device)
model.to(device)

image = Image.open("0_0.tif").convert("RGB")
timeini = time.time()

pixel_values = processor(image, return_tensors="pt").pixel_values 
generated_ids = model.generate(pixel_values)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0] 

timeend = time.time() - timeini
print("\nResult: ", generated_text)
print("Execution time: ", timeend)
```

When I used the MODEL_PATH option 1, I obtain the next error:
```
Traceback (most recent call last):
  File "trocr_infer.py", line 11, in <module>
    model = VisionEncoderDecoderModel.from_pretrained(MODEL_PATH)
    ...
    OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ./models/checkpoints/checkpoint_10000/ is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```

With the option 2, I obtain the next error:
```
$ python trocr_infer.py 
Running in device: cuda
Traceback (most recent call last):
  File "trocr_infer.py", line 21, in <module>
    generated_ids = model.generate(pixel_values)
    ...
    RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

And this are the files that I have under the previous folders:
models/:
checkpoints/  config.json  preprocessor_config.json  pytorch_model.bin  runs/  training_args.bin
models/checkpoints/checkpoint-10000/:
config.json  optimizer.pt  preprocessor_config.json  pytorch_model.bin  rng_state.pth  scaler.pt  scheduler.pt  trainer_state.json  training_args.bin

Thank you both for your quick reply!!

**Comment by emigomez** [comment]
The problem was that my model is on the GPU, but my data is on the CPU. So, I need to send my data to GPU changing on the previous code that I have shared:

`generated_ids = model.generate(pixel_values.to(device))`

And that is working.

Thank you!!

**Comment by CuarteroAlvaro** [comment]
Yes, i was just writing the answer!

**Comment by CuarteroAlvaro** [comment]
@ydshieh, The problem appears when trying to load the preprocessor from a local checkpoint. I think this code will reproduce the issue:

```python
from transformers import TrOCRProcessor, VisionEncoderDecoderModel

processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-printed')
model = VisionEncoderDecoderModel.from_pretrained('microsoft/trocr-base-printed')
model.save_pretrained("./local_checkpoint")
loaded_preprocessor = TrOCRProcessor.from_pretrained('./local_checkpoint')
loaded_model = VisionEncoderDecoderModel.from_pretrained('./local_checkpoint')
print(loaded_preprocessor, loaded_model)

```

**Comment by ydshieh** [comment]
Hi, @CuarteroAlvaro 

In you code snippet, there is 1 line missing
```
processor.save_pretrained('./local_checkpoint')  # <-- this is required 
```
The following will work
```
from transformers import TrOCRProcessor, VisionEncoderDecoderModel

processor = TrOCRProcessor.from_pretrained('microsoft/trocr-base-printed')
model = VisionEncoderDecoderModel.from_pretrained('microsoft/trocr-base-printed')
model.save_pretrained("./local_checkpoint")
processor.save_pretrained('./local_checkpoint')  # <-- this is required 
loaded_preprocessor = TrOCRProcessor.from_pretrained('./local_checkpoint') 
loaded_model = VisionEncoderDecoderModel.from_pretrained('./local_checkpoint')
print(loaded_preprocessor, loaded_model)
```

But I can't reproduce the error shown in @NouamaneTazi 's original issue.
```
KeyError: <class 'transformers.models.vision_encoder_decoder.configuration_vision_encoder_decoder.VisionEncoderDecoderConfig'>
```
