### ISSUE TITLE
KeyError: 'src_texts' in train_distil_marian_enro.sh

### ISSUE THREAD

**Issue by Bachstelze** [huggingface/transformers#17781]
### System Info

```shell
0% 0/6 [00:00<?, ?it/s][INFO|trainer_utils.py:686] 2022-06-20 14:53:01,661 >> The following columns in the training set don't have a corresponding argument in `MarianMTModel.forward` and have been ignored: id, src_texts, tgt_texts. If id, src_texts, tgt_texts are not expected by `MarianMTModel.forward`,  you can safely ignore this message.
Traceback (most recent call last):
  File "transformers/examples/legacy/seq2seq/finetune_trainer.py", line 375, in <module>
    main()
  File "transformers/examples/legacy/seq2seq/finetune_trainer.py", line 313, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1413, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 1625, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer_utils.py", line 696, in __call__
    return self.data_collator(features)
  File "/content/transformers/examples/legacy/seq2seq/utils.py", line 298, in __call__
    batch = self._encode(batch)
  File "/content/transformers/examples/legacy/seq2seq/utils.py", line 334, in _encode
    [x["src_texts"] for x in batch],
  File "/content/transformers/examples/legacy/seq2seq/utils.py", line 334, in <listcomp>
    [x["src_texts"] for x in batch],
KeyError: 'src_texts'
  0% 0/6 [00:00<?, ?it/s]
```
```


### Who can help?

Model Marian: @patil-suraj

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

./examples/legacy/seq2seq/train_distil_marian_enro.sh

### Expected behavior

```shell
fine-tune the marian model
```

**Comment by AWilkinsonSorenson** [comment]
Same issue

**Comment by dataaug** [comment]
pip install transformers==4.15.0
