### ISSUE TITLE
 求教：load BERT 模型报错 

### ISSUE THREAD

**Issue by aaronzhangTechGeek** [huggingface/transformers#18107]
### System Info

OS: Windows-10-10.0.19041-SP0
Python: 3.8.3
PyTorch: 1.12.0+cpu
TensorFlow: 2.6.0
HanLP: 2.1.0-beta.36

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I tried the 2 options:

1. recog = hanlp.load('MSRA_NER_BERT_BASE_ZH')
OR
2. recog = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)

Error Log:
>>> import hanlp
>>> recognizer = hanlp.load(hanlp.pretrained.ner.MSRA_NER_BERT_BASE_ZH)
2022-07-12 16:32:32.871385: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-07-12 16:32:32.871563: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-07-12 16:32:44.634072: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2022-07-12 16:32:44.634254: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-07-12 16:32:44.654910: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: SZH-C-000XF
2022-07-12 16:32:44.655263: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: SZH-C-000XF
2022-07-12 16:32:51.161833: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Failed to load https://file.hankcs.com/hanlp/ner/ner_bert_base_msra_20211227_114712.zip.
If the problem still persists, please submit an issue to https://github.com/hankcs/HanLP/issues
When reporting an issue, make sure to paste the FULL ERROR LOG below.
================================ERROR LOG BEGINS================================
OS: Windows-10-10.0.19041-SP0
Python: 3.8.3
PyTorch: 1.12.0+cpu
TensorFlow: 2.6.0
HanLP: 2.1.0-beta.36
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\__init__.py", line 43, in load
    return load_from_meta_file(save_dir, 'meta.json', verbose=verbose, **kwargs)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\utils\component_util.py", line 175, in load_from_meta_file
    raise e from None
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\utils\component_util.py", line 99, in load_from_meta_file
    obj.load(save_dir, verbose=verbose, **kwargs)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\common\keras_component.py", line 214, in load
    self.build(**merge_dict(self.config, training=False, logger=logger, **kwargs, overwrite=True, inplace=True))
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\common\keras_component.py", line 224, in build
    self.model = self.build_model(**merge_dict(self.config, training=kwargs.get('training', None),
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\components\taggers\transformers\transformer_tagger_tf.py", line 34, in build_model
    model, tokenizer = build_transformer(transformer, max_seq_length, len(self.transform.tag_vocab), tagging=True)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\layers\transformers\loader_tf.py", line 11, in build_transformer
    tokenizer = AutoTokenizer_.from_pretrained(transformer)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\hanlp\layers\transformers\pt_imports.py", line 68, in from_pretrained
    tokenizer = cls.from_pretrained(get_tokenizer_mirror(transformer), use_fast=use_fast,
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\transformers\models\auto\tokenization_auto.py", line 535, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\transformers\models\auto\configuration_auto.py", line 705, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\transformers\configuration_utils.py", line 553, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\AAH2SZH\AppData\Roaming\Python\Python38\site-packages\transformers\configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load config for 'bert-base-chinese'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-chinese' is the correct path to a directory containing a config.json file

### Expected behavior

fix the error

**Comment by whaleloops** [comment]
what is your transformers version?
