### ISSUE TITLE
Running `examples/pytorch/summarization/run_summarization.py --help` gives `TypeError: can only concatenate tuple (not "str") to tuple`

### ISSUE THREAD

**Issue by mattf1n** [huggingface/transformers#18222]
### System Info

- `transformers` version: 4.21.0.dev0
- Platform: macOS-12.3-x86_64-i386-64bit
- Python version: 3.10.0
- Huggingface_hub version: 0.7.0
- PyTorch version (GPU?): 1.11.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.5.0 (cpu)
- Jax version: 0.3.13
- JaxLib version: 0.3.10
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sgugger @patil-suraj 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running `examples/pytorch/summarization/run_summarization.py --help` gives `TypeError: can only concatenate tuple (not "str") to tuple` in my environment.
1. `git clone https://github.com/huggingface/transformers`
2. `cd transformers`
3. `pip install .`
4. `pip install -r examples/pytorch/summarization/requirements.txt`
5. `python examples/pytorch/summarization/run_summarization.py --help`

### Expected behavior

(full traceback)
```
Traceback (most recent call last):
  File "/Users/matthewf/transformers/examples/pytorch/summarization/run_summarization.py", line 735, in <module>
    main()
  File "/Users/matthewf/transformers/examples/pytorch/summarization/run_summarization.py", line 304, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/Users/matthewf/.pyenv/versions/3.9.7/envs/transformers/lib/python3.9/site-packages/transformers/hf_argparser.py", line 217, in parse_args_into_dataclasses
    namespace, remaining_args = self.parse_known_args(args=args)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1853, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2062, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2002, in consume_optional
    take_action(action, args, option_string)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1930, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 1094, in __call__
    parser.print_help()
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2550, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 2534, in format_help
    return formatter.format_help()
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 530, in _format_action
    help_text = self._expand_help(action)
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 626, in _expand_help
    return self._get_help_string(action) % params
  File "/Users/matthewf/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/argparse.py", line 697, in _get_help_string
    help += ' (default: %(default)s)'
TypeError: can only concatenate tuple (not "str") to tuple
```

**Comment by sgugger** [comment]
Thanks for flagging! The PR mentioned above should fix it.
