### ISSUE TITLE
ConnectionError when downloading weights

### ISSUE THREAD

**Issue by LivC93** [huggingface/transformers#20019]
### System Info

transformers.__version__: 4.24.0
python: 3.7.13
OS: Ubuntu 22.04.1 LTS
conda 4.12.0

### Who can help?

@LysandreJik 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, EsmForProteinFolding

model = EsmForProteinFolding.from_pretrained("facebook/esmfold_v1")
```

Error:

```
File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 566, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 524, in _fp_read
    data = self._fp.read(chunk_amt)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/http/client.py", line 465, in read
    n = self.readinto(b)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/http/client.py", line 509, in readinto
    n = self.fp.readinto(b)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 627, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 592, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/urllib3/response.py", line 448, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_esm.py", line 5, in <module>
    model = EsmForProteinFolding.from_pretrained("facebook/esmfold_v1")
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2091, in from_pretrained
    resolved_archive_file = cached_file(pretrained_model_name_or_path, filename, **cached_file_kwargs)
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1231, in hf_hub_download
    headers=headers,
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 490, in http_get
    for chunk in r.iter_content(chunk_size=1024):
  File "/home/liviu/anaconda3/envs/tcr/lib/python3.7/site-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
```

### Expected behavior

The weights are getting downloaded and at around 8-10% i get the above error. This behaviour is solved if I use my Uni VPN. 

Do I need special credentials to use ESMFold? Why would it work over VPN but not directly?

**Comment by sgugger** [comment]
Looks like it's a connection issue on your end. There is no special credentials needed to load the model :-)

**Comment by LivC93** [comment]
> Looks like it's a connection issue on your end. There is no special credentials needed to load the model :-)

@sgugger thanks for the fast answer. if I write like this:

`model = EsmForProteinFolding.from_pretrained("https://dl.fbaipublicfiles.com/fair-esm/models/esmfold_3B_v1.pt")`

It works just fine I get no errors, but I get the following warning

```
UserWarning: Using `from_pretrained` with the url of a file (here https://dl.fbaipublicfiles.com/fair-esm/models/esmfold_3B_v1.pt) is deprecated and won't be possible anymore in v5 of Transformers. You should host your file on the Hub (hf.co) instead and use the repository ID. Note that this is not compatible with the caching system (your file will be downloaded at each execution) or multiple processes (each process will download the file in a different temporary file).
  f"Using `from_pretrained` with the url of a file (here {url}) is deprecated and won't be possible anymore in"
```

**Comment by sgugger** [comment]
Yes, you should use the repo ID from the Hub.

**Comment by HalfBakedBaker** [comment]
im getting this error : Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config from: E:\AIStableDif\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\v2-1_512-nonema-pruned.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading:  20%|█████████████                                                    | 795M/3.94G [00:53<02:54, 18.1MB/s]Traceback (most recent call last):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\kiera\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
  File "C:\Users\kiera\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\kiera\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\kiera\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 566, in read
    with self._error_catcher():
  File "C:\Users\kiera\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\urllib3\response.py", line 449, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\ui.py", line 1646, in <lambda>
    fn=lambda value, k=k: run_settings_single(value, key=k),
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\ui.py", line 1487, in run_settings_single
    if not opts.set(key, value):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\shared.py", line 479, in set
    self.data_labels[key].onchange()
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\webui.py", line 64, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()))
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 344, in reload_model_weights
    load_model(checkpoint_info)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\modules\sd_models.py", line 312, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 563, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 630, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 147, in __init__
    model, _, _ = open_clip.create_model_and_transforms(arch, device=torch.device('cpu'), pretrained=version)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\open_clip\factory.py", line 201, in create_model_and_transforms
    model = create_model(
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\open_clip\factory.py", line 159, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\open_clip\pretrained.py", line 312, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\open_clip\pretrained.py", line 282, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1242, in hf_hub_download
    http_get(
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 495, in http_get
    for chunk in r.iter_content(chunk_size=1024):
  File "E:\AIStableDif\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 760, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading:  20%|█████████████                                                    | 796M/3.94G [01:10<02:54, 18.1MB/s]

**Comment by HalfBakedBaker** [comment]
adding git pull to the user.bat file fixed the issue for me, turns out automatic 1111 was out of date ( incase anyone else having same issue and sees this )
