### ISSUE TITLE
No module named 'keras.saving.hdf5_format'

### ISSUE THREAD

**Issue by cvinker** [huggingface/transformers#20457]
I am running a virtual instance of Ubuntu 22.04LTS on Google Cloud. I have followed these instructions:[https://huggingface.co/docs/transformers/installation](url)
I am running solely CPU so I followed the instructions for that. Independently installed tensorflow, flax, and pytorch without error. 
After doing this and using the test command:
`python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('we love you'))"
`

I get the following error:

```
(.env) colinvink2002@instance-1:~$ python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('we love you'))"
2022-11-25 18:45:40.340282: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-11-25 18:45:40.556836: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-11-25 18:45:40.556907: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-11-25 18:45:41.795427: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-11-25 18:45:41.795623: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe
2022-11-25 18:45:41.795646: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 629/629 [00:00<00:00, 298kB/s]
Traceback (most recent call last):
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1076, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/colinvink2002/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/models/distilbert/modeling_tf_distilbert.py", line 34, in <module>
    from ...modeling_tf_utils import (
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/modeling_tf_utils.py", line 39, in <module>
    from keras.saving.hdf5_format import save_attributes_to_hdf5_group
ModuleNotFoundError: No module named 'keras.saving.hdf5_format'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 727, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/pipelines/base.py", line 233, in infer_framework_load_model
    _class = getattr(transformers_module, f"TF{architecture}", None)
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1067, in __getattr__
    value = getattr(module, name)
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1066, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/colinvink2002/.env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1078, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.distilbert.modeling_tf_distilbert because of the following error (look up to see its traceback):
No module named 'keras.saving.hdf5_format'
```

**Comment by cvinker** [comment]
Ah, I used `pip install git+https://github.com/huggingface/transformers` works now.
