### ISSUE TITLE
Couldn't reach server at '{}' to download vocabulary files.

### ISSUE THREAD

**Issue by venusafroid** [huggingface/transformers#2116]
Traceback (most recent call last):
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f912c2cc550>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-base-chinese-vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f912c2cc550>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 360, in _from_pretrained
    resolved_vocab_files[file_id] = cached_path(file_path, cache_dir=cache_dir, force_download=force_download, proxies=proxies, resume_download=resume_download)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/file_utils.py", line 180, in cached_path
    resume_download=resume_download)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/file_utils.py", line 327, in get_from_cache
    http_get(url, temp_file, proxies=proxies, resume_size=resume_size)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/file_utils.py", line 243, in http_get
    response = requests.get(url, stream=True, proxies=proxies, headers=headers)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-base-chinese-vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f912c2cc550>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bert.py", line 125, in <module>
    text_train, text_dev, text_test, label_train, label_dev, label_test = load_dataset('qa_dataset/Beauty_domain.txt', max_len = 60)
  File "bert.py", line 96, in load_dataset
    text_list = prepare_data(text_list)
  File "bert.py", line 54, in prepare_data
    tokenizer = BertTokenizer.from_pretrained("bert-base-chinese")
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 286, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/hgy/anaconda3/envs/pytorch-python3/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 372, in _from_pretrained
    raise EnvironmentError(msg)
OSError: Couldn't reach server at '{}' to download vocabulary files.

**Comment by paulmwatson** [comment]
Did you find out what the problem was @venusafroid ?

**Comment by guoquan** [comment]
> Did you find out what the problem was @venusafroid ?

I think op had a problem connecting to s3 as shown in the log
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /models.huggingface.co/bert/bert-base-chinese-vocab.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f912c2cc550>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
@paulmwatson Not sure if it s the same issue for you. 
The cases for `EnvironmentError` varies. There are file not exist, archive format not recognized, and many other raise by OS.
I got cache directory access denied, for example.
You may refer to the earlier part of your log.

However, I think it is a bug having `"{}"` in log string. Maybe they forgot to put a more informative argument in the format string.

**Comment by ZiedHY** [comment]
Hello, I am calling the "fill-mask" pipeline with "camembert-base" and I am also facing this same issue when running on AWS Lambda:
`module initialization error: Couldn't reach server at '{}' to download vocabulary files.`

Since I have a size limit around 260Mb for my lambda deployment package, downloading the model (.bin) manually and saving it to my working directory was not possible. I've tried to download it from another s3 repo and I also tried many proxies, but without success. 
I am using this "light" pytorch version: 1.0.1.post2. 

Do you have any idea? @paulmwatson @guoquan @thomwolf @LysandreJik @VictorSanh @julien-c 

Thank you!!  
--
