### ISSUE TITLE
Conversion Script Tatoeba

### ISSUE THREAD

**Issue by hthanhbmt** [huggingface/transformers#21306]
### System Info

I follow this guide https://github.com/huggingface/transformers/tree/main/scripts/tatoeba to convert models from Tatoeba Translation Challenge to Huggingface but when I ran 
`python3 src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py --models kor-eng --save_dir converted` 
it returns like the below, I found that the find_vocab_file function requires a vocab file with ext .yml, but the model from Tatoeba doesn't has.

```
  0%|                                                                                                          | 0/1 [00:01<?, ?it/s]Traceback (most recent call last):
  File "src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py", line 1324, in <module>
    resolver.convert_models(args.models[0])
  File "src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py", line 90, in convert_models
    convert(save_dir / model["_name"], dest_dir / f"opus-mt-{pair_name}")
  File "/tmp/transformers/src/transformers/models/marian/convert_marian_to_pytorch.py", line 663, in convert
    opus_state = OpusState(source_dir)
  File "/tmp/transformers/src/transformers/models/marian/convert_marian_to_pytorch.py", line 494, in __init__
    self.tokenizer = self.load_tokenizer()
  File "/tmp/transformers/src/transformers/models/marian/convert_marian_to_pytorch.py", line 592, in load_tokenizer
    add_special_tokens_to_vocab(self.source_dir, not self.share_encoder_decoder_embeddings)
  File "/tmp/transformers/src/transformers/models/marian/convert_marian_to_pytorch.py", line 409, in add_special_tokens_to_vocab
    vocab = load_yaml(find_vocab_file(model_dir))
  File "/tmp/transformers/src/transformers/models/marian/convert_marian_to_pytorch.py", line 385, in find_vocab_file
    return list(model_dir.glob("*vocab.yml"))[0]
IndexError: list index out of range
```

@sgugger @stevhliu 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.  clone and install https://github.com/huggingface/transformers/tree/main/scripts/tatoeba
2. run python3 src/transformers/models/marian/convert_marian_tatoeba_to_pytorch.py --models kor-eng --save_dir converted

### Expected behavior

it can convert successfully

**Comment by sgugger** [comment]
cc @ArthurZucker

**Comment by ArthurZucker** [comment]
I'll have a look thanks for reporting

**Comment by ArthurZucker** [comment]
Sorry, but it seems that all the formats are messed up w.r.t. the old scripts. These are not maintained and thus we don't plan on fixing this. If you want to however, feel free to contribute!
