### ISSUE TITLE
Is there support for TensorflowJs?

### ISSUE THREAD

**Issue by hamletbatista** [huggingface/transformers#2135]
## ❓ Questions & Help

I managed to save my tenforflow 2.0 model and I see keras .h5 and config.json files.

When I run the tensorflowjs converter it seems to run with no issues.

!tensorflowjs_converter --input_format=keras save/tf_model.h5 save/tfjs_model

I see the output as expected in the generated files. But, when I try to load them from Javascript, I get these errors:

models.ts:287 Uncaught (in promise) TypeError: Cannot read property 'model_config' of null
    at models.ts:287
    at common.ts:14
    at Object.next (common.ts:14)
    at a (common.ts:14)

I found some Github issues like this one https://github.com/tensorflow/tfjs/issues/931, that mention the issue is that the .h5 file only includes the weights and they provide a workaround which involves saving the model with the weights, but it is not clear to me how to do that with the HF library.

Is this something you support or is there a way to get the Keras model with the weights?

**Comment by julien-c** [comment]
My understanding is that tfjs is still kinda unstable so you’d be better off bringing that issue there.

That being said, @Pierrci has tried to do similar stuff so might be able to chime in.

**Comment by hamletbatista** [comment]
thanks, @julien-c I will repost there. Do you think I could have better luck if I try this with torchjs instead? 

I tried ONNX and faced multiple roadblocks. I didn't anticipate running transformer models in JavaScript would be so challenging 😅

**Comment by Pierrci** [comment]
> I found some Github issues like this one [tensorflow/tfjs#931](https://github.com/tensorflow/tfjs/issues/931), that mention the issue is that the .h5 file only includes the weights and they provide a workaround which involves saving the model with the weights, but it is not clear to me how to do that with the HF library.
> 
> Is this something you support or is there a way to get the Keras model with the weights?

Yes the first step is actually to convert the Keras model into a SavedModel format, you can see this notebook as an example: https://colab.research.google.com/drive/1p1Nifh1P-vqAZ1gHsNSCXAHzVWzl5YPP (from my experiments it doesn't work on all models).

Once you have the SavedModel then you can use (in another environment with TF 1.15 since it's the [TFJS converter requirement](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/python/requirements.txt)) the `tfjs.converters.convert_tf_saved_model` method to convert to TFJS format. But then you might run into exceptions like `Unsupported Ops` (it seems a lot of operators are yet to be implemented in TFJS).

Feel free to cross-reference this issue if you post another issue in the TFJS repo!

**Comment by hamletbatista** [comment]
thanks, @Pierrci let me try this out

**Comment by hamletbatista** [comment]
@Pierrci the conversion to savedmodel works, but now I get an error when converting to tfjs:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/position_embeddings/embedding_lookup was passed float from Func/StatefulPartitionedCall/input/_3:0 incompatible with expected resource.

I will try changing the input tensor spec to float32

**Comment by Pierrci** [comment]
@hamletbatista which version of TensorFlow did you use to convert to SavedModel format? Is it the nightly or an older one like 2.0?

**Comment by hamletbatista** [comment]
@Pierrci I used 2.0. Then, I created a second version using the nightly, but my Colab crashed. Trying it now. I'll let you know.

**Comment by hamletbatista** [comment]
@Pierrci I  get the same error with TF nightly. I will post it in TFJS and cross-reference this issue 

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:303: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/position_embeddings/embedding_lookup was passed float from Func/StatefulPartitionedCall/input/_3:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 429, in convert_tf_saved_model
    frozen_graph = _freeze_saved_model_v2(concrete_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 315, in _freeze_saved_model_v2
    concrete_func).graph
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py", line 575, in convert_variables_to_constants_v2
    converted_input_indices)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/convert_to_constants.py", line 371, in _construct_concrete_function
    new_output_names)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py", line 632, in function_from_graph_def
    wrapped_import = wrap_function(_imports_graph_def, [])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py", line 610, in wrap_function
    collections={}),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py", line 86, in __call__
    return self.call_with_variable_creator_scope(self._fn)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py", line 92, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/wrap_function.py", line 630, in _imports_graph_def
    importer.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 0 of node StatefulPartitionedCall/tf_bert_for_sequence_classification/bert/embeddings/position_embeddings/embedding_lookup was passed float from Func/StatefulPartitionedCall/input/_3:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 645, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 649, in main
    convert(argv[0].split(' '))
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/converter.py", line 595, in convert
    strip_debug_ops=args.strip_debug_ops)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 432, in convert_tf_saved_model
    output_node_names)
  File "/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/tf_saved_model_conversion_v2.py", line 305, in _freeze_saved_model_v1
    sess, g.as_graph_def(), output_node_names)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 277, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 197, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/graph_util_impl.py", line 152, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: Identity is not in graph

**Comment by hamletbatista** [comment]
Hi @Pierrci made a copy of your notebook and tried my model there and got it to export fine. Thanks a lot for your help! Now, let's see if it works in JavaScript :)

**Comment by hamletbatista** [comment]
Now I get a missing operator AddV2 in TFJS

Uncaught (in promise) Error: Tensorflow Op is not supported: AddV2

I will take a break and look into this.

**Comment by hamletbatista** [comment]
Got it to work with tfjs 1.4.0.

**Comment by Pierrci** [comment]
Wonderful! Can I ask you what is the model you're working with @hamletbatista?

**Comment by hamletbatista** [comment]
@Pierrci Sure. I wrote a couple of articles about this. See https://www.searchenginejournal.com/automated-intent-classification-using-deep-learning-part-2/318691/

I'm trying to get this to work from within Excel and need it working in JavaScript while keeping things simple. I tried Ludwig, but it doesn't support this. See https://github.com/uber/ludwig/issues/575

**Comment by Pierrci** [comment]
Thanks!
