### ISSUE TITLE
Finetuning RAG-Getting git.exc.InvalidGitRepositoryError 

### ISSUE THREAD

**Issue by harithareddy84** [huggingface/transformers#21555]
### System Info

- `transformers` version: 4.26.0
- Platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.27
- Python version: 3.10.8
- Huggingface_hub version: 0.12.0
- PyTorch version (GPU?): 1.13.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

For finetuning,I ran below command 
!python "finetune_rag.py" \
    --data_dir "RAGData" \
    --output_dir "output_ft" \
    --model_name_or_path facebook/rag-token-base \
    --model_type rag_token \
    --distributed_retriever pytorch \
    --gpus 2 \
    --do_train \
    --do_predict 

Getting following error:
The tokenizer class you load from this checkpoint is 'RagTokenizer'. 
The class this function is called from is 'BartTokenizerFast'.
Traceback (most recent call last):
  File "/workspace/finetune_rag.py", line 649, in <module>
    main(args)
  File "/workspace/finetune_rag.py", line 586, in main
    model: GenerativeQAModule = GenerativeQAModule(args)
  File "/workspace/finetune_rag.py", line 157, in __init__
    save_git_info(self.hparams.output_dir)
  File "/workspace/utils_rag.py", line 145, in save_git_info
    repo_infos = get_git_info()
  File "/workspace/utils_rag.py", line 161, in get_git_info
    repo = git.Repo(path)
  File "/opt/conda/lib/python3.10/site-packages/git/repo/base.py", line 282, in __init__
    self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir
  File "/opt/conda/lib/python3.10/site-packages/git/repo/base.py", line 363, in common_dir
    raise InvalidGitRepositoryError()
git.exc.InvalidGitRepositoryError

Please help.

### Who can help?

@lhoestq 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

For finetuning,I ran below command  in Jupyter notebook
!python "finetune_rag.py" \
    --data_dir "RAGData" \
    --output_dir "output_ft" \
    --model_name_or_path facebook/rag-token-base \
    --model_type rag_token \
    --distributed_retriever pytorch \
    --gpus 2 \
    --do_train \
    --do_predict 

### Expected behavior

Finetuning of RAG

**Comment by gante** [comment]
Hi @harithareddy84 👋 It seems like you have a `git`-related issue, not a `transformers`-related issue. I'm afraid we won't be able to help -- try searching for the error message :)

**Comment by Luckick** [comment]
> Hi @harithareddy84 👋 It seems like you have a `git`-related issue, not a `transformers`-related issue. I'm afraid we won't be able to help -- try searching for the error message :)

It is from a huggingface example: https://github.com/huggingface/transformers/blob/main/examples/research_projects/rag/README.md
Following the README file to run the command will get such error. Something to set up the folders must be missing so the experiment is not able to be replicated.

**Comment by mujeeb-gh** [comment]
> ### System Info
> * `transformers` version: 4.26.0
> * Platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.27
> * Python version: 3.10.8
> * Huggingface_hub version: 0.12.0
> * PyTorch version (GPU?): 1.13.1 (True)
> * Tensorflow version (GPU?): not installed (NA)
> * Flax version (CPU?/GPU?/TPU?): not installed (NA)
> * Jax version: not installed
> * JaxLib version: not installed
> * Using GPU in script?:
> * Using distributed or parallel set-up in script?:
> 
> For finetuning,I ran below command !python "finetune_rag.py" --data_dir "RAGData" --output_dir "output_ft" --model_name_or_path facebook/rag-token-base --model_type rag_token --distributed_retriever pytorch --gpus 2 --do_train --do_predict
> 
> Getting following error: The tokenizer class you load from this checkpoint is 'RagTokenizer'. The class this function is called from is 'BartTokenizerFast'. Traceback (most recent call last): File "/workspace/finetune_rag.py", line 649, in main(args) File "/workspace/finetune_rag.py", line 586, in main model: GenerativeQAModule = GenerativeQAModule(args) File "/workspace/finetune_rag.py", line 157, in **init** save_git_info(self.hparams.output_dir) File "/workspace/utils_rag.py", line 145, in save_git_info repo_infos = get_git_info() File "/workspace/utils_rag.py", line 161, in get_git_info repo = git.Repo(path) File "/opt/conda/lib/python3.10/site-packages/git/repo/base.py", line 282, in **init** self.working_dir: Optional[PathLike] = self._working_tree_dir or self.common_dir File "/opt/conda/lib/python3.10/site-packages/git/repo/base.py", line 363, in common_dir raise InvalidGitRepositoryError() git.exc.InvalidGitRepositoryError
> 
> Please help.
> 
> ### Who can help?
> @lhoestq
> 
> ### Information
> * [ ]  The official example scripts
> * [ ]  My own modified scripts
> 
> ### Tasks
> * [ ]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
> * [ ]  My own task or dataset (give details below)
> 
> ### Reproduction
> For finetuning,I ran below command in Jupyter notebook !python "finetune_rag.py" --data_dir "RAGData" --output_dir "output_ft" --model_name_or_path facebook/rag-token-base --model_type rag_token --distributed_retriever pytorch --gpus 2 --do_train --do_predict
> 
> ### Expected behavior
> Finetuning of RAG

Hi! Were you able to resolve the error
