### ISSUE TITLE
Whisper should suppress task tokens

### ISSUE THREAD

**Issue by guillaumekln** [huggingface/transformers#22465]
### System Info

- `transformers` version: 4.27.4
- Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 2.0.0+cu117 (True)

### Who can help?

@ArthurZucker @sanchit-gandhi 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm not sure if it is the best place to report the issue, but openai/whisper updated the default list of suppressed tokens in [this commit](https://github.com/openai/whisper/commit/eab8d920edf3947294c466f3912c24ed4b191264). In particular the task tokens should be suppressed by default:

```python
>>> import transformers
>>> config = transformers.AutoConfig.from_pretrained("openai/whisper-tiny")
>>> tokenizer = transformers.AutoTokenizer.from_pretrained("openai/whisper-tiny")
>>> assert tokenizer.convert_tokens_to_ids("<|transcribe|>") in config.suppress_tokens
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> assert tokenizer.convert_tokens_to_ids("<|translate|>") in config.suppress_tokens
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

### Expected behavior

The default list of suppressed tokens should be match the list in the reference implementation.

All Whisper configurations should be updated accordingly.

**Comment by ArthurZucker** [comment]
Nice! You indeed reported this to the correct place, thanks for this catch. We should update the model!

**Comment by sanchit-gandhi** [comment]
Great catch! Would you like to open some PR's on the HF Hub to fix these `suppress_tokens` lists @guillaumekln? E.g. for the `tiny` model we need to update `suppress_tokens` in the generation config: https://huggingface.co/openai/whisper-tiny/blob/a8d76517e6d65d92771752dbbf5e9c0a1a5b3a0d/generation_config.json#L126

**Comment by guillaumekln** [comment]
Sure, I just opened pull requests for all Whisper models on the Hub. I updated both `config.json` and `generation_config.json` in separate PRs.

**Comment by sanchit-gandhi** [comment]
Thank you for the Hub PRs @guillaumekln, very clean! They all looked correct so have merged them on the Hub side 👍 Closing as complete!
