### ISSUE TITLE
Four tests fail when running the full test suite

### ISSUE THREAD

**Issue by aaugustin** [huggingface/transformers#2250]
## 🐛 Bug

```
RUN_SLOW=1 python -m unittest discover -s transformers/tests -p '*_test.py' -t . -v
```

```
======================================================================
ERROR: test_model_from_pretrained (transformers.tests.modeling_tf_albert_test.TFAlbertModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../transformers/transformers/configuration_utils.py", line 160, in from_pretrained
    config = cls.from_json_file(resolved_config_file)
  File ".../transformers/transformers/configuration_utils.py", line 213, in from_json_file
    with open(json_file, "r", encoding='utf-8') as reader:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/pq/hzv7wgqs5fq0hf1bwzy4mlzr0000gn/T/transformers_test/5b4c66df217ea00b14f607787de616bbff332ae36147a92cd94219160006685a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../transformers/transformers/tests/modeling_tf_albert_test.py", line 221, in test_model_from_pretrained
    model = TFAlbertModel.from_pretrained(model_name, cache_dir=CACHE_DIR)
  File ".../transformers/transformers/modeling_tf_utils.py", line 249, in from_pretrained
    **kwargs
  File ".../transformers/transformers/configuration_utils.py", line 173, in from_pretrained
    raise EnvironmentError(msg)
OSError: Model name 'albert-base-uncased' was not found in model name list (albert-xxlarge-v2, albert-large-v1, albert-xlarge-v1, albert-base-v2, albert-base-v1, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v1). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/albert-base-uncased/config.json' was a path or url to a configuration file named config.json or a directory containing such a file but couldn't find any such file at this path or url.

======================================================================
ERROR: test_model_from_pretrained (transformers.tests.modeling_tf_xlm_test.TFXLMModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../transformers/transformers/tests/modeling_tf_xlm_test.py", line 255, in test_model_from_pretrained
    model = XLMModel.from_pretrained(model_name, cache_dir=CACHE_DIR)
NameError: name 'XLMModel' is not defined

======================================================================
FAIL: test_inference_masked_lm (transformers.tests.modeling_roberta_test.RobertaModelIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../transformers/transformers/tests/modeling_roberta_test.py", line 227, in test_inference_masked_lm
    torch.allclose(output[:, :3, :3], expected_slice, atol=1e-3)
AssertionError: False is not true

======================================================================
FAIL: test_inference_masked_lm (transformers.tests.modeling_tf_roberta_test.TFRobertaModelIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../transformers/transformers/tests/modeling_tf_roberta_test.py", line 220, in test_inference_masked_lm
    numpy.allclose(output[:, :3, :3].numpy(), expected_slice.numpy(), atol=1e-3)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by aaugustin** [comment]
The first two are easy fixes. I put fixes in the test parallelization PR.

The last two are likely the same bug, but I'm out of my depth there.

**Comment by thomwolf** [comment]
I guess this has been fixed by now
