### ISSUE TITLE
get_class_from_dynamic_module may throw exception in multiple process

### ISSUE THREAD

**Issue by maofagui** [huggingface/transformers#22555]
### System Info

- `transformers` version: 4.22.1
- Platform: macOS-10.15.7-x86_64-i386-64bit
- Python version: 3.8.16
- Huggingface_hub version: 0.13.3
- PyTorch version (GPU?): 1.13.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no need
- Using distributed or parallel set-up in script?: no need

### Who can help?

@ArthurZucker  @sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

To simplify the problem, I design a simple code fragment to reproduce the bug: 

`
import multiprocessing as mp

def func():
    from transformers import AutoTokenizer, AutoModel

    local_dir = "/Users/mfg/Code/huggingface/glm-10b"
    tokenizer = AutoTokenizer.from_pretrained(local_dir, trust_remote_code=True)
    model = AutoModel.from_pretrained(local_dir, trust_remote_code=True)
    print(tokenizer)

if __name__ == '__main__':
    procs = []
    for i in range(10):
        p = mp.Process(target=func)
        p.start()
        procs.append(p)

    for p in procs:
        p.join()

    print("done")

`
All files in dir "/Users/mfg/Code/huggingface/glm-10b" can be found in https://huggingface.co/THUDM/glm-10b/tree/main
(no need to download the large file[pytorch_model.bin](https://huggingface.co/THUDM/glm-10b/blob/main/pytorch_model.bin) )

After you run, you may meet the exception below:
`
Process Process-6:
Process Process-5:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mfg/Code/alipay/Alps/modelhub_test/torch_submit/mp_load_model/main.py", line 7, in func
    tokenizer = AutoTokenizer.from_pretrained("/Users/mfg/Code/huggingface/glm-10b", trust_remote_code=True)
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 594, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 375, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 148, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.local.tokenization_glm' has no attribute 'GLMChineseTokenizer'
Traceback (most recent call last):
copy /Users/mfg/Code/huggingface/glm-10b/tokenization_glm.py /Users/mfg/.cache/huggingface/modules/transformers_modules/local/tokenization_glm.py
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mfg/Code/alipay/Alps/modelhub_test/torch_submit/mp_load_model/main.py", line 7, in func
    tokenizer = AutoTokenizer.from_pretrained("/Users/mfg/Code/huggingface/glm-10b", trust_remote_code=True)
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 594, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 375, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
Process Process-10:
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 148, in get_class_in_module
    return getattr(module, class_name)
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/mfg/Code/alipay/Alps/modelhub_test/torch_submit/mp_load_model/main.py", line 7, in func
    tokenizer = AutoTokenizer.from_pretrained("/Users/mfg/Code/huggingface/glm-10b", trust_remote_code=True)
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 594, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 375, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/opt/miniconda3/envs/py38_torch/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 148, in get_class_in_module
    return getattr(module, class_name)
AttributeError: module 'transformers_modules.local.tokenization_glm' has no attribute 'GLMChineseTokenizer'
AttributeError: module 'transformers_modules.local.tokenization_glm' has no attribute 'GLMChineseTokenizer'
`

### Expected behavior

no bug

**Comment by maofagui** [comment]
I will try to fix this bug and push a commit soon.

**Comment by ArthurZucker** [comment]
Awesome thanks for reporting this!

**Comment by maofagui** [comment]
> This will be fixed by #22537

OK~

**Comment by abowloflrf** [comment]
I met the same `AttributeError` issue. But the problem still exist after I update the master branch code with this fix https://github.com/huggingface/transformers/pull/22537. I'm wondering if that pr really fix this issue?

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/17028350/231663726-b80068a8-10f3-44d8-94aa-9a96102aed08.png">

Some information:

I saved glm-10b model files on NFS storage, launch 8 process one node. Add debug code as blow:
```python
# /opt/conda/lib/python3.8/site-packages/transformers/dynamic_module_utils.py
def get_class_in_module(class_name, module_path):
    """
    Import a module on the cache directory for modules and extract a class from it.
    """
    module_path = module_path.replace(os.path.sep, ".")
    module = importlib.import_module(module_path)
    try:
        return getattr(module, class_name)
    except:
        with open('/root/.cache/huggingface/modules/transformers_modules/glm-10b-chinese/configuration_glm.py', 'r') as f:
            print('print /root/.cache configuration_glm.py')
            print(f.read())
        raise
```

When the `AttributeError` exception happened, I found this code print `configuration_glm.py` file in `/root/.cache` is empty.
