### ISSUE TITLE
Compute Accuracy in clip-roberta

### ISSUE THREAD

**Issue by skaulintel** [huggingface/transformers#22641]
### Feature request

Is it possible to include an accuracy metric when training clip-roberta?

### Motivation

We would like to have something other than loss to track during training.

### Your contribution

I tried creating a dummy compute_metrics function to pass to GaudiTrainer thusly. 

    metric = evaluate.load("accuracy")
    def compute_metrics(p):
        return 1

get the following error:

Traceback (most recent call last):
  File "run_clip.py", line 553, in <module>
    main()
  File "run_clip.py", line 532, in main
    metrics = trainer.evaluate()
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2932, in evaluate
    output = eval_loop(
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer.py", line 1074, in evaluation_loop
    logits_dtype = get_dtype(logits)
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 43, in get_dtype
    return [get_dtype(logits_tensor) for logits_tensor in logits]
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 43, in <listcomp>
    return [get_dtype(logits_tensor) for logits_tensor in logits]
  File "/usr/local/lib/python3.8/dist-packages/optimum/habana/transformers/trainer_utils.py", line 45, in get_dtype
    raise TypeError(f"logits should be of type torch.Tensor or tuple, got {type(logits)} which is not supported")
TypeError: logits should be of type torch.Tensor or tuple, got <class 'transformers.modeling_outputs.BaseModelOutputWithPoolingAndCrossAttentions'> which is not supported

**Comment by regisss** [comment]
Hi @skaulintel! According to what I see in the traceback, this issue is specific to Optimum Habana. Could you move this issue [there](https://github.com/huggingface/optimum-habana/issues) please? And then I'll follow up.
