### ISSUE TITLE
Unable to install transformers due to RuntimeError with libssl.so.10

### ISSUE THREAD

**Issue by Kodhandarama** [huggingface/transformers#22716]
### System Info
Runnin gthis code on a red hat linux machine

I tried installing transformers with all the methods mentioned in https://huggingface.co/docs/transformers/installation

I am hitting the same error (related to pipelines):

Traceback (most recent call last):
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/utils/import_utils.py", line 1125, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/eng/s/sxc220013/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/pipelines/__init__.py", line 29, in <module>
    from ..models.auto.configuration_auto import AutoConfig
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/models/__init__.py", line 15, in <module>
    from . import (
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/models/mt5/__init__.py", line 36, in <module>
    from ..t5.tokenization_t5_fast import T5TokenizerFast
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/models/t5/tokenization_t5_fast.py", line 24, in <module>
    from ...tokenization_utils_fast import PreTrainedTokenizerFast
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/tokenization_utils_fast.py", line 25, in <module>
    import tokenizers.pre_tokenizers as pre_tokenizers_fast
  File "/home/eng/s/sxc220013/anaconda3/lib/python3.9/site-packages/tokenizers/__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/utils/import_utils.py", line 1115, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/eng/s/sxc220013/Documents/transformers/src/transformers/utils/import_utils.py", line 1127, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
libssl.so.10: cannot open shared object file: No such file or directory

### Who can help?

@Narsil @sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I ran the following commands : 

conda install -c huggingface transformers
python -c "from transformers import pipeline; print(pipeline('sentiment-analysis')('I love you'))"

### Expected behavior

I would expect that the following python command prints the output of the sentiment analysis.

**Comment by Narsil** [comment]
Do you have openssl installd in your environment ?

`conda install -c anaconda openssl` ? 

This library is missing from your environment and `tokenizers` is looking for it when loading.
Or do you have another version of ssl installed maybe ? You can do `locate libssl` to try and find it.

**Comment by amyeroberts** [comment]
@Kodhandarama A similar issue has been raised in #21805. As noted there, this isn't a Transformers issue per se, but appears to arise when installing with `conda`. Other users reported installing with `pip` or running `conda update tokenizers` resolved the issue.

**Comment by Narsil** [comment]
@ArthurZucker FYI.
