### ISSUE TITLE
Loading Trained RAG Model

### ISSUE THREAD

**Issue by YichiRockyZhang** [huggingface/transformers#24386]
### System Info

Python 3.9.16
Transformers 4.13.0
WSL

### Who can help?

@ArthurZucker @younesbelkada @shamanez

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

After finetuning RAG, I'm left with the following directory, and I'm not sure how to load the resulting checkpoint.

![image](https://github.com/huggingface/transformers/assets/29335344/5480c778-7b8e-40e5-a2ed-b543a970e50d)

I should note the checkpoint is ~6 GB while the [original huggingface checkpoint](https://huggingface.co/facebook/rag-token-base/tree/main) is 2 GB. I suspect this is because I used the [`finetune_rag_ray_end2end.sh`](https://github.com/huggingface/transformers/tree/main/examples/research_projects/rag-end2end-retriever) script, so it includes all 3 models (reader, retriever, generator).

Below are my attempts to load the checkpoint

**Attempt 1**
```py
ds = load_dataset(path='wiki_dpr', name='psgs_w100.multiset.compressed', split='train')

rag_tokenizer = RagTokenizer.from_pretrained("facebook/rag-token-base")
rag_retriever = RagRetriever.from_pretrained(
    "facebook/rag-token-base",
    use_dummy_dataset=False,
    indexed_dataset=ds,
    index_name="embeddings",
)

rag_model = RagTokenForGeneration.from_pretrained("facebook/rag-token-base", retriever=rag_retriever)

checkpoint_path = "/fs/nexus-scratch/yzhang42/rag_end2end/model_checkpoints_MS/val_avg_em=0.0026-step_count=601.0.ckpt"

rag_model.load_state_dict(torch.load(checkpoint_path))
```

The program runs forever with the following traceback when I interrupt it:
```
Some weights of RagTokenForGeneration were not initialized from the model checkpoint at facebook/rag-token-base and are newly initialized: ['rag.generator.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/ray/_private/services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.
  warnings.warn(warning_message)
^CTraceback (most recent call last):
  File "/nfshomes/yzhang42/rag/notebooks/rag_eval.py", line 37, in <module>
    rag_model.load_state_dict(torch.load(checkpoint_path))
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/ray/actor.py", line 1005, in _deserialization_helper
    return worker.core_worker.deserialize_and_register_actor_handle(
  File "python/ray/_raylet.pyx", line 1594, in ray._raylet.CoreWorker.deserialize_and_register_actor_handle
  File "python/ray/_raylet.pyx", line 1563, in ray._raylet.CoreWorker.make_actor_handle
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 402, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/ray/_private/function_manager.py", line 487, in _load_actor_class_from_gcs
    time.sleep(0.001)
KeyboardInterrupt
```

**Attempt 2**
```py
from transformers import AutoConfig, AutoModel, PretrainedConfig, RagTokenizer, RagRetriever, BartForConditionalGeneration, RagTokenForGeneration, RagSequenceForGeneration, RagConfig
from transformers import BartModel

qe_config = PretrainedConfig(
    name_or_path=\
        "/fs/nexus-scratch/yzhang42/rag_end2end/model_checkpoints_MS/checkpoint601/generator_tokenizer/tokenizer_config.json")
gen_config = PretrainedConfig(
    name_or_path=\
    "/fs/nexus-scratch/yzhang42/rag_end2end/model_checkpoints_MS/checkpoint601/question_encoder_tokenizer/tokenizer_config.json")

RagConfig.from_question_encoder_generator_configs(
    question_encoder_config=qe_config,
    generator_config=gen_config
)
```

Gives the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[2], line 11
      4 qe_config = PretrainedConfig(
      5     name_or_path=\
      6         "/fs/nexus-scratch/yzhang42/rag_end2end/model_checkpoints_MS/checkpoint601/generator_tokenizer/tokenizer_config.json")
      7 gen_config = PretrainedConfig(
      8     name_or_path=\
      9     "/fs/nexus-scratch/yzhang42/rag_end2end/model_checkpoints_MS/checkpoint601/question_encoder_tokenizer/tokenizer_config.json")
---> 11 RagConfig.from_question_encoder_generator_configs(
     12     question_encoder_config=qe_config,
     13     generator_config=gen_config
     14 )

File /fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/transformers/models/rag/configuration_rag.py:183, in RagConfig.from_question_encoder_generator_configs(cls, question_encoder_config, generator_config, **kwargs)
    172 @classmethod
    173 def from_question_encoder_generator_configs(
    174     cls, question_encoder_config: PretrainedConfig, generator_config: PretrainedConfig, **kwargs
    175 ) -> PretrainedConfig:
    176     r"""
    177     Instantiate a :class:`~transformers.EncoderDecoderConfig` (or a derived class) from a pre-trained encoder model
    178     configuration and decoder model configuration.
   (...)
    181         :class:`EncoderDecoderConfig`: An instance of a configuration object
    182     """
--> 183     return cls(question_encoder=question_encoder_config.to_dict(), generator=generator_config.to_dict(), **kwargs)

File /fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/transformers/models/rag/configuration_rag.py:140, in RagConfig.__init__(self, vocab_size, is_encoder_decoder, prefix, bos_token_id, pad_token_id, eos_token_id, decoder_start_token_id, title_sep, doc_sep, n_docs, max_combined_length, retrieval_vector_size, retrieval_batch_size, dataset, dataset_split, index_name, index_path, passages_path, use_dummy_dataset, reduce_loss, label_smoothing, do_deduplication, exclude_bos_score, do_marginalize, output_retrieved, use_cache, forced_eos_token_id, **kwargs)
    136 decoder_model_type = decoder_config.pop("model_type")
    138 from ..auto.configuration_auto import AutoConfig
--> 140 self.question_encoder = AutoConfig.for_model(question_encoder_model_type, **question_encoder_config)
    141 self.generator = AutoConfig.for_model(decoder_model_type, **decoder_config)
    143 self.reduce_loss = reduce_loss

File /fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py:492, in AutoConfig.for_model(cls, model_type, *args, **kwargs)
    490     config_class = CONFIG_MAPPING[model_type]
    491     return config_class(*args, **kwargs)
--> 492 raise ValueError(
    493     f"Unrecognized model identifier: {model_type}. Should contain one of {', '.join(CONFIG_MAPPING.keys())}"
    494 )

ValueError: Unrecognized model identifier: . Should contain one of imagegpt, qdqbert, vision-encoder-decoder, trocr, fnet, segformer, vision-text-dual-encoder, perceiver, gptj, layoutlmv2, beit, rembert, visual_bert, canine, roformer, clip, bigbird_pegasus, deit, luke, detr, gpt_neo, big_bird, speech_to_text_2, speech_to_text, vit, wav2vec2, m2m_100, convbert, led, blenderbot-small, retribert, ibert, mt5, t5, mobilebert, distilbert, albert, bert-generation, camembert, xlm-roberta, pegasus, marian, mbart, megatron-bert, mpnet, bart, blenderbot, reformer, longformer, roberta, deberta-v2, deberta, flaubert, fsmt, squeezebert, hubert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm-prophetnet, prophetnet, xlm, ctrl, electra, speech-encoder-decoder, encoder-decoder, funnel, lxmert, dpr, layoutlm, rag, tapas, splinter, sew-d, sew, unispeech-sat, unispeech
```

### Expected behavior

I'm not sure what expected behavior is supposed to be.

**Comment by younesbelkada** [comment]
Hi @YichiRockyZhang 
Thanks for the issue, looking at your environment (transformers == 4.13.0) I would probably give it a try with on of the newest version of transformers. It seems the config didn't saved properly the model identifier for some reason. Would it be possible to use a recent version of the lib for you?

**Comment by ydshieh** [comment]
Hi @YichiRockyZhang


If @younesbelkada's above suggesion is still not working, it would helps a lot if you can provide a short but a bit more complete code example that you:
- create/load the initialize model(s)
- save it to the checkpoint (without the need of training/fine-tuning)
- (you already provide this part) the way you try to load the saved checkpoint

This way, it's easier and fast for us to reproduce and look into the issue. Thank you in advance.

**Comment by YichiRockyZhang** [comment]
Hi @younesbelkada . Thanks for the response! Running the finetuning script results in the following error in reference to the `Seq2SeqDataset` class in [`utils_rag.py`](https://github.com/huggingface/transformers/blob/main/examples/research_projects/rag-end2end-retriever/utils_rag.py).

```
Sanity Checking DataLoader 0: 100%|██████████| 2/2 [00:19<00:00, 10.28s/it]/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py:229: UserWarning: You called `self.log('step_count', ...)` in your `validation_epoch_end` but the value needs to be floating point. Converting it to torch.float32.
  warning_cache.warn(
                                                                           Traceback (most recent call last):
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 207, in on_run_start
    self.trainer.reset_train_dataloader(self.trainer.lightning_module)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1856, in reset_train_dataloader
    self.train_dataloader = self._data_connector._request_dataloader(RunningStage.TRAINING, model=model)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 459, in _request_dataloader
    dataloader = source.dataloader()
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 532, in dataloader
    return self.instance.trainer._call_lightning_module_hook(self.name, pl_module=self.instance)
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1595, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/fs/nexus-scratch/yzhang42/rag_end2end/finetune_rag.py", line 482, in train_dataloader
    dataloader = self.get_dataloader("train", batch_size=self.hparams.train_batch_size, shuffle=True)
  File "/fs/nexus-scratch/yzhang42/rag_end2end/finetune_rag.py", line 470, in get_dataloader
    dataset = self.get_dataset(type_path)
  File "/fs/nexus-scratch/yzhang42/rag_end2end/finetune_rag.py", line 460, in get_dataset
    dataset = Seq2SeqDataset(
  File "/fs/nexus-scratch/yzhang42/rag_end2end/utils_rag.py", line 64, in __init__
    self.src_lens = self.get_char_lens(self.src_file)
  File "/fs/nexus-scratch/yzhang42/rag_end2end/utils_rag.py", line 110, in get_char_lens
    return [len(x) for x in Path(data_file).open().readlines()]
  File "/fs/nexus-scratch/yzhang42/miniconda3/envs/qa3/lib/python3.9/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2682: ordinal not in range(128)
```

Hi @ydshieh ! Unfortunately, I believe my problem is specific to fine-tuning. I'm using the only fine-tuning script for this model that I can find (in huggingface documentation and even on the internet). The script uses pytorch lightning to train and save the model. The below snippet from [`finetune_rag.py`](https://github.com/huggingface/transformers/blob/main/examples/research_projects/rag-end2end-retriever/finetune_rag.py) details how the models is saved.

```py
    @pl.utilities.rank_zero_only
    def on_save_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        save_path = self.output_dir.joinpath("checkpoint{}".format(self.step_count))
        self.model.config.save_step = self.step_count
        # self.model.save_pretrained(save_path)
        self.tokenizer.save_pretrained(save_path)

        if self.custom_config.end2end:
            modified_state_dict = self.model.state_dict()
            for key in self.model.state_dict().keys():
                if key.split(".")[1] == "ctx_encoder":
                    del modified_state_dict[key]
            self.model.save_pretrained(save_directory=save_path, state_dict=modified_state_dict)

            save_path_dpr = os.path.join(self.dpr_ctx_check_dir, "checkpoint{}".format(self.step_count))
            self.model.rag.ctx_encoder.save_pretrained(save_path_dpr)
            self.context_tokenizer.save_pretrained(save_path_dpr)
```

I understand HF does not maintain these scripts, but for what it's worth, I think retrieval-augmented models are very important and should have a bit more support!

**Comment by ydshieh** [comment]
@YichiRockyZhang 

Thanks for sharing more details. What I means is that you can still make a self-complete code snippet:

- how you (or the script create the model)
- then save the model using the method `on_save_checkpoint` you provided

You don't go through the training part in the script, just the create/save part. By ` self-complete`, it means we can just run it directly to see the failure you have. Of course you need to wrap up things in your own way (not just showing us the definition of `on_save_checkpoint`).

**Comment by YichiRockyZhang** [comment]
@ydshieh Hi, thank you for the quick responses! I've edited my above reply to reflect the fact that upgrading to transformers==4.30.2 seemed to have worked after making sure my data was ASCII encoded. Though it does seem that the fine-tuning script is only saving the whole model after the first epoch. I've adjusted the code to be 

```py
    @pl.utilities.rank_zero_only
    def on_save_checkpoint(self, checkpoint: Dict[str, Any]) -> None:
        save_path = self.output_dir.joinpath("checkpoint{}".format(self.step_count))
        self.model.config.save_step = self.step_count
        # self.model.save_pretrained(save_path)
        self.tokenizer.save_pretrained(save_path)

        if self.custom_config.end2end:
            modified_state_dict = self.model.state_dict()
            for key in self.model.state_dict().keys():
                if key.split(".")[1] == "ctx_encoder":
                    del modified_state_dict[key]
            self.model.save_pretrained(save_directory=save_path, state_dict=modified_state_dict)

            save_path_dpr = os.path.join(self.dpr_ctx_check_dir, "checkpoint{}".format(self.step_count))
            self.model.rag.ctx_encoder.save_pretrained(save_path_dpr)
            self.context_tokenizer.save_pretrained(save_path_dpr)
        else: #NEW
            state_dict = self.model.state_dict()
            self.model.save_pretrained(save_directory=save_path, state_dict=state_dict)
```

I will update this thread in the morning once fine-tuning is finished. If my fix doesn't work out, I'll try to put together a more minimal and self-complete script for debugging purposes! 🤗

**Comment by ydshieh** [comment]
Nice and good luck :-) !

**Comment by hyadava** [comment]
@ YichiRockyZhang Were you able to successfully load the fine-tuned rag model from a checkpoint? I'm running into the same issue that you reported. If I try the lightning `load_from_checkpoint()` function to load the model from a checkpoint I run into format errors
```
Traceback (most recent call last):
  File "/mnt/task_runtime/examples/research_projects/rag-end2end-retriever/finetune_rag.py", line 886, in <module>
    main(args)
  File "/mnt/task_runtime/examples/research_projects/rag-end2end-retriever/finetune_rag.py", line 812, in main
    model: GenerativeQAModule = GenerativeQAModule(args)
  File "/mnt/task_runtime/examples/research_projects/rag-end2end-retriever/finetune_rag.py", line 149, in __init__
    model = BaseTransformer.load_from_checkpoint(os.path.join(args.model_name_or_path, "last_checkpoint.ckpt"))
  File "/miniforge/envs/iris/lib/python3.10/site-packages/lightning/pytorch/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/lightning/pytorch/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/lightning/fabric/utilities/cloud_io.py", line 60, in _load
    return torch.load(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
  File "/miniforge/envs/iris/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/miniforge/envs/iris/lib/python3.10/pickle.py", line 1590, in load_reduce
    stack[-1] = func(*args)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/ray/actor.py", line 1631, in _deserialization_helper
    return worker.core_worker.deserialize_and_register_actor_handle(
  File "python/ray/_raylet.pyx", line 4478, in ray._raylet.CoreWorker.deserialize_and_register_actor_handle
  File "python/ray/_raylet.pyx", line 4429, in ray._raylet.CoreWorker.make_actor_handle
  File "/miniforge/envs/iris/lib/python3.10/site-packages/ray/_private/function_manager.py", line 539, in load_actor_class
    actor_class = self._load_actor_class_from_gcs(
  File "/miniforge/envs/iris/lib/python3.10/site-packages/ray/_private/function_manager.py", line 634, in _load_actor_class_from_gcs
    class_name = ensure_str(class_name)
  File "/miniforge/envs/iris/lib/python3.10/site-packages/ray/_private/utils.py", line 243, in ensure_str
    assert isinstance(s, bytes), f"Expected str or bytes, got {type(s)}"
AssertionError: Expected str or bytes, got <class 'NoneType'>
```

**Comment by YichiRockyZhang** [comment]
@hyadava This was a while ago but I would basically recommend using a different implementation. I'm fuzzy on whether I got it to work, but I do recall the process was rather troublesome. If possible, I would recommend using a different RAG implementation.

**Comment by hyadava** [comment]
@YichiRockyZhang Thanks for your reply!
Yes I agree, the implementation seems to be half baked. Do you recommend any rag implementation (which has the fine-tuning capability)?

**Comment by YichiRockyZhang** [comment]
@hyadava While I didn't use it too much, Pinecone seemed pretty solid :). Best of luck!
