### ISSUE TITLE
Error when try to load pretrained model

### ISSUE THREAD

**Issue by BrahianVT** [huggingface/transformers#24470]
### System Info

I've been trying to  load a pretrained model:

When I tried to execute this :

from transformers import T5ForConditionalGeneration,T5Tokenizer  
import torch  
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")  
models = T5ForConditionalGeneration.from_pretrained("Michau/t5-base-en-generate-headline")  
tokenizer = T5Tokenizer.from_pretrained("Michau/t5-base-en-generate-headline")

The result: is  : 
` Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import T5ForConditionalGeneration,T5Tokenizer
>>> import torch
>>>
>>> device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
>>> models = T5ForConditionalGeneration.from_pretrained("Michau/t5-base-en-generate-headline")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2259, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py", line 1252, in hf_hub_download
    with FileLock(lock_path):
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\filelock\_api.py", line 255, in __enter__
    self.acquire()
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\filelock\_api.py", line 213, in acquire
    self._acquire()
  File "C:\Users\BrahianVT\AppData\Local\Programs\Python\Python310\lib\site-packages\filelock\_windows.py", line 27, in _acquire
    fd = os.open(self.lock_file, flags, self._context.mode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\BrahianVT/.cache\\huggingface\\hub\\models--Michau--t5-base-en-generate-headline\\blobs\\W/"957fcaeed54459456a54d98d552a7773e717333f.lock'`

![image](https://github.com/huggingface/transformers/assets/12876560/46c229cf-aea1-4855-a36a-c9f21533e250)

I'm like a beginner in this topic anyone could help?
Regards

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from transformers import T5ForConditionalGeneration,T5Tokenizer
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
models = T5ForConditionalGeneration.from_pretrained("Michau/t5-base-en-generate-headline")
tokenizer = T5Tokenizer.from_pretrained("Michau/t5-base-en-generate-headline")

### Expected behavior

I expect the model object

**Comment by sgugger** [comment]
Please follow the issue template and give us the result of `transformers-cli env`.

**Comment by BrahianVT** [comment]
thanks installing transaformers fixed the error, I'm like a beginner in this topic , sorry 
Regards
