### ISSUE TITLE
Trouble fine tuning distilbertmodel

### ISSUE THREAD

**Issue by drissg1** [huggingface/transformers#2499]
## 🐛 Bug

Trying to run lm_finetuning on the distilbert multilanguage

Getting the following error when I run:
python lm_finetuning.py \
    --model_type='distilbert' \
    --model_name_or_path=distilbert-base-multilingual-cased\
    --train_data_file=small.txt \
    --output_dir=output \
    --mlm \
    --do_train\
    --save_total_limit=2 \
    --save_steps=1000 \
    --no_cuda

similar error when trying to run on GPU.

```
Traceback (most recent call last):
  File "lm_finetuning.py", line 712, in <module>
    main()
  File "lm_finetuning.py", line 662, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "lm_finetuning.py", line 299, in train
    outputs = model(inputs, masked_lm_labels=labels) if args.mlm else model(inputs, labels=labels)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_distilbert.py", line 550, in forward
    masked_lm_labels.view(-1))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1838, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at /pytorch/aten/src/THNN/generic/ClassNLLCriterion.c:97
Epoch:   0%|                                                                                                                                                                 | 0/1 [00:02<?, ?it/s]
Iteration:   0%|  
 ```

**Comment by txus** [comment]
According to https://github.com/huggingface/transformers/issues/2418#issuecomment-571721526, until a fix is released you should change the `-100` in your script to `-1`. It worked for me with Albert.
