### ISSUE TITLE
run_generation.py script does not work for most models

### ISSUE THREAD

**Issue by bortzmeyer** [huggingface/transformers#25143]
### System Info

- `transformers` version: 4.32.0.dev0
- Platform: Linux-6.1.0-10-amd64-x86_64-with-glibc2.36
- Python version: 3.11.2
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@sgugger

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
%  python run_generation.py  --model_type=xlnet  --model_name_or_path=xlnet
07/27/2023 16:10:16 - WARNING - __main__ - device: cpu, n_gpu: 0, 16-bits training: False
Traceback (most recent call last):
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/xlnet/resolve/main/spiece.model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/transformers/utils/hub.py", line 418, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-64c27ac9-32554ee53bfea1b506174ea7;b2323fa4-9a04-4657-a548-5ceed2fb666e)

Repository Not Found for url: https://huggingface.co/xlnet/resolve/main/spiece.model.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bortzmeyer/Programmation/Python/HuggingFace/essais/run_generation.py", line 448, in <module>
    main()
  File "/home/bortzmeyer/Programmation/Python/HuggingFace/essais/run_generation.py", line 354, in main
    tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1800, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
                                    ^^^^^^^^^^^^
  File "/home/bortzmeyer/.local/lib/python3.11/site-packages/transformers/utils/hub.py", line 439, in cached_file
    raise EnvironmentError(
OSError: xlnet is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

```

We have a similar error message with most models listed in the output of   `python run_generation.py --help` Only gpt2 and ctrl seems to work.

### Expected behavior

I expected all models listed in the help to actually work.

**Comment by sgugger** [comment]
I'm not sure why you expect this command to work: you are passing `--model_name_or_path=xlnet` which is not a valid model identifier on the Hub (as the error clearly says). You need to pick an actual model, all xlnet variants are listed [here](https://huggingface.co/models?sort=trending&search=xlnet).

**Comment by bortzmeyer** [comment]
> I'm not sure why you expect this command to work: 

Because this is the output of the `--help`  option? OK, with a full name, it works better, thanks.
