### ISSUE TITLE
use_auth_token deprecation in pipeline

### ISSUE THREAD

**Issue by maxjeblick** [huggingface/transformers#25141]
### System Info

I noticed that `pipeline` uses `use_auth_token` argument which raises `FutureWarning: The use_auth_token argument is deprecated and will be removed in v5 of Transformers.`.
Replacing `use_auth_token=True` with `token=True` argument does not yet work in `pipeline` (will raise an error).

Sys Info
```
- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.14.1
- Safetensors version: 0.3.1
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

### Who can help?

@narsil

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import torch
from transformers import pipeline

model_name = "h2oai/h2ogpt-gm-oasst1-en-2048-falcon-7b-v3"

generate_text = pipeline(
    model=model_name,
    torch_dtype="auto",
    trust_remote_code=True,
    use_fast=True,
    device_map={"": "cuda:0"},
    use_auth_token=True)

res = generate_text(
    "Why is drinking water so healthy?",
    min_new_tokens=2,
    max_new_tokens=256,
    do_sample=False,
    num_beams=1,
    temperature=float(0.3),
    repetition_penalty=float(1.2),
    renormalize_logits=True
)
print(res[0]["generated_text"])
```

### Expected behavior

pipeline handles `token=True` argument.

**Comment by sgugger** [comment]
cc @ydshieh Looks like it comes from the PR from yesterday.

**Comment by ydshieh** [comment]
Thanks for reporting, I will work on this. Not very easy to hanlde this history it turns out 👀

**Comment by maxjeblick** [comment]
Sure @ydshieh :
```
from transformers import pipeline

model_name = "facebook/opt-125m"  # small model for testing purposes

generate_text = pipeline(
    model=model_name,
    torch_dtype="auto",
    trust_remote_code=True,
    use_fast=True,
    device_map={"": "cuda:0"},
    token=True)

res = generate_text(
    "Why is drinking water so healthy?",
    min_new_tokens=2,
    max_new_tokens=256,
    do_sample=False,
    num_beams=1,
    temperature=float(0.3),
    repetition_penalty=float(1.2),
    renormalize_logits=True
)
print(res[0]["generated_text"])
```
get's

```
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
Traceback (most recent call last):
  File "/home/max/.config/JetBrains/PyCharm2023.2/scratches/scratch_2.py", line 13, in <module>
    res = generate_text(
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 200, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1122, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1129, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1028, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 261, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/generation/utils.py", line 1282, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/home/max/.virtualenvs/h2o-llmstudio-0x1AIe7C/lib/python3.10/site-packages/transformers/generation/utils.py", line 1155, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['token'] (note: typos in the generate arguments will also show up in this list)
```

**Comment by ydshieh** [comment]
Thanks! So the error only happens at the generation time, very strange it has been passed to that method! Definitely need a fix. I am on it.
