### ISSUE TITLE
more and more difficult to use

### ISSUE THREAD

**Issue by Misoknisky** [huggingface/transformers#25577]
### System Info

huggingface is going the same way as TensorFlow, version control is getting worse and worse. In particular, the versions between different packages need to be strictly adapted, which is more troublesome than TensorFlow!

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Extremely bad experience! When I used the datasets library to load the glue dataset, I found that the datasets library had a chain reaction with hub, evaluate, pandas, etc., and various conflicts did not match. The data formats provided by different hubs and other libraries are not compatible, and it is really a headache to adapt them.

### Expected behavior

Extremely bad experience! When I used the datasets library to load the glue dataset, I found that the datasets library had a chain reaction with hub, evaluate, pandas, etc., and various conflicts did not match. The data formats provided by different hubs and other libraries are not compatible, and it is really a headache to adapt them.

**Comment by Misoknisky** [comment]
>>> from datasets import load_dataset
>>>
>>>
>>> load_dataset('glue','cola')
Resolving data files: 100%|██████████████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 125829.12it/s]
Downloading data files: 100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 5518.82it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 95.26it/s]
Generating train split: 8550 examples [00:00, 287753.65 examples/s]
Traceback (most recent call last):
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/builder.py", line 1940, in _prepare_split_single
    writer.write_table(table)
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/arrow_writer.py", line 572, in write_table
    pa_table = table_cast(pa_table, self._schema)
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/table.py", line 2328, in table_cast
    return cast_table_to_schema(table, schema)
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/table.py", line 2286, in cast_table_to_schema
    raise ValueError(f"Couldn't cast\n{table.schema}\nto\n{features}\nbecause column names don't match")
ValueError: Couldn't cast
gj04: string
1: int64
Unnamed: 2: string
our friends wo n't buy this analysis , let alone the next one we propose .: string
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 837
to
{'gj04': Value(dtype='string', id=None), '1': Value(dtype='int64', id=None), 'Unnamed: 2': Value(dtype='string', id=None), "Our friends won't buy this analysis, let alone the next one we propose.": Value(dtype='string', id=None)}
because column names don't match

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/mounts/work/lyk/anaconda3/envs/torch/lib/python3.8/site-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset

**Comment by ArthurZucker** [comment]
Hey! Thanks for providing feedback, though this is the `transformers` repository, `datasets` has its own repo [here](https://github.com/huggingface/datasets) if you want to give them your thoughts!
