### ISSUE TITLE
`self.tokenizer` is nil in example code

### ISSUE THREAD

**Issue by adsr** [huggingface/transformers#25675]
### System Info

- `transformers` version: 4.33.0.dev0
- Platform: Linux-6.1.0-9-amd64-x86_64-with-glibc2.36
- Python version: 3.11.4
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: N
- Using distributed or parallel set-up in script?: N

### Who can help?

 @ArthurZucker @younesbelkada @sgugger

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

(Apologies if I have something wrong in my setup.) I'm running into an error while following along with a simple example from https://huggingface.co/tasks/text-generation:

```
user@host:~/test$ venv/bin/python -c 'from transformers import pipeline; pipe = pipeline("text-generation", model="cerebras/btlm-3b-8k-base", trust_remote_code=True); print(pipe("hello world", max_length=1, num_return_sequences=1))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/test/test/venv/lib/python3.11/site-packages/transformers/pipelines/text_generation.py", line 204, in __call__
    return super().__call__(text_inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/test/venv/lib/python3.11/site-packages/transformers/pipelines/base.py", line 1129, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/test/venv/lib/python3.11/site-packages/transformers/pipelines/base.py", line 1135, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/test/venv/lib/python3.11/site-packages/transformers/pipelines/text_generation.py", line 207, in preprocess
    inputs = self.tokenizer(
             ^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
user@host:~/test$ 
```

For readability, here is the same Python code formatted:

```python
from transformers import pipeline
pipe = pipeline("text-generation", model="cerebras/btlm-3b-8k-base", trust_remote_code=True)
print(pipe("hello world", max_length=1, num_return_sequences=1))
```

### Expected behavior

No exception, or a friendlier one

**Comment by adsr** [comment]
I just noticed the example code on https://huggingface.co/cerebras/btlm-3b-8k-base differs from https://huggingface.co/tasks/text-generation. That's probably it.
