### ISSUE TITLE
ValueError: Some specified arguments are not used by the HfArgumentParser: ['\\']

### ISSUE THREAD

**Issue by mohammedtoumi007** [huggingface/transformers#25795]
### System Info

I am doing a project question answer about chart.  For fine-tuning BART MODEL. I tried to use "run_summarization.py" for fine-tuning from transformers. But, I came across with the following error :

Traceback (most recent call last):
  File "/content/OpenCQA/baseline_models/bart/transformers/examples/pytorch/summarization/run_summarization.py", line 782, in <module>
    main()
  File "/content/OpenCQA/baseline_models/bart/transformers/examples/pytorch/summarization/run_summarization.py", line 331, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 347, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['\\']

Can anyone give some information about this error !!

### Who can help?

@Lisand

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

run BART model

### Expected behavior

run BART model

**Comment by yu-shaonian** [comment]
I came across this problem, too

**Comment by ArthurZucker** [comment]
Hey, we can't help you if you don't provide a reproducer and share the output of `transformers-cli envs`. I suspect you just have a typo in the call you are making to the script.

**Comment by mohammedtoumi007** [comment]
@ArthurZucker i update the script

**Comment by ArthurZucker** [comment]
You should try:
```bash
python -m torch.distributed.run \
    --nproc_per_node 1 transformers/examples/pytorch/summarization/run_summarization.py \
    --model_name_or_path facebook/bart-base \
    --do_train \
    --do_eval \
    --do_predict \
    --train_file /content/OpenCQA/baseline_models/bart/inputs/train.csv \
    --validation_file /content/OpenCQA/baseline_models/bart/inputs/val.csv \
    --test_file /content/OpenCQA/baseline_models/bart/inputs/test.csv \
    --text_column ${model}_text \
    --summary_column ${summary}_answer \
    --output_dir /content/OpenCQA/baseline_models/bart/outputsTest/$model \
    --overwrite_output_dir \
    --learning_rate=0.00005 \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --predict_with_generate \
    --num_beams=4 \
    --max_source_length=800 \
    --max_target_length=128 \
    --generation_max_length=128 \
    --eval_steps=500 \
    --save_steps=500 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --weight_decay=0.01 \
    --max_steps=5000 
```

**Comment by mohammedtoumi007** [comment]
@ArthurZucker yes i run this envs but it show me this error : 

Traceback (most recent call last):
  File "/content/OpenCQA/baseline_models/bart/transformers/examples/pytorch/summarization/run_summarization.py", line 782, in <module>
    main()
  File "/content/OpenCQA/baseline_models/bart/transformers/examples/pytorch/summarization/run_summarization.py", line 331, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/usr/local/lib/python3.10/dist-packages/transformers/hf_argparser.py", line 347, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['\\']

**Comment by ArthurZucker** [comment]
Sorry @mohammedtoumi007, I can't debug in your stead, your issue is that you have a typo in the command, which I cannot reproduce. Try to run the full command in one line and make sure you don't add extra `/`. 

Again, this works:
```python
python -m torch.distributed.run     --nproc_per_node 1 transformers/examples/pytorch/summarization/run_summarization.py     --model_name_or_path facebook/bart-base     --do_train     --do_eval     --do_predict     --train_file /content/OpenCQA/baseline_models/bart/inputs/train.csv     --validation_file /content/OpenCQA/baseline_models/bart/inputs/val.csv     --test_file /content/OpenCQA/baseline_models/bart/inputs/test.csv     --text_column ${model}_text     --summary_column ${summary}_answer     --output_dir /content/OpenCQA/baseline_models/bart/outputsTest/$model     --overwrite_output_dir     --learning_rate=0.00005     --per_device_train_batch_size=4     --per_device_eval_batch_size=4     --predict_with_generate     --num_beams=4     --max_source_length=800     --max_target_length=128     --generation_max_length=128     --eval_steps=500     --save_steps=500     --evaluation_strategy steps     --load_best_model_at_end     --weight_decay=0.01     --max_steps=5000
```
