### ISSUE TITLE
MT5/MT0 cannot finetune with lora in 8bit mode

### ISSUE THREAD

**Issue by Victordongy** [huggingface/transformers#25792]
### System Info

transformers version: 4.24.0
Platform: Linux-5.4.0-150-generic-x86_64-with-glibc2.29
Python version: 3.8.10
Huggingface_hub version: 0.16.4
Safetensors version: 0.3.1
Accelerate version: 0.20.3
Accelerate config: not found
PyTorch version (GPU?): 2.0.0+cu117 (True)
Tensorflow version (GPU?): 2.12.0 (False)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
Using GPU in script?: Yes
Using distributed or parallel set-up in script?: No

### Who can help?

@younesbelkada @ArthurZucker

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
model = auto_model.from_pretrained(
            "google/mt5-large"
            load_in_8bit=True,
            device_map='auto',
            **kwargs
            )

model = prepare_model_for_int8_training(model)

 config = LoraConfig(
          r=8,
          lora_alpha=8,
          target_modules=["q","v"],
          lora_dropout=0.5,
          bias="none",
          task_type=SEQ_2_SEQ_LM,
      )
model = get_peft_model(model, config)

trainer.train()
```
and I got the error as 
```
Traceback (most recent call last):
  ...
  File "/temp/models/t5.py", line 72, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/temp/dg_venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/temp/dg_venv/lib/python3.8/site-packages/peft/tuners/lora.py", line 817, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: expected scalar type Float but found Char
```

### Expected behavior

Model should be trained successfully.

**Comment by younesbelkada** [comment]
hi @Victordongy 
Thanks for the issue can you try to re-run LoRA training with the latest peft and transformers?
```bash
pip install -U transformers peft
```
