### ISSUE TITLE
Incorrect batched generation for Llama-2 with `pad_token` = `eos_token`

### ISSUE THREAD

**Issue by wjfwzzc** [huggingface/transformers#25790]
### System Info

- `transformers` version: 4.32.0
- Platform: Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.31
- Python version: 3.9.2
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): 2.12.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @gante 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python3
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


def run(
    model_name_or_path: str,
    pad_token_mode: str = "eos_token",
    dtype: torch.dtype = torch.float16,
):
    model = AutoModelForCausalLM.from_pretrained(
        model_name_or_path,
        low_cpu_mem_usage=True,
        torch_dtype=dtype,
        device_map="auto",
        use_cache=True,
        trust_remote_code=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(
        model_name_or_path,
        trust_remote_code=True,
        use_fast=False,
        legacy=False,
        padding_side="left",
    )
    if pad_token_mode == "eos_token":
        tokenizer.pad_token = tokenizer.eos_token
    elif pad_token_mode == "unk_token":
        tokenizer.pad_token = tokenizer.unk_token
    elif pad_token_mode == "new_token":
        tokenizer.add_special_tokens({"pad_token": "[PAD]"})
        model.resize_token_embeddings(len(tokenizer))
    else:
        raise NotImplementedError
    print(f"pad_token: {tokenizer.pad_token}, pad_token_id: {tokenizer.pad_token_id}")
    model.config.pad_token_id = tokenizer.pad_token_id
    model.generation_config.pad_token_id = tokenizer.pad_token_id

    # examples extracted from MMLU's abstract_algebra subject with 5-shots
    examples = [
        "The following are multiple choice questions (with answers) about abstract algebra.\n\nFind all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.\nA. 0\nB. 1\nC. 2\nD. 3\nAnswer: B\n\nStatement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: B\n\nStatement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: C\n\nStatement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: A\n\nFind the characteristic of the ring 2Z.\nA. 0\nB. 3\nC. 12\nD. 30\nAnswer: A\n\nFind the degree for the given field extension Q(sqrt(2), sqrt(3), sqrt(18)) over Q.\nA. 0\nB. 4\nC. 2\nD. 6\nAnswer:",
        "The following are multiple choice questions (with answers) about abstract algebra.\n\nFind all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.\nA. 0\nB. 1\nC. 2\nD. 3\nAnswer: B\n\nStatement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: B\n\nStatement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: C\n\nStatement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: A\n\nFind the characteristic of the ring 2Z.\nA. 0\nB. 3\nC. 12\nD. 30\nAnswer: A\n\nLet p = (1, 2, 5, 4)(2, 3) in S_5 . Find the index of <p> in S_5.\nA. 8\nB. 2\nC. 24\nD. 120\nAnswer:",
        "The following are multiple choice questions (with answers) about abstract algebra.\n\nFind all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.\nA. 0\nB. 1\nC. 2\nD. 3\nAnswer: B\n\nStatement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: B\n\nStatement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: C\n\nStatement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: A\n\nFind the characteristic of the ring 2Z.\nA. 0\nB. 3\nC. 12\nD. 30\nAnswer: A\n\nFind all zeros in the indicated finite field of the given polynomial with coefficients in that field. x^5 + 3x^3 + x^2 + 2x in Z_5\nA. 0\nB. 1\nC. 0,1\nD. 0,4\nAnswer:",
        "The following are multiple choice questions (with answers) about abstract algebra.\n\nFind all c in Z_3 such that Z_3[x]/(x^2 + c) is a field.\nA. 0\nB. 1\nC. 2\nD. 3\nAnswer: B\n\nStatement 1 | If aH is an element of a factor group, then |aH| divides |a|. Statement 2 | If H and K are subgroups of G then HK is a subgroup of G.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: B\n\nStatement 1 | Every element of a group generates a cyclic subgroup of the group. Statement 2 | The symmetric group S_10 has 10 elements.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: C\n\nStatement 1| Every function from a finite set onto itself must be one to one. Statement 2 | Every subgroup of an abelian group is abelian.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer: A\n\nFind the characteristic of the ring 2Z.\nA. 0\nB. 3\nC. 12\nD. 30\nAnswer: A\n\nStatement 1 | A factor group of a non-Abelian group is non-Abelian. Statement 2 | If K is a normal subgroup of H and H is a normal subgroup of G, then K is a normal subgroup of G.\nA. True, True\nB. False, False\nC. True, False\nD. False, True\nAnswer:",
    ]

    expected_answers = []
    for example in examples:
        inputs = tokenizer(
            example,
            return_tensors="pt",
            add_special_tokens=False,
            padding=True,
            return_token_type_ids=False,
        ).to("cuda")
        outputs = model.generate(**inputs, do_sample=False, max_new_tokens=1)
        pred = tokenizer.decode(outputs[0], skip_special_tokens=True)
        ans = pred[len(example) :]
        expected_answers.append(ans)

    inputs = tokenizer(
        examples,
        return_tensors="pt",
        add_special_tokens=False,
        padding=True,
        return_token_type_ids=False,
    ).to("cuda")
    outputs = model.generate(**inputs, do_sample=False, max_new_tokens=1)
    batched_preds = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    batched_answers = [
        pred[len(example) :] for pred, example in zip(batched_preds, examples)
    ]

    # when pad_token_mode = "eos_token", the expected_answers and batched_answers should be the same
    # however only the longest example (without padding) is the same, the rest are different
    for i, (expected_answer, batched_answer) in enumerate(
        zip(expected_answers, batched_answers)
    ):
        if expected_answer == batched_answer:
            print(f"sample {i} is the same")
        else:
            print(
                f"sample {i} is different, expected_answer: `{expected_answer}`, batched_answer: `{batched_answer}`"
            )


if __name__ == "__main__":
    model_name_or_path = "meta-llama/Llama-2-7b-hf"
    # model_name_or_path = "gpt2-xl"
    # model_name_or_path = "bigscience/bloomz-7b1-mt"
    # model_name_or_path = "facebook/opt-1.3b"
    run(model_name_or_path, "eos_token")
    run(model_name_or_path, "unk_token")
    run(model_name_or_path, "new_token")
```

### Expected behavior

I tried to batched generate with llama-2. So following the common practice, I set `pad_token` to `eos_token`. However I found all generated texts are incorrect except the longest one (without padding).
More interesting thing is if I set `pad_token` to `unk_token`, everything seems fine.
I also tried to add a new token but it leads to an error.
Other models like `gpt2-xl`, `bigscience/bloomz-7b1-mt` and `facebook/opt-1.3b` work fine in all three cases. Update: `llama` v1 seems also work fine.

**Comment by psinger** [comment]
I have personally also seen a lot of strange behavior with single row vs. larger batch in llama, so decided to dig in a bit.

It seems with batch and padding, the logits are nan. There is something funamentally wrong with the llama-2-7b-hf float16 weights.

You can solve your issue by setting `torch_dtype=torch.bfloat16` and the predictions match.

However, the logits are still slightly off between single row and multi batch, which should not be the case. They are also off when using `unk_token`.

**Comment by ArthurZucker** [comment]
If " even with bfloat the logits are off. " then why would `float16` be the main culprit? 

Anyway could you try https://github.com/huggingface/transformers/pull/25284 ? With and without padding should give the same results yes, but depending on the padding scheme (left or right) it might not always be the case.

**Comment by psinger** [comment]
The logits are off, but they are close enough that the generated token matches. With float16 you get nans.

Best you run the code yourself to see.

**Comment by wjfwzzc** [comment]
> (You seem to be using `trust_remote_code = True` not sure why you would need that here?)

Just because this reproduction code is cherry-picked from a large evaluation tool which needs to support other models. Can be removed here.

> 1. you might be using the wrong padding side,

`padding_side = left` output as follows:
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.36s/it]
pad_token: </s>, pad_token_id: 2
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
sample 0 is different, expected_answer: ` B`, batched_answer: ``
sample 1 is different, expected_answer: ` A`, batched_answer: ``
sample 2 is different, expected_answer: ` C`, batched_answer: ``
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.53s/it]
pad_token: <unk>, pad_token_id: 0
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.52s/it]
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
pad_token: [PAD], pad_token_id: 32000
sample 0 is different, expected_answer: ` B`, batched_answer: ``
sample 1 is the same
sample 2 is different, expected_answer: ` C`, batched_answer: ``
sample 3 is the same
```

`padding_side = right` output as follows:
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [03:03<00:00, 91.87s/it]
pad_token: </s>, pad_token_id: 2
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
sample 0 is different, expected_answer: ` B`, batched_answer: `
`
sample 1 is different, expected_answer: ` A`, batched_answer: `
`
sample 2 is different, expected_answer: ` C`, batched_answer: `
`
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.71s/it]
pad_token: <unk>, pad_token_id: 0
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
sample 0 is different, expected_answer: ` B`, batched_answer: `Љ`
sample 1 is different, expected_answer: ` A`, batched_answer: `Љ`
sample 2 is different, expected_answer: ` C`, batched_answer: `Љ`
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.53s/it]
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
pad_token: [PAD], pad_token_id: 32000
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
sample 0 is different, expected_answer: ` B`, batched_answer: ` is`
sample 1 is different, expected_answer: ` A`, batched_answer: ` is`
sample 2 is different, expected_answer: ` C`, batched_answer: ` is`
sample 3 is the same
```

BTW, I do believe we should get the same results for both `right` and `left` for all transformers if we have a correct `attention_mask` and `position_ids` as @psinger says., because the transformer is permutation invariant.

> 2\. You mention resizing leads to an issue, could you share the traceback?

Trackback as follows, it's interesting that the error only shows on A30, no error on A100. Maybe it's a pytorch's bug?
```python3
Traceback (most recent call last):
  File "/mnt/bn/wjfwzzc-data/code/lab/genai_llm_eval/issue_padding.py", line 99, in <module>
    run(model_name_or_path, "new_token")
  File "/mnt/bn/wjfwzzc-data/code/lab/genai_llm_eval/issue_padding.py", line 59, in run
    outputs = model.generate(**inputs, do_sample=False, max_new_tokens=1)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py", line 1596, in generate
    return self.greedy_search(
  File "/usr/local/lib/python3.9/dist-packages/transformers/generation/utils.py", line 2444, in greedy_search
    outputs = self(
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/models/llama/modeling_llama.py", line 827, in forward
    logits = self.lm_head(hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/hooks.py", line 286, in pre_forward
    set_module_tensor_to_device(
  File "/usr/local/lib/python3.9/dist-packages/accelerate/utils/modeling.py", line 281, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([32001, 4096])), this look incorrect.
```

**Comment by wjfwzzc** [comment]
> You can solve your issue by setting `torch_dtype=torch.bfloat16` and the predictions match.

It does work!
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.58s/it]
pad_token: </s>, pad_token_id: 2
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.56s/it]
pad_token: <unk>, pad_token_id: 0
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:13<00:00,  6.86s/it]
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
pad_token: [PAD], pad_token_id: 32000
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
```

**Comment by wjfwzzc** [comment]
> Anyway could you try #25284 ?

It also works! With left padding and float16.
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.57s/it]
pad_token: </s>, pad_token_id: 2
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/transformers/generation/configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.51s/it]
pad_token: <unk>, pad_token_id: 0
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.52s/it]
You are resizing the embedding layer without providing a `pad_to_multiple_of` parameter. This means that the new embeding dimension will be 32001. This might induce some performance reduction as *Tensor Cores* will not be available. For more details  about this, or help on choosing the correct value for resizing, refer to this guide: https://docs.nvidia.com/deeplearning/performance/dl-performance-matrix-multiplication/index.html#requirements-tc
pad_token: [PAD], pad_token_id: 32000
sample 0 is the same
sample 1 is the same
sample 2 is the same
sample 3 is the same
```

**Comment by ArthurZucker** [comment]
I’ll investigate 👍 but if setting the pad token to unk_token works, again I doubt it has anything to do with fp16 casting. 
Adding a token should work, and the pad index should be given to the model when using from pretrained to make sure the embedding returns zeros tensors!

**Comment by psinger** [comment]
> but if setting the pad token to unk_token works

Even though it works in this examples, as I said before, the final logits still do not match.
So probably the better check is to compare the logits, and not generated tokens.

**Comment by ArthurZucker** [comment]
Sorry both! I'm taking all the Llama issues to dive in this! Thanks for your inputs

**Comment by ArthurZucker** [comment]
Sorry for the delay, @gante just FYI!
