### ISSUE TITLE
Error:  index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by rishabh063** [huggingface/transformers#25806]
### System Info

Error:  index 0 is out of bounds for dimension 0 with size 0
Traceback (most recent call last):
    outputs = generator(raw_image, points_per_batch=64)
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/mask_generation.py", line 173, in __call__
    return super().__call__(image, *args, num_workers=num_workers, batch_size=batch_size, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1121, in __call__
    return next(
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1035, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/opt/conda/lib/python3.10/site-packages/transformers/pipelines/mask_generation.py", line 242, in _forward
    masks, iou_scores, boxes = self.image_processor.filter_masks(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/sam/image_processing_sam.py", line 670, in filter_masks
    return self._filter_masks_pt(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/sam/image_processing_sam.py", line 768, in _filter_masks_pt
    masks = _mask_to_rle_pytorch(masks)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/sam/image_processing_sam.py", line 1201, in _mask_to_rle_pytorch
    counts += [cur_idxs[0].item()] + btw_idxs.tolist() + [height * width - cur_idxs[-1]]

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

transformer== 4.33.0.dev0

generator = pipeline("mask-generation", model="facebook/sam-vit-huge", device=0)
model = generator.model

outputs = generator(raw_image, points_per_batch=64)

### Expected behavior

Not Fail

**Comment by rishabh063** [comment]
This happens when the image has nothing to mask , I.e plain image or very Faded images where there is nothing to segment . 

It should Return an empty Array and not an error
