### ISSUE TITLE
ImportError: cannot import name 'GPTQQuantizer' from partially initialized module 'optimum.gptq'

### ISSUE THREAD

**Issue by jessiewiswjc** [huggingface/transformers#26045]
### System Info

- `transformers` version: 4.33.1
- Platform: Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.17
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@SunMarc @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

code is
```
from transformers import AutoModelForCausalLM, AutoTokenizer, GPTQConfig
import torch
if torch.cuda.is_available():
    print(torch.cuda.device_count())

model_id = "/mnt/data/wangjiancheng/checkpoint-38241"

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

dataset = ["auto-gptq is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."]
gptq_config = GPTQConfig(bits=8, dataset = dataset, tokenizer=tokenizer)

quant_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=gptq_config, trust_remote_code=True).to(torch.device("cuda:1"))

```

and error is

```
8
Traceback (most recent call last):
  File "/mnt/data/wangjiancheng/auto_gptq.py", line 13, in <module>
    quant_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=gptq_config, trust_remote_code=True).to(torch.device("cuda:1"))
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2577, in from_pretrained
    from optimum.gptq import GPTQQuantizer
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/optimum/gptq/__init__.py", line 15, in <module>
    from .quantizer import GPTQQuantizer, load_quantized_model
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/optimum/gptq/quantizer.py", line 44, in <module>
    from auto_gptq.modeling._utils import autogptq_post_init
  File "/mnt/data/wangjiancheng/auto_gptq.py", line 13, in <module>
    quant_model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=gptq_config, trust_remote_code=True).to(torch.device("cuda:1"))
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2577, in from_pretrained
    from optimum.gptq import GPTQQuantizer
ImportError: cannot import name 'GPTQQuantizer' from partially initialized module 'optimum.gptq' (most likely due to a circular import) (/mnt/data/wangjiancheng/miniconda3/envs/autogptq/lib/python3.9/site-packages/optimum/gptq/__init__.py)

```

### Expected behavior

code with no error

**Comment by SunMarc** [comment]
Hi @jessiewiswjc. This happens because you named your file auto_gptq.py. Please rename it and let me know if it works.

**Comment by jessiewiswjc** [comment]
> Hi @jessiewiswjc. This happens because you named your file auto_gptq.py. Please rename it and let me know if it works.

Thanks very much and it works after renaming.
