### ISSUE TITLE
WhisperTokenizerFast omits language and task tokens

### ISSUE THREAD

**Issue by tsobolev** [huggingface/transformers#26184]
### System Info

- `transformers` version: 4.34.0.dev0
- Platform: Linux-5.15.120+-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.3
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.0+cpu (False)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.2 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

Hello.

WhisperTokenizerFast omits language and task tokens: <|ka|><|transcribe|>
Is it bug or feature? 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```

from transformers import WhisperTokenizer, AutoFeatureExtractor, WhisperTokenizerFast

model_ckpt = "openai/whisper-tiny"

tokenizer = WhisperTokenizer.from_pretrained(model_ckpt, language="ka", task="transcribe")
tokenizer_fast = WhisperTokenizerFast.from_pretrained(model_ckpt, language="ka", task="transcribe")
feature_extractor = AutoFeatureExtractor.from_pretrained(model_ckpt)

input_ids = tokenizer('ქართული სახელმწიფოებრიობისა და კულტურის მდგრადობა უშუალოდ დაკავშირებული იყო საქართველოს დედაქალაქის ბედთან.')['input_ids']
print('tokenizer_slow:',tokenizer.decode(input_ids, skip_special_tokens=False))

input_ids = tokenizer_fast('ქართული სახელმწიფოებრიობისა და კულტურის მდგრადობა უშუალოდ დაკავშირებული იყო საქართველოს დედაქალაქის ბედთან.')['input_ids']
print('tokenizer_fast:',tokenizer.decode(input_ids, skip_special_tokens=False))
```

tokenizer_slow: <|startoftranscript|><|ka|><|transcribe|><|notimestamps|>ქართული სახელმწიფოებრიობისა და კულტურის მდგრადობა უშუალოდ დაკავშირებული იყო საქართველოს დედაქალაქის ბედთან.<|endoftext|>
tokenizer_fast: <|startoftranscript|><|notimestamps|>ქართული სახელმწიფოებრიობისა და კულტურის მდგრადობა უშუალოდ დაკავშირებული იყო საქართველოს დედაქალაქის ბედთან.<|endoftext|>

### Expected behavior

tokenizer_fast: <|startoftranscript|><|ka|><|transcribe|><|notimestamps|>ქართული სახელმწიფოებრიობისა და კულტურის მდგრადობა უშუალოდ დაკავშირებული იყო საქართველოს დედაქალაქის ბედთან.<|endoftext|>

**Comment by ArthurZucker** [comment]
Hey! Thanks for reporting. You need to call the `tokenizer_fast.set_prefix_tokens()` function to make sure the changes are applied. 
A fix would be to call this function in the `__init__`, would you like to open a PR for the fix?

**Comment by ArthurZucker** [comment]
cc @sanchit-gandhi if there was a reason not to call this at init time?

**Comment by tsobolev** [comment]
When I call this function in the __init__, it causes error:
```
Traceback (most recent call last):
  File "/home/user/transformers/my-test.py", line 6, in <module>
    tokenizer_fast = WhisperTokenizerFast.from_pretrained(model_ckpt, language="ka", task="transcribe")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/transformers/src/transformers/tokenization_utils_base.py", line 1967, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/transformers/src/transformers/tokenization_utils_base.py", line 2130, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/transformers/src/transformers/models/whisper/tokenization_whisper_fast.py", line 182, in __init__
    self.set_prefix_tokens()
  File "/home/user/transformers/src/transformers/models/whisper/tokenization_whisper_fast.py", line 432, in set_prefix_tokens
    prefix_token_ids = self.prefix_tokens
                       ^^^^^^^^^^^^^^^^^^
  File "/home/user/transformers/src/transformers/models/whisper/tokenization_whisper_fast.py", line 450, in prefix_tokens
    bos_token_id = all_special_ids[-106]
                   ~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range
```
I can insert self.set_prefix_tokens() in beginning of _batch_encode_plus and  _encode_plus and it works, but this doesn't seem to be the right solution.

**Comment by ArthurZucker** [comment]
That is not what I meant. Once the tokenizer is initialized, just call `tokenizer.set_prefix_tokens()`. This should only be set once. Touching the processor on the fly is not completely recommended 😉

**Comment by tsobolev** [comment]
If I instantiate `tokenizer_fast` in my script and then call `tokenizer_fast.set_prefix_tokens()` everything works fine.

> A fix would be to call this function in the `__init__`

As i understand, the fix is to eliminating the need to extra call the function `set_prefox_tokens()` after instantiating `tokenizer_fast`?

I'm trying to figure out if it's possible to make `WhisperTokenizerFast` and `WhisperTokenizer` behave the same way,
because `WhisperTokenizer` does not require an additional `set_prefix_tokens()` call. 
This inconsistency is a bit confusing.

**Comment by ArthurZucker** [comment]
The confusion here comes from the difference between a fast and a slow tokenizer. In a fast tokenizer, the inputs is processed not using `build_inputs_with_special_tokens` but using the `processor`. Fast tokenizers are based on rust, and are supposed to be initialized once and not modified much. Adding the `set_prefox_tokens()` is the fix for this as it allows initializing with different parameters. 

The slow tokenizer uses a property that is always re_computed on the fly. This can add (probably small) overhead, but is also not very clear it seems.

**Comment by tsobolev** [comment]
Still unclear.
Is it possible to make WhisperTokenizerFast produce same output as WhisperTokenizer instansiated with same code, without extra set_prefix_tokens() (make it under the hood), or it feature and i should close this issue? 
Anyway, with extra call set_prefix_tokens() after instantiating tokenizer everything works fine.

**Comment by sanchit-gandhi** [comment]
I didn't add the Whisper fast tokenizer, but for equivalent behaviour with the slow one, the prefix tokens should be set at  `__init__`. It looks like they're only registered in the processor when we call `set_prefix_tokens`: https://github.com/huggingface/transformers/blob/e4e55af79c9b3dfd15cc2224f8f5b80680d83f03/src/transformers/models/whisper/tokenization_whisper_fast.py#L435

I guess it's not possible to do this in the `__init__` because we need access to `all_special_ids` (property) and the encoding method `convert_ids_to_tokens`. Unless you know of a workaround @ArthurZucker like a post init?

**Comment by ArthurZucker** [comment]
We will be able to do this once #23909 is merged 😉 I'll take care of it. 
@tsobolev sorry for being unclear: we will fix this to have the same behaviour at init time. You can in the mean time use the fix I proposed.

**Comment by ArthurZucker** [comment]
I think this was fixed by updating the tokenizer so closing 😉

**Comment by swigls** [comment]
Hello! Seems like this issue remains in `transformers==4.52.4`.

`WhisperTokenizer.encode()` and `WhisperTokenizerFast.encode()` returns different prefix tokens, unless `WhisperTokenizerFast.set_prefix_tokens()` is called explicitly a prior.
```bash
>>> from transformers import WhisperTokenizer, WhisperTokenizerFast
tok = WhisperTokenizer.from_pretrained("openai/whisper-large-v3", task="transcribe", language="en")
>>> tok("asdf")
{'input_ids': [50258, 50259, 50360, 50364, 296, 45953, 50257], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}
>>> tokfast = WhisperTokenizerFast.from_pretrained("openai/whisper-large-v3", task="transcribe", language="en")
>>> tokfast("asdf")
{'input_ids': [50258, 50364, 296, 45953, 50257], 'attention_mask': [1, 1, 1, 1, 1]}
>>> tokfast.set_prefix_tokens()
>>> tokfast("asdf")
{'input_ids': [50258, 50259, 50360, 50364, 296, 45953, 50257], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}
```
