### ISSUE TITLE
param `document-question-answering` raises `KeyError` in pipeline

### ISSUE THREAD

**Issue by regmibijay** [huggingface/transformers#26671]
### System Info

Running following combination on a windows Machine with properly set up WSL + Cuda environment. 

Machine: 
- CPU: i7-9700K + 16GB DDR4 RAM
- GPU: RTX 3060 TI 8GB GDDR6

Libraries: Python 3.10
```
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-io-gcs-filesystem==0.31.0
transformers==4.34.0
```
Currently with 
```python
pipeline("document-question-answering")
```
I see 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 797, in pipeline
    model, default_revision = get_default_model_and_revision(targeted_task, framework, task_options)
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 405, in get_default_model_and_revision
    return default_models[framework]
KeyError: 'tf'
```
With [recommended](https://huggingface.co/tasks/document-question-answering) way I see 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 834, in pipeline
    framework, model = infer_framework_load_model(
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 282, in infer_framework_load_model
    raise ValueError(
ValueError: Could not load model naver-clova-ix/donut-base-finetuned-docvqa with any of the following classes: (<class 'transformers.models.vision_encoder_decoder.modeling_tf_vision_encoder_decoder.TFVisionEncoderDecoderModel'>,). See the original errors:

while loading with TFVisionEncoderDecoderModel, an error is thrown:
Traceback (most recent call last):
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/models/vision_encoder_decoder/modeling_tf_vision_encoder_decoder.py", line 336, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/home/bijayregmi/.local/lib/python3.10/site-packages/transformers/modeling_tf_utils.py", line 2823, in from_pretrained
    raise EnvironmentError(
OSError: naver-clova-ix/donut-base-finetuned-docvqa does not appear to have a file named tf_model.h5 but there is a file for PyTorch weights. Use `from_pt=True` to load this model from those weights.
```

I think this might be an unintended bug and core issue is not isolateable with minimal research for my end user perspective. 

Please feel free to comment on this if you require further information.

### Who can help?

@Narsil 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline

pipeline("document-question-answering")
```

### Expected behavior

Expected behaviour would be: 

- library searches for predefined, pretrained model for given pipeline and downloads it from HF
- Library initializes weights and other params
- Library is ready to accept further instructions

**Comment by regmibijay** [comment]
Looks like this has been mitigated with current version.
