### ISSUE TITLE
Using with vLLM and runpod gives error stating Repo id must be in the form 'repo_name'...

### ISSUE THREAD

**Issue by rafa-9** [huggingface/transformers#26720]
### Describe the bug

I have tried [multiple templates](https://github.com/runpod-workers/worker-vllm) that use vLLM and deploy them to Runpod but the deployment is prevented by this bug where it checks for the repo_id.
For faster deployments Runpod suggests to download the model to an external storage which is usually mounted on `/runpod-volume/`. Thus any model that is downloaded is stored in the location `/runpod-volume/namespace/repo_name`. 
The [checks in the validator](https://github.com/huggingface/huggingface_hub/blob/5d2d297084b230d7725b9ccafe6eb9a7f7c9a40e/src/huggingface_hub/utils/_validators.py#L123) prevent the models from loading. 
How can we bypass this issue? Thanks!

### Reproduction

Deploy any model on Runpod using vLLM template 
(Template examples: 
1. https://github.com/winglian/worker-vllm-new
2. https://github.com/anthonypoe/worker-vllm

### Logs

```shell
2023-10-08T23:48:58.162625747Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
2023-10-08T23:48:58.162627886Z     resolved_config_file = cached_file(
2023-10-08T23:48:58.162629374Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
2023-10-08T23:48:58.162730559Z     resolved_file = hf_hub_download(
2023-10-08T23:48:58.162745609Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
2023-10-08T23:48:58.162754559Z     validate_repo_id(arg_value)
2023-10-08T23:48:58.162757898Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
2023-10-08T23:48:58.162814363Z     raise HFValidationError(
2023-10-08T23:48:58.162818078Z huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/runpod-volume/Mistralic-7B-1-AWQ'. Use `repo_type` argument if needed.
2023-10-08T23:48:58.162819633Z 
2023-10-08T23:48:58.162821011Z During handling of the above exception, another exception occurred:
2023-10-08T23:48:58.162822300Z 
2023-10-08T23:48:58.162823725Z Traceback (most recent call last):
2023-10-08T23:48:58.162825121Z   File "/root/handler.py", line 45, in <module>
2023-10-08T23:48:58.162882887Z     llm = AsyncLLMEngine.from_engine_args(engine_args)
2023-10-08T23:48:58.162885347Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 480, in from_engine_args
2023-10-08T23:48:58.162974437Z     engine_configs = engine_args.create_engine_configs()
2023-10-08T23:48:58.162976606Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 174, in create_engine_configs
2023-10-08T23:48:58.163023514Z     model_config = ModelConfig(self.model, self.tokenizer,
2023-10-08T23:48:58.163025692Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/vllm/config.py", line 74, in __init__
2023-10-08T23:48:58.163081539Z     self.hf_config = get_config(model, trust_remote_code, revision)
2023-10-08T23:48:58.163083550Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/vllm/transformers_utils/config.py", line 27, in get_config
2023-10-08T23:48:58.163115027Z     return MistralConfig.from_pretrained(model, revision=revision)
2023-10-08T23:48:58.163116921Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/configuration_utils.py", line 591, in from_pretrained
2023-10-08T23:48:58.163244365Z     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-10-08T23:48:58.163250169Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
2023-10-08T23:48:58.163338403Z     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-10-08T23:48:58.163341533Z   File "/root/miniconda3/envs/pytorch/lib/python3.10/site-packages/transformers/configuration_utils.py", line 696, in _get_config_dict
2023-10-08T23:48:58.163438067Z     raise EnvironmentError(
2023-10-08T23:48:58.163443403Z OSError: Can't load the configuration of '/runpod-volume/Mistralic-7B-1-AWQ'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '/runpod-volume/Mistralic-7B-1-AWQ' is the correct path to a directory containing a config.json file
```

### System info

```shell
n/a
```

**Comment by ArthurZucker** [comment]
Agreed 😉 will open a PR
