### ISSUE TITLE
Error in loading model `TheBloke/Llama-2-7B-GGML` in google colab 

### ISSUE THREAD

**Issue by rajveer43** [huggingface/transformers#26727]
### System Info

OS: Windows 10
platform: google colab 

code 
```python
# Load model directly
from transformers import AutoModel
model = AutoModel.from_pretrained("TheBloke/Llama-2-7B-GGML")
```
 error
```
Downloading (…)lve/main/config.json: 100%
29.0/29.0 [00:00<00:00, 869B/s]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-1-ab811f62978d>](https://localhost:8080/#) in <cell line: 3>()
      1 # Load model directly
      2 from transformers import AutoModel
----> 3 model = AutoModel.from_pretrained("TheBloke/Llama-2-7B-GGML")

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   2968                             )
   2969                         else:
-> 2970                             raise EnvironmentError(
   2971                                 f"{pretrained_model_name_or_path} does not appear to have a file named"
   2972                                 f" {_add_variant(WEIGHTS_NAME, variant)}, {TF2_WEIGHTS_NAME}, {TF_WEIGHTS_NAME} or"

OSError: TheBloke/Llama-2-7B-GGML does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```
2. trial

```python
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="TheBloke/Llama-2-7B-GGML")
```
error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-2-ca57a68ffa3e>](https://localhost:8080/#) in <cell line: 4>()
      2 from transformers import pipeline
      3 
----> 4 pipe = pipeline("text-generation", model="TheBloke/Llama-2-7B-GGML")

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py](https://localhost:8080/#) in infer_framework_load_model(model, config, model_classes, task, framework, **model_kwargs)
    280             for class_name, trace in all_traceback.items():
    281                 error += f"while loading with {class_name}, an error is thrown:\n{trace}\n"
--> 282             raise ValueError(
    283                 f"Could not load model {model} with any of the following classes: {class_tuple}. See the original errors:\n\n{error}\n"
    284             )

ValueError: Could not load model TheBloke/Llama-2-7B-GGML with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForCausalLM'>). See the original errors:

while loading with AutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 2970, in from_pretrained
    raise EnvironmentError(
OSError: TheBloke/Llama-2-7B-GGML does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.

while loading with TFAutoModelForCausalLM, an error is thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 269, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 568, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.llama.configuration_llama.LlamaConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
Model type should be one of BertConfig, CamembertConfig, CTRLConfig, GPT2Config, GPT2Config, GPTJConfig, OpenAIGPTConfig, OPTConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoFormerConfig, TransfoXLConfig, XGLMConfig, XLMConfig, XLMRobertaConfig, XLNetConfig.
```

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

trying to use it for implementing ToT framework

### Expected behavior

Model loaded

**Comment by ArthurZucker** [comment]
Hey! Could you share the output of `transformers-cli env`? Would help to know which version of transformers you are runnign!

**Comment by ArthurZucker** [comment]
cc @younesbelkada I can reproduce this, might be a GPTQ command we are missing no?

**Comment by rajveer43** [comment]
Sure
