### ISSUE TITLE
PreTrainedTokenizerFast v4.34.1 fails on `self._tokenizer.get_added_tokens_decoder()`

### ISSUE THREAD

**Issue by programjames** [huggingface/transformers#26991]
### System Info

System info:
```
- Platform: Linux-REDACTED
- Python version: 3.11.REDACTED
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```
Note: No GPU.

Here's the stacktrace.
```
Traceback (most recent call last):
  File "/home/james/Documents/ml/rwkv-steering/rwkv_model/tokenizer.py", line 5, in <module>
    MyTokenizer = PreTrainedTokenizerFast(tokenizer_file=os.path.join(my_dir, "rwkv-3b", "20B_tokenizer.json"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/miniconda3/envs/rwkv-steering/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 167, in __init__
    encoder = list(self.added_tokens_encoder.keys()) + [str(token) for token in tokens_to_add]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/miniconda3/envs/rwkv-steering/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 226, in added_tokens_encoder
    return {k.content: v for v, k in sorted(self.added_tokens_decoder.items(), key=lambda item: item[0])}
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/miniconda3/envs/rwkv-steering/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 236, in added_tokens_decoder
    return self._tokenizer.get_added_tokens_decoder()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tokenizers.Tokenizer' object has no attribute 'get_added_tokens_decoder'
```
Dropping down to v4.34.0 succeeded, so this is in the latest version. Also, I likely won't be replying to comments.

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just this line of code:
```python3
from transformers import PreTrainedTokenizerFast
PreTrainedTokenizerFast(tokenizer_file="rwkv-3b/20B_tokenizer.json"))
```

### Expected behavior

It shouldn't throw an error.

**Comment by ArthurZucker** [comment]
Hey! Could you share the tokenizer file? I cannot reproduce this one my side otherwise.
Here is what I used:
```python 
>>> !wget https://huggingface.co/RWKV/rwkv-4-3b-pile/raw/main/tokenizer.json
>>> PreTrainedTokenizerFast(tokenizer_file='tokenizer.json')
```

**Comment by programjames** [comment]
I'm using [https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4/20B_tokenizer.json](https://github.com/BlinkDL/RWKV-LM/blob/main/RWKV-v4/20B_tokenizer.json).

**Comment by ArthurZucker** [comment]
Still can reproduce this as it's working fine for me. Make sure you have `tokenizers==0.14.1` :
```python 
>>> !wget https://raw.githubusercontent.com/BlinkDL/RWKV-LM/main/RWKV-v4/20B_tokenizer.json
>>> from transformers import PreTrainedTokenizerFast
>>> tokenizer = PreTrainedTokenizerFast(tokenizer_file = "tokenizer.json")
>>> tokenizer
PreTrainedTokenizerFast(name_or_path='', vocab_size=50254, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("<|padding|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50254: AddedToken("                        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50255: AddedToken("                       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50256: AddedToken("                      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50257: AddedToken("                     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50258: AddedToken("                    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50259: AddedToken("                   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50260: AddedToken("                  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50261: AddedToken("                 ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50262: AddedToken("                ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50263: AddedToken("               ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50264: AddedToken("              ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50265: AddedToken("             ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50266: AddedToken("            ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50267: AddedToken("           ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50268: AddedToken("          ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50269: AddedToken("         ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50270: AddedToken("        ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50271: AddedToken("       ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50272: AddedToken("      ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50273: AddedToken("     ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50274: AddedToken("    ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50275: AddedToken("   ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
	50276: AddedToken("  ", rstrip=False, lstrip=False, single_word=False, normalized=True, special=False),
}
```

**Comment by shreyasgm** [comment]
I'm getting the same error, and am also able to reproduce the error from the example provided by OP. I have `tokenizers==0.14.1` and `transformers==4.35.0`

**Comment by ArthurZucker** [comment]
@shreyasgm are you using the same checkpoints? 
That's very strange I ran this last month, re-ran it today and I do not have an issue. Can you make sure your intepreter has the correct tokenizers and transformers version by priting it and provide a reproducible snippet / link to a colab?
