### ISSUE TITLE
ImportError using Llama 2 with BetterTransformer

### ISSUE THREAD

**Issue by jpgard** [huggingface/transformers#27030]
### System Info

I'm attempting to fine-tune a Llama2 model. My training loop works fine without BetterTransformers, but when I attempt to import the module it looks like there is an ImportError: `ImportError: cannot import name '_expand_mask' from 'transformers.models.llama.modeling_llama' `. 

I already installed Transformers from git as described in [this issue](https://github.com/huggingface/transformers/issues/24514).

Version info:
* `transformers @ git+https://github.com/huggingface/transformers@32f799db0d625ec5cf82624ff2604c5a891ebf61`
* `optimum==1.13.2`
* `Python 3.8.16`

Full stack trace is below. Any suggestions? Thanks!

```
Traceback (most recent call last):
  File "scripts/train.py", line 235, in <module>
    main(model_arguments=model_args,
  File "scripts/train.py", line 81, in main
    from optimum.bettertransformer import BetterTransformer
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/__init__.py", line 14, in <module>
    from .models import BetterTransformerManager
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/__init__.py", line 17, in <module>
    from .decoder_models import (
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/decoder_models.py", line 53, in <module>
    from .attention import (
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/attention.py", line 24, in <module>
    from transformers.models.llama.modeling_llama import _expand_mask as _llama_expand_mask
ImportError: cannot import name '_expand_mask' from 'transformers.models.llama.modeling_llama' (/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py)
Traceback (most recent call last):
  File "scripts/train.py", line 235, in <module>
    main(model_arguments=model_args,
  File "scripts/train.py", line 81, in main
    from optimum.bettertransformer import BetterTransformer
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/__init__.py", line 14, in <module>
    from .models import BetterTransformerManager
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/__init__.py", line 17, in <module>
    from .decoder_models import (
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/decoder_models.py", line 53, in <module>
    from .attention import (
  File "/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/optimum/bettertransformer/models/attention.py", line 24, in <module>
    from transformers.models.llama.modeling_llama import _expand_mask as _llama_expand_mask
ImportError: cannot import name '_expand_mask' from 'transformers.models.llama.modeling_llama' (/path/to/miniconda3/envs/myenv/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py)
```

This is probably a question for @ArthurZucker based on his answer to the post linked above!

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Installing the versions above and importing BetterTransformers should reproduce the issue but I haven't tried it.

### Expected behavior

I expect to import BetterTransformer without errors.

**Comment by ArthurZucker** [comment]
cc @fxmarty this function is private and was removed in #26792! 
Let's transfer this to optimum library
