### ISSUE TITLE
Unable to uninstall transformers package 

### ISSUE THREAD

**Issue by Ahmed-Roushdy** [huggingface/transformers#27297]
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `adapter-transformers` version: 3.2.1
- Platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Huggingface_hub version: 0.12.1
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

 @ArthurZucke

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
 pip uninstall transformers
Uninstalling transformers-4.26.1:
  Would remove:
    /opt/miniconda3/bin/transformers-cli
    /opt/miniconda3/lib/python3.8/site-packages/transformers-4.26.1.dist-info/*
    /opt/miniconda3/lib/python3.8/site-packages/transformers/*
Proceed (Y/n)? Y
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [Errno 1] Operation not permitted: '/opt/miniconda3/bin/transformers-cli' -> '/tmp/pip-uninstall-hvzzdqd1/transformers-cli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 680, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 381, in remove
    moved.stash(path)
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 272, in stash
    renames(path, new_path)
  File "/opt/miniconda3/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 313, in renames
    shutil.move(old, new)
  File "/opt/miniconda3/lib/python3.8/shutil.py", line 812, in move
    os.unlink(src)
PermissionError: [Errno 1] Operation not permitted: '/opt/miniconda3/bin/transformers-cli' 
```

### Expected behavior

to successfully uninstall the package

**Comment by amyeroberts** [comment]
Hi @Ahmed-Roushdy, thanks for opening an issue. 

From the error, it looks like this isn't a transformers library but due to not having write access for running pip in the environment. As such, this isn't something we're able to help with. If you installed `transformers` using `sudo`, you should try uninstalling with `sudo` too.
