### ISSUE TITLE
ERROR in run_hp_search_optuna when trying to use multi-GPU

### ISSUE THREAD

**Issue by sstoia** [huggingface/transformers#27487]
### System Info

- transformers version: 4.28.1
- Platform: Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.16
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 1.13.1 (False)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The problem appears when using `run_hp_search_optuna` method from transformers/integrations.py . This method is called when trying to perform an hyperparameter search with the `Trainer.hyperparameter_search` method:

```python
best_trial = trainer.hyperparameter_search(
     direction='maximize',
     backend='optuna',
     hp_space=optuna_hp_space,
     n_trials=10,
)
```

The error obtained is the next one:

`Traceback (most recent call last):
  File "/mnt/beegfs/sstoia/proyectos/LLM_finetuning_stratified_multiclass_optuna.py", line 266, in <module>
    best_trial = trainer.hyperparameter_search(
  File "/mnt/beegfs/sstoia/.conda/envs/env/lib/python3.9/site-packages/transformers/trainer.py", line 2592, in hyperparameter_search
    best_run = backend_dict[backend](self, n_trials, direction, **kwargs)
  File "/mnt/beegfs/sstoia/.conda/envs/env/lib/python3.9/site-packages/transformers/integrations.py", line 218, in run_hp_search_optuna
    args = pickle.loads(bytes(args_main_rank))
_pickle.UnpicklingError: pickle data was truncated`

### Expected behavior

It should work, as the same function without multi-GPU works fine. I guess the problem comes from a parallelization error, as both GPUs may write on the same file.

**Comment by amyeroberts** [comment]
cc @muellerzr @pacman100

**Comment by linhdvu14** [comment]
I'm running into the same issue. Any updates on this please?

**Comment by amyeroberts** [comment]
Gentle ping @muellerzr @pacman100

**Comment by amyeroberts** [comment]
Another ping @muellerzr @pacman100

**Comment by NishchalPrasad** [comment]
Running into the same issue. Using the latest version of transformers (4.40.1) and python: 3.11

**Comment by tomaarsen** [comment]
Having the same issue with my Trainer subclass when doing HPO with DDP and optuna.

**Comment by svduplessis** [comment]
Same issue here. Also trying to run hyperparameter search with DDP (accelerate launch) using Trainer and Optuna as the backend. 

The following error is returned:
```
[rank2]: Traceback (most recent call last):
[rank2]:   File "/scratch-small-local/303700.hpc1.hpc/run_hpo_optuna.py", line 1054, in <module>
[rank2]:     main()
[rank2]:   File "/scratch-small-local/303700.hpc1.hpc/run_hpo_optuna.py", line 956, in main
[rank2]:     best_trial = trainer.hyperparameter_search(
[rank2]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/trainer.py", line 3206, in hyperparameter_search
[rank2]:     best_run = backend_obj.run(self, n_trials, direction, **kwargs)
[rank2]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/hyperparameter_search.py", line 72, in run
[rank2]:     return run_hp_search_optuna(trainer, n_trials, direction, **kwargs)
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 237, in run_hp_search_optuna
[rank2]:     args = pickle.loads(bytes(args_main_rank))
[rank2]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: _pickle.UnpicklingError: pickle data was truncated
[rank1]: Traceback (most recent call last):
[rank1]:   File "/scratch-small-local/303700.hpc1.hpc/run_hpo_optuna.py", line 1054, in <module>
[rank1]:     main()
[rank1]:   File "/scratch-small-local/303700.hpc1.hpc/run_hpo_optuna.py", line 956, in main
[rank1]:     best_trial = trainer.hyperparameter_search(
[rank1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/trainer.py", line 3206, in hyperparameter_search
[rank1]:     best_run = backend_obj.run(self, n_trials, direction, **kwargs)
[rank1]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/hyperparameter_search.py", line 72, in run
[rank1]:     return run_hp_search_optuna(trainer, n_trials, direction, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/2x22/mlm/miniconda/envs/thesis/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 237, in run_hp_search_optuna
[rank1]:     args = pickle.loads(bytes(args_main_rank))
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: _pickle.UnpicklingError: pickle data was truncated
```

**Comment by amyeroberts** [comment]
Another ping @muellerzr @SunMarc

**Comment by SunMarc** [comment]
Hey @sstoia and @tomaarsen and everyone who has this issue ! I was able to reproduce the error and fix with the PR above! Let me know if this works on your side !

**Comment by aakash0017** [comment]
Is the library updated? I'm still having the same issue

**Comment by SunMarc** [comment]
Please install the latest version of transformers that was release today and let us know if this is fixed !

**Comment by aakash0017** [comment]
Thanks for the update.

The loading of the model works now, but I get this error as soon as the training starts. 

`[rank6]: Traceback (most recent call last):
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/llama-finetuning/training/fsdp_custom_optuna.py", line 230, in <module>
[rank6]:     best_trials = trainer.hyperparameter_search(
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/trainer.py", line 3466, in hyperparameter_search
[rank6]:     best_run = backend_obj.run(self, n_trials, direction, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/hyperparameter_search.py", line 72, in run
[rank6]:     return run_hp_search_optuna(trainer, n_trials, direction, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/integrations/integration_utils.py", line 279, in run_hp_search_optuna
[rank6]:     trainer.train(resume_from_checkpoint=None)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 434, in train
[rank6]:     output = super().train(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
[rank6]:     return inner_training_loop(
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
[rank6]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/trainer.py", line 3606, in training_step
[rank6]:     self.accelerator.backward(loss, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/accelerate/accelerator.py", line 2242, in backward
[rank6]:     self.scaler.scale(loss).backward(**kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank6]:     torch.autograd.backward(
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank6]:     _engine_run_backward(
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank6]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1125, in unpack_hook
[rank6]:     frame.recompute_fn(*args)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1519, in recompute_fn
[rank6]:     fn(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 676, in forward
[rank6]:     hidden_states, self_attn_weights, present_key_value = self.self_attn(
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/home/ubuntu/cluster-finetune-cluster/newenv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 602, in forward
[rank6]:     attn_output = torch.nn.functional.scaled_dot_product_attention(
[rank6]: RuntimeError: The expanded size of the tensor (3596) must match the existing size (1798) at non-singleton dimension 3.  Target sizes: [4, 32, 1798, 3596].  Tensor sizes: [4, 1, 1798, 1798]`
