### ISSUE TITLE
Needed disk space of RAG model

### ISSUE THREAD

**Issue by wangjinghao123** [huggingface/transformers#27504]
### System Info

Hi, I'm trying to finetune RAG model. I have downloaded the wiki_dpr dataset in advance, but during the finetuning the following occured.

Loading index from wiki_dpr with index name exact
WARNING:datasets.builder:Using custom data configuration psgs_w100.nq.exact-f44336eb78506dd9
Traceback (most recent call last):
  File "transformers/examples/research_projects/rag/finetune_rag.py", line 649, in <module>
    main(args)
  File "transformers/examples/research_projects/rag/finetune_rag.py", line 586, in main
    model: GenerativeQAModule = GenerativeQAModule(args)
  File "transformers/examples/research_projects/rag/finetune_rag.py", line 195, in __init__
    self.model.retriever.init_retrieval(self.distributed_port)
  File "/home/lr/jhwang/wiki_auto_split/transformers/examples/research_projects/rag/distributed_pytorch_retriever.py", line 71, in init_retrieval
    self.index.init_index()
  File "/home/lr/jhwang/.local/lib/python3.6/site-packages/transformers/models/rag/retrieval_rag.py", line 284, in init_index
    dummy=self.use_dummy_dataset,
  File "/home/lr/jhwang/.local/lib/python3.6/site-packages/datasets/load.py", line 1751, in load_dataset
    use_auth_token=use_auth_token,
  File "/home/lr/jhwang/.local/lib/python3.6/site-packages/datasets/builder.py", line 651, in download_and_prepare
    f"Not enough disk space. Needed: {size_str(self.info.size_in_bytes or 0)} (download: {size_str(self.info.download_size or 0)}, generated: {size_str(self.info.dataset_size or 0)}, post-processed: {size_str(self.info.post_processing_size or 0)})"
OSError: Not enough disk space. Needed: 174.51 GiB (download: 66.09 GiB, generated: 73.03 GiB, post-processed: 35.39 GiB)

Is this normal? How many GBs does the RAG model need in total? Also, is there a way to change the path so that I can download the 174.51GB data to another place? Thanks a lot!

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

CUDA_VISIBLE_DEVICES="0" python3 transformers/examples/research_projects/rag/finetune_rag.py \
    --data_dir wiki_auto \
    --output_dir wiki_auto_rag \
    --model_name_or_path facebook/rag-sequence-base \
    --model_type rag_sequence \
    --fp16 \
    --gpus 1\

### Expected behavior

finetune process

**Comment by amyeroberts** [comment]
Hi @wangjinghao123, thanks for raising an issue! 

This is a question best placed in our [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.
