### ISSUE TITLE
Model download: tf-xlm-roberta-large "tf_model.h5" file missing 

### ISSUE THREAD

**Issue by paradc2** [huggingface/transformers#2769]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): tf-xlm-roberta-large

The "tf_model.h5" file for tf-xlm-roberta-large appears to be missing as the following url from model hub is returning "NoSuchKey" errors: https://s3.amazonaws.com/models.huggingface.co/bert/jplu/tf-xlm-roberta-large/tf_model.h5

If intentional, is it being reupload soon?

**Comment by RichJackson** [comment]
same for roberta-base and roberta-large

**Comment by julien-c** [comment]
cc @jplu :)

**Comment by julien-c** [comment]
@jplu Renamed the file using `aws s3 mv s3://models.huggingface.co/bert/jplu/tf-xlm-roberta-large/xlm-roberta-large-tf_model.h5 s3://models.huggingface.co/bert/jplu/tf-xlm-roberta-large/tf_model.h5`

Does it work now @paradc2 ?

@RichJackson Which exact models are you taking about?

**Comment by jplu** [comment]
humm this is weird I was sure to have properly named the models... This is certainly my bad then. I'm really sorry guys!

Here what I have when I `ls` my repo:
```
(transformers) ┌─[jplu@robinson] - [~/transformers] - [ven. févr. 07, 16:05]
└─[$] <git:(fix-tf-distil*)> ./transformers-cli s3 ls   
Filename                             LastModified             ETag                                   Size       
------------------------------------ ------------------------ -------------------------------------- ---------- 
tf-camembert-base/config.json        2020-01-31T23:00:26.000Z "da462af1da162d7145bf47f066533574"            596 
tf-camembert-base/tf_model.h5        2020-01-30T12:25:25.000Z "fbce3cf6602dbb56daf6ea2b9642eefc"      545172724 
tf-flaubert-base-cased/config.json   2020-01-31T23:00:26.000Z "b1bb00ff27331cee714b82d659b18d0e"            942 
tf-flaubert-base-cased/tf_model.h5   2020-01-31T16:53:31.000Z "1418889252dda2462c2e8b8b0b74010d"      764558620 
tf-flaubert-base-uncased/config.json 2020-01-31T23:00:26.000Z "b88f774bef4f4ab20748b728441fd03e"            942 
tf-flaubert-base-uncased/tf_model.h5 2020-01-31T16:54:12.000Z "db954070da0d1435e07ae67713de63c3"      757260944 
tf-flaubert-large-cased/config.json  2020-01-31T23:00:26.000Z "e0a5f3081bbb858a0096daa18a55157d"           1030 
tf-flaubert-large-cased/tf_model.h5  2020-01-31T16:55:28.000Z "10b53d7cec21cc2d5a28a8d6a225e0ad"     1775057844 
tf-flaubert-small-cased/config.json  2020-01-31T23:00:27.000Z "b4fe61d6ed58fbbc00d3f5aca3a23829"           1007 
tf-flaubert-small-cased/tf_model.h5  2020-01-31T16:54:58.000Z "a8c6e15d7434dca7d49f1666b4933f2a"      358615548 
tf-xlm-roberta-base/config.json      2020-01-31T23:00:27.000Z "3bb4d32c4818bf4ce53021f6ce7839df"            737 
tf-xlm-roberta-base/tf_model.h5      2020-01-30T10:30:20.000Z "248f95f776e119c46132860f11085c2d"     1885418496 
tf-xlm-roberta-large/config.json     2020-01-31T23:00:27.000Z "d6f295d68b0414208f5fc1cbc2f0dce6"            738 
tf-xlm-roberta-large/tf_model.h5     2020-02-07T14:51:57.000Z "44602b7afc746bc6971e793f4534dcf0-390" 3271420488
```

**Comment by RichJackson** [comment]
here's the exception:


```
02/07/2020 15:03:17 - INFO - transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-vocab.json from cache at /home/kxfv271/.cache/torch/transformers/d0c5776499adc1ded22493fae699da0971c1ee4c2587111707a4d177d20257a2.ef00af9e673c7160b4d41cfda1f48c5f4cba57d5142754525572a846a1ab1b9b
02/07/2020 15:03:17 - INFO - transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base-merges.txt from cache at /home/kxfv271/.cache/torch/transformers/b35e7cd126cd4229a746b5d5c29a749e8e84438b14bcdb575950584fe33207e8.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
02/07/2020 15:03:18 - INFO - transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base/pytorch_model.bin from cache at None
Traceback (most recent call last):
  File "<masked>lib/python3.7/site-packages/torch/serialization.py", line 289, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<masked>/lib/python3.7/site-packages/transformers/modeling_utils.py", line 467, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "<masked/>lib/python3.7/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "<masked>/lib/python3.7/site-packages/torch/serialization.py", line 217, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "<masked>/lib/python3.7/site-packages/torch/serialization.py", line 202, in __init__
    _check_seekable(buffer)
  File "<masked>/lib/python3.7/site-packages/torch/serialization.py", line 292, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "<masked>/lib/python3.7/site-packages/torch/serialization.py", line 285, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/data/home/kxfv271/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/data/home/kxfv271/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/datadrive/pycharm_project_817/aznlp_tools/rbert_paper/rbert_ablations.py", line 1182, in <module>
    main()
  File "/datadrive/pycharm_project_817/aznlp_tools/rbert_paper/rbert_ablations.py", line 1108, in main
    cache_dir=args.cache_dir if args.cache_dir else None
  File "<masked>/lib/python3.7/site-packages/transformers/modeling_utils.py", line 470, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```

looks like the vocab and config files are still available?

**Comment by LysandreJik** [comment]
@RichJackson, this is a different error to @paradc2. Could you show us which command raised this error?

**Comment by RichJackson** [comment]
I'm running a (modified) version of the run_glue.py example. I think the problem is on [this line](https://github.com/huggingface/transformers/blob/73368963b200f2d70d2267bd49a3fa794850b3ff/examples/run_glue.py#L634). If you don't provide a --cache-dir argument, this evaluates to None? Hence the above log line:

```
02/07/2020 15:03:18 - INFO - transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base/pytorch_model.bin from cache at None
```

i.e. model links seem to be ok

**Comment by julien-c** [comment]
do you mind opening a new issue for this?

**Comment by paradc2** [comment]
@julien-c yes, the tf-xlm-roberta-large download works as expected now. Thanks!

**Comment by MoutafatinKhalil** [comment]
> 
> 
> I'm running a (modified) version of the run_glue.py example. I think the problem is on [this line](https://github.com/huggingface/transformers/blob/73368963b200f2d70d2267bd49a3fa794850b3ff/examples/run_glue.py#L634). If you don't provide a --cache-dir argument, this evaluates to None? Hence the above log line:
> 
> ```
> 02/07/2020 15:03:18 - INFO - transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-base/pytorch_model.bin from cache at None
> ```
> 
> i.e. model links seem to be ok

Hi Sir, i have the same problem with Camembert while fine-tuning on FQUAD. any solutions Sir ?
