### ISSUE TITLE
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

### ISSUE THREAD

**Issue by mclassen** [huggingface/transformers#27699]
### System Info

I should have the latest version.
When executing a query against a GGUF model, I get this error:

Traceback (most recent call last):
  File "/workspace/text-generation-webui/modules/callbacks.py", line 57, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/workspace/text-generation-webui/modules/llamacpp_model.py", line 141, in generate
    completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Create a standard TheBloke runpod template for TextGen WebUI
2. download TheBloke/Phind-CodeLlama-34B-v2-GGUF, doesn't really matter which quantized file specifically
3. any query should trigger the TypeError
4. the output is empty

### Expected behavior

1. There should be no error.
2. The output should show the result of the query.

**Comment by inestyne** [comment]
Me to, just getting started will follow

**Comment by honato** [comment]
Run the set up again. when you updated there was a new requirements.txt. I had the same issue and running the setup again fixed it right up.

**Comment by makingitup** [comment]
I've also been getting this error for several days now. Tried resetting the pod, creating new pods with different gpus or different models. Always getting the same error.

**Comment by ArthurZucker** [comment]
Hey! 🤗 seems like the issue is with `llama_cpp` rather than transformers 😅

**Comment by makingitup** [comment]
The issue is the template installing the wrong requirement.

https://github.com/TheBlokeAI/dockerLLM/issues/12

**Comment by vmajor** [comment]
Still broken. Cannot use GGUF with ooba.

**Comment by walesdata** [comment]
I encountered this error.

1. Stop the server
2. Run update_linux.sh
3. Start the server

Fixed.
