### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by jerin-scalers-ai** [huggingface/transformers#27769]
### System Info

Transformers: 4.35.2
Torch: 2.1.1-cpu

### Who can help?

@Narsil 
I attempted text generation with the Llama 2 model using the transformer text generation pipeline on a CPU. The model precision was configured to float16 using the torch_dtype argument, but encountered the following issues. While I successfully executed FP32 and BF16 models on the CPU, it seems that transformers does not support FP16 on CPU.  Is FP16 supported by transformers on CPU ? The detailed error is provided below:
```
Traceback (most recent call last):
  File "/home/user/sagar/wrkld-llm-hf-cpu/performance-testing/llm/test.py", line 21, in <module>
    output = text_generator(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 208, in __call__
    return super().__call__(text_inputs, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1140, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1147, in run_single
    model_outputs = self.forward(model_inputs, **forward_params)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/pipelines/text_generation.py", line 271, in _forward
    generated_sequence = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, **generate_kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 1673, in generate
    return self.greedy_search(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 2521, in greedy_search
    outputs = self(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 1009, in forward
    outputs = self.model(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 897, in forward
    layer_outputs = decoder_layer(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 626, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 244, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/pypoetry/virtualenvs/llama2-benchmark-qWVSPitQ-py3.10/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

model_id = "meta-llama/Llama-2-7b-chat-hf"
device = "cpu"
torch_dtype = torch.float16
tokenizer = AutoTokenizer.from_pretrained(model_id)
input_text = "Discuss the history and evolution of artificial intelligence in 80 words"

text_generator = pipeline(
    "text-generation",
    model=model_id,
    tokenizer=tokenizer,
    return_tensors=True,
    device=device,
    torch_dtype = torch_dtype,
)


# Inference benchmarking
output = text_generator(
    input_text,
    max_new_tokens=100,
    temperature=0.1,
)
print(tokenizer.decode(output[0]["generated_token_ids"]))
num_tokens = len(output[0]["generated_token_ids"])
```

### Expected behavior

Is FP16 supported by transformers on CPU ?

**Comment by ArthurZucker** [comment]
Hello, the issue does not lie with transformers but `torch` which does not support FP16 on CPU. 🤗
