### ISSUE TITLE
ValueError: Tokenizer class CPMAntTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by jq460494839** [huggingface/transformers#27938]
### System Info

transformers==4.35.2

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. download cpm-ant-10b from huggingface
2. load cpm-ant tokenizer locally

### Expected behavior

Traceback (most recent call last):
  File "/opt/projects/FastChat/fastchat/train/train.py", line 301, in <module>
    train()
  File "/opt/projects/FastChat/fastchat/train/train.py", line 273, in train
    tokenizer = transformers.AutoTokenizer.from_pretrained(
  File "/root/miniconda/envs/torch_npu/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 766, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class CPMAntTokenizer does not exist or is not currently imported.

**Comment by ArthurZucker** [comment]
```python
from transformers import CpmAntTokenizer
```

is what you are looking for
