### ISSUE TITLE
Can't do word timestamps and beam search at the same time (whisper)

### ISSUE THREAD

**Issue by Snarkdoof** [huggingface/transformers#28007]
### System Info

Tested on python 3.8.10, transformers 4.36.0.dev0

### Who can help?

@ArthurZucker @sanchit-gandhi (suggested by peregilk)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import pipeline
import torch
model = "NbAiLabBeta/nb-whisper-base"
device = "cuda:0"

p = pipeline("automatic-speech-recognition",
             model,
             torch_dtype=torch.float16,
             device=device,
             return_timestamps="word")
args = {"language": "norwegian", "task": "transcribe", "num_beams": 3}
outputs = p(audiofile,
            chunk_length_s=28,
            batch_size=6,
            generate_kwargs=args)
```

Fails with:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1132, in __call__
    return next(
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.8/dist-packages/transformers/pipelines/automatic_speech_recognition.py", line 552, in _forward
    generate_kwargs["num_frames"] = stride[0] // self.feature_extractor.hop_length
TypeError: unsupported operand type(s) for //: 'tuple' and 'int'

It works with *either* num_beams:1 OR return_timestamps=True/False, but not combined.

### Expected behavior

It should return processed data. :)

**Comment by amyeroberts** [comment]
cc @gante

**Comment by Pranjalya** [comment]
I believe there's already an active PR for this: https://github.com/huggingface/transformers/pull/26699 However, the PR might need a little more work as it is not a polished solution yet (at least that's what I think).

**Comment by xenova** [comment]
Fixed by https://github.com/huggingface/transformers/pull/28114 👍
