### ISSUE TITLE
can not find dataset_name transformersbook/codeparrot

### ISSUE THREAD

**Issue by sxsxsx** [huggingface/transformers#28063]
### System Info

python scripts/preprocessing.py \
--dataset_name transformersbook/codeparrot \
--output_dir codeparrot-clean

can not find dataset_name transformersbook/codeparrot

the error is

Traceback (most recent call last):
  File "scripts/preprocessing.py", line 171, in <module>
    ds = load_dataset(args.dataset_name, split="train")
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/load.py", line 1627, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/load.py", line 1464, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/load.py", line 1174, in dataset_module_factory
    raise e1 from None
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/load.py", line 1156, in dataset_module_factory
    return CommunityDatasetModuleFactoryWithoutScript(
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/load.py", line 801, in get_module
    else get_patterns_in_dataset_repository(dataset_info)
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/data_files.py", line 473, in get_patterns_in_dataset_repository
    return _get_data_files_patterns(resolver)
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/data_files.py", line 101, in _get_data_files_patterns
    data_files = pattern_resolver(pattern)
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/datasets/data_files.py", line 305, in _resolve_single_pattern_in_dataset_repository
    glob_iter = [PurePath(filepath) for filepath in fs.glob(pattern) if fs.isfile(filepath)]
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/fsspec/spec.py", line 606, in glob
    pattern = glob_translate(path + ("/" if ends_with_sep else ""))
  File "/home/admin/miniconda3/envs/huggingface/lib/python3.8/site-packages/fsspec/utils.py", line 734, in glob_translate
    raise ValueError(

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

scripts/preprocessing.py

### Expected behavior

run success

**Comment by amyeroberts** [comment]
Hi @sxsxsx, thanks for raising this issue! 

Could you please provide information about the running environment: run `transformers-cli env` in the terminal and copy-paste the output? 

Is the script being run `examples/research_projects/codeparrot/scripts/preprocessing.py ? Please note that the research examples are not actively maintained and so may no longer be compatible with the most recent libraries. 

I'm not able to reproduce the issue with loading the dataset. It's possible there was a transient issue with connecting to the hub. Could you try running the code again?

I'm able to run: 
```
from datasets import load_dataset

dataset = load_dataset("transformersbook/codeparrot", split="train", streaming=True)
```
