### ISSUE TITLE
 QWenLMHeadModel does not support Flash Attention 2.0 yet.

### ISSUE THREAD

**Issue by zhangfan-algo** [huggingface/transformers#28100]
![image](https://github.com/huggingface/transformers/assets/47747764/63db1736-d049-4ab0-8187-df43d3afb75e)

**Comment by qingyuanxingsi** [comment]
+1

**Comment by amyeroberts** [comment]
Hi @zhangfan-algo, thanks for creating this feature request. 

Is this model code on the hub? If so, the request to add FA2 support should be done on the discussion page for that model. 

In the meantime - we should update this message on our end to route users to the correct place.

**Comment by txy6666yr** [comment]
> Hi @zhangfan-algo, thanks for creating this feature request.
> 
> Is this model code on the hub? If so, the request to add FA2 support should be done on the discussion page for that model.
> 
> In the meantime - we should update this message on our end to route users to the correct place.

魔塔下载的模型，今天微调的时候出现这个错误：
```
Traceback (most recent call last):
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/train_bash.py", line 15, in <module>
    main()
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/train_bash.py", line 5, in main
    run_exp()
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/train/tuner.py", line 26, in run_exp
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/train/sft/workflow.py", line 29, in run_sft
    model, tokenizer = load_model_and_tokenizer(model_args, finetuning_args, training_args.do_train)
  File "/mnt/pfs-guan-ssai/nlu/data/tianxy/LLaMA-Factory-2/src/llmtuner/model/loader.py", line 67, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3456, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1302, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1382, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: QWenLMHeadModel does not support Flash Attention 2.0 yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new
```
