### ISSUE TITLE
Emu2 seems to fail to find remote model

### ISSUE THREAD

**Issue by CoffeeVampir3** [huggingface/transformers#28233]
### System Info

- `transformers` version: 4.37.0.dev0
- Platform: Linux-6.6.8-arch1-1-x86_64-with-glibc2.38
- Python version: 3.10.12
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: 3090TI/A4000 (Ada)
- Using distributed or parallel set-up in script?: no

### Who can help?

@amyeroberts @ArthurZucker @younesbelkada

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Using the example script for EMU2-GEN <https://huggingface.co/BAAI/Emu2-Gen>
The only modification I made was to set the path to my local copy of the model: `path = "mypath"`

I've included the code for reference at the bottom of this post.

```
(base) ➜  Emu2-Gen python test.py      
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:28<00:00,  3.61s/it]
Keyword arguments {'trust_remote_code': True} are not expected by EmuVisualGenerationPipeline and will be ignored.
Loading pipeline components...:   0%|                                                                                                                                                                                | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/ue/Emu2-Gen/test.py", line 22, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1264, in from_pretrained
    maybe_raise_or_warn(
  File "/home/blackroot/miniforge3/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 299, in maybe_raise_or_warn
    library = importlib.import_module(library_name)
  File "/home/blackroot/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.modeling_emu'
```

I'm not sure if this is on the transformers end or an issue with the remote module loading. Cheers.

```python
import cv2
from diffusers import DiffusionPipeline
import numpy as np
from PIL import Image
import requests
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# For the first time of using,
# you need to download the huggingface repo "BAAI/Emu2-GEN" to local first
path = "/mnt/ue/Emu2-Gen"

multimodal_encoder = AutoModelForCausalLM.from_pretrained(
    f"{path}/multimodal_encoder",
    trust_remote_code=True,
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16"
)
tokenizer = AutoTokenizer.from_pretrained(f"{path}/tokenizer")

pipe = DiffusionPipeline.from_pretrained(
    path,
    custom_pipeline="pipeline_emu2_gen",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    use_safetensors=True,
    variant="bf16",
    multimodal_encoder=multimodal_encoder,
    tokenizer=tokenizer,
)

#For the non-first time of using, you can init the pipeline directly
pipe = DiffusionPipeline.from_pretrained(
    path,
    custom_pipeline="pipeline_emu2_gen",
    torch_dtype=torch.bfloat16,
    use_safetensors=True,
    variant="bf16",
)

pipe.to("cuda")

# text-to-image
prompt = "impressionist painting of an astronaut in a jungle"
ret = pipe(prompt)
ret.images[0].save("astronaut.png")

# image editing
image = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
prompt = [image, "wearing a red hat on the beach."]
ret = pipe(prompt)
ret.images[0].save("dog_hat_beach.png")

# grounding generation
def draw_box(left, top, right, bottom):
    mask = np.zeros((448, 448, 3), dtype=np.uint8)
    mask = cv2.rectangle(mask, (left, top), (right, bottom), (255, 255, 255), 3)
    mask = Image.fromarray(mask)
    return mask

dog1 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog1.jpg?raw=true',stream=True).raw).convert('RGB')
dog2 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog2.jpg?raw=true',stream=True).raw).convert('RGB')
dog3 = Image.open(requests.get('https://github.com/baaivision/Emu/Emu2/examples/dog3.jpg?raw=true',stream=True).raw).convert('RGB')
dog1_mask = draw_box( 22,  14, 224, 224)
dog2_mask = draw_box(224,  10, 448, 224)
dog3_mask = draw_box(120, 264, 320, 438)

prompt = [
    "<grounding>",
    "A photo of",
    "<phrase>the first dog</phrase>"
    "<object>",
    dog1_mask,
    "</object>",
    dog1,
    "<phrase>the second dog</phrase>"
    "<object>",
    dog2_mask,
    "</object>",
    dog2,
    "<phrase>the third dog</phrase>"
    "<object>",
    dog3_mask,
    "</object>",
    dog3,
    "on the grass",
]
ret = pipe(prompt)
ret.images[0].save("three_dogs.png")
```

### Expected behavior

The expected behaviour is that the module is loaded by transformers.

**Comment by younesbelkada** [comment]
Hi @CoffeeVampir3 
Thanks a lot for the issue ! 
It seems the issues is raised from the diffusion pipeline side, more precisely during the `DiffusionPipeline.from_pretrained`. Can you try to load the model with the latest version of diffusers? `pip install -U diffusers`
