### ISSUE TITLE
Early stopping required metric_for_best_model, but did not find eval_f1 so early stopping is disabled

### ISSUE THREAD

**Issue by ManishChandra12** [huggingface/transformers#28530]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.18
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.25.0
- Accelerate config:    not found
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@muellerzr @pacman100

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import os
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from transformers import TrainingArguments, Trainer
from transformers import EarlyStoppingCallback, IntervalStrategy
import numpy as np
import evaluate

os.environ["CUDA_VISIBLE_DEVICES"]=str(gpu_id)
from datasets import Dataset, DatasetDict
train_k = pd.read_csv('new_train_set_toxicity_train.csv', usecols=["text", "k"])
train_k.rename(columns={"text":"text", "k":"label"}, inplace=True)
val_k = pd.read_csv('new_train_set_toxicity_val.csv', usecols=["text", "k"])
val_k.rename(columns={"text":"text", "k":"label"}, inplace=True)
test_k = pd.read_csv('new_train_set_toxicity_test.csv', usecols=["text", "k"])
test_k.rename(columns={"text":"text", "k":"label"}, inplace=True)

train_k = Dataset.from_pandas(train_k)
val_k = Dataset.from_pandas(val_k)
test_k = Dataset.from_pandas(test_k)

ds = DatasetDict()
ds['train'] = train_k
ds['val'] = val_k
ds['test'] = test_k

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
def tokenize_function(examples):
    return tokenizer(str(examples['text']), padding="max_length", truncation=True)

tokenized_datasets = ds.map(tokenize_function)
tokenized_train_k = tokenized_datasets["train"]
tokenized_val_k = tokenized_datasets["val"]

model_k = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=6)
training_args = TrainingArguments(output_dir="trained_k_predictors", evaluation_strategy="steps", eval_steps=100, metric_for_best_model = 'f1', learning_rate=1e-3, num_train_epochs=5, weight_decay=0.01, load_best_model_at_end=True, per_device_train_batch_size = 16, per_device_eval_batch_size = 32, save_total_limit = 3, optim="adafactor", label_names=['label'], remove_unused_columns=False,)
metric = evaluate.load("f1")
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {'f1': metric.compute(predictions=predictions, references=labels)}
trainer = Trainer(model=model_k, args=training_args, train_dataset=tokenized_train_k, eval_dataset=tokenized_val_k, callbacks = [EarlyStoppingCallback(early_stopping_patience=3)])
trainer.train()
```

## Error message:
{'eval_runtime': 21.6631, 'eval_samples_per_second': 208.926, 'eval_steps_per_second': 3.277, 'epoch': 0.47}                                                                                                       
  9%|████████████████                                                                                                                                                           | 5                       [26/1960]
00/5305 [06:15<41:00,  1.95it/s]
100%|████████████████████████████████████████████████████████████████████�     $                                                                                                                          [24/1960]
�█████████████████████████████████████████████�early stopping required metric_for_best_model, but did not find eval_f1 so                                                                                 [23/1960]
 early stopping is disabled██████████████████████████| 71/71 [00:21<00:00,  3.42it/s]
Traceback (most recent call last):                                                                                                                                                                                 
  File "/scratch/manish/apl/apl_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/manish/apl/apl_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/manish/apl/src/apl.py", line 386, in <module>
    main()
  File "/scratch/manish/apl/src/apl.py", line 139, in main
    trainer.train()
  File "/scratch/manish/apl/apl_env/lib/python3.8/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/scratch/manish/apl/apl_env/lib/python3.8/site-packages/transformers/trainer.py", line 1922, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/scratch/manish/apl/apl_env/lib/python3.8/site-packages/transformers/trainer.py", line 2282, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/scratch/manish/apl/apl_env/lib/python3.8/site-packages/transformers/trainer.py", line 2407, in _save_checkpoint
    metric_value = metrics[metric_to_check]
KeyError: 'eval_f1'
  9%|███████████████▉                                                                                                                                                         | 500                        [3/1960]
/5305 [06:18<1:00:34,  1.32it/s]

### Expected behavior

Train the model with early stopping enabled.

**Comment by ManishChandra12** [comment]
Hi @amyeroberts. Thanks for the quick response.

The error persists even if I pass ```compute_metrics``` to ```Trainer```.

PS: I have updated the original issue by adding ```compute_metrics```.

**Comment by amyeroberts** [comment]
@ManishChandra12 OK, thanks for reporting back. Is the error exactly the same as before? 

Could you update the script to use a public dataset, or provide a sample of the dataset so we can run the code to reproduce on our end?

**Comment by ManishChandra12** [comment]
@amyeroberts yes, the error is exactly the same as before.

Here is a sample of the dataset:
[val.csv](https://github.com/huggingface/transformers/files/13950970/val.csv)
[test.csv](https://github.com/huggingface/transformers/files/13950971/test.csv)
[train.csv](https://github.com/huggingface/transformers/files/13950972/train.csv)

**Comment by amyeroberts** [comment]
Hi @ManishChandra12, I'm able to run the provided code and data without error on main. Could you try updating your transformers version to the latest release v4.36.2?

**Comment by adrienchaton** [comment]
@ManishChandra12 @amyeroberts could you figure out the issue?

When I run the code with the provided example data, it also says
"early stopping required metric_for_best_model, but did not find eval_f1 so early stopping is disabled"
and when I run ```trainer.evaluate()``` it only returns the following keys ```'eval_runtime', 'eval_samples_per_second', 'eval_steps_per_second', 'epoch'``` so neither the loss or the F1 score

I am on v4.36.2.

I also have the same issue with my code, to recapitulate:
- TrainingArguments.prediction_loss_only = False
- TrainingArguments.metric_for_best_model = "name_of_my_metric"
- TrainingArguments.greater_is_better = True
- Trainer.compute_metrics = fn_eval_metric which is a function that returns {"name_of_my_metric": score_to_improve}

I am going through the source code of the Trainer to try to figure out what happens in detail because it seems the compute_metrics function isn't called at all ... I tried to introduce a bug in the function but there is no error as it should happen if the function was called, the only error comes at the end of the evaluation loop as it doesn't find the "eval_name_of_my_metric" key ...

I am puzzled, any hints would be great on how to fix this, thanks!

**Comment by amyeroberts** [comment]
@adrienchaton - could you try running on the latest release v4.37?

**Comment by adrienchaton** [comment]
@amyeroberts thanks, I updated to v4.37 but the problem persists in the same way.

And if I set 
- Trainer.compute_metrics = None
- TrainingArguments.metric_for_best_model = "loss"
- TrainingArguments.greater_is_better = False
- TrainingArguments.prediction_loss_only = True

Then the same error comes, stating
```
transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
transformers/trainer.py", line 2300, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
transformers/trainer.py", line 2389, in _save_checkpoint
    metric_value = metrics[metric_to_check]
KeyError: 'eval_loss'```

**Comment by adrienchaton** [comment]
this issue might be related, but setting or not the label_names in TrainingArguments didnt change my issues

https://discuss.huggingface.co/t/why-do-i-get-no-validation-loss-and-why-are-metrics-not-calculated/32373

**Comment by adrienchaton** [comment]
@amyeroberts @ManishChandra12 I think I figured out the problem, TrainingArguments.label_names wasn't configured properly and it would silently be ignored by the trainer which seems to run evaluation but doesnt compute any metric, neither the loss, nor the custom metrics if providing a compute_metrics function

making sure that your data_collator returns a "labels" key AND setting label_names=["labels"] should fix the problem

I am not the only one who faced this problem .. I think it would be better to print a warning e.g. "compute_metrics provided but no label_names, thus metrics will be ignored" because it is misleading to see the progress bar with all eval samples being processed while the metrics arent computed because label_names keys arent found in the input

**Comment by amyeroberts** [comment]
Thanks for updating with the fix @adrienchaton! 

I'll let @pacman100 and @muellerzr decide on the best way to handle / flag on the trainer side

**Comment by muellerzr** [comment]
@adrienchaton printing a warning would be great IMO! Would you like to open a PR?

**Comment by adrienchaton** [comment]
@muellerzr cool, I will do that within the next days and you can let me know if that fits :)

**Comment by xmz111** [comment]
This is an odd issue caused by "label". Actually, supervised leaning should be considered by transformers team, since some documentations are not clear.
For me, I named label column as "label" and delete the arg in training_args: `#label_names=["label"],`. This issue raises because some modules (especially data_collator module) in Trainer don't receive labels. See codes and annotation in `/lib/python3.8/site-packages/transformers/trainer.py (747th line)`: `# Labels may be named label or label_ids, the default data collator handles that.`
Transformer is an amazing and convenient lib, hope some notes can be added to help people process labels.

**Comment by adrienchaton** [comment]
I am sorry guys .. I still havent prepared the PR, work is quite busy at the moment

**Comment by lejinvarghese** [comment]
fwiw, this issue seems to be showing up even in non classification tasks too, not sure if it's explicitly just tied to the `label_names` only. my base model also seems unable to [return](https://github.com/huggingface/transformers/blob/25245ec26dc29bcf6102e1b4ddd0dfd02e720cf5/src/transformers/trainer.py#L3965-L3968) the loss, could that be related?
