### ISSUE TITLE
Tokenizer `encode/decode` methods are inconsistent, TypeError: argument 'ids': 'list' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by scruel** [huggingface/transformers#28635]
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
- Python version: 3.11.6
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run the following code:
```python
from transformers import AutoTokenizer

text = "test"
tokenizer = AutoTokenizer.from_pretrained("gpt2")
encoded = tokenizer.encode(text, return_tensors='pt')
result_text = tokenizer.decode(encoded, skip_special_tokens=True)
print(text)
```

Will raise exception:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    tokenizer.decode(encoded, skip_special_tokens=True)
  File "/home/scruel/mambaforge/envs/vae/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3748, in decode
    return self._decode(
           ^^^^^^^^^^^^^
  File "/home/scruel/mambaforge/envs/vae/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 625, in _decode
    text = self._tokenizer.decode(token_ids, skip_special_tokens=skip_special_tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'ids': 'list' object cannot be interpreted as an integer
```

### Expected behavior

Should be able to print the original text `"test"`, rather than raise an exception(`TypeError`).

**Comment by scruel** [comment]
Sure, already working on it, I will create a PR later today.

**Comment by scruel** [comment]
Hi @ArthurZucker, 
- Should be keep related APIs as same as `huggingface/tokenizers` lib? Consider if we only have one `(de)encode` methods which not just process single but batches, it will be impossible to distinguish the difference between `List[TextInput]` and `PreTokenizedInput` with its own power without changing the logic or adding extra parameters, consider they are just the same thing, so I think:
  - We add a `batch` parameter to the `(de)encode` methods, and keeping/adding the `(de)encode_batch` methods.
  - We change the logic of the function, like if the method receives `list[str]` type input, we only treat it as batched strings, rather than pre-toeknized single string.
  BTW, I wonder to ask why you decided to only remove list-object's leading batch axis for this? May it can provide some convince for users while using `encode` method?
- I prefer to use `Enum`s with inner methods, rather than use "magic strings" everywhere in the project (fine for API to provide user convenience), during the refracting period, I found lost of the legacy code that used "magic strings", even for condition tests.
-

**Comment by ArthurZucker** [comment]
Sorry for such a big change in the API I'd rather take care of it, I was more referring to a small PR that supports for now decoding a batch of inputs with decode! 

About all the points you mentioned, for me the direction of the library is a bit different. Appart from removing calls to TF everywhere which indeed should be protected the same way as flax!

**Comment by scruel** [comment]
> Sorry for such a big change in the API I'd rather take care of it, I was more referring to a small PR that supports for now decoding a batch of inputs with decode!

`decode` itself can't handle such tasks well, as I mentioned before:
> it will be impossible to distinguish the difference between List[TextInput] and PreTokenizedInput with its own power without changing the logic or adding extra parameters

So yes, it becomes a "big change".

> the direction of the library is a bit different

Can you explain this more? I think most of the points are just about the code style, so it won't affect the direction of anything, but may improve the maintainability :)

> Appart from removing calls to TF everywhere which indeed should be protected the same way as flax!

Cool, I'm glad that you also think so, we'd better consider this more, consider having `import` statement for frequently used functions is definitely a bad idea coz it has to look up those libraries every time, even Python will only do one true import for one library (heavy operation).
