### ISSUE TITLE
Add Flash Attention 2 support for Flan-T5

### ISSUE THREAD

**Issue by mrticker** [huggingface/transformers#28917]
### Feature request

Add Flash Attention 2 support for Flan-T5

### Motivation

```
loading weights file model.safetensors from cache at /pretrained/models--google--flan-t5-large/snapshots/0613663d0d48ea86ba8cb3d7a44f0f65dc596a2a/model.safetensors
Instantiating T5ForConditionalGeneration model under default dtype torch.float16.
Traceback (most recent call last):
  File "/mount/train_flan.py", line 86, in <module>
    model = T5ForConditionalGeneration.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3444, in from_pretrained
    config = cls._autoset_attn_implementation(
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1302, in _autoset_attn_implementation
    cls._check_and_enable_flash_attn_2(
  File "/opt/conda/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1382, in _check_and_enable_flash_attn_2
    raise ValueError(
ValueError: T5ForConditionalGeneration does not support Flash Attention 2.0 yet. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new
```

### Your contribution

^

**Comment by sbrunk** [comment]
The main Flash Attention 2 discussion tracking issue and discussion seems to be  https://github.com/huggingface/transformers/issues/26350
