### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data! when moving LLaVa from meta device to CUDA

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/transformers#28972]
### System Info

Transformers 4.37.0.dev0

### Who can help?

@ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Reproduction

Getting this error:
```
Traceback (most recent call last):
  File "src/transformers/models/llava/test_meta_device.py", line 10, in <module>
    model.to(device)
  File "/home/niels/python_projects/transformers/src/transformers/modeling_utils.py", line 2556, in to
    return super().to(*args, **kwargs)
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/niels/python_projects/transformers/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

when running this:

```python
from transformers import LlavaConfig, LlavaForConditionalGeneration
import torch

config = LlavaConfig()

with torch.device("meta"):
    model = LlavaForConditionalGeneration(config)

model.load_state_dict(original_state_dict, assign=True)

device = "cuda:0"
model.to(device)
```
Taken from [this script](https://github.com/NielsRogge/transformers/blob/5be6e778e091f046f3158d9d2acf7cfeb5f539c3/src/transformers/models/llava/convert_llava_1_6_to_hf.py#L118-L145). Weird enough, the same thing works for CogVLM as seen [here](https://github.com/NielsRogge/transformers/blob/f190a38dbcc25c1a882b060659c6f2abb99d9dcf/src/transformers/models/cogvlm/convert_cogvlm_original_to_pytorch.py#L109-L115), but not for LLaVa.

Based on this PR: https://github.com/huggingface/transformers/pull/26849 (which fixed a similar issue for DETR), this may have to do with some modules that cannot be splitted

### Expected behavior

I'd like to first load LLaVa on the "meta" device, and then load the weights as I'm converting from the original repository. The "meta" device allows to load the HF model much faster as I've observed with CogVLM (thanks @ArthurZucker as I didn't know about this!)

**Comment by NielsRogge** [comment]
Ok I'm seeing the same error with BERT:
```python
from transformers import BertConfig, BertModel
import torch

config = BertConfig()

with torch.device("meta"):
    model = BertModel(config)

pretrained_model = BertModel.from_pretrained("bert-base-uncased")
original_state_dict =  {k:v.to("cuda") for k,v in pretrained_model.state_dict().items()}
model.load_state_dict(original_state_dict, assign=True)

device = "cuda:0"
model.to(device)
```
Trying to figure out why this works for CogVLM but not for BERT or LLaVa..

**Comment by muellerzr** [comment]
@NielsRogge the issue lies in the parameters being initialized. Instead of using `with torch.device("meta")` use `init_empty_weights` from accelerate instead and it will work just fine:

```python
from transformers import BertConfig, BertModel
from accelerate import init_empty_weights

config = BertConfig.from_pretrained("bert-base-uncased")

with init_empty_weights():
    model = BertModel(config)

pretrained_model = BertModel.from_pretrained("bert-base-uncased")
model.load_state_dict(pretrained_model.state_dict(), assign=True)

model.to("cuda")
```

**Comment by NielsRogge** [comment]
Thanks, I indeed noticed that it had to do something with buffers, great, thanks a lot!

**Comment by ArthurZucker** [comment]
Also I believe that low cpu mem usage should be equally as fast no?

**Comment by VarunGumma** [comment]
Hi @NielsRogge and @muellerzr 

I get a similar issue with transformers 4.51, when running the following code. I get the same error even without the `torch_dtype`

```python
model = AutoModelForSeq2SeqLM.from_pretrained(
    "prajdabre/rotary-indictrans2-en-indic-dist-200M",
    trust_remote_code=True,
    torch_dtype=torch.float16,
)

model = model.to("cuda")
```

### StackTrace
```python
File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/transformers/modeling_utils.py:3698, in PreTrainedModel.to(self, *args, **kwargs)
   3693     if dtype_present_in_args:
   3694         raise ValueError(
   3695             "You cannot cast a GPTQ model in a new `dtype`. Make sure to load the model using `from_pretrained` using the desired"
   3696             " `dtype` by passing the correct `torch_dtype` argument."
   3697         )
-> 3698 return super().to(*args, **kwargs)

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:1343, in Module.to(self, *args, **kwargs)
   1340         else:
   1341             raise
-> 1343 return self._apply(convert)

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:903, in Module._apply(self, fn, recurse)
    901 if recurse:
    902     for module in self.children():
--> 903         module._apply(fn)
    905 def compute_should_use_set_data(tensor, tensor_applied):
    906     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    907         # If the new tensor has compatible tensor type as the existing tensor,
    908         # the current behavior is to change the tensor in-place using `.data =`,
   (...)    913         # global flag to let the user control whether they want the future
    914         # behavior of overwriting the existing tensor or not.

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:903, in Module._apply(self, fn, recurse)
    901 if recurse:
    902     for module in self.children():
--> 903         module._apply(fn)
    905 def compute_should_use_set_data(tensor, tensor_applied):
    906     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    907         # If the new tensor has compatible tensor type as the existing tensor,
    908         # the current behavior is to change the tensor in-place using `.data =`,
   (...)    913         # global flag to let the user control whether they want the future
    914         # behavior of overwriting the existing tensor or not.

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:903, in Module._apply(self, fn, recurse)
    901 if recurse:
    902     for module in self.children():
--> 903         module._apply(fn)
    905 def compute_should_use_set_data(tensor, tensor_applied):
    906     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    907         # If the new tensor has compatible tensor type as the existing tensor,
    908         # the current behavior is to change the tensor in-place using `.data =`,
   (...)    913         # global flag to let the user control whether they want the future
    914         # behavior of overwriting the existing tensor or not.

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:930, in Module._apply(self, fn, recurse)
    926 # Tensors stored in modules are graph leaves, and we don't want to
    927 # track autograd history of `param_applied`, so we have to use
    928 # `with torch.no_grad():`
    929 with torch.no_grad():
--> 930     param_applied = fn(param)
    931 p_should_use_set_data = compute_should_use_set_data(param, param_applied)
    933 # subclasses may have multiple child tensors so we need to use swap_tensors

File ~/.miniconda3/envs/hf2/lib/python3.12/site-packages/torch/nn/modules/module.py:1336, in Module.to.<locals>.convert(t)
   1334 except NotImplementedError as e:
   1335     if str(e) == "Cannot copy out of meta tensor; no data!":
-> 1336         raise NotImplementedError(
   1337             f"{e} Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() "
   1338             f"when moving module from meta to a different device."
   1339         ) from None
   1340     else:
   1341         raise

NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
```

Any ideas?

**Comment by daskol** [comment]
@NielsRogge The issue https://github.com/huggingface/transformers/issues/41038 seems relevant to this one.
