### ISSUE TITLE
InferenceOutputError when using translation from @huggingface/inference

### ISSUE THREAD

**Issue by shweta-24** [huggingface/transformers#29014]
### System Info

Running application within a docker container. Following is the output of the command 'docker exec -it <container>  env'

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=244dc091910d
TERM=xterm
APP_BASE_URL=http://localhost:3000
DUCKDB_AUTO_PROFILE=
NODE_VERSION=18.12.1
YARN_VERSION=1.22.19
NODE_ENV=development
HOME=/root

### Who can help?

@ArthurZucker @younesbelkada @Sun

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Running the following script
```javascript

import { HfInference } from '@huggingface/inference';

hfTranslate = new HfInference(token);
async huggingFaceTranslate(s: string): Promise<string> {
        try{
            const results = await hfTranslate.translation({
                model: 'Helsinki-NLP/opus-mt-sv-en',
                inputs: s,
            })
            return results.translation_text;

        }
        catch(err){
            console.error(err);
            return s;
        } 
    }
}

const translation = await huggingFaceTranslate('Övrig viltfågel')
console.log(translation);
```
I get the following error output:
```
InferenceOutputError: Invalid inference output: Expected type Array<{translation_text: string}>. Use the 'request' method with the same parameters to do a custom call with no type checking.
    at translation (/home/procuro/app/node_modules/@huggingface/inference/dist/index.js:767:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async huggingFaceTranslate (/home/procuro/app/scripts/hugging_face_translation_test.ts:16:25)
    at async main (/home/procuro/app/scripts/hugging_face_translation_test.ts:31:25)
    at async /home/procuro/app/scripts/hugging_face_translation_test.ts:38:9
Övrig viltfågel
```

### Expected behavior

The call to hfTranslate.translation() must return the translated text for 'Övrig viltfågel'. Something close to 'other game bird'

**Comment by amyeroberts** [comment]
Move this to huggingface.js as it seems to be more related to that repo
