### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by vincent507cpu** [huggingface/transformers#29074]
### System Info

I was trying to run **https://github.com/dvlab-research/LongLoRA/blob/main/fine-tune.py**, but I first encountered `ValueError: Tokenizer class ChatGLMTokenizer does not exist or is not currently imported.` (it's been solved by switching line 135 and line 141 snippests). Then I had a new error (please see below).

Could anyone help me? Thanks a lot!

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`python fine-tune.py --output_dir ./output_models/chatglm3-6b-32k`

### Expected behavior

```
/home/zwj/GitHub/LongLoRA-main/llama_attn_replace.py:464: UserWarning: Flash attention is only supported on A100 or H100 GPU during training due to head dim > 64 backward.ref: https://github.com/HazyResearch/flash-attention/issues/190#issuecomment-1523359593
  warnings.warn(
Loading checkpoint shards: 100%|█████████████████████████████████████████████| 7/7 [00:02<00:00,  3.38it/s]
Traceback (most recent call last):
  File "/home/zwj/GitHub/LongLoRA-main/fine-tune.py", line 217, in <module>
    train()
  File "/home/zwj/GitHub/LongLoRA-main/fine-tune.py", line 165, in train
    smart_tokenizer_and_embedding_resize(
  File "/home/zwj/GitHub/LongLoRA-main/fine-tune.py", line 81, in smart_tokenizer_and_embedding_resize
    model.resize_token_embeddings(len(tokenizer))
  File "/home/zwj/miniconda3/envs/longlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1811, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens, pad_to_multiple_of)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zwj/miniconda3/envs/longlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1832, in _resize_token_embeddings
    self.set_input_embeddings(new_embeddings)
  File "/home/zwj/miniconda3/envs/longlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1610, in set_input_embeddings
    base_model.set_input_embeddings(value)
  File "/home/zwj/miniconda3/envs/longlora/lib/python3.11/site-packages/transformers/modeling_utils.py", line 1612, in set_input_embeddings
    raise NotImplementedError
NotImplementedError
```

**Comment by xiaobaoxia** [comment]
Hi Vincent,
I've meet the same problem,  which also raise with no set_input_embeddings. Could you please tell me how to fix it?
Thanks.
