### ISSUE TITLE
Quantization Error: register_buffer is not in module_parameters.

### ISSUE THREAD

**Issue by DonggeunYu** [huggingface/transformers#29201]
### System Info

Not a system issue. Code issue.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code:
~~~
import torch
from transformers.models.deformable_detr.modeling_deformable_detr import DeformableDetrModel
from transformers import BitsAndBytesConfig


bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        llm_int8_skip_modules=[
            'deformable_detr_model',
        ],
        bnb_4bit_compute_dtype=torch.float32,
    )
model = DeformableDetrModel.from_pretrained("SenseTime/deformable-detr", device_map="cuda:0", torch_dtype=torch.half, quantization_config=bnb_config)
~~~

### Expected behavior

Log:
~~~
Traceback (most recent call last):
  File "/selfsup/a.py", line 13, in <module>
    model = DeformableDetrModel.from_pretrained("SenseTime/deformable-detr", device_map="cuda:0", torch_dtype=torch.half, quantization_config=bnb_config)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 802, in _load_state_dict_into_meta_model
    or (not hf_quantizer.check_quantized_param(model, param, param_name, state_dict))
  File "/usr/local/lib/python3.10/dist-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 124, in check_quantized_param
    if isinstance(module._parameters[tensor_name], bnb.nn.Params4bit):
KeyError: 'bias'
~~~

**Comment by ArthurZucker** [comment]
Sorry for the delay! 
cc @SunMarc and @younesbelkada
