### ISSUE TITLE
Thread-autoconversion error

### ISSUE THREAD

**Issue by geoffvdr** [huggingface/transformers#29513]
Hello,

I am trying to load the `facebook/mms-1b` speech model and I am getting a 'conversion error' that I have never encountered before.

The code:
```python
from transformers import (
    AutoConfig,
    AutoModelForCTC
)
config = AutoConfig.from_pretrained("facebook/mms-1b")
model = AutoModelForCTC.from_pretrained(
         "facebook/mms-1b",
        config=config,
    )
``` 

The error:
```
Error during conversion: ValueError('Queue is full! Please try again.')
Exception in thread Thread-autoconversion:
Traceback (most recent call last):
  File "[/opt/conda/lib/python3.11/threading.py", line 1045](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/tree/project_antwerp/huggingface/exp/opt/conda/lib/python3.11/threading.py#line=1044), in _bootstrap_inner
    self.run()
  File "[/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 761](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/tree/project_antwerp/huggingface/exp/opt/conda/lib/python3.11/site-packages/ipykernel/ipkernel.py#line=760), in run_closure
    _threading_Thread_run(self)
  File "[/opt/conda/lib/python3.11/threading.py", line 982](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/tree/project_antwerp/huggingface/exp/opt/conda/lib/python3.11/threading.py#line=981), in run
    self._target(*self._args, **self._kwargs)
  File "[/opt/conda/lib/python3.11/site-packages/transformers/safetensors_conversion.py", line 89](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/tree/project_antwerp/huggingface/exp/opt/conda/lib/python3.11/site-packages/transformers/safetensors_conversion.py#line=88), in auto_conversion
    sha = get_conversion_pr_reference(api, pretrained_model_name_or_path, **cached_file_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/opt/conda/lib/python3.11/site-packages/transformers/safetensors_conversion.py", line 82](https://jupyterhub.ilabt.imec.be/user/gvdrreyd@ilabt.imec.be/lab/tree/project_antwerp/huggingface/exp/opt/conda/lib/python3.11/site-packages/transformers/safetensors_conversion.py#line=81), in get_conversion_pr_reference
    sha = f"refs/pr/{pr.num}"
                     ^^^^^^
AttributeError: 'NoneType' object has no attribute 'num'
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/mms-1b and are newly initialized: ['lm_head.bias', 'lm_head.weight', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
``` 

I am using `transformers 4.39.0.dev0` Any idea?

Thank you.

**Comment by LysandreJik** [comment]
Hey @geoffvdr, this is fixed on `main`; if you update your clone you shouldn't have this error anymore. Thanks!

**Comment by geoffvdr** [comment]
thank you @LysandreJik !

**Comment by LysandreJik** [comment]
Awesome! Let me close this as fixed.
