### ISSUE TITLE
examples/pytorch/language_modeling/requirements.txt needs to be updated

### ISSUE THREAD

**Issue by Patchwork53** [huggingface/transformers#30097]
### System Info

- `transformers` version: 4.40.0.dev0
- Platform: Linux-5.15.133+-x86_64-with-glibc2.31
- Python version: 3.10.13
- Huggingface_hub version: 0.21.4
- Safetensors version: 0.4.2
- Accelerate version: 0.28.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.1.2 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.2 (gpu)
- Jax version: 0.4.23
- JaxLib version: 0.4.23.dev20240116
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

# Observation
The requirement specifies datasets>=1.8.0 however, all scripts (such as `run_mlm.py`) pass the `token` argument to `load_dataset()`.  `token` was added in datasets version 2.14.0 (replacing `use_auth_token`). Tried simply replacing with  `datasets==2.14.0` or  `datasets>=2.14.0` but had dependency issues.

# Reproduction

1. Use an env with datasets<2.14.0
2. Pip install examples/pytorch/language-modeling/requirements.txt
3. Run script (from README.md)
```
python run_mlm.py \
    --model_name_or_path FacebookAI/roberta-base \
    --train_file path_to_train_file \
    --validation_file path_to_validation_file \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-mlm
```

# Traceback
```python
Traceback (most recent call last):
  File "/kaggle/working/run_mlm.py", line 704, in <module>
    main()
  File "/kaggle/working/run_mlm.py", line 371, in main
    raw_datasets = load_dataset(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 1664, in load_dataset
    builder_instance = load_dataset_builder(
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 1516, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 265, in __init__
    self.config, self.config_id = self._create_builder_config(
  File "/opt/conda/lib/python3.10/site-packages/datasets/builder.py", line 367, in _create_builder_config
    builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
TypeError: TextConfig.__init__() got an unexpected keyword argument 'token'
```

### Expected behavior

Train model normally.

**Comment by amyeroberts** [comment]
Hi @Patchwork53, thanks for raising this! Would you like to open a PR with this fix? This way you get the github contribution for spotting and recommending the fix
