### ISSUE TITLE
Remove `mps` workaround for `isin()`

### ISSUE THREAD

**Issue by pcuenca** [huggingface/transformers#30430]
### Feature request

Remove `mps` workaround for `isin()`

### Motivation

#30376 introduced a workaround for `isin()` on `mps` devices, because PyTorch does not support that op yet: https://github.com/pytorch/pytorch/issues/77764#issuecomment-2067838075.

Going forward, it'd be desirable to use the much more readable `isin()` version. This issue is meant to track PyTorch support of `isin()` on `mps` so we can remove the workaround and simplify the code.

### Your contribution

I can submit a PR when the op is eventually supported.

**Comment by amyeroberts** [comment]
Thanks for creating an issue @pcuenca so we can track!

**Comment by pcuenca** [comment]
Add `wip` label to exempt from stale bot.

**Comment by hvaara** [comment]
I believe support for `torch.isin` used in this way was added (xref pytorch/pytorch#154010) in Pytorch `v2.4.0`, which was released on 2024-07-24.

Which version(s) of PyTorch is transformers targeting support for with MPS as the backend? Is it based on time since release, certain amount of version bumps (eg n+2), etc? If you're targeting versions at or after `v2.4.0`, the workaround can be cleaned up (and I'm happy to send a PR if you'd like).

**Comment by hvaara** [comment]
Actually it looks like this was already cleaned up in #41307 (don't know why I didn't check the code before posting - sorry for the noise). I guess this issue can be closed.

I'm still curious which version of PyTorch you're targeting though. Eg., GQA was introduced in `v2.5.0`, so should be version guarded if you're aiming for PyTorch `>= v2.4.0`.

**Comment by pcuenca** [comment]
Taking a quick look, I see GQA being guarded [here](https://github.com/huggingface/transformers/blob/3c52b78ac083cd98e794105c7e822fdaeb6d37cd/src/transformers/integrations/sdpa_attention.py#L28) (when used directly) and [here](https://github.com/huggingface/transformers/blob/3c52b78ac083cd98e794105c7e822fdaeb6d37cd/src/transformers/utils/import_utils.py#L584) (used through the flex attention interface).

Are there any unguarded uses you found? Please, let us know!

I agree the original issue should be closed and I'm doing it now, please feel free to open a new one if necessary 🤗

**Comment by hvaara** [comment]
For example here

https://github.com/huggingface/transformers/blob/3c52b78ac083cd98e794105c7e822fdaeb6d37cd/src/transformers/integrations/sdpa_attention.py#L62

There are a couple other instances here and there you can find by searching for `enable_gqa`.

**Comment by pcuenca** [comment]
But https://github.com/huggingface/transformers/blob/3c52b78ac083cd98e794105c7e822fdaeb6d37cd/src/transformers/integrations/sdpa_attention.py#L58

**Comment by hvaara** [comment]
Oh yes, you're right of course. So sorry 😅 I just remembered seeing it when debugging a different issue in the text encoder for glm-image.

Actually, the issue isn't in transformers at all - it's originating in diffusers it seems. Running the MRE below on PyTorch `v2.4.0` produces the stack trace I attached.

I'll try to figure out exactly how this happens and open a new issue (in the correct repo 😅).

#### MRE

```python
import torch
import transformers
import diffusers
from diffusers.pipelines.glm_image import GlmImagePipeline
from datetime import datetime, timezone

print(f"{transformers.__version__=}")
print(f"{diffusers.__version__=}")
print(torch.utils.collect_env.get_pretty_env_info())

ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S.%f")[:-3] + "Z"
device = "mps"

pipe = GlmImagePipeline.from_pretrained("zai-org/GLM-Image", torch_dtype=torch.bfloat16, device_map=device)

prompt = "A beautifully designed modern food magazine style dessert recipe illustration, themed around a raspberry mousse cake. The overall layout is clean and bright, divided into four main areas: the top left features a bold black title 'Raspberry Mousse Cake Recipe Guide', with a soft-lit close-up photo of the finished cake on the right, showcasing a light pink cake adorned with fresh raspberries and mint leaves; the bottom left contains an ingredient list section, titled 'Ingredients' in a simple font, listing 'Flour 150g', 'Eggs 3', 'Sugar 120g', 'Raspberry puree 200g', 'Gelatin sheets 10g', 'Whipping cream 300ml', and 'Fresh raspberries', each accompanied by minimalist line icons (like a flour bag, eggs, sugar jar, etc.); the bottom right displays four equally sized step boxes, each containing high-definition macro photos and corresponding instructions, arranged from top to bottom as follows: Step 1 shows a whisk whipping white foam (with the instruction 'Whip egg whites to stiff peaks'), Step 2 shows a red-and-white mixture being folded with a spatula (with the instruction 'Gently fold in the puree and batter'), Step 3 shows pink liquid being poured into a round mold (with the instruction 'Pour into mold and chill for 4 hours'), Step 4 shows the finished cake decorated with raspberries and mint leaves (with the instruction 'Decorate with raspberries and mint'); a light brown information bar runs along the bottom edge, with icons on the left representing 'Preparation time: 30 minutes', 'Cooking time: 20 minutes', and 'Servings: 8'. The overall color scheme is dominated by creamy white and light pink, with a subtle paper texture in the background, featuring compact and orderly text and image layout with clear information hierarchy."

image = pipe(
    prompt=prompt,
    height=32 * 32,
    width=36 * 32,
    num_inference_steps=50,
    guidance_scale=1.5,
    generator=torch.Generator(device=device).manual_seed(42),
).images[0]

filename = f"output_glm-image_{ts}.png"
image.save(filename)
print(f"Saved {filename}.")
```

<details><summary>

#### Env info

</summary>

```
transformers.__version__='5.2.0.dev0'
diffusers.__version__='0.37.0.dev0'
PyTorch version: 2.4.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 26.3 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.6.3.2)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-26.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] numpy==2.4.2
[pip3] torch==2.4.0
[conda] numpy                     2.4.2                    pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
```

</details>

<details><summary>

#### Stack Trace

</summary>

```
Traceback (most recent call last):
  File "/Users/hvaara/dev/huggingface/transformers/broken.mps.py", line 33, in <module>
    image = pipe(
            ^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/pipelines/glm_image/pipeline_glm_image.py", line 969, in __call__
    noise_pred_cond = self.transformer(
                      ^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/transformers/transformer_glm_image.py", line 650, in forward
    hidden_states, encoder_hidden_states = block(
                                           ^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/transformers/transformer_glm_image.py", line 409, in forward
    attn_hidden_states, attn_encoder_hidden_states = self.attn1(
                                                     ^^^^^^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/miniforge3/envs/pt240/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/attention_processor.py", line 605, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/transformers/transformer_glm_image.py", line 327, in __call__
    hidden_states = dispatch_attention_fn(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/attention_dispatch.py", line 360, in dispatch_attention_fn
    return backend_fn(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/hvaara/dev/huggingface/diffusers/src/diffusers/models/attention_dispatch.py", line 2447, in _native_attention
    out = torch.nn.functional.scaled_dot_product_attention(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scaled_dot_product_attention() got an unexpected keyword argument 'enable_gqa'
```

</details>

**Comment by pcuenca** [comment]
No worries @hvaara, and thanks for the repro 🙌 cc @sayakpaul from the diffusers team for info, but please do open a new issue if you dig deeper 🤗
