### ISSUE TITLE
What should I do if I want to get a past dev version like v4.9.0.dev0

### ISSUE THREAD

**Issue by CharonsPluto** [huggingface/transformers#30496]
I tried to reproduce a project on GitHub, but encountered some difficulties. I attempted to compare the code of this project with the original transformers library. However, this project was forked from v4.9.0.dev0, and the current available versions cloned from GitHub do not include this dev version.

This is evidence suggesting that the code was forked from v4.9.0.dev0.
`# Will error if the minimal version of Transformers is not installed. Remove at your own risks.
check_min_version("4.9.0.dev0")`
I found this in examples/pytorch/summarization/run_summarization.py    line 58-59.

**Comment by amyeroberts** [comment]
Hi @CharonsPluto, thanks for opening an issue! 

This is more of a git and pypi question, than something specific to transformers. When we make a new release e.g. [v4.40.1](https://github.com/huggingface/transformers/releases/tag/v4.40.1), all of the commits on `main` are on the version `4.41.0.dev`. When we release the next stable minor version, they will all be included in 4.41.0 and receive the 4.41.0 tag. 

If the version listed is `v4.9.0.dev0` then this could have been from any commit between the 4.8 and 4.9 releases. All of the examples will have had the min version updated to 4.9.0.dev in the 4.8 release. I'd therefore suggest checking out from this version. 

> current available versions cloned from GitHub do not include this dev version.

Current available versions of what? If it's transformers you can clone the repo yourself and checkout to any point in its git history e.g. [to the v4.8 release](https://github.com/huggingface/transformers/releases/tag/v4.8.0).

**Comment by CharonsPluto** [comment]
> Hi @CharonsPluto, thanks for opening an issue!
> 
> This is more of a git and pypi question, than something specific to transformers. When we make a new release e.g. [v4.40.1](https://github.com/huggingface/transformers/releases/tag/v4.40.1), all of the commits on `main` are on the version `4.41.0.dev`. When we release the next stable minor version, they will all be included in 4.41.0 and receive the 4.41.0 tag.
> 
> If the version listed is `v4.9.0.dev0` then this could have been from any commit between the 4.8 and 4.9 releases. All of the examples will have had the min version updated to 4.9.0.dev in the 4.8 release. I'd therefore suggest checking out from this version.
> 
> > current available versions cloned from GitHub do not include this dev version.
> 
> Current available versions of what? If it's transformers you can clone the repo yourself and checkout to any point in its git history e.g. [to the v4.8 release](https://github.com/huggingface/transformers/releases/tag/v4.8.0).

Hi amyeroberts,thanks a lot for your reply!

The project which i tried to reproduce seems to forked transformers on June 23, 2021,the latest version before that day i can find in release is v4.7.0 which released on Jun 18 2021 and just the next day the author forked(Jun 24) version v4.8.0 and v4.8.1 released.But what i typed just now show that the project seems forked from v4.8-v4.9

The author uses a bash script to train and evaluate the model. Due to network restrictions on the server, I cannot fetch models and datasets from Hugging Face. I attempted to download the model and dataset to my local machine and then upload them to the server for use, but I'm unsure how to proceed. Here is a snippet of the bash code.
`python -u examples/pytorch/summarization/run_summarization.py \
    --dataset_name 'xsum' \
    --model_name_or_path 'facebook/bart-large' \
    ...`

I attempted to use` load_dataset `on my local machine and then save the dataset to disk using `dataset.save_to_disk`. After saving the dataset locally, I uploaded it to a folder named 'xsum' on the server. Then, I tried to modify the 'xsum' in "`--dataset_name 'xsum'`" in the script to the path of the 'xsum' folder on the server, but it didn't work.Here is the bug information:
`User
Traceback (most recent call last):
File "/home/u200110114/jupyterlab/unify-parameter-efficient-tuning-master/examples/pytorch/summarization/run_summarization.py", line 691, in <module>
main ()
File "/home/u200110114/jupyterlab/unify-parameter-efficient-tuning-master/examples/pytorch/summarization/run_summarization.py", line 328, in main
datasets = load dataset (data_args.dataset_name, data_args.dataset_config_name, cache_dir=model_args.cache_dir)
File "/home/u200110114/.conda/envs/python39/1ib/python3.9/site-packages/datasets/load.py", line 2556, in load dataset
builder instance = load dataset builder (
File "/home/u200110114/.conda/envs/python39/lib/python3.9/site-packages/datasets/load.py", line 2228, in load_dataset_builder
dataset module = dataset_module_factory(
File "/home/u200110114/.conda/envs/python39/lib/python3.9/site-packages/datasets/load.py", line 1879, in dataset_module_factory
raise el from None
File "/home/u200110114/.conda/envs/python39/1ib/python3.9/site-packages/datasets/load.py", line 1812, in dataset_module_factory
raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type (e) . name_})")
ConnectionError: Couldn't reach 'xsum' on the Hub (ConnectionError)`

Thank you in advance for your help.

**Comment by amyeroberts** [comment]
Hi @CharonsPluto, this is more of a question for our forums [forums](https://discuss.huggingface.co/). We try to reserve the github issues for feature requests and bug reports.

**Comment by CharonsPluto** [comment]
Get it .Thanks a lot for your answers
