### ISSUE TITLE
Cannot convert llama 3 model to hf

### ISSUE THREAD

**Issue by Bedoshady** [huggingface/transformers#30604]
### System Info

I have an intel based computer with 32 gb of ram

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I have downloaded llama 3 model from meta and have .pth file, I tried running convert_llama_weights_to_hf.py but I get `Fetching all parameters from the checkpoint at H:\Downloads\llama3-main\Meta-Llama-3-8B.
Loading the checkpoint in a Llama model.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 33/33 [00:04<00:00,  7.07it/s]
Saving in the Transformers format.
Traceback (most recent call last):
  File "H:\Downloads\transformers\src\transformers\models\llama\convert_llama_weights_to_hf.py", line 407, in <module>
    main()
  File "H:\Downloads\transformers\src\transformers\models\llama\convert_llama_weights_to_hf.py", line 396, in main
    write_model(
  File "H:\Downloads\transformers\src\transformers\models\llama\convert_llama_weights_to_hf.py", line 313, in write_model
    shutil.rmtree(tmp_model_path)
  File "H:\tools\MiniConda2\envs\tg\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "H:\tools\MiniConda2\envs\tg\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "H:\tools\MiniConda2\envs\tg\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'H:\\Downloads\\llama3-main\\Meta-Llama-3-8B\\tmp\\pytorch_model-1-of-33.bin'` what should I do?

### Expected behavior

The model should be converted to hf without errors

**Comment by VISWANATH78** [comment]
check on your permissions to your file . might work as it says Access is denied . use CHMOD and provide read and write access for the specif model path.

**Comment by Bedoshady** [comment]
I am running this on windows 10 using python in miniconda.
