### ISSUE TITLE
BART BartForSequenceClassification example

### ISSUE THREAD

**Issue by easonnie** [huggingface/transformers#3096]
# 🐛 Bug
I'm trying the run the code on the documentation.
https://huggingface.co/transformers/model_doc/bart.html#bartforsequenceclassification

```
from transformers import BartTokenizer, BartForSequenceClassification
import torch

tokenizer = BartTokenizer.from_pretrained('bart-large')
model = BartForSequenceClassification.from_pretrained('bart-large')
input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute",
add_special_tokens=True)).unsqueeze(0)  # Batch size 1
labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
outputs = model(input_ids, labels=labels)
loss, logits = outputs[:2]
```

output:
```
Traceback (most recent call last):
  File "/ssd-playpen/yixin1/projects/cleartheuncertainty/utest/utest_transformer/utest_bart.py", line 11, in <module>
    outputs = model(input_ids, labels=labels)
  File "/ssd-playpen/yixin1/projects/cleartheuncertainty/ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd-playpen/yixin1/projects/cleartheuncertainty/ENV/lib/python3.7/site-packages/transformers/modeling_bart.py", line 1327, in forward
    loss = F.cross_entropy(logits.view(-1, self.num_labels), labels.view(-1))
  File "/ssd-playpen/yixin1/projects/cleartheuncertainty/ENV/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'BartForSequenceClassification' object has no attribute 'num_labels'
```

I guess this should be a quick fix or so.

**Comment by sshleifer** [comment]
Thanks for reporting this!
