### ISSUE TITLE
Error loading Gemma-2-9b-it tokenizer

### ISSUE THREAD

**Issue by murthyrudra** [huggingface/transformers#32350]
### System Info

```
- `transformers` version: 4.43.2
- Platform: Linux-4.18.0-513.11.1.el8_9.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.9
- Huggingface_hub version: 0.24.2
- Safetensors version: 0.4.3
- Accelerate version: 0.30.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A100-SXM4-80GB
```

### Who can help?

@ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
My tokeizers version is `0.19.1`
When I load Gemma-2-9B model, I don't face any issues

```
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-9b")
```

However, when I try to load the instruction-tuned variant I am getting the following error
```
>>> tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-9b-it")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/conda/lm_eval_eleuther/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 833, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/conda/lm_eval_eleuther/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 687, in get_tokenizer_config
    result = json.load(reader)
             ^^^^^^^^^^^^^^^^^
  File "/user/conda/lm_eval_eleuther/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/user/conda/lm_eval_eleuther/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/conda/lm_eval_eleuther/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1758 column 1 (char 39618)
```

### Expected behavior

No error and the tokenizer loads successfully

**Comment by ArthurZucker** [comment]
Hey! I can't reproduce this, maybe a download issue?

**Comment by murthyrudra** [comment]
Hi, sorry seems to be the case. I tried it on a different machine and it's working. Thanks for the reply :)
