### ISSUE TITLE
Saving Phi 3 vision fails due to tensor sharing

### ISSUE THREAD

**Issue by EricLBuehler** [huggingface/transformers#32354]
Hello and thank you for the great work here!

We are trying to save a Phi 3 vision mode, but are running into some issues saving it as safetensors.

Due to a shared weight, saving unfortunately fails when using safetensors. I was wondering if there is a solution to de-tie the weight? I attempted to de-tie manually by copying the tensor, but that did not work (perhaps I did it incorrectly, as there is another reference?).

## Minimum reproducible example
```py
from transformers import AutoModelForCausalLM

model_id = "lamm-mit/Cephalo-Phi-3-vision-128k-4b-alpha"

model = AutoModelForCausalLM.from_pretrained(
    model_id, device_map="cuda", trust_remote_code=True, torch_dtype="auto"
)

model.save_pretrained("out", safe_serialization=True)
```

**Comment by nmoeller** [comment]
I am running in the same Problem, when i am using the Phi-3-Vision of Hugging Face. Our final goal currently is to convert a finetuned Phi3-Vision with LoRa to Onnx and inference it with the `onnxruntime-genai`.

Maybe some context how did i get here :

1. We trained an LoRa Adapater for Phi3-Vision
2. I tried to merge the Lora Adapter and save the Model with the adjusted LoRa Weights
3. I was always running in the Error posted below
4. I decided to remove the LoRa Adapter loading and only trying to save the Base Phi3-Vision and got the same error

The script to reproduce :

```
from transformers import AutoModelForCausalLM

model_id = "microsoft/Phi-3-vision-128k-instruct"

model = AutoModelForCausalLM.from_pretrained(
    model_id, device_map="cuda", trust_remote_code=True, torch_dtype="auto"
)

model.save_pretrained("out", safe_serialization=True)
```

The Error Message (i do not want to set safe_serialization=false)

```
Execution failed. User process 'Rank 0' exited with status code 1. Please check log file 'user_logs/std_log_process_0.txt' for error details. Error: Traceback (most recent call last):
  File "save_phi3_vision.py", line 9, in <module>
    model.save_pretrained("out", safe_serialization=True)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2546, in save_pretrained
    raise RuntimeError(
RuntimeError: The weights trying to be saved contained shared tensors [{'model.embed_tokens.weight', 'model.vision_embed_tokens.wte.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.
```

**Comment by ArthurZucker** [comment]
Hey! I am seeing `trust_remote_code=True` which means the code being use is potentially not well supported. 
Try cloning weights of the embed token in the `model.vision_embed_tokens.wte` manually, could help

**Comment by jjbuck** [comment]
I ran into this same thing with https://huggingface.co/microsoft/Phi-3.5-vision-instruct. Hope it's OK to resurrect this thread from September....


Setting `trust_remote_code=True` seems to be required in this case.

Here's the stack trace I'm seeing.

```
Traceback (most recent call last):
  File "/home/ubuntu/***/sft.py", line 100, in main
    trainer.train()
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 2122, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 2541, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 3000, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 3090, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 3719, in save_model
    self._save(output_dir)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/trainer.py", line 3823, in _save
    self.model.save_pretrained(
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 2958, in save_pretrained
    raise RuntimeError(
RuntimeError: The weights trying to be saved contained shared tensors [{'model.vision_embed_tokens.wte.weight', 'model.embed_tokens.weight'}] that are mismatching the transformers base configuration. Try saving using `safe_serialization=False` or remove this tensor sharing.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
 50%|███████████████████████████████████████████████████████████████████████████████                                                                               | 10/20 [00:57<00:57,  5.71s/it]
Traceback (most recent call last):
  File "/home/ubuntu/***/.venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/***/.venv/lib/python3.12/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/***/.venv/bin/python3', 'core/training/sft.py', 'training=users/jonabuck/test']' returned non-zero exit status 1.
```
