### ISSUE TITLE
Tutorial for using DeepSpeed's activation checkpointing instead of PyTorch's

### ISSUE THREAD

**Issue by huyiwen** [huggingface/transformers#32409]
### Feature request

Is there a tutorial for using DeepSpeed's activation checkpointing instead of PyTorch's?

I'm using `Trainer` with ZeRO integration to train my model. Here's my code:

```python
if training_args.deepspeed_gradient_checkpointing and training_args.deepspeed:
        from deepspeed.runtime.activation_checkpointing.checkpointing import checkpoint
        model._set_gradient_checkpointing(training_args.deepspeed_gradient_checkpointing, checkpoint)
```

```json
{
"activation_checkpointing": {
    "partition_activations": true,
    "cpu_checkpointing": true,
    "contiguous_memory_optimization": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
  }
}
```

```shell
torchrun --nproc_per_node=8 \
    --nnodes=${NNODES} \
    --node_rank=${NODE_RANK} \
    --master_addr=${MASTER_ADDR} \
    --master_port=${MASTER_PORT} \
    train.py \
    --deepspeed ${DEEPSPEED_CONFIG_PATH} \
    --gradient_checkpointing False
```

However, I got this:

```
def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.LongTensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: bool = False,
        use_cache: bool = False,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
        output_attentions = False

        bsz, q_len, _ = hidden_states.size()  # <---- this got error

        query_states = self.q_proj(hidden_states)
        key_states = self.k_proj(hidden_states)
        value_states = self.v_proj(hidden_states)
```

```
  File "modeling_xxx.py", line 518, in forward
    bsz, q_len, _ = hidden_states.size()
ValueError: not enough values to unpack (expected 3, got 2)
```

### Motivation

It seems there isn't such a tutorial available at the moment in either [deepspeed](https://deepspeed.readthedocs.io/en/latest/activation-checkpointing.html)'s tutorial or [huggingface](https://huggingface.co/docs/transformers/v4.43.3/en/deepspeed#activationgradient-checkpointing).

### Your contribution

Provide my results

**Comment by huyiwen** [comment]
```python
if training_args.deepspeed_gradient_checkpointing and training_args.deepspeed:
        from deepspeed.runtime.activation_checkpointing.checkpointing import configure
        configure(deepspeed_config=training_args.hf_deepspeed_config)
        from deepspeed.runtime.activation_checkpointing.checkpointing import checkpoint
        model._set_gradient_checkpointing(training_args.deepspeed_gradient_checkpointing, checkpoint)
```
After calling `configure`, I started the training loop. But I got a new error after two training steps:
```
  0%|          | 1/2709 [00:17<13:24:22, 17.82s/it]
  0%|          | 2/2709 [00:26<9:27:25, 12.58s/it] Traceback (most recent call last):
  File "train.py", line 395, in <module>
    train()
  File "train.py", line 389, in train
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File ".../site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File ".../site-packages/transformers/trainer.py", line 2356, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File ".../site-packages/transformers/trainer.py", line 2786, in _maybe_log_save_evaluate
    tr_loss_scalar = self._nested_gather(tr_loss).mean().item()
  File ".../site-packages/transformers/trainer.py", line 3995, in _nested_gather
    tensors = distributed_concat(tensors)
  File ".../site-packages/transformers/trainer_pt_utils.py", line 223, in distributed_concat
    dist.all_gather(output_tensors, tensor)
  File ".../site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File ".../site-packages/torch/distributed/distributed_c10d.py", line 2806, in all_gather
    work = default_pg.allgather([tensor_list], [tensor])
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
ncclInternalError: Internal check failed.
```

@stevhliu

**Comment by huyiwen** [comment]
```
Traceback (most recent call last):
  File "train.py", line 395, in <module>
    train()
  File "train.py", line 389, in train
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File ".../site-packages/transformers/trainer.py", line 1938, in train
    return inner_training_loop(
  File ".../site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File ".../site-packages/transformers/trainer.py", line 3318, in training_step
    loss = self.compute_loss(model, inputs)
  File ".../site-packages/transformers/trainer.py", line 3363, in compute_loss
    outputs = model(**inputs)
  File ".../site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File ".../site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File ".../site-packages/deepspeed/runtime/engine.py", line 1822, in forward
    loss = self.module(*inputs, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "model/modeling_miniyulan.py", line 1255, in forward
    outputs = self.model(
  File ".../site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "model/modeling_miniyulan.py", line 1057, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File ".../site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 985, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File ".../site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File ".../site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 562, in forward
    outputs = run_function(*inputs_cuda)
  File ".../site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "model/modeling_miniyulan.py", line 801, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File ".../site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File ".../site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "model/modeling_miniyulan.py", line 517, in forward
    bsz, q_len, _ = hidden_states.size()
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by ArthurZucker** [comment]
cc @muellerzr and @SunMarc

**Comment by hrushikesh198** [comment]
I am interested to try out partition_activations from deepspeed. Has anybody found a solution to use it with transformers?

**Comment by veritas9872** [comment]
Has anyone found a solution to this problem?

**Comment by qgallouedec** [comment]
Hey @huyiwen, sorry for the very slow reply here, we're catching up on the backlog. cc @hrushikesh198 @veritas9872, same answer.

This one isn't really a transformers issue: `partition_activations` is DeepSpeed's *tensor-model-parallel* feature. It slices every activation with `item.view(-1).narrow(0, start, numel // mp_size)`, and `mp_size` is only ever assigned from an `mpu` (`get_model_parallel_world_size()`).
You passed `mpu_=None`, so `mp_size` stays at its default of `1`: the "partition" degenerates into a flattened full copy that saves no memory and throws away the `[bsz, q_len, hidden]` shape your attention layer then tries to unpack, which is why you get `not enough values to unpack (expected 3, got 2)`
 Separately, `configure()` runs `_configure_defaults()` first, so calling `configure(mpu_=None)` without `deepspeed_config=` silently *resets* your `activation_checkpointing` JSON block instead of applying it. The Trainer + ZeRO integration doesn't use DeepSpeed model/pipeline parallelism, so there is no mpu to hand it; this has been a stated non-goal since #9606.

The part you actually want does work today: leave `partition_activations` off and use `checkpoint_in_cpu=True` on its own (DeepSpeed has a standalone CPU-offload branch in `CheckpointFunction.forward`).

More generally, #29648 has the supported recipes for selective checkpointing and activation offloading: `gradient_checkpointing_enable` forwards `gradient_checkpointing_kwargs` straight into `torch.utils.checkpoint.checkpoint` https://github.com/huggingface/transformers/blob/dfb1af66d4e8dd12c35a1147f88a4e833ae8bfe0/src/transformers/modeling_utils.py#L3187-L3204
so torch's own `context_fn=create_selective_checkpoint_contexts(policy_fn)` and `saved_tensors_hooks` cover both without any DeepSpeed-specific plumbing.
