### ISSUE TITLE
PR #31502 bumps up PyTorch requirement to >=2.4

### ISSUE THREAD

**Issue by gheinrich** [huggingface/transformers#33197]
### System Info

Hello, unless I am mistaken, PR #31502 bumps up the PyTorch version requirement to >=2.4. This requirement comes from [pytorch_utils.py](https://github.com/huggingface/transformers/blob/main/src/transformers/pytorch_utils.py#L27):

```
ALL_LAYERNORM_LAYERS = [nn.LayerNorm, nn.RMSNorm]
```

I think `torch.nn.RMSNorm` was introduced in PyTorch 2.4.

However the main [README](https://github.com/huggingface/transformers/blob/main/README.md) still states that:

> This repository is tested on Python 3.8+, Flax 0.4.1+, PyTorch 1.11+, and TensorFlow 2.6+.

cc @ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

With PyTorch<2.4:

```
python -c "from transformers import pytorch_utils"
Traceback (most recent call last):
  File "/opt/conda/envs/vila/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1659, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/opt/conda/envs/vila/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/conda/envs/vila/lib/python3.10/site-packages/transformers/pytorch_utils.py", line 27, in <module>
    ALL_LAYERNORM_LAYERS = [nn.LayerNorm, nn.RMSNorm]
AttributeError: module 'torch.nn' has no attribute 'RMSNorm'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/conda/envs/vila/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1647, in __getattr__
    value = self._get_module(name)
  File "/opt/conda/envs/vila/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1661, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pytorch_utils because of the following error (look up to see its traceback):
module 'torch.nn' has no attribute 'RMSNorm'
```

### Expected behavior

The documentation should be updated, or we should not have to use PyTorch>=2.4.

**Comment by vasqu** [comment]
#33177 fixes this, it will be reverted to the non-torch version of RMSNorm so that older versions are compatible.

**Comment by gheinrich** [comment]
I see, thank you.
