### ISSUE TITLE
BUG: AutoModel.from_pretrained(modelName)

### ISSUE THREAD

**Issue by NarwhalChen** [huggingface/transformers#34709]
### System Info

when using AutoModel.from_pretrained(modelName) it has error message Error: Could not locate file: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/onnx/model.onnx", but there is nothing in this url, and i think the bug is in file src/transformers/utils/hub.py, line 149 
HUGGINGFACE_CO_PREFIX = HUGGINGFACE_CO_RESOLVE_ENDPOINT + "/{model_id}/resolve/{revision}/{filename}"
![image](https://github.com/user-attachments/assets/166fed8a-b17a-4af1-bbc9-46ea63957df2)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

async function loadModel(modelName: string) {
    
        console.log(modelName);
    try {
        const tokenizer = await AutoTokenizer.from_pretrained(modelName);
        const model = await AutoModel.from_pretrained(modelName);
        
        console.log(model);
        console.log(tokenizer);
        return { model, tokenizer };
    } catch (error) {
        console.log(error);
        return null;
    }
}
and report 
try {
       8 |         const tokenizer = await AutoTokenizer.from_pretrained(modelName);
    >  9 |         const model = await AutoModel.from_pretrained(modelName);
         |                       ^
      10 |
      11 |         console.log(model);
      12 |         console.log(tokenizer);

      at getSession (node_modules/.pnpm/@huggingface+transformers@3.0.2/node_modules/@huggingface/transformers/dist/webpack:/@huggingface/transformers/src/models.js:178:1)
      at node_modules/.pnpm/@huggingface+transformers@3.0.2/node_modules/@huggingface/transformers/dist/webpack:/@huggingface/transformers/src/models.js:297:63
          at Array.map (<anonymous>)
      at constructSessions (node_modules/.pnpm/@huggingface+transformers@3.0.2/node_modules/@huggingface/transformers/dist/webpack:/@huggingface/transformers/src/models.js:296:1)
      at Function.from_pretrained (node_modules/.pnpm/@huggingface+transformers@3.0.2/node_modules/@huggingface/transformers/dist/webpack:/@huggingface/transformers/src/models.js:920:1)
      at Function.from_pretrained (node_modules/.pnpm/@huggingface+transformers@3.0.2/node_modules/@huggingface/transformers/dist/webpack:/@huggingface/transformers/src/models.js:6034:1)
      at loadModel (src/model/model.service.ts:9:23)
      at loadAllChatsModels (src/model/model.service.ts:28:31)
      at Object.<anonymous> (__tests__/loadAllChatsModels.spec.ts:23:9)

  console.log
    Error: Could not locate file: "https://huggingface.co/google-bert/bert-base-uncased/resolve/main/onnx/model.onnx".

### Expected behavior

expected to pull model in true url

**Comment by LysandreJik** [comment]
Hey @NarwhalChen, do you mind sharing a fully reproducible code snippet that runs into this issue? Also this seems to run in node rather than python?

**Comment by LysandreJik** [comment]
cc @xenova, this seems linked to transformers.js rather than transformers
