### ISSUE TITLE
Bug for logger.warning_once

### ISSUE THREAD

**Issue by Snowdar** [huggingface/transformers#34985]
https://github.com/huggingface/transformers/blob/5523e38b553ff6c46b04d2376870fcd842feeecc/src/transformers/generation/configuration_utils.py#L765

The UserWarning could not be loggered by logging and here is a simple test:
```
>>> from transformers.generation.configuration_utils import logger
>>> logger.warning_once('error', UserWarning)
--- Logging error ---
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/test/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniconda3/envs/test/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/home/testminiconda3/envs/test/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/test/miniconda3/envs/test/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "<stdin>", line 1, in <module>
  File "/home/test/miniconda3/envs/test/lib/python3.11/site-packages/transformers/utils/logging.py", line 328, in warning_once
    self.warning(*args, **kwargs)
Message: 'error'
Arguments: (<class 'UserWarning'>,)
```

**Comment by Rocketknight1** [comment]
Seems legit, so thank you for the bug report! Would you be willing to open a PR to fix that line?

**Comment by secrettoad** [comment]
Hi @Rocketknight1 , I took a look at this and it seems like a usage error. 

`msg % self.args` is always going to fail if `self.args` doesn't have the same number of elements as there are format specifiers in the the first argument (in this case 0, not equal to the one argument supplied - the class `UserWarning`).

If I am misunderstanding, can you please let me know what you would expect the log/warning to look like given @Snowdar's inputs? Then I will adjust my test case and submit a fix/PR.

**Comment by secrettoad** [comment]
Okay great. Thank you.
