### ISSUE TITLE
No use `no_sync` context manager when gradient accumulation w/ deepspeed's zero stage 2 or 3 via `accelerate`

### ISSUE THREAD

**Issue by nzw0301** [huggingface/transformers#34984]
### Feature request

`trainer.train` with deepspeed stage 2 or 3 via `accelerate` and gradient accumulation does not work as I expected. I suspect this is because deepspeed 0.16.0 introduces `no_sync` context manager https://github.com/microsoft/DeepSpeed/pull/6675.

For example, the error looks like 

```
Traceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 90, in main
    trainer.train()
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 2123, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/transformers/trainer.py", line 2480, in _inner_training_loop
    with context():
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/accelerate/accelerator.py", line 973, in no_sync
    with context():
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/deepspeed/runtime/engine.py", line 1995, in no_sync
    assert not self.zero_optimization_partition_gradients(), \
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: no_sync context manager is incompatible with gradient partitioning logic of ZeRO stage 3
```

### Motivation

In my understanding, `trainer.train()` with deepspeed via HF `accelerate` and gradient accumulation uses own forward computation implementation rather than `accelerate.accumulate` defined at 

https://github.com/huggingface/transformers/blob/052e652d6d53c2b26ffde87e039b723949a53493/src/transformers/trainer.py#L2474C75-L2482

So `no_sync` is always used. Even we give

```python
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': {'sync_each_batch': True}, 'use_configured_state': False}
``` 
to `TrainingArguments` to use a feature introduced by https://github.com/huggingface/transformers/issues/29425.

### Your contribution

As suggested https://github.com/huggingface/transformers/issues/29425#issuecomment-2505015569, adding some warning to config might be helpful, but ideally addressing this feature is much nicer but I do not know the right approach.

**Comment by nzw0301** [comment]
I'm not sure but https://github.com/huggingface/transformers/pull/35157 might fix the issue?

**Comment by SunMarc** [comment]
Let us know if this indeed fixes your issue !

**Comment by Superskyyy** [comment]
Nope, 4.48.0 still have the exact same problem.

**Comment by nzw0301** [comment]
By updating transformers and deepspeed, the stage 3 works as I expected now.
