### ISSUE TITLE
Can't evaluate official TensorFlow NER model

### ISSUE THREAD

**Issue by TarasPriadka** [huggingface/transformers#3641]
# 🐛 Bug: Can't evaluate official TensorFlow NER model

## Information

Model I am using (Bert, XLNet ...): I am using bert-base-multilingual-cased

Language I am using the model on (English, Chinese ...): German

The problem arises when using:
* [X] the official example scripts: I was using the official script for the NER model training.
at this link https://github.com/huggingface/transformers/tree/master/examples/ner
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: I was training an NER model
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Follow the steps to download the data and run the model for TensorFlow
2. Training the model for 3 epochs
3. On evaluation, the model will fail
4. Then I tried to explicitly call the evaluation of the model. Using this:
python3 run_tf_ner.py --data_dir ~/data --model_type bert --labels ~/data/labels.txt --model_name_or_path $BERT_MODEL --output_dir $OUTPUT_DIR --max_seq_length  $MAX_LENGTH --num_train_epochs $NUM_EPOCHS --per_device_train_batch_size $BATCH_SIZE --save_steps $SAVE_STEPS --seed $SEED --do_eval

Here is what I see when calling the evaluation step:

```I0405 20:15:11.758301 140712645343040 modeling_tf_utils.py:388] loading weights file germeval-model/tf_model.h5
2020-04-05 20:15:12.024952: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-05 20:15:12.031397: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-04-05 20:15:12.032399: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ae8970 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-05 20:15:12.032438: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
I0405 20:15:15.697083 140712645343040 run_tf_ner.py:418] Loading features from cached file /home/taras/data/cached_dev_bert-base-multilingual-cased_128.tf_record
Traceback (most recent call last):
  File "run_tf_ner.py", line 641, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "run_tf_ner.py", line 576, in main
    args, strategy, model, tokenizer, labels, pad_token_label_id, mode="dev"
  File "run_tf_ner.py", line 314, in evaluate
    eval_iterator = progress_bar(eval_dataset, total=num_eval_steps, parent=master, display=args["n_device"] > 1)
  File "/home/taras/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py", line 226, in __init__
    super().__init__(gen, total, display, leave, parent, master)
  File "/home/taras/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py", line 24, in __init__
    parent.add_child(self)
  File "/home/taras/.local/lib/python3.7/site-packages/fastprogress/fastprogress.py", line 264, in add_child
    self.child.prefix = f'Epoch {self.main_bar.last_v+1}/{self.main_bar.total} :'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

## Expected behavior

Train an NER model and be able to evaluate and predict using the trained weights.

## Environment info
- `transformers` version: 2.7.0
- Platform: Linux-4.19.0-8-cloud-amd64-x86_64-with-debian-10.3
- Python version: 3.7.3
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.2.0-rc2 (False)
- Using GPU in script?: Yes, Tesla K80
- Using distributed or parallel set-up in script?: No

**Comment by TarasPriadka** [comment]
Another comment, I have looked at the cache that the model outputs, and it has a bunch of question marks for all of the cache files(train,dev,test). This leads me thinking that I might be doing something wrong. If someone knows where I might have made a mistake, please let me know.

**Comment by apcode** [comment]
This has been fixed in this PR https://github.com/fastai/fastprogress/pull/59
You will have to update fastprogress to the latest build on master for it to work.

**Comment by TarasPriadka** [comment]
Thank you! I will check if it got fixed for me and close the issue.

**Comment by TarasPriadka** [comment]
@apcode Thanks it worked wonderful! Closing the issue.
