### ISSUE TITLE
run_glue.py example doesn't work for distilbert models

### ISSUE THREAD

**Issue by ereday** [huggingface/transformers#3810]
# 🐛 Bug

## Information
Hi all, 

I am succesfully able to run the run_glue.py example with BERT, XLNet and other architectures. However, when I try distilbert I got the following error:
```

Traceback (most recent call last):
  File "run_glue.py", line 562, in <module>
    main()
  File "run_glue.py", line 510, in main
    train_dataset = load_and_cache_examples(args, args.task_name, tokenizer, evaluate=False)
  File "run_glue.py", line 373, in load_and_cache_examples
    all_token_type_ids = torch.tensor([f.token_type_ids for f in features], dtype=torch.long)
TypeError: an integer is required (got type NoneType)
```

Model I am using (Bert, XLNet ...):
distilbert (distilbert-base-cased)
Language I am using the model on (English, Chinese ...):
English
The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: GLUE/SST-2
* [ ] my own task or dataset: (give details below)

## To reproduce

```
export GLUE_DIR=./glue/glue_data
export TASK_NAME=SST-2
CUDA_VISIBLE_DEVICES=2,3 python run_glue.py \
    --model_type DistilBERT \
    --model_name_or_path distilbert-base-cased \
    --task_name $TASK_NAME \
    --do_train \
    --do_eval \
    --data_dir $GLUE_DIR/$TASK_NAME \
    --max_seq_length 128 \
    --per_gpu_train_batch_size 32 \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --output_dir ./output/$TASK_NAME/
```

## Environment info

```
     - `transformers` version: 2.8.0
- Platform: Linux-5.5.15-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
- Python version: 3.6.5
- PyTorch version (GPU?): 1.4.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO
```

**Comment by julien-c** [comment]
Hi @ereday could you please try from the `trainer` branch described in PR #3800?
