### ISSUE TITLE
Can't install transformers in conda environment

### ISSUE THREAD

**Issue by chen-bowen** [huggingface/transformers#3829]
# 🐛 Bug

I tried to install transformers into a conda environment

```
pip install transformers
Collecting transformers
  Using cached transformers-2.8.0-py3-none-any.whl (563 kB)
Collecting tokenizers==0.5.2
  Downloading tokenizers-0.5.2-cp38-cp38-macosx_10_15_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.6 MB/s 
Collecting tqdm>=4.27
  Downloading tqdm-4.45.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 23.6 MB/s 
Collecting filelock
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting regex!=2019.12.17
  Using cached regex-2020.4.4.tar.gz (695 kB)
Collecting boto3
  Using cached boto3-1.12.39-py2.py3-none-any.whl (128 kB)
Requirement already satisfied: numpy in ./Anaconda/anaconda3/envs/nlp/lib/python3.8/site-packages (from transformers) (1.18.2)
Collecting sentencepiece
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/chen_bowen/Anaconda/anaconda3/envs/nlp/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lz/65hfhw790_z85w_09kvvm37r0000gn/T/pip-install-lezphia4/sentencepiece/setup.py'"'"'; __file__='"'"'/private/var/folders/lz/65hfhw790_z85w_09kvvm37r0000gn/T/pip-install-lezphia4/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lz/65hfhw790_z85w_09kvvm37r0000gn/T/pip-install-lezphia4/sentencepiece/pip-egg-info
         cwd: /private/var/folders/lz/65hfhw790_z85w_09kvvm37r0000gn/T/pip-install-lezphia4/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lz/65hfhw790_z85w_09kvvm37r0000gn/T/pip-install-lezphia4/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/Users/chen_bowen/Anaconda/anaconda3/envs/nlp/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```



python version: Python 3.8.2
OS: Mac OSX 10.15.3
Anaconda version: conda 4.8.0

**Comment by ck37** [comment]
Looking at the error message, you seem to be running into an error with the sentencepiece package, not transformers.

I looked at the sentencepiece GitHub repo and there is an open issue on this here:
https://github.com/google/sentencepiece/issues/452

**Comment by nateraw** [comment]
Looks like this issue can be closed now. @chen-bowen can you confirm?

**Comment by Adhundi7** [comment]
This happened to me while installing Transformers. Well, as above this is an open issue with sentencepiece. Follow this link to install sentencepiece. [https://github.com/google/sentencepiece/issues/452#issuecomment-717518978](url)

After, I did the usual _pip install transformers_. Was able to get it set and running.
