### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for BertForTokenClassification

### ISSUE THREAD

**Issue by pz325** [huggingface/transformers#3956]
Since about 1600 BST, 24 Apr 2020, loading ner pipeline gives RuntimeError:
```
from transformers import pipeline
nlp = pipeline("ner", ignore_labels=[])
```

> Traceback (most recent call last):
  File "test.py", line 2, in <module>
    nlp = pipeline("ner", ignore_labels=[])
  File "/Users/xxx/Github/xxx/xxx/.venv/lib/python3.6/site-packages/transformers/pipelines.py", line 1091, in pipeline
    model = model_class.from_pretrained(model, config=config, **model_kwargs)
  File "/Users/xxx/Github/xxx/xxx/.venv/lib/python3.6/site-packages/transformers/modeling_auto.py", line 1086, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/Users/xxx/Github/xxx/xxx/.venv/lib/python3.6/site-packages/transformers/modeling_utils.py", line 558, in from_pretrained
    model.__class__.__name__, "\n\t".join(error_msgs)
RuntimeError: Error(s) in loading state_dict for BertForTokenClassification:
        size mismatch for classifier.weight: copying a param with shape torch.Size([9, 1024]) from checkpoint, the shape in current model is torch.Size([2, 1024]).
        size mismatch for classifier.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([2]).

- `transformers` version: 2.5.1
- Platform: macos 10.14.6
- Python version:  3.6.5
- PyTorch version (GPU?): 
- Tensorflow version (GPU?): 2.0.0
- Using GPU in script?: 
- Using distributed or parallel set-up in script?:

**Comment by pz325** [comment]
An update: after upgrading to transformers 2.8.0, the reported issue is gone. 

Nevertheless, could you share an explanation please?
