### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'abs' when run example/run_bertology.py

### ISSUE THREAD

**Issue by ThomasSYT** [huggingface/transformers#4103]
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...):
Bert
Language I am using the model on (English, Chinese ...):
English
The problem arises when using:
* [ ] the official example scripts: (give details below)
example/run_bertology.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
GLUE mnli

## To reproduce

export TASK_NAME=mnli
python ./run_bertology.py     --data_dir $GLUE_DIR/$TASK_NAME     
                              --model_name bert-base-uncased     
                              --task_name $TASK_NAME     
                              --max_seq_length 128     
                              --output_dir ./tmp/$TASK_NAME/     
                              --try_masking 

After 2 Iterations:
Traceback (most recent call last):
  File "run_bertology.py", line 427, in <module>
    main()
  File "run_bertology.py", line 422, in main
    head_mask = mask_heads(args, model, eval_dataloader)
  File "run_bertology.py", line 180, in mask_heads
    args, model, eval_dataloader, compute_entropy=False, head_mask=new_head_mask
  File "run_bertology.py", line 105, in compute_heads_importance
    head_importance += head_mask.grad.abs().detach()
AttributeError: 'NoneType' object has no attribute 'abs'

I printed the 'head_mask' when the error occurs:
head_mask: tensor([[1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1.],
        [1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.]], device='cuda:0',
       grad_fn=<ViewBackward>)

## Expected behavior

At the 3 positions of tensor, it should be "requires_grad=True".
head_mask: tensor([[1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.]], device='cuda:0',
       requires_grad=True)

## Environment info

     
- `transformers` version:2.8.0
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):1.15
- Using GPU in script?:yes
- Using distributed or parallel set-up in script?:

**Comment by bing0037** [comment]
I also have this error, anyone has the solution?
