### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 229888: invalid start byte

### ISSUE THREAD

**Issue by codehunk628** [huggingface/transformers#4254]
os : google colab
from transformers import *
tokenizer = AutoTokenizer.from_pretrained('https://s3-us-west-2.amazonaws.com/ai2-s2-research/scibert/huggingface_pytorch/scibert_scivocab_uncased.tar')
![SCI_BERT](https://user-images.githubusercontent.com/51091425/81477029-d94ddc00-9232-11ea-90ca-827a0e0ecc80.PNG)

**Comment by BramVanroy** [comment]
I don't think you can load .tars directly. Simply use the name as described in [the model page](https://huggingface.co/allenai/scibert_scivocab_uncased), and it should work.

```python
tokenizer = AutoTokenizer.from_pretrained("allenai/scibert_scivocab_uncased")
```

**Comment by codehunk628** [comment]
Thank You @BramVanroy  it solved the issue. But Now, I am facing another issue.
Runtime Error Size mismatch.
Actually I am trying to retrain the snli_roberta model with sci bert embedding .
I have already modified the config file under training_config folder for nli roberta.
ERROR LOG :
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Beginning training.
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Epoch 0/9
2020-05-10 10:45:14,020 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 5493.272
2020-05-10 10:45:14,128 - INFO - allennlp.training.trainer - GPU 0 memory usage MB: 10
2020-05-10 10:45:14,130 - INFO - allennlp.training.trainer - Training
  0%|          | 0/17168 [00:00<?, ?it/s]2020-05-10 10:45:14,131 - INFO - allennlp.data.samplers.bucket_batch_sampler - No sorting keys given; trying to guess a good one
2020-05-10 10:45:14,152 - INFO - allennlp.data.samplers.bucket_batch_sampler - Using ['tokens'] as the sorting keys
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 144, in train_model_from_args
    dry_run=args.dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 203, in train_model_from_file
    dry_run=dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 266, in train_model
    dry_run=dry_run,
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 463, in _train_worker
    metrics = train_loop.run()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/commands/train.py", line 525, in run
    return self.trainer.train()
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 732, in train
    train_metrics = self._train_epoch(epoch)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 500, in _train_epoch
    batch_outputs = self.batch_outputs(batch, for_training=True)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/training/trainer.py", line 406, in batch_outputs
    output_dict = self._pytorch_model(**batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/models/basic_classifier.py", line 133, in forward
    embedded_text = self._feedforward(embedded_text)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/Practice-Notebooks/Modl/allennlp/allennlp/modules/feedforward.py", line 107, in forward
    output = dropout(activation(layer(output)))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [32 x 768], m2: [1024 x 1024] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:41
  0%|          | 0/17168 [00:36<?, ?it/s]

**Comment by codehunk628** [comment]
Thank You @BramVanroy .
Its working.
