### ISSUE TITLE
Can't set attribute 'device'

### ISSUE THREAD

**Issue by nmc1998** [huggingface/transformers#4330]
I'm BERT finetunning, came across this problem
Here is my config, i'm running on 3rd GPU:
```json
BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "device": "cuda:3",
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_hidden_states": true,
  "output_past": true,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "type_vocab_size": 2,
  "use_pooler": true,
  "vocab_size": 105879,
  "weight_class": [
    1,
    1
  ]
}
```
and here is the output error in terminal:
```
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model = BERTQa.from_pretrained(args.folder_model, config=config)
  File "/home/dle/anaconda3/envs/phobert/lib/python3.7/site-packages/transformers/modeling_utils.py", line 622, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/dstore/home/dle/phobert/QA_PhoBERT/ZaloBert.py", line 10, in __init__
    self.device = 'cuda:3'
  File "/home/dle/anaconda3/envs/phobert/lib/python3.7/site-packages/torch/nn/modules/module.py", line 638, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
```

**Comment by Winsonguo** [comment]
I met the same issue, have you fixed?  Thanks.
