### ISSUE TITLE
Cannot import transformers due to issue with signal.py (SIGKILL)

### ISSUE THREAD

**Issue by scottleith** [huggingface/transformers#5003]
# 🐛 Bug

Can't import transformers, get a problem with signal.py. I see that an issue was recently fixed... should I install a nightly build, or...?

>>> import transformers
2020-06-15 05:40:54.098560: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\15194\anaconda3\envs\ai_env\lib\site-packages\transformers\__init__.py", line 371, in <module>
    from .benchmark import PyTorchBenchmark, PyTorchBenchmarkArguments
  File "C:\Users\15194\anaconda3\envs\ai_env\lib\site-packages\transformers\benchmark\__init__.py", line 10, in <module>
    from .benchmark import PyTorchBenchmark
  File "C:\Users\15194\anaconda3\envs\ai_env\lib\site-packages\transformers\benchmark\benchmark.py", line 32, in <module>
    from .benchmark_utils import Benchmark, Memory, measure_peak_memory_cpu, start_memory_tracing, stop_memory_tracing
  File "C:\Users\15194\anaconda3\envs\ai_env\lib\site-packages\transformers\benchmark\benchmark_utils.py", line 19, in <module>
    from signal import SIGKILL
**ImportError: cannot import name 'SIGKILL' from 'signal' (C:\Users\15194\anaconda3\envs\ai_env\lib\signal.py)**

## Expected behavior

The package to import.

## Environment info
- `transformers` version: 2.11
- Platform: Windows 10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.5.0, GPU = yes ( torch.cuda.is_available == True).
- Tensorflow version (GPU?): 2.2.0; GPU = yes.
- Using GPU in script?: No.
- Using distributed or parallel set-up in script?: No.

**Comment by scottleith** [comment]
Just had to reinstall. I installed pytorch AFTER transformers, and I cloned the transformers repository. Just uninstalled and reinstalled with pip install transformers and the issue went away.
