### ISSUE TITLE
The correct way to save and load pretrained MarianTokenizer?

### ISSUE THREAD

**Issue by erikchwang** [huggingface/transformers#5037]
I want to save a pretrained MarianTokenizer to a local directory ("my_dir") and then load it:
> import transformers
> transformers.AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-de").save_pretrained("my_dir")
> tokenizer = transformers.AutoTokenizer.from_pretrained("my_dir")

But the above code failed: 

> Traceback (most recent call last):
>   File "/Users/anaconda/lib/python3.6/site-packages/transformers/configuration_utils.py", line 239, in get_config_dict
>     local_files_only=local_files_only,
>   File "/Users/anaconda/lib/python3.6/site-packages/transformers/file_utils.py", line 267, in cached_path
>     raise EnvironmentError("file {} not found".format(url_or_filename))
> OSError: file my_dir/config.json not found
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "/Users/anaconda/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 195, in from_pretrained
>     config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
>   File "/Users/anaconda/lib/python3.6/site-packages/transformers/configuration_auto.py", line 196, in from_pretrained
>     config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
>   File "/Users/anaconda/lib/python3.6/site-packages/transformers/configuration_utils.py", line 252, in get_config_dict
>     raise EnvironmentError(msg)
> OSError: Can't load config for 'my_dir'. Make sure that:
> - 'my_dir' is a correct model identifier listed on 'https://huggingface.co/models'
> - or 'my_dir' is the correct path to a directory containing a config.json file
>

**Comment by erikchwang** [comment]
#4371
