### ISSUE TITLE
Error when loading Flaubert model 

### ISSUE THREAD

**Issue by saharghannay** [huggingface/transformers#5058]
# 🐛 Bug

## Information
I am trying to run the  example run_ner.pl using the Flaubert model. 
But I got this error: 

Traceback (most recent call last):
  File "/py37/lib/python3.7/site-packages/torch/serialization.py", line 191, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/py37/lib/python3.7/site-packages/transformers/modeling_utils.py", line 516, in from_pretrained
    state_dict = torch.load(resolved_archive_file, map_location="cpu")
  File "/py37/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/py37/lib/python3.7/site-packages/torch/serialization.py", line 549, in _load
    _check_seekable(f)
  File "/py37/lib/python3.7/site-packages/torch/serialization.py", line 194, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/py37/lib/python3.7/site-packages/torch/serialization.py", line 187, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/py37/lib/python3.7/site-packages/transformers/modeling_auto.py", line 1098, in from_pretrained
    return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
  File "/py37/lib/python3.7/site-packages/transformers/modeling_utils.py", line 519, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 

I got an other error when I added  from_tf=True. 

Do you have idea how can I solve this problem.

**Comment by LysandreJik** [comment]
Hi! Could you show what command you used to launch the script?

**Comment by saharghannay** [comment]
I was runing the token classification example : https://github.com/huggingface/transformers/blob/master/examples/token-classification/run.sh with flaubert-large-cased as model name. 

I tried to  use the downloaded  model from https://huggingface.co/flaubert models, but after 100 epochs the results are very bad, the model did not learn any thing. 
I Don't  understand what is the problem with  flaubert-large-cased model. 
Note that flaubert-base-cased model give  good results on NER taks.
