### ISSUE TITLE
BertForPreTraining and BertModel when loading TF checkpoints

### ISSUE THREAD

**Issue by jungwhank** [huggingface/transformers#5335]
Hello, 
I want to load tensorflow checkpoints and when I run code below

```python
config = BertConfig.from_json_file('./bert_config.json')
config.output_hidden_states = True
bert_model = BertForPreTraining.from_pretrained('./model.ckpt', from_tf=True, config=config)
......
self.bert = bert_model
.......
bert_seq_out, _ = self.bert(input_ids, token_type_ids=segment_ids, attention_mask=input_mask,
output_hidden_states=False)

```

got error like this

```
Traceback (most recent call last):
  File "train_tf.py", line 738, in <module>
    neg_log_likelihood = model.neg_log_likelihood(input_ids, segment_ids, input_mask, label_ids)
  File "train_tf.py", line 605, in neg_log_likelihood
    bert_feats = self._get_bert_features(input_ids, segment_ids, input_mask)
  File "train_tf.py", line 542, in _get_bert_features
    bert_seq_out, _ = self.bert(input_ids, token_type_ids=segment_ids, attention_mask=input_mask, output_hidden_states=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'output_hidden_states'
```

I think it is because I use `BertForPreTraining` instead of `BertModel`,
but when I use `BertModel`, I got error like below

```
/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    592                 return modules[name]
    593         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 594             type(self).__name__, name))
    595 
    596     def __setattr__(self, name, value):

AttributeError: 'BertModel' object has no attribute 'bias'
```

How can I fix and load TF checkpoint correctly?
any help will be appreciated

**Comment by LysandreJik** [comment]
Hi! What is your library version? The `output_hidden_states` as argument to the call method was only added in the v3.0.0 version, which was released this morning.
