### ISSUE TITLE
How to download Pre-trained T5 model?

### ISSUE THREAD

**Issue by deepankar27** [huggingface/transformers#5712]
Hi,

I tried looking for ways to download & use T5-small pre-trained model but didn't get any API mentioned in documentation to download it. Though I found links but don't know will it work if I pass the path of the model?

Thanks in advance..

**Comment by patrickvonplaten** [comment]
```python 
from transformers import T5ForConditionalGeneration

t5 = T5ForConditionalGeneration.from_pretrained("t5-small")
```

does not work?

**Comment by deepankar27** [comment]
@patrickvonplaten Thanks for the pointer, I tried & getting this:

```
>>> from transformers import T5ForConditionalGeneration
>>> t5 = T5ForConditionalGeneration.from_pretrained("t5-small")
Traceback (most recent call last):
  File "/root/anaconda3/envs/docsearch/lib/python3.7/site-packages/transformers/configuration_utils.py", line 242, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/docsearch/lib/python3.7/site-packages/transformers/modeling_utils.py", line 604, in from_pretrained
    **kwargs,
  File "/root/anaconda3/envs/docsearch/lib/python3.7/site-packages/transformers/configuration_utils.py", line 200, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/docsearch/lib/python3.7/site-packages/transformers/configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 't5-small'. Make sure that:

- 't5-small' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-small' is the correct path to a directory containing a config.json file
```

I am new on huggingface API. I am going to download it & give path of the model. Let's see how it works... But let me know if you can give me some suggestions.

**Comment by LysandreJik** [comment]
Hi @deepankar27, do you mind specifying which `transformers` version you're using?

**Comment by deepankar27** [comment]
@LysandreJik Sorry for the late reply, I figured it out, issue was with my config files. Thanks... :)

**Comment by rukshar69** [comment]
Where in the computer memory is the T5-small model being downloaded?
