### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by marton-avrios** [huggingface/transformers#5739]
Trying to run seq2seq example scripts with multiple gpus and wandb logging and I get
```
Traceback (most recent call last):
  File "/home/martongyorgy/projects/tmp/transformers/examples/seq2seq/finetune.py", line 364, in <module>
	xsum_rouge.json
  File "/home/martongyorgy/projects/tmp/transformers/examples/seq2seq/finetune.py", line 342, in main
    logger=logger,
  File "/home/martongyorgy/projects/tmp/transformers/examples/lightning_base.py", line 330, in generic_train
    trainer.fit(model)
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 891, in fit
    self.ddp_train(task, model)
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 530, in ddp_train
    self.run_pretrain_routine(model)
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1046, in run_pretrain_routine
    self.configure_checkpoint_callback()
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/site-packages/pytorch_lightning/trainer/callback_config.py", line 60, in configure_checkpoint_callback
    "checkpoints"
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/martongyorgy/miniconda3/envs/transformers/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

To reproduce follow the instructions in the seq2seq example Readme to download XSUM then run
```
export PYTHONPATH="../":"${PYTHONPATH}"

python finetune.py \
    --learning_rate=3e-5 \
    --fp16 \
    --gpus 2 \
    --do_train \
    --n_val 1000 \
    --val_check_interval 0.1 \
    --data_dir xsum \
    --output_dir xsum_frozen_embs \
    --model_name_or_path t5-small \
    --train_batch_size 16 --eval_batch_size 16 --freeze_embeds --freeze_encoder \
    --num_train_epochs 6 \
    --max_target_length=60 --val_max_target_length=60 --test_max_target_length=100 \
    --logger wandb
```

Happens in pytorch-lightning 0.8.1, fixed in 0.8.4. But there is another problem in  0.8.4, see #5584

**Comment by sshleifer** [comment]
Hopefully fixed by https://github.com/huggingface/transformers/pull/5361
