### ISSUE TITLE
Benchmark: traceback does not describe real problem

### ISSUE THREAD

**Issue by sshleifer** [huggingface/transformers#5892]
To reproduce:
- execute a command that results in 'N/A'
- long traceback describes tuple unpacking. The real problem is what caused the N/A and is far above in a small logger.error statement.

Example Command:
```bash
python examples/benchmarking/run_benchmark.py --models facebook/mbart-large-en-ro
```

Traceback:
```python
1 / 1
ERROR:transformers.benchmark.benchmark_utils:<class 'transformers.configuration_bart.MBartConfig'>
<class 'transformers.configuration_bart.MBartConfig'>
Traceback (most recent call last):
  File "examples/benchmarking/run_benchmark.py", line 29, in <module>
    main()
  File "examples/benchmarking/run_benchmark.py", line 25, in main
    benchmark.run()
  File "/home/shleifer/transformers_fork/src/transformers/benchmark/benchmark_utils.py", line 665, in run
    memory, inference_summary = self.inference_memory(model_name, batch_size, sequence_length)
ValueError: too many values to unpack (expected 2)
```

This may not be worth a fix, and probably won't be fixed soon, but posting for others who might run into this or have ideas for a fix.

**Comment by sshleifer** [comment]
Working command after MbartConfig change:
```bash
export d=mbart_benchmark_data
python examples/benchmarking/run_benchmark.py --models facebook/mbart-large-en-ro \
  --log_filename $d/log.txt \
  --inference_memory_csv \ 
  $d/inference_memory.csv \ 
  --train_memory_csv $d/train_memory.csv \
  --train_time_csv $d/train_time.csv \
  --inference_time_csv $d/inference_time.csv \
  --fp16 --log_print --training  --save_to_csv \
  --batch_sizes 4 8 12 16
```
