### ISSUE TITLE
Failed to save tokenizer with AddedToken in additional_special_tokens

### ISSUE THREAD

**Issue by yobekiko** [huggingface/transformers#6025]
# 🐛 Bug

I tried to add new special tokens to some tokenizer. I wanted them to be `AddedToken` in order to handle specific whitespace striping. But I got the following error when saving the tokenizer.

## To reproduce

```python
>>> from transformers import BertTokenizer
>>> from tokenizers import AddedToken
>>> tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
>>> new_token = AddedToken('new_token', lstrip=True)
>>> tokenizer.add_special_tokens({'additional_special_tokens': [new_token]})
1
>>> tokenizer.save_pretrained('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/junyuan/anaconda3/envs/deep/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1371, in save_pretrained
    f.write(json.dumps(write_dict, ensure_ascii=False))
  File "/home/junyuan/anaconda3/envs/deep/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/junyuan/anaconda3/envs/deep/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/junyuan/anaconda3/envs/deep/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/junyuan/anaconda3/envs/deep/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AddedToken is not JSON serializable
```

**Comment by LysandreJik** [comment]
Fixed by #6026
