### ISSUE TITLE
allenai/longformer-large-4096 unavailable

### ISSUE THREAD

**Issue by CMobley7** [huggingface/transformers#6108]
For some reason, I'm unable to download allenai/longformer-large-4096. Everything was working an hour ago, but all of a sudden I get the error included below. It's still listed on https://huggingface.co/models?search=allenai%2Flongformer-large-4096. I'm not sure what's up. Any ideas?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 242, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ptcc/run_glue.py", line 246, in <module>
    main()
  File "/ptcc/run_glue.py", line 123, in main
    cache_dir=model_args.cache_dir,
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 203, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'allenai/longformer-large-4096'. Make sure that:

- 'allenai/longformer-large-4096' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'allenai/longformer-large-4096' is the correct path to a directory containing a config.json file


Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 242, in get_config_dict
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ptcc/run_glue.py", line 246, in <module>
    main()
  File "/ptcc/run_glue.py", line 123, in main
    cache_dir=model_args.cache_dir,
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_auto.py", line 203, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/transformers/configuration_utils.py", line 251, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'allenai/longformer-large-4096'. Make sure that:

- 'allenai/longformer-large-4096' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'allenai/longformer-large-4096' is the correct path to a directory containing a config.json file
```

**Comment by CMobley7** [comment]
The issue seems to have resolved itself. So, I'm closing the issue.
