### ISSUE TITLE
convert_pytorch_checkpoint_to_tf2.py AttributeError: cls.seq_relationship.weight not found in PyTorch model

### ISSUE THREAD

**Issue by DenisStenyushkin** [huggingface/transformers#6124]
Hi all. I'm trying to convert a pre-trained BERT model from PyTorch into TF2 format and facing a problem.

Model being converted: DeepPavlov/rubert-base-cased. I downloaded all files into a local folder.
File convert_pytorch_checkpoint_to_tf2.py from master branch - I downloaded it separately.

The command I'm running:
`python convert_pytorch_checkpoint_to_tf2.py --tf_dump_path ./rubert-base-cased_tf2/ --model_type bert --pytorch_checkpoint_path ./rubert-base-cased-pt/pytorch_model.bin --config_file ./rubert-base-cased-pt/config.json`

And the stacktrace:
```
Traceback (most recent call last):
  File "convert_pytorch_checkpoint_to_tf2.py", line 364, in <module>
    convert_all_pt_checkpoints_to_tf(
  File "convert_pytorch_checkpoint_to_tf2.py", line 298, in convert_all_pt_checkpoints_to_tf
    convert_pt_checkpoint_to_tf(
  File "convert_pytorch_checkpoint_to_tf2.py", line 209, in convert_pt_checkpoint_to_tf
    tf_model = load_pytorch_checkpoint_in_tf2_model(tf_model, pytorch_checkpoint_path)
  File "/Users/denisstenyushkin/.virtualenvs/tf2_pytorch/lib/python3.8/site-packages/transformers/modeling_tf_pytorch_utils.py", line 92, in load_pytorch_checkpoint_in_tf2_model
    return load_pytorch_weights_in_tf2_model(
  File "/Users/denisstenyushkin/.virtualenvs/tf2_pytorch/lib/python3.8/site-packages/transformers/modeling_tf_pytorch_utils.py", line 166, in load_pytorch_weights_in_tf2_model
    raise AttributeError("{} not found in PyTorch model".format(name))
AttributeError: cls.seq_relationship.weight not found in PyTorch model
```

Versions:
- `transformers` version: 3.0.2
- Platform: macOS-10.15.5-x86_64-i386-64bit
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6.0 (False)
- Tensorflow version (GPU?): 2.3.0 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

**Comment by patrickvonplaten** [comment]
Hey @DenisStenyushkin,

It seems like you have the PyTorch model trained with our library, so you can simply do:

```python
from transformers import TFBertModel
model = TFBertModel.from_pretrained("./rubert-base-cased-pt", from_pt=True)

model.save("./rubert-base-cased") # this adds a TF model file (tf_model.h5) to your directory
```

Let me know if this does not solve your problem!
