### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cache_dir'

### ISSUE THREAD

**Issue by Abbyyan** [huggingface/transformers#6989]
## Environment info

     
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1.
2.
3.

## Expected behavior
I'm fine tuning with the example `run_language_modeling.py`as follows.
```shell
python run_language_modeling.py --output_dir=output_dir --model_type gpt2 --model_name_or_path distilgpt2  --do_train  --train_data_file=xxx.data.txt
```
It failed with error 
```shell
Traceback (most recent call last):
  File "run_language_modeling.py", line 313, in <module>
    main()
  File "run_language_modeling.py", line 242, in main
    get_dataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
  File "run_language_modeling.py", line 143, in get_dataset
    cache_dir=cache_dir,
TypeError: __init__() got an unexpected keyword argument 'cache_dir'
```
Could you please tell me how to use it ? Thanks a lot.

**Comment by Abbyyan** [comment]
Solved with  https://github.com/huggingface/transformers/issues/319
