### ISSUE TITLE
broken pypi scipy package that affects tests under `examples`

### ISSUE THREAD

**Issue by stas00** [huggingface/transformers#7098]
In case someone runs into this:
```
PYTHONPATH="src" pytest examples/test_examples.py
ImportError while importing test module '/mnt/nvme1/code/huggingface/transformers-examples/examples/test_examples.py'.
Hint: make sure your test modules/packages have valid Python names.                                                                                               
Traceback:                                                                                                                                                        
/home/stas/anaconda3/envs/main-38/lib/python3.8/importlib/__init__.py:127: in import_module                                                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                                                                   
examples/test_examples.py:38: in <module>                                                                                                                         
    import run_glue                                                                                                                                               
examples/text-classification/run_glue.py:30: in <module>                                                                                                          
    from transformers import (                                                                                                                                    
E   ImportError: cannot import name 'glue_compute_metrics' from 'transformers' (/mnt/nvme1/code/huggingface/transformers-examples/src/transformers/__init__.py)  
```
Looking into the code, the problem was coming from:
```
if is_sklearn_available():
    from .data import glue_compute_metrics, xnli_compute_metrics
``` 
for some reason, it was returning `False`.

Looking deeper, I got here:
```
try:
    from sklearn.metrics import f1_score, matthews_corrcoef

    from scipy.stats import pearsonr, spearmanr

    _has_sklearn = True
except (AttributeError, ImportError):
    _has_sklearn = False

def is_sklearn_available():
    return _has_sklearn
```
So next trying:
```
python -c "from sklearn.metrics import f1_score, matthews_corrcoef"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/sklearn/base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 20, in <module>
    from scipy.sparse import issparse
ModuleNotFoundError: No module named 'scipy.sparse'
```
but the requirement was already installed:

```
pip install scipy
```
A search gave this answer: https://stackoverflow.com/a/59692528/9201239 which solved the problem.
```
pip uninstall scipy
conda install scipy
```
So there is something wrong with that `scipy` package on pypi.

**Comment by stas00** [comment]
The solution is above, so closing this - as it was a FYI post if someone else runs into this.
