### ISSUE TITLE
Bug in finetuning ALBERT on text-classification in GLUE

### ISSUE THREAD

**Issue by ReyonRen** [huggingface/transformers#7172]
Thanks for your beautiful work!

I use transformers-3.1.0, and when I run `run_glue.py` in `examples/text-classification/`, it return a bug info, 
```
Traceback (most recent call last):
  File "run_glue.py", line 246, in <module>
    main()
  File "run_glue.py", line 127, in main
    cache_dir=model_args.cache_dir,
  File "/mnt/dqa/yinheju/env/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_auto.py", line 220, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/mnt/dqa/yinheju/env/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1425, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/mnt/dqa/yinheju/env/python3.7_torch1.1/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1531, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 'albert-base-v2' was not found in tokenizers model name list (albert-base-v1, albert-large-v1, albert-xlarge-v1, albert-xxlarge-v1, albert-base-v2, albert-large-v2, albert-xlarge-v2, albert-xxlarge-v2). We assumed 'albert-base-v2' was a path, a model identifier, or url to a directory containing vocabulary files named ['spiece.model'] but couldn't find such vocabulary files at this path or url.
```
Please help me to solve this problem, thank you!!!

**Comment by ReyonRen** [comment]
I found when run the demo in https://huggingface.co/transformers/model_doc/albert.html#albertforsequenceclassification, also has this problem....  HELP!~~~~~~~~~
```
>>> from transformers import AlbertTokenizer, AlbertForSequenceClassification
>>> import torch

>>> tokenizer = AlbertTokenizer.from_pretrained('albert-base-v2')
>>> model = AlbertForSequenceClassification.from_pretrained('albert-base-v2', return_dict=True)

>>> inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
>>> labels = torch.tensor([1]).unsqueeze(0)  # Batch size 1
>>> outputs = model(**inputs, labels=labels)
>>> loss = outputs.loss
>>> logits = outputs.logits
```

**Comment by ReyonRen** [comment]
Hello, I found that the problem should be that my server cannot connect to the external network, so how can I use transformers in this situation?

**Comment by dwtenis** [comment]
I have the same problem, if you have solved, cound you tell me how? thx!
