### ISSUE TITLE
The absence of source/target language parameters when using MBart in Summarization example

### ISSUE THREAD

**Issue by shiningliang** [huggingface/transformers#7369]
## Environment info

     
- `transformers` version: 3.2.0
- Platform: Ubuntu 16.04
- Python version: 3.7
- PyTorch version (GPU?): 1.6.0+cu101
- Tensorflow version (GPU?): 1.15
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help

Summarization: @sshleifer
## Information

Model I am using (Bert, XLNet ...): MBart

The problem arises when using:
* [x] the official example scripts: (give details below)
I'm following the example for finetuning a summarization model.
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)
xsum

## To reproduce

1. Using the script [finetune.sh](https://github.com/huggingface/transformers/blob/78387cc63e/examples/seq2seq/finetune.sh)
2. Keep all the default parameters
3. Add --model_name_or_path facebook/mbart-large-cc25 --data_dir datasets/xsum --src_lang en_XX --tgt_lang en_XX

```
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/shining/code/seq2seq/finetune.py", line 440, in <module>
    main(args)
  File "/home/shining/code/seq2seq/finetune.py", line 415, in main
    logger=logger,
  File "/home/shining/code/seq2seq/lightning_base.py", line 385, in generic_train
    trainer.fit(model)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/states.py", line 48, in wrapped_fn
    result = fn(self, *args, **kwargs)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1073, in fit
    results = self.accelerator_backend.train(model)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_backend.py", line 51, in train
    results = self.trainer.run_pretrain_routine(model)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in run_pretrain_routine
    self._run_sanity_check(ref_model, model)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1257, in _run_sanity_check
    eval_results = self._evaluate(model, self.val_dataloaders, max_batches, False)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 305, in _evaluate
    for batch_idx, batch in enumerate(dataloader):
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/shining/code/seq2seq/utils.py", line 232, in collate_fn
    add_prefix_space=self.add_prefix_space,
  File "/home/shining/miniconda3/lib/python3.7/site-packages/transformers/tokenization_mbart.py", line 236, in prepare_seq2seq_batch
    self.set_src_lang_special_tokens(src_lang)
  File "/home/shining/miniconda3/lib/python3.7/site-packages/transformers/tokenization_mbart.py", line 268, in set_src_lang_special_tokens
    self.cur_lang_code = self.lang_code_to_id[src_lang]
KeyError: None
```
## Expected behavior
Because the summarization example uses pytorch-linghtning backend I could only track the bug in the collate_fn function in Seq2SeqDataset. I noticed that the parameter self.src_lang=None.

**Comment by sshleifer** [comment]
add 
```
        self.dataset_kwargs["src_lang"] = hparams.src_lang
        self.dataset_kwargs["tgt_lang"] = hparams.tgt_lang
```
here https://github.com/huggingface/transformers/blob/master/examples/seq2seq/finetune.py#L70
