### ISSUE TITLE
Problem with automatic best model loading.

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/transformers#7556]
When I provide `load_best_model_at_end=True`, `metric_for_best_model='eval_f1_macro` and `greater_is_better=True` together with `save_total_limit=2` this happens:

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "train_aws.py", line 174, in opt
    trainer.train()
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/transformers/trainer.py", line 810, in train
    and self.global_step % self.args.eval_steps == 0
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "train_aws.py", line 197, in <module>
    study.optimize(opt)
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/optuna/study.py", line 328, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/optuna/study.py", line 726, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/optuna/study.py", line 755, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "train_aws.py", line 174, in opt
    trainer.train()
  File "/home/ubuntu/miniconda3/envs/hf/lib/python3.7/site-packages/transformers/trainer.py", line 810, in train
    and self.global_step % self.args.eval_steps == 0
ZeroDivisionError: integer division or modulo by zero
```

**Comment by sgugger** [comment]
It's hard to know what's going on without seeing your code. The error indicates `args.eval_steps = 0` and this argument is not modified by the `Trainer` itself, so you should make sure you did set it to something >0.

**Comment by PhilipMay** [comment]
You are right. I had `eval_steps = 0`. Thanks for the feedback!
