### ISSUE TITLE
When downloading RAG dpr indexes,  there is a pickle file loading error

### ISSUE THREAD

**Issue by zhangdongxu** [huggingface/transformers#7686]
When I try to finetune RAG with following code:

```
self.config = RagConfig.from_pretrained("facebook/rag-token-base", n_docs=2, use_dummy_dataset=False)
self.tokenizer = RagTokenizer.from_pretrained("facebook/rag-token-base")
self.tokenizer.pad_token_id =  AutoTokenizer.from_pretrained("facebook/bart-large").pad_token_id
retriever = RagRetriever.from_pretrained("facebook/rag-token-base" use_dummy_dataset=False)
self.model = RagTokenForGeneration.from_pretrained("facebook/rag-token-base", retriever=retriever, config=self.config)
```
An error occurs, which seems that a downloaded pickle file cannot be loaded. I put the error message below.
I assigned 200GB memory so it should not be an memory issue. I'm not sure if this is a trivial error due to my own implementation bugs or it is more common. Thank you very much!!

--------------
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/numpy/lib/npyio.py", line 447, in load return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred: 

Traceback (most recent call last):
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/builder.py", line 553, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs) 
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/builder.py", line 841, in _prepare_split
    generator, unit=" examples", total=split_info.num_examples, leave=False, disable=not_verbose
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File ".cache/huggingface/modules/datasets_modules/datasets/wiki_dpr/14b973bf2a456087ff69c0fd34526684eed22e48e0dfce4338f9a22b965ce7c2/wiki_dpr.py", line 132, in _generate_examples 
    vecs = np.load(open(vectors_files.pop(0), "rb"), allow_pickle=True)
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file <_io.BufferedReader name='.cache/huggingface/datasets/downloads/cd4183aaa482e0e3724cb8b2efafc6c762914aabed38c16a41f922ff7d5e90f9'> as a pickle

Traceback (most recent call last):
  File "src/finetune.py", line 432, in <module>
    main(args)
  File "src/finetune.py", line 371, in main
    model: SummarizationModule = SummarizationModule(args)
  File "src/finetune.py", line 73, in __init__
    super().__init__(hparams, num_labels=None, mode=self.mode, **kwargs)
  File "src/lightning_base.py", line 130, in __init__
    retriever = RagRetriever.from_pretrained("facebook/rag-token-base", use_dummy_dataset=False)
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/retrieval_rag.py", line 310, in from_pretrained
    config, question_encoder_tokenizer=question_encoder_tokenizer, generator_tokenizer=generator_tokenizer
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/retrieval_rag.py", line 301, in __init__
    self.init_retrieval()
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/retrieval_rag.py", line 327, in init_retrieval
    self.index.init_index()
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/retrieval_rag.py", line 241, in init_index
    dummy=self.use_dummy_dataset,
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/load.py", line 611, in load_dataset
    ignore_verifications=ignore_verifications,
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/builder.py", line 476, in download_and_prepare
    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
  File "anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/builder.py", line 555, in _download_and_prepare
    raise OSError("Cannot find data file. " + (self.manual_download_instructions or ""))
OSError: Cannot find data file.
srun: error: node006: task 0: Exited with exit code 1

**Comment by zhangdongxu** [comment]
It was probably because I repeatly downloaded the indexes and the previous incomplete files still exist. Issue closed

**Comment by tangxiangru** [comment]
I met the same bug.
