### ISSUE TITLE
Reformer model does not work with padded sequences

### ISSUE THREAD

**Issue by FabianBell** [huggingface/transformers#7929]
## Environment info

     
- `transformers` version: 3.4.0
- Platform: Linux
- Python version: 3.8.5
- PyTorch version (GPU?): 1.6.0 (No)
- Tensorflow version (GPU?): 2.3.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help

@patrickvonplaten 
## Information

Model I am using (Bert, XLNet ...): Reformer 

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: (give the name) CommonGen
* [ ] my own task or dataset: (give details below)

## To reproduce

```python
from transformers import ReformerTokenizer, ReformerModel


tokenizer = ReformerTokenizer.from_pretrained('google/reformer-crime-and-punishment')
seq = tokenizer(['Hello this is a test.', 'This is a test as well'], padding=True, return_tensors='pt')
reformer = ReformerModel.from_pretrained('google/reformer-crime-and-punishment')
out = reformer(**seq)
```
```python
Traceback (most recent call last):
  File "reformerbug.py", line 20, in <module>
    out = reformer(**seq)
  File "/home/fabian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fabian/.local/lib/python3.8/site-packages/transformers/modeling_reformer.py", line 2096, in forward
    embedding_output = self.embeddings(
  File "/home/fabian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fabian/.local/lib/python3.8/site-packages/transformers/modeling_reformer.py", line 252, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/home/fabian/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fabian/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 124, in forward
    return F.embedding(
  File "/home/fabian/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

## Expected behavior
The model should properly calculate the forward pass given the encoded sequence.

**Comment by patrickvonplaten** [comment]
The only Reformer tokenizer we have actually doesn't have a PAD Token which is why this leads to problems. The PR attached below removes the PAD token. Before padding one should set 

```python
tokenizer.pad_token = tokenizer.eos_token
```

Similar to GPT2 this won't cause any problems thanks to causal masking, see: https://github.com/huggingface/transformers/issues/4122#issuecomment-713749343
