### ISSUE TITLE
 'EncoderDecoderModel' object has no attribute '_init_weights' after `model.resize_token_embeddings(len(tokenizer))`

### ISSUE THREAD

**Issue by XinXia2019** [huggingface/transformers#7953]
## Details
Version transformers==3.4.0
torch==1.6.0
torchvision==0.7.0

>>> tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
>>>tokenizer.add_special_tokens({"additional_special_tokens": ['extra1', 'extra2']})
1
>>> model = EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased')
>>> model.resize_token_embeddings(len(tokenizer))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxia/anaconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 607, in resize_token_embeddings
    model_embeds = base_model._resize_token_embeddings(new_num_tokens)
  File "/Users/xxia/anaconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 622, in _resize_token_embeddings
    new_embeddings = self._get_resized_embeddings(old_embeddings, new_num_tokens)
  File "/Users/xxia/anaconda3/lib/python3.8/site-packages/transformers/modeling_utils.py", line 659, in _get_resized_embeddings
    self._init_weights(new_embeddings)
  File "/Users/xxia/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 771, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'EncoderDecoderModel' object has no attribute '_init_weights'

Thanks for help!

**Comment by patrickvonplaten** [comment]
Hello @XinXia2019, sadly `resize_token_embeddings` is not supported yet for `EncoderDecoderModel`. Instead you could just manually instantiate the encoder and decoder and apply `resize_token_embeddings` on each part before wrapping them into the `EncoderDecoderModel` framework.

**Comment by XinXia2019** [comment]
Thanks!
