### ISSUE TITLE
Hello world example fail with transformers-3.4

### ISSUE THREAD

**Issue by guotong1988** [huggingface/transformers#8086]
## Environment info

- `transformers` version:3.4
- Platform: Mac
- Python version: 3.6
- PyTorch version (GPU?): 
- Tensorflow version (GPU?): 2.3
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help

 albert, bert, GPT2, XLM: @LysandreJik 
 tokenizers: @mfuntowicz
 Trainer: @sgugger
 

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

Download all the code of branch-3.4.0

```
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/bert-base-uncased-tokenizer.json")
model = TFAutoModel.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/bert-base-uncased-pytorch_model.bin")

inputs = tokenizer("Hello world!", return_tensors="tf")
outputs = model(**inputs)
print(outputs)
```

Model downloaded from https://mirrors.tuna.tsinghua.edu.cn/hugging-face-models/

Get error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
in line 4

**Comment by thomwolf** [comment]
We will probably need at least the full error trace

**Comment by guotong1988** [comment]
```
Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated
Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained.
Traceback (most recent call last):
  File "/Users/gt/Desktop/transformers-3.4.0/my_code/test.py", line 4, in <module>
    model = TFAutoModel.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/bert-base-uncased-pytorch_model.bin")
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/modeling_tf_auto.py", line 493, in from_pretrained
    pretrained_model_name_or_path, return_unused_kwargs=True, **kwargs
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/configuration_auto.py", line 330, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/configuration_utils.py", line 374, in get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/configuration_utils.py", line 456, in _dict_from_json_file
    text = reader.read()
  File "/Users/gt/Py36-tf1.4/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by LysandreJik** [comment]
This line: `model = TFAutoModel.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/bert-base-uncased-pytorch_model.bin")`

should point to a directory contining both the model file and the configuration. Also, you're loading a `pytorch_model.bin` in a `TFAutoModel`, whereas this is a TensorFlow automodel.

- You should make sure that you're loading from a directory containing either `(pytorch_model.bin, config.json)` for PyTorch, or `(tf_model.h5, config.json)` for TensorFlow
- You can load a PyTorch model in TensorFlow, but you should specify `from_pt=True`, and you can load a TensorFlow model in PyTorch but you should specify the `from_tf=True` option.

You can find more information about this in the [quick tour](https://huggingface.co/transformers/quicktour.html#under-the-hood-pretrained-models).

**Comment by guotong1988** [comment]
```
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/")
model = TFAutoModel.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/")

inputs = tokenizer("Hello world!", return_tensors="tf")
outputs = model(**inputs)
print(outputs)
```

![image](https://user-images.githubusercontent.com/4702353/97378792-32531e80-18fe-11eb-9da3-5bc8dd0bda1d.png)


```
Traceback (most recent call last):
  File "/Users/gt/Desktop/transformers-3.4.0/my_code/test.py", line 3, in <module>
    tokenizer = AutoTokenizer.from_pretrained("/Users/gt/Desktop/transformers-3.4.0/my_code/")
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/tokenization_auto.py", line 333, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/Users/gt/Desktop/transformers-3.4.0/src/transformers/tokenization_utils_base.py", line 1591, in from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name '/Users/gt/Desktop/transformers-3.4.0/my_code/' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). We assumed '/Users/gt/Desktop/transformers-3.4.0/my_code/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
```

**Comment by LysandreJik** [comment]
Hello, as said before you need your files to be correctly named. Your model should be `pytorch_model.bin` or `tf_model.h5`, your configuration `config.json`, and your tokenizer should also be pointing to a file that has an appropriate name. You seem to be loading a `bert-base-cased` model, which should be used with a `BertTokenizer` that uses `vocab.txt` files, as it is shown in the error.

**Comment by guotong1988** [comment]
Thank you.
