### ISSUE TITLE
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by yuchenlin** [huggingface/transformers#8232]
## Environment info

     
- `transformers` version:
- Platform: ubuntu 18.04
- Python version: 3.7
- PyTorch version (GPU?): 1.4.0
- Tensorflow version (GPU?): 
- Using GPU in script?: no
- Using distributed or parallel set-up in script?:no

### Who can help

 Trainer: @sgugger
 

## Information

This import is not compatible with PyTorch 1.4.0 

The problem arises when using:
* [ *] the official example scripts: (give details below) 

The tasks I am working on is:
* [ *] an official GLUE/SQUaD task: (give the name) 
## To reproduce

```python
>>> from transformers import PreTrainedTokenizer, is_tf_available, is_torch_available
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuchenlin/anaconda3/envs/mcqa/lib/python3.7/site-packages/transformers/__init__.py", line 611, in <module>
    from .trainer import Trainer
  File "/home/yuchenlin/anaconda3/envs/mcqa/lib/python3.7/site-packages/transformers/trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "/home/yuchenlin/anaconda3/envs/mcqa/lib/python3.7/site-packages/transformers/trainer_pt_utils.py", line 26, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/home/yuchenlin/anaconda3/envs/mcqa/lib/python3.7/site-packages/torch/optim/lr_scheduler.py)
```

**Comment by sgugger** [comment]
Oh I didn't check when they added this. Do you know if PyTorch 1.4.0 is the last version without it? Will add a fix this morning.

**Comment by stas00** [comment]
`SAVE_STATE_WARNING` has been removed 3 days ago: https://github.com/pytorch/pytorch/pull/46813

can we re-code this not to use that constant?

**Comment by stas00** [comment]
otherwise will need:
```
--- a/src/transformers/trainer_pt_utils.py
+++ b/src/transformers/trainer_pt_utils.py
@@ -34,7 +34,7 @@ from .utils import logging
 if is_torch_tpu_available():
     import torch_xla.core.xla_model as xm

-if version.parse(torch.__version__) <= version.parse("1.4.1"):
+if version.parse(torch.__version__) <= version.parse("1.4.1") or version.parse(torch.__version__) > version.parse("1.7.0"):
     SAVE_STATE_WARNING = ""
 else:
     from torch.optim.lr_scheduler import SAVE_STATE_WARNING
```
