### ISSUE TITLE
[commit #29b536a]AttributeError: module 'numpy.random' has no attribute 'Generator'

### ISSUE THREAD

**Issue by ksjae** [huggingface/transformers#8278]
## Environment info

     
- `transformers` version: commit #29b536a
- Platform: Linux
- Python version: 3.7.4
- PyTorch version (GPU?): 1.4.0
- Tensorflow version (GPU?): N/A
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help
I don't know, anyone?

## Information

The problem arises when using:
```
import transformers
```

The tasks I am working on is:
(ANY)

## To reproduce

```
import transformers
```

## Error message
```
File "/home01/a1204a01/.local/bin/transformers-cli", line 6, in <module>
    from transformers.commands.transformers_cli import main
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/transformers/__init__.py", line 22, in <module>
    from .integrations import (  # isort:skip
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/transformers/integrations.py", line 81, in <module>
    from .file_utils import is_torch_tpu_available  # noqa: E402
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/transformers/file_utils.py", line 87, in <module>
    import datasets  # noqa: F401
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/datasets/__init__.py", line 27, in <module>
    from .arrow_dataset import Dataset, concatenate_datasets
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 175, in <module>
    class Dataset(DatasetInfoMixin, IndexableMixin):
  File "/home01/a1204a01/.local/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 1889, in Dataset
    new_fingerprint: Optional[str] = None,
AttributeError: module 'numpy.random' has no attribute 'Generator'
```

## Expected behavior

Import

**Comment by ksjae** [comment]
Another error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-279c49635b32> in <module>
----> 1 import transformers

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/__init__.py in <module>
    133 
    134 # Pipelines
--> 135 from .pipelines import (
    136     Conversation,
    137     ConversationalPipeline,

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/pipelines.py in <module>
     35 from .file_utils import add_end_docstrings, is_tf_available, is_torch_available
     36 from .modelcard import ModelCard
---> 37 from .tokenization_auto import AutoTokenizer
     38 from .tokenization_bert import BasicTokenizer
     39 from .tokenization_utils import PreTrainedTokenizer

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/tokenization_auto.py in <module>
    117 
    118 if is_tokenizers_available():
--> 119     from .tokenization_albert_fast import AlbertTokenizerFast
    120     from .tokenization_bart_fast import BartTokenizerFast
    121     from .tokenization_bert_fast import BertTokenizerFast

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/tokenization_albert_fast.py in <module>
     21 
     22 from .file_utils import is_sentencepiece_available
---> 23 from .tokenization_utils_fast import PreTrainedTokenizerFast
     24 from .utils import logging
     25 

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/tokenization_utils_fast.py in <module>
     28 from tokenizers.decoders import Decoder as DecoderFast
     29 
---> 30 from .convert_slow_tokenizer import convert_slow_tokenizer
     31 from .file_utils import add_end_docstrings
     32 from .tokenization_utils import PreTrainedTokenizer

/scratch/a1204a01/.conda/envs/notebook/lib/python3.7/site-packages/transformers/convert_slow_tokenizer.py in <module>
     26 
     27 # from transformers.tokenization_openai import OpenAIGPTTokenizer
---> 28 from transformers.utils import sentencepiece_model_pb2 as model
     29 
     30 from .file_utils import requires_sentencepiece

ImportError: cannot import name 'sentencepiece_model_pb2' from 'transformers.utils' (/home01/a1204a01/.local/lib/python3.7/site-packages/transformers/utils/__init__.py)
```

**Comment by LysandreJik** [comment]
Hi! could you let us know how you installed `transformers`?

**Comment by ksjae** [comment]
I built from source, by ```git clone``` and ```pip install .```

**Comment by ksjae** [comment]
Fixed by reinstalling python3 and reinstalling transformer with latest commit
