### ISSUE TITLE
  assert tgt_line, f"empty tgt line for index {index}" with t5 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8356]
Hi
I am trying to run fineutne_trainer with this command and I got assert error  thanks for your help

export TPU_IB_ADDRESS=10.160.244.2

start=`date +%s`
python xla_spawn.py --num_cores 8 \
    finetune_trainer.py \
    --tokenizer_name t5-small --model_name_or_path t5-small \
    --data_dir wmt_en_de \
    --output_dir /home/rabeeh/outputs/verify --overwrite_output_dir \
    --learning_rate=3e-4 \
    --warmup_steps 500 \
    --per_device_train_batch_size=128 --per_device_eval_batch_size=128\
    --num_train_epochs=1 \
    --save_steps 500 --eval_steps 500 \
    --logging_steps 200 \
    --max_source_length 128 --max_target_length 128 --val_max_target_length 128 --test_max_target_length 128 \
    --task translation --label_smoothing 0.1 \
     --freeze_encoder --freeze_embeds \
     --num_train_epochs=1 \
                 --logging_first_step --logging_steps 200 \
                         --do_train --do_eval --evaluate_during_training \
                             --prediction_loss_only \

    "$@"

end=`date +%s`
runtime=$((end-start))
echo running time $runtime

logs 

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch_xla/distributed/parallel_loader.py", line 141, in _loader_worker
    _, data = next(data_iter)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/home/rabeeh/examples/seq2seq/utils.py", line 246, in __getitem__
    assert tgt_line, f"empty tgt line for index {index}"
AssertionError: empty tgt line for index 4549523

**Comment by rabeehkarimimahabadi** [comment]
@patil-suraj

**Comment by rabeehkarimimahabadi** [comment]
I am guessing maybe this issue is making it slower on tpus? on en-ro which it does not happen it is faster

**Comment by yarinKuper** [comment]
@rabeehkarimimahabadi did you solve the issue?
