### ISSUE TITLE
finetune_trainer crashes in the beginning 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [huggingface/transformers#8383]
Hi
I am trying to run 

```
python finetune_trainer.py \
--model_name_or_path /idiap/temp/rkarimi/pretrained_transformers/t5-small/ \
--data_dir=/home/rabeeh/data/test_data/wmt_en_ro \
--learning_rate=3e-5 \
--output_dir=/home/rabeeh/temp \
--max_source_length=512 \
--max_target_length=56 \
--do_train --do_predict \
--overwrite_output_dir\
"$@"

```

I got the following issue, thanks for your help 
(internship) rkarimi@vgnh001:/idiap/user/rkarimi/dev/internship/seq2seq$ bash run_idiap.sh 
Traceback (most recent call last):
  File "finetune_trainer.py", line 7, in <module>
    from seq2seq_trainer import Seq2SeqTrainer
  File "/remote/idiap.svm/user.active/rkarimi/dev/internship/seq2seq/seq2seq_trainer.py", line 7, in <module>
    from transformers import PreTrainedModel, Trainer, logging
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/transformers/__init__.py", line 22, in <module>
    from .integrations import (  # isort:skip
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/transformers/integrations.py", line 81, in <module>
    from .file_utils import is_torch_tpu_available  # noqa: E402
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/transformers/file_utils.py", line 87, in <module>
    import datasets  # noqa: F401
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/__init__.py", line 27, in <module>
    from .arrow_dataset import Dataset, concatenate_datasets
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 40, in <module>
    from .arrow_reader import ArrowReader
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/arrow_reader.py", line 31, in <module>
    from .utils import cached_path, logging
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/utils/__init__.py", line 20, in <module>
    from .download_manager import DownloadManager, GenerateMode
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/utils/download_manager.py", line 25, in <module>
    from .file_utils import HF_DATASETS_CACHE, cached_path, get_from_cache, hash_url_to_filename
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 118, in <module>
    os.makedirs(HF_MODULES_CACHE, exist_ok=True)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/idiap/home/rkarimi/.cache/huggingface'

**Comment by rabeehkarimimahabadi** [comment]
My gpu instances does not have access to download the files, could you please assist me? could it be not hardcoded in the codes? so user could download the files and put them in the directory?

**Comment by rabeehkarimimahabadi** [comment]
could you tell me what is this trying to download in the beginning?

**Comment by rabeehkarimimahabadi** [comment]
apparently the code downloads some stuff in datasets/utils/file_utils.py ? could you tell me how to resolve this issue? thanks

**Comment by rabeehkarimimahabadi** [comment]
my gpu instance cannot download ""https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets" inside this file.
