### ISSUE TITLE
DPR model: FileNotFoundError: Couldn't find file

### ISSUE THREAD

**Issue by danyaljj** [huggingface/transformers#8506]
I am using DPR model: 
```python 
from transformers import DPRQuestionEncoderTokenizer, DPRQuestionEncoder
from datasets import load_dataset

question_tokenizer = DPRQuestionEncoderTokenizer.from_pretrained('facebook/dpr-question_encoder-single-nq-base')
question_encoder = DPRQuestionEncoder.from_pretrained('facebook/dpr-question_encoder-single-nq-base')
wiki = load_dataset("wiki_dpr", with_embeddings=False, with_index=True, split="train")

def get_top(question, topk=5):
    question_emb = question_encoder(**question_tokenizer(question, return_tensors="pt"))[0].detach().numpy()
    passages_scores, passages = wiki.get_nearest_examples("embeddings", question_emb, k=topk)
    all_passgae = ""
    for score, title, text in zip(passages_scores, passages['title'], passages['text']):
        if len(all_passgae.split(" ")) < 450:
            all_passgae += f" ({title}) {text}"
    return all_passgae

get_top("who was the first US president?")
```

This was working until last week. However, now when running it I am getting the following error:
```
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 1.65MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 493/493 [00:00<00:00, 443kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 438M/438M [00:05<00:00, 73.8MB/s]
Downloading: 7.91kB [00:00, 7.04MB/s]                                                                                                                                                  
Downloading: 21.9kB [00:00, 19.5MB/s]                                                                                                                                                  
Using custom data configuration psgs_w100.no_embeddings.compressed
Downloading and preparing dataset wiki_dpr/psgs_w100.no_embeddings.compressed (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /home/danielk/.cache/huggingface/datasets/wiki_dpr/psgs_w100.no_embeddings.compressed/0.0.0/14b973bf2a456087ff69c0fd34526684eed22e48e0dfce4338f9a22b965ce7c2...
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.54k/1.54k [00:00<00:00, 1.66MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13.8G/13.8G [03:41<00:00, 62.3MB/s]
Traceback (most recent call last):
  File "2.create_tasks.py", line 9, in <module>
    wiki = load_dataset("wiki_dpr", with_embeddings=False, with_index=True, split="train")
  File "/home/danielk/qoogle-experiments/env37/lib/python3.7/site-packages/datasets/load.py", line 611, in load_dataset
    ignore_verifications=ignore_verifications,
  File "/home/danielk/qoogle-experiments/env37/lib/python3.7/site-packages/datasets/builder.py", line 468, in download_and_prepare
    self._download_prepared_from_hf_gcs()
  File "/home/danielk/qoogle-experiments/env37/lib/python3.7/site-packages/datasets/builder.py", line 507, in _download_prepared_from_hf_gcs
    resource_path = utils.cached_path(remote_cache_dir + "/" + resource_file_name)
  File "/home/danielk/qoogle-experiments/env37/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 308, in cached_path
    use_etag=download_config.use_etag,
  File "/home/danielk/qoogle-experiments/env37/lib/python3.7/site-packages/datasets/utils/file_utils.py", line 474, in get_from_cache
    raise FileNotFoundError("Couldn't find file at {}".format(url))
FileNotFoundError: Couldn't find file at https://storage.googleapis.com/huggingface-nlp/cache/datasets/wiki_dpr/psgs_w100.no_embeddings.compressed/0.0.0/psgs_w100.nq.IVFPQ4096_HNSW32_PQ64-IP-train.faiss
``` 

I wonder if the changes made to the model-hub has anything to do with this. 
@LysandreJik @lhoestq @julien-c 

Here is my environment, for completeness: 

```
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
```
and
```
tensorboard              2.4.0
tensorboard-plugin-wit   1.7.0
tensorboardX             2.1
tensorflow               2.3.1
tensorflow-datasets      4.1.0
tensorflow-estimator     2.3.0
tensorflow-metadata      0.25.0
tensorflow-text          2.3.0
termcolor                1.1.0
tfds-nightly             4.1.0.dev202011120108
threadpoolctl            2.1.0
tokenizers               0.9.3
torch                    1.6.0
tqdm                     4.49.0
transformers             3.5.0
typing-extensions        3.7.4.3
urllib3                  1.26.1
```

**Comment by lhoestq** [comment]
Thanks for reporting !
Indeed the index was renamed recently. It should be good now

**Comment by danyaljj** [comment]
Got it. Upon re-trying the code, it works fine.
