### ISSUE TITLE
Error: Asking to return token_type_ids while setting add_special_tokens to False

### ISSUE THREAD

**Issue by chrk623** [huggingface/transformers#8578]
In the code below, while using `batch_encode_plus`, i get the error saying that i asked ***“to return token_type_ids while setting add_special_tokens to False”***, when `return_token_type_ids` is `False`. I'm not sure if i am comprehending the error message correctly. For this specific case, I also found that the behaviour between `BertTokenizer` and `BertTokenizerFast` is different.

```python
from transformers import AutoTokenizer
t = AutoTokenizer.from_pretrained("bert-base-uncased", add_special_tokens=False)

txt = ["huggingface", "transformers"]
t.batch_encode_plus(
    txt,
    add_special_tokens=False,
    return_attention_mask=False,
    return_token_type_ids=False,
)
```
Error message
```
Traceback (most recent call last):
  File "/Users/charcohui/Desktop/env/mlenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-226d8ccb1c88>", line 5, in <module>
    return_token_type_ids=False,
  File "/Users/charcohui/Desktop/env/mlenv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2399, in batch_encode_plus
    **kwargs,
  File "/Users/charcohui/Desktop/env/mlenv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 567, in _batch_encode_plus
    verbose=verbose,
  File "/Users/charcohui/Desktop/env/mlenv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 617, in _batch_prepare_for_model
    verbose=verbose,
  File "/Users/charcohui/Desktop/env/mlenv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 2681, in prepare_for_model
    "Asking to return token_type_ids while setting add_special_tokens to False "
ValueError: Asking to return token_type_ids while setting add_special_tokens to False results in an undefined behavior. Please set add_special_tokens to True or set return_token_type_ids to None.
```

However, it works when `BertTokenizerFast` is used:
```python
tfast = AutoTokenizer.from_pretrained("bert-base-uncased", use_fast=True, add_special_tokens=False)
tfast.batch_encode_plus(
    txt,
    add_special_tokens=False,
    return_attention_mask=False,
    return_token_type_ids=False,
)
# {'input_ids': [[17662, 12172], [19081]]}
```

**Comment by LysandreJik** [comment]
Hi, indeed this seems to be an error. Fixing this in #8854 if it is so.
