### ISSUE TITLE
AttributeError: type object 'T5ForConditionalGeneration' has no attribute 'from_config'

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#8762]
## Environment info
- `transformers` version: 3.5.1
- Platform: Linux
- Python version: 3.7
- PyTorch version (GPU?): 1.6
- Tensorflow version (GPU?): - 
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no 

### Who can help

 Model Cards: @julien-c
 Text Generation: @patrickvonplaten @TevenLeScao
 T5: @patrickvonplaten
 examples/seq2seq: @patil-suraj

## Information

Hi
I would like to use T5 untrained here is the command I try:

` model = T5ForConditionalGeneration.from_config(config=config)
`
I am getting this error, could you assist me please? thank you Looks weird error to me, since from_config should work based on documentations. thanks 

```
  File "finetune_t5_trainer.py", line 88, in main
    model = T5ForConditionalGeneration.from_config(config=config)
AttributeError: type object 'T5ForConditionalGeneration' has no attribute 'from_config'

```

## To reproduce
Please run the command given

## Expected behavior
load unpretrained model

**Comment by rabeehk** [comment]
I also tried to use automodel for this, I needed to modify the T5Config, I called it like this with automodel:

`  model = AutoModel.from_config(config)
`
I am getting this error:

```
Traceback (most recent call last):
  File "finetune_t5_trainer.py", line 236, in <module>
    main()
  File "finetune_t5_trainer.py", line 89, in main
    model = AutoModel.from_config(config)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/internship/lib/python3.7/site-packages/transformers/modeling_auto.py", line 604, in from_config
    config.__class__, cls.__name__, ", ".join(c.__name__ for c in MODEL_MAPPING.keys())
ValueError: Unrecognized configuration class <class 'seq2seq.models.t5.configuration_t5.T5Config'> for this kind of AutoModel: AutoModel.
Model type should be one of RetriBertConfig, T5Config, DistilBertConfig, AlbertConfig, CamembertConfig, XLMRobertaConfig, BartConfig, LongformerConfig, RobertaConfig, LayoutLMConfig, SqueezeBertConfig, BertConfig, OpenAIGPTConfig, GPT2Config, MobileBertConfig, TransfoXLConfig, XLNetConfig, FlaubertConfig, FSMTConfig, XLMConfig, CTRLConfig, ElectraConfig, ReformerConfig, FunnelConfig, LxmertConfig, BertGenerationConfig, DebertaConfig, DPRConfig, XLMProphetNetConfig, ProphetNetConfig.



```

**Comment by rabeehk** [comment]
solved with model = T5ForConditionalGeneration(config=config)  syntax has been changed from 3.5.0 to 3.5.1 thanks
