### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Q_fyRn/sacrebleu/

### ISSUE THREAD

**Issue by rabeehk** [huggingface/transformers#8898]
Hi
I am trying with master branch getting this error when installign requirements inside examples 
thanks. 

Collecting seqeval (from -r ../requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (43kB)
    100% |████████████████████████████████| 51kB 13.4MB/s 
Collecting psutil (from -r ../requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz (465kB)
    100% |████████████████████████████████| 471kB 2.7MB/s 
Collecting sacrebleu (from -r ../requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/b9/d6/258a1e63463b4731a387f0872dca759c330bf4845cc0464f2c65028674b6/sacrebleu-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Q_fyRn/sacrebleu/setup.py", line 65, in <module>
        version = get_version(),
      File "/tmp/pip-install-Q_fyRn/sacrebleu/setup.py", line 56, in get_version
        with open(os.path.join(os.path.dirname(__file__), 'sacrebleu.py'), encoding='utf-8') as fin:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Q_fyRn/sacrebleu/

**Comment by rabeehk** [comment]
Installing transformers is also broken

(test) rabeeh@gpu4:~/transformers/examples/seq2seq$ pip install git+https://github.com/huggingface/transformers.git
Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-V7nNeF
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-V7nNeF/setup.py", line 156
        entries = "\n".join([f'    "{k}": "{v}",' for k, v in deps.items()])
                                                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-V7nNeF/

**Comment by rabeehk** [comment]
issue solved with python = 3.7
