### ISSUE TITLE
Help to run an Example Code (it's a bug maybe ?)

### ISSUE THREAD

**Issue by Sourciluss667** [huggingface/transformers#8911]
## Environment info
     
- `transformers` version: 4.0.0
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.0+cpu (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help 

I don't know :(

## Information

Model I am using (Bert, XLNet ...): fmikaelian/camembert-base-fquad

The problem arises when using:
* [x] the official example scripts: (give details below)

When using the default example script i get this error : 

```
Traceback (most recent call last):
  File ".\test.py", line 5, in <module>
    nlp({
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\pipelines.py", line 1874, in __call__
    start, end = self.model(**fw_args)[:2]
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 1286, in forward
    outputs = self.roberta(
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 687, in forward 
    embedding_output = self.embeddings(
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 117, in forward 
    inputs_embeds = self.word_embeddings(input_ids)
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\sparse.py", line 124, in forward
    return F.embedding(
  File "C:\Users\WTFAn\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)
```

## Expected behavior

I don't know where I forgot something, but this example code give me this error and I don't know how to resolve this, because the error come from the lib. If someone can help me :)

```
from transformers import pipeline

nlp = pipeline('question-answering', model='fmikaelian/camembert-base-fquad', tokenizer='fmikaelian/camembert-base-fquad')

nlp({
    'question': "Qui est Claude Monet?",
    'context': "Claude Monet, né le 14 novembre 1840 à Paris et mort le 5 décembre 1926 à Giverny, est un peintre français et l’un des fondateurs de l'impressionnisme."
})
```

Edit : I have this issue with all 'question-answering' pipeline

**Comment by LysandreJik** [comment]
Hmmm, this is weird, I can't reproduce with a very similar environment:

```py
- `transformers` version: 4.0.0
- Platform: Linux-5.9.11-arch2-1-x86_64-with-glibc2.10
- Python version: 3.8.3
- PyTorch version (GPU?): 1.7.0 (True)
- Tensorflow version (GPU?): 2.3.1 (False)
```

Differing element here seems to be Windows vs Linux. Do you mind trying to install the library from `master` and telling me if that works?

You can try it with:

```
pip install git+https://github.com/huggingface/transformers
```

**Comment by davidmezzetti** [comment]
For what it's worth, I ran into the same issue using a GitHub Actions workflow with the following environment:

```python
- `transformers` version: 4.0.0
- Platform: Windows Server 2019
- Python version: 3.6.8
- PyTorch version (GPU?): 1.6.0 (No)
```

I modified the workflow to run against the master branch and the issue appears to be resolved there.

**Comment by Sourciluss667** [comment]
Yes this command solve my issue, thank you :)
