### ISSUE TITLE
Saving model errors

### ISSUE THREAD

**Issue by cyfugr** [huggingface/transformers#9144]
I am trying to fine-tune distillbert for a multilabel task using a V100 gpu and latest transformers from pip. When i try to save the model i get this error: 
```
Traceback (most recent call last):
  File "script/fine_tune_distillbert.py", line 51, in <module>
    model.save_pretrained(ROOT_DIR)
  File "/usr/local/lib/python3.7/dist-packages/transformers/modeling_tf_utils.py", line 534, in save_pretrained
    self.save_weights(output_model_file)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 2085, in save_weights
    hdf5_format.save_weights_to_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/saving/hdf5_format.py", line 640, in save_weights_to_hdf5_group
    param_dset = g.create_dataset(name, val.shape, dtype=val.dtype)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/group.py", line 143, in create_dataset
    if '/' in name:
TypeError: a bytes-like object is required, not 'str'
```

The model init:

```
model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels= max_lab)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)
model.compile(optimizer=optimizer, loss=model.compute_loss, metrics=['accuracy']) # can also use any keras loss fn

model.fit(train_dataset.shuffle(1000).batch(256), epochs=3, batch_size=256,
          validation_data=val_dataset.shuffle(1000).batch(256))
```

The way i am saving after sucessfuly training the model is this : 

```
import os
ROOT_DIR = os.path.abspath(os.curdir)
ROOT_DIR = ROOT_DIR + "/model"

tokenizer.save_pretrained(ROOT_DIR)
model.save_pretrained(ROOT_DIR)
```

Tokenizer is saved perfectly. I have tried to run the same code in a colab notebook ( with much less data) and it saves perfectly but when i use a service like `spell.ml` i get this error.

@LysandreJik

**Comment by LysandreJik** [comment]
Hi, I'm sorry but I don't know spell.ml or how it works; if it works in a colab notebook and saves correctly, it seems the issue comes from spell.ml rather than transformers.
