### ISSUE TITLE
Fail to reload tokenizer from save_pretrained method

### ISSUE THREAD

**Issue by jc-hou** [huggingface/transformers#9330]
Hi,
to reproduce:
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
tokenizer.save_pretrained(".")
tokenizer = AutoTokenizer.from_pretrained(".")
```
with error msg:
```
file ./config.json not found
Traceback (most recent call last):
  File "/data/stars/user/jhou/Test/pytorch_test/huggingface/jc-hou_fork/transformers/src/transformers/configuration_utils.py", line 389, in get_config_dict
    local_files_only=local_files_only,
  File "/data/stars/user/jhou/Test/pytorch_test/huggingface/jc-hou_fork/transformers/src/transformers/file_utils.py", line 1015, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file ./config.json not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/stars/user/jhou/Test/pytorch_test/huggingface/jc-hou_fork/transformers/src/transformers/models/auto/tokenization_auto.py", line 337, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/data/stars/user/jhou/Test/pytorch_test/huggingface/jc-hou_fork/transformers/src/transformers/models/auto/configuration_auto.py", line 341, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/stars/user/jhou/Test/pytorch_test/huggingface/jc-hou_fork/transformers/src/transformers/configuration_utils.py", line 401, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for '.'. Make sure that:

- '.' is a correct model identifier listed on 'https://huggingface.co/models'

- or '.' is the correct path to a directory containing a config.json file

```
Thanks.
transformers:4.1.0
 tokenizers: @mfuntowicz

**Comment by patil-suraj** [comment]
Hi @jc-hou,

The `Auto*` classes require the `config.json` (which is saved when you save the model) file to find the correct model/tokenizer class for loading the model/tokenizer. To directly load the tokenizer without the model use the specific tokenizer class, in this case, `BertTokenizer`.

**Comment by jc-hou** [comment]
Hi, thanks. I understand.
