### ISSUE TITLE
Can not load a saved tokenizer using AutoTokenizer

### ISSUE THREAD

**Issue by hadifar** [huggingface/transformers#9498]
## Environment info

     
- `transformers` version:
- Platform: ubuntu 18.04
- Python version: 3.8
- PyTorch version (GPU?): No
- Tensorflow version (GPU?): No
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

@mfuntowicz
@patrickvonplaten

## Information

I'm using following code to save and load t5 tokenizer:

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('t5-small')
tokenizer.add_tokens(['<sep>', '<hl>'])
tokenizer.save_pretrained('./t5-tokenizer-test/')

tokenizer2 = AutoTokenizer.from_pretrained('./t5-tokenizer-test/')

```

But it throws the following exception:

During handling of the above exception, another exception occurred:
```

Traceback (most recent call last):
  File "/home/amir/PycharmProjects/question_generation/testifier.py", line 19, in <module>
    tokenizer2 = AutoTokenizer.from_pretrained('./t5-tokenizer-test/')
  File "/home/amir/PycharmProjects/question_generation/venv/lib/python3.7/site-packages/transformers/models/auto/tokenization_auto.py", line 345, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/amir/PycharmProjects/question_generation/venv/lib/python3.7/site-packages/transformers/models/auto/configuration_auto.py", line 349, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/amir/PycharmProjects/question_generation/venv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 418, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for './t5-tokenizer-test/'. Make sure that:

- './t5-tokenizer-test/' is a correct model identifier listed on 'https://huggingface.co/models'

- or './t5-tokenizer-test/' is the correct path to a directory containing a config.json file
```

If I replace Autotokenizer with T5Tokenizer the issue will be fixed:
```

from transformers import T5Tokenizer

tokenizer = T5Tokenizer.from_pretrained('t5-small')
tokenizer.add_tokens(['<sep>', '<hl>'])
tokenizer.save_pretrained('./t5-tokenizer-test/')

tokenizer2 = T5Tokenizer.from_pretrained('./t5-tokenizer-test/')
```

**Comment by patil-suraj** [comment]
Hi @hadifar 

The `AutoTokenizer` needs to know the model type to load the correct `Tokenizer` class, and that information is stored in the `config` file, so if `config.json` is not present it can not load the correct class. And `config.json` is saved when saving the model using `.save_pretrained` method. To load a separately saved tokenizer you should use the respective tokenizer class
