### ISSUE TITLE
pegasus fine-tune: TypeError: shift_tokens_right() missing 1 required positional argument: 'decoder_start_token_id'

### ISSUE THREAD

**Issue by cheop-byeon** [huggingface/transformers#9568]
## Environment info
- `transformers` version: 4.2.0dev0
- Platform: Linux-3.10.0-1062.18.1.el7.x86_64-x86_64-with-centos-7.7.1908-Core
- Python version: 3.7.3
- PyTorch version (GPU?): 1.7.1 (False)
- Tensorflow version (GPU?): 2.4.0 (False)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help
@mfuntowicz
@sgugger
@patrickvonplaten

## Information
I am trying to do the fine-fune of pegasus in the summarization task of xsum dataset according to the instructions here.

## To reproduce
add more paramters in finetune_pegasus_xsum.sh
```
python finetune.py \
    --gpus 0 \
    --learning_rate=1e-4 \
    --do_train \
    --do_predict \
    --n_val 1000 \
    --val_check_interval 0.25 \
    --max_source_length 512 --max_target_length 56 \
    --freeze_embeds --label_smoothing 0.1 --adafactor --task summarization_xsum \
    --model_name_or_path google/pegasus-xsum \
    --output_dir=xsum_results \
    --data_dir xsum \
    --tokenizer_name google/pegasus-large \
    "$@"
```
in the terminal:
```
(env) (base) [cheop.byeon@node01 seq2seq-distillation]$ sh finetune_pegasus_xsum.sh 
/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: Checkpoint directory xsum_results exists and is not empty. With save_top_k=1, all files in this directory will be deleted when a checkpoint is saved!
  warnings.warn(*args, **kwargs)
/home/cheop.byeon/env/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "finetune.py", line 442, in <module>
    main(args)
  File "finetune.py", line 417, in main
    logger=logger,
  File "/home/cheop.byeon/transformers/examples/research_projects/seq2seq-distillation/lightning_base.py", line 389, in generic_train
    trainer.fit(model)
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 48, in train
    results = self.train_or_test()
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 68, in train_or_test
    results = self.trainer.train()
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 462, in train
    self.run_sanity_check(self.get_model())
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 570, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 171, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/home/cheop.byeon/env/lib/python3.7/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 64, in validation_step
    output = self.trainer.model.validation_step(*args)
  File "finetune.py", line 182, in validation_step
    return self._generative_step(batch)
  File "finetune.py", line 226, in _generative_step
    loss_tensors = self._step(batch)
  File "finetune.py", line 145, in _step
    decoder_input_ids = shift_tokens_right(tgt_ids, pad_token_id)
TypeError: shift_tokens_right() missing 1 required positional argument: 'decoder_start_token_id'
```
## Expected behavior
To make the finetune works in my environment.

**Comment by patrickvonplaten** [comment]
Hey @cheop-byeon, 

we no longer actively maintain the `research_projects` folder ourselves. To solve your problem you can however just add 
`model.config.decoder_start_token_id` as the third argument to the function.

**Comment by patrickvonplaten** [comment]
Note that we recommend that you use the research project with it's proposed version being `pip install transformers==4.1.0`. We won't do actively maintain the code in `research_projects` anymore.

**Comment by cheop-byeon** [comment]
Thanks for your response, it did word by just adding the third parameter.
Well, I am not sure I passed the correct name to the arguments:

--model_name_or_path google/pegasus-xsum \
--tokenizer_name google/pegasus-large \

or 
--model_name_or_path google/pegasus-large \
--tokenizer_name google/pegasus-xum \

I saw both in others' post.
@patrickvonplaten
