### ISSUE TITLE
SQuAD 2.0 metric not supported

### ISSUE THREAD

**Issue by yonatanbitton** [huggingface/transformers#9620]
Hello.
I'm trying to run the official `run_qa.py` code for SQuAD 2.0.

You have an open TODO here that is causing a bug: https://github.com/huggingface/transformers/blob/master/examples/question-answering/run_qa.py#L436

I would like to know what is the status of this TODO, and if it is going to be updated, or is there a way around it.

This is the current code:

```python
    current_dir = os.path.sep.join(os.path.join(__file__).split(os.path.sep)[:-1])
    metric = load_metric(os.path.join(current_dir, "squad_v2_local") if data_args.version_2_with_negative else "squad")
```

I receive: 
```
FileNotFoundError: Couldn't find file locally at .../squad_v2_local/squad_v2_local.py,
```

I've tried to change it to: 
```python
metric = load_metric("squad_v2" if data_args.version_2_with_negative else "squad")
```

But this is the stacktrace I receive: 
```
Traceback (most recent call last):
  File "/data/users/yonatab/transformers_pip/QA/run_qa_val_more_valueable.py", line 557, in <module>
    main()
  File "/data/users/yonatab/transformers_pip/QA/run_qa_val_more_valueable.py", line 538, in main
    results = trainer.evaluate()
  File "/data/users/yonatab/transformers_pip/QA/trainer_qa.py", line 63, in evaluate
    metrics = self.compute_metrics(eval_preds)
  File "/data/users/yonatab/transformers_pip/QA/run_qa_val_more_valueable.py", line 499, in compute_metrics
    return metric.compute(predictions=p.predictions, references=p.label_ids)
  File "/data/users/yonatab/transformers_pip/trans_pip/lib/python3.6/site-packages/datasets/metric.py", line 398, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/home/ec2-user/.cache/huggingface/modules/datasets_modules/metrics/squad_v2/7529efd518b03f775290694e7b797412cb2253e90b4f843af83cf7434cccb3a8/squad_v2.py", line 108, in _compute
    exact_raw, f1_raw = get_raw_scores(dataset, predictions)
  File "/home/ec2-user/.cache/huggingface/modules/datasets_modules/metrics/squad_v2/7529efd518b03f775290694e7b797412cb2253e90b4f843af83cf7434cccb3a8/evaluate.py", line 111, in get_raw_scores
    gold_answers = [a["text"] for a in qa["answers"] if normalize_answer(a["text"])]
  File "/home/ec2-user/.cache/huggingface/modules/datasets_modules/metrics/squad_v2/7529efd518b03f775290694e7b797412cb2253e90b4f843af83cf7434cccb3a8/evaluate.py", line 111, in <listcomp>
    gold_answers = [a["text"] for a in qa["answers"] if normalize_answer(a["text"])]
TypeError: string indices must be integers
100%|███████████████████████████████████████████| 13/13 [00:05<00:00,  2.51it/s]
```

How can I solve it? 

Thanks

**Comment by LysandreJik** [comment]
@sgugger would know about this TODO; I think the fix has landed in `datasets`, right?

**Comment by sgugger** [comment]
Yes, this should be fixed directly from `datasets` now, will update the script this afternoon.
