### ISSUE TITLE
squad_v2 crashes during evaluation

### ISSUE THREAD

**Issue by yuvalkirstain** [huggingface/transformers#9763]
## Environment info

- `transformers` version: 4.2.2
- Platform: Linux-4.9.5-64-nvidia-418.43-x86_64-with-debian-jessie-sid
- Python version: 3.7.7
- PyTorch version (GPU?): 1.7.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: False

### Who can help
@sgugger @patrickvonplaten 

## Information

Model I am using (Bert, XLNet ...):  bert-base-uncased

The problem arises when using:
* [ ] the official example scripts: examples/question-answering/run_qa.py

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: SQuAD **v2**

## To reproduce

Run:
```
python run_qa.py --model_name_or_path bert-base-uncased --dataset_name squad_v2 --do_train --do_eval --per_device_train_batch_size 12 --learning_rate 3e-5 --num_train_epochs 2 --max_seq_length 384 --doc_stride 128 --output_dir /tmp/debug_squad/ --evaluation_strategy steps --fp16
```

```
***** Running Evaluation *****
  Num examples = 12134
  Batch size = 8

01/23/2021 21:32:15 - INFO - utils_qa -   Post-processing 11873 example predictions split into 12134 features.#######################################################6| 1514/1517 [01:04<00:00, 23.34it/s]
100%|##############################################################################################################################################################| 11873/11873 [00:40<00:00, 291.51it/s]
01/23/2021 21:32:56 - INFO - utils_qa -   Saving predictions to /tmp/debug_squad/predictions.json.####################################################################| 1517/1517 [01:23<00:00, 23.34it/s]
01/23/2021 21:32:56 - INFO - utils_qa -   Saving nbest_preds to /tmp/debug_squad/nbest_predictions.json.##########################################################9| 11868/11873 [00:40<00:00, 303.46it/s]
Traceback (most recent call last):
  File "run_qa.py", line 495, in <module>
    main()
  File "run_qa.py", line 457, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/home/olab/kirstain/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/trainer.py", line 929, in train
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch)
  File "/home/olab/kirstain/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/trainer.py", line 1004, in _maybe_log_save_evaluate
    metrics = self.evaluate()
  File "/specific/netapp5_3/rent_public/olab-01-08-2021/kirstain/transformers/examples/question-answering/trainer_qa.py", line 63, in evaluate
    metrics = self.compute_metrics(eval_preds)
  File "run_qa.py", line 439, in compute_metrics
    return metric.compute(predictions=p.predictions, references=p.label_ids)
  File "/home/olab/kirstain/anaconda3/envs/transformers/lib/python3.7/site-packages/datasets/metric.py", line 398, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/specific/netapp5_3/rent_public/olab-01-08-2021/kirstain/.cache/huggingface/modules/datasets_modules/metrics/squad/4791a1e1b37b2b0b8d8d4b7d4793349432fe03a61be5b08c8b30c6b4d86363f1/squad.py", li$e 100, in _compute
    score = evaluate(dataset=dataset, predictions=pred_dict)
  File "/specific/netapp5_3/rent_public/olab-01-08-2021/kirstain/.cache/huggingface/modules/datasets_modules/metrics/squad/4791a1e1b37b2b0b8d8d4b7d4793349432fe03a61be5b08c8b30c6b4d86363f1/evaluate.py", line 68, in evaluate
    exact_match += metric_max_over_ground_truths(exact_match_score, prediction, ground_truths)
  File "/specific/netapp5_3/rent_public/olab-01-08-2021/kirstain/.cache/huggingface/modules/datasets_modules/metrics/squad/4791a1e1b37b2b0b8d8d4b7d4793349432fe03a61be5b08c8b30c6b4d86363f1/evaluate.py", line 53, in metric_max_over_ground_truths
    return max(scores_for_ground_truths)
ValueError: max() arg is an empty sequence
```

## Expected behavior
completing the evaluation without an exception

Thank you! :)

**Comment by yuvalkirstain** [comment]
It might be because I didn't provide the version_2_with_negative argument. Sorry! :)
